### ISSUE TITLE
gosimple: replace func signatures with named ones

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#10]
```
func createHandler() func(http.ResponseWriter, *http.Request) {
}
```

should be

```
func createHandler() http.HandlerFunc {
}
```

I'd do this for all named and exported interfaces in the std. If it's at all useful, I gather them in a go generate for `interfacer` here: https://github.com/mvdan/interfacer/blob/master/std.go

**Comment by dominikh** [comment]
This is a bit of a tough one. For one, it might make unhelpful suggestions. A function `(*go/types.Package) string` isn't always a `go/types.Qualifier`, for example. Second, changing the return value will also require changing part of the function body.

If we were to do this, it would probably need a hard-coded list of allowed suggestions. I have a feeling that said list would only consist of http.HandlerFunc and might not be worth the effort.

**Comment by mvdan** [comment]
> it might make unhelpful suggestions

Ah, true.

> Second, changing the return value will also require changing part of the function body.

Could you give an example? I can't think of one. In my particular case, the body did not require any changes.

> If we were to do this, it would probably need a hard-coded list of allowed suggestions. I have a feeling that said list would only consist of http.HandlerFunc and might not be worth the effort.

I think it would be worth the effort even if it was just for `http.HandlerFunc`. A quick study shows, from the std:

```
type ast.FieldFilter func(name string, value reflect.Value) bool
type ast.Importer func(imports map[string]*Object, path string) (pkg *Object, err error)
type scanner.ErrorHandler func(pos token.Position, msg string)
type types.Qualifier func(*Package) string
type http.HandlerFunc func(ResponseWriter, *Request)
type filepath.WalkFunc func(path string, info os.FileInfo, err error) error
```

I think all of those would make sense. They're all self-explanatory, given their package names.

**Comment by dominikh** [comment]
Not all functions that maps from a package to a string are types.Qualifiers. The same is true for most of these functions.

Disregard the comment about needing changes to the body. However, functions should probably return http.Handler, not http.HandlerFunc, making it a deceptive suggestion.

**Comment by mvdan** [comment]
Well, it depends on whether you use a handler interface implementation or a func :)

I agree that this would have some false positives, though. Closing.

**Comment by dominikh** [comment]
> Well, it depends on whether you use a handler interface implementation or a func :)

```
func foo() http.Handler {
  fn := func(http.ResponseWriter, *http.Request) {
  }
  return http.HandlerFunc(fn)
}
```

would be the recommended way of returning a function-based http.Handler, so that the caller doesn't need to be concerned with that implementation detail. See https://golang.org/src/net/http/server.go?s=52275:52325#L1744 for an example.
