### ISSUE TITLE
simple: fmt.{Printf,Fprintf,Sprintf} without arguments can be simplified

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#100]
Expressed as gofmt -r rules:

```Go
fmt.Printf(s) -> fmt.Print(s)
fmt.Fprintf(w, s) -> fmt.Fprint(w, s)
fmt.Sprintf(s) -> s
```

But not sure if there'll be too many false positives due to "wanting consistency with surrounding code".

Spotted in `net/http`:

- https://github.com/golang/go/blob/61336b78c18e90d90d68c5c2ce61d8d530669ed1/src/net/http/fs.go#L107
- https://github.com/golang/go/blob/61336b78c18e90d90d68c5c2ce61d8d530669ed1/src/net/http/fs.go#L119

**Comment by shurcooL** [comment]
The simplification is only possible if the format string doesn't contain any % verbs.

Otherwise, it's a change in behavior:

https://play.golang.org/p/IWZlS-Szz1

But `vet` already catches printf calls when number of verbs != number of arguments. As long as that's done before someone incorrectly simplifies such code...

**Comment by shurcooL** [comment]
At the end of the day, just like with most other simplification opportunities, the original code is either invalid (staticcheck material) or overy complex (gosimple material). There's no way to reliably infer the original user intent.

**Comment by dominikh** [comment]
For dynamic format strings, staticcheck emits a warning that this is potentially dangerous. I don't believe gosimple should flag this, due to false positives caused by consistency.
