### ISSUE TITLE
Failure to import tview

### ISSUE THREAD

**Issue by SamWhited** [dominikh/go-tools#1003]
Version: `staticcheck 2020.2.4 (v0.1.4)`

```
$ staticcheck -debug.version
staticcheck 2020.2.4 (v0.1.4)

Compiled with Go version: devel +b116404444ad 20201223173118
Main module:
        honnef.co/go/tools@v0.1.4 (sum: h1:SadWOkti5uVN1FAMgxn165+Mw00fuQKyk4Gyn/inxNQ=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.4.2 (sum: h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=)
        golang.org/x/sys@v0.0.0-20210514084401-e8d321eab015 (sum: h1:hZR0X1kPW+nwyJ9xRxqZk1vx5RUObAPBdKVvXPDUH/E=)
        golang.org/x/tools@v0.1.1 (sum: h1:wGiQel/hW0NnEkJUk8lbzkX2gFJU6PFxf1v5OlCfuOs=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```

Go version: `go version devel +b116404444ad 20201223173118 linux/amd64` (I'm actually only seeing this on the FreeBSD version but it should be the same version of Go and the same version of staticcheck, I am not seeing it on the linux version but don't have a shell on the FreeBSD machine to get the correct version string)

I ran staticcheck on a project that imports tview and get:

```
  > [line 26 : column 2] - could not import github.com/rivo/tview (invalid package name: "")
```

But the import and project work fine.

**Comment by dominikh** [comment]
I'm sorry, but I cannot debug this. Not without the complete issue template filled in (including the output of `go env` and the actual invocation of Staticcheck) and accurate version information that can be trusted.

Finally, the output you showed doesn't look like output made by `staticcheck`. How were you running Staticcheck?

Considering this is working fine on Linux but not FreeBSD, my first suspicion would be an issue in your environment.

**Comment by SamWhited** [comment]
Oops, I didn't realize I'd left those off. That said, I'm also very sorry, I got this tool confused with something else. This is *not* the tool outputting that error. My apologies.

**Comment by dominikh** [comment]
No worries. Thanks for following up.
