### ISSUE TITLE
QF1000: don't offer .+Index(Rune|Byte) for constant needles

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#1007]
Yes, IndexByte is ever so slightly faster than Index, but upstream seems to strongly believe that constant needles should just use Index, for simplicity's sake. Quoting Russ Cox from https://github.com/golang/go/issues/46336:

> Calling those all “Index” for the sake of discussion (any call with a constant sep should use Index anyway)

See #525 for some prior discussion.

**Comment by rsc** [comment]
If we write Index the right way, then calls to Index should be inlined to IndexByte anyway.
