### ISSUE TITLE
Remove -debug.version, use `go version -m` instead

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#1009]
Modern `go version` seems to display all the information we want:

```
$ go version -m staticcheck 
staticcheck: devel go1.17-32b73ae180 Mon May 24 20:57:01 2021 +0000
	path	honnef.co/go/tools/cmd/staticcheck
	mod	honnef.co/go/tools	(devel)	
	dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
	dep	golang.org/x/mod	v0.3.0	h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
	dep	golang.org/x/sys	v0.0.0-20210119212857-b64e53b001e4	h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
	dep	golang.org/x/tools	v0.1.0	h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=
	dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
```

Subsumes #901

**Comment by dominikh** [comment]
@mvdan what's the most reliable/cross-shell way of getting the path of an executable, so that we can pass it to `go version`? `which`? `command -v`?

**Comment by mvdan** [comment]
@dominikh do you mean POSIX shell? On what platforms?

**Comment by dominikh** [comment]
@mvdan Whatever works on as many UNIX-like platforms as possible, so presumably bash/dash/zsh. Something we can put in the issue template, a la

> Output of `go version -m $(get the path of staticcheck)`

**Comment by mvdan** [comment]
Ah. I don't think there's a great answer there; `which` is a coreutils thing and not a shell thing, so you'd depend on it being installed or on differences between GNU and others. `command` is a built in in Bash and many other mainstream shells, but as far as I can see it's not defined in any POSIX spec.

Realistically, I think either will be fine, as they should work on the vast majority of machines. But neither is fully portable for unix-y shells.

This makes me think that we should make a proposal for `go version -m program_name`, and the Go tool should use `exec.LookPath` to actually find the binary. This would also avoid the non-portability of command substitutions, which would not work on Windows.

**Comment by dominikh** [comment]
I'm not sure making `go version` do that would be in the spirit of unix-y tools. It opens a whole can of worms: should it also look in the current directory? Should it also look in GOPATH/bin even if it's not on the PATH? No other tool behaves like that. For example, you can't just do `ldd <prog>` and have it find `<prog>` in PATH.

The alternative from our end would be to trust that the user is at least capable of finding out and passing a path to `go version`, a rather basic skill. And we're already helping them for the majority of platforms.

We could also keep our flag, but make it call `go version` with the correct path, instead of reimplementing `go version` ourselves, which is basically what we're doing right now. But I'm not sure that would be worth it. The current code is probably less complex than calling `go version`.

**Comment by mvdan** [comment]
For what it's worth, my tools will continue to have a normal version flag. They don't have anything like your `-debug.version`, but I think that's fine - any user who needs that very detailed module info can most likely figure out where their binary is and how to point `go version -m` at it :)

**Comment by dominikh** [comment]
This isn't worth the effort.
