### ISSUE TITLE
cmd/all: add profiling flags

### ISSUE THREAD

**Issue by fortytw2** [dominikh/go-tools#103]
`goimports` integrates a couple cli flags for trace / profile output. Would definitely be interesting to see similar functionality integrated into go-tools. 

```
usage: goimports [flags] [path ...]
  -cpuprofile string
    	CPU profile output
...
  -memprofile string
    	memory profile output
  -memrate int
    	if > 0, sets runtime.MemProfileRate
  -trace string
    	trace profile output
...
```

**Comment by shurcooL** [comment]
> Would definitely be interesting

That was added by Brad when he was optimizing `goimports` performance. What use would these flags have for users? It would pollute existing set of flags. "Interesting" doesn't sound like it justifies this, are there additional uses?

If there's a need to profile or debug go-tools tools, can't that be done by modifying the source code? E.g.:

```Go
func main() {
	f, err := os.Create("cpu.prof")
	if err != nil {
		log.Fatal("could not create CPU profile: ", err)
	}
	if err := pprof.StartCPUProfile(f); err != nil {
		log.Fatal("could not start CPU profile: ", err)
	}
	defer pprof.StopCPUProfile()
...
```

**Comment by mvdan** [comment]
I usually do this in my projects by keeping a commit adding these flags in a separate branch. Then, whenever I need to play with performance optimizations, I just rebase that branch on master and use the flags.

I agree with @shurcooL that the flags shouldn't be exposed to regular users. Especially since once you add them, there's no way back - unless you're fine with breaking backwards compatibility.

**Comment by dominikh** [comment]
I am tempted to permanently add these flags, under a `-debug.<key>` namespace. Reasons being: 1) I need these flags repeatedly, so it's easier for me to have the flags always be there. 2) Other people may want to improve the performance of the tools, so they can reuse the flags.

We can make it clear that flags in `-debug` can come and go and shouldn't be considered part of the tool.

**Comment by shurcooL** [comment]
Under `-debug.<key>` namespace and with "can come and go" disclaimer SGTM.

**Comment by dominikh** [comment]
We have profiling flags now.
