### ISSUE TITLE
SA4006 💢 False positive in staticcheck

### ISSUE THREAD

**Issue by jrwren** [dominikh/go-tools#1037]
staticcheck 2021.1 (v0.2.0)

Compiled with Go version: go1.16.4
Main module:
        honnef.co/go/tools@v0.2.0 (sum: h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
        golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

go version go1.16.3 linux/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jawren/.cache/go-build"
GOENV="/home/jawren/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jawren/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jawren/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3481250682=/tmp/go-build -gno-record-gcc-switches"

I didn't run a command, but vscode did. I can repro by running `staticcheck ./mypkg`

Output of the command and what's wrong with the output:

mypkg:87:3: this value of err is never used (SA4006)

It is wrong because that value of err IS used.

This is from a private repo, but the awkward code looks like this:

```go
	var err error
	contentType := strings.SplitN(q.Header.Get(`Content-Type`), `;`, 2)[0]
	switch contentType {
	case `application/json`:
		a, err = setupJSON(one, q.Body)
	case `multipart/form-data`:
		file, header, err := q.FormFile(`file`)
		if err != nil {
			evt.Fail(err.Error())
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		defer file.Close()
		a, err = setupFormData(header.Filename, file) // THIS IS LINE 87 WITH THE ERROR.
	case ``:
		evt.Fail(`no content type provided`)
		http.Error(w, `no content type provided`, http.StatusBadRequest)
		return
	default:
		evt.Fail(`content type`, contentType, `not supported`)
		http.Error(w, `content type not supported`, http.StatusBadRequest)
		return
	}
	if err != nil { // THIS IS WHERE THE err VALUE IS USED.
		evt.Fail(err.Error())
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

```

**Comment by dominikh** [comment]
`		file, header, err := q.FormFile(`file`)` this line declares a new `err` variable that shadows the one from the outer scope. The later assignment assigns to the shadowed variable. That value never gets read.

**Comment by jrwren** [comment]
whoa! TIL the scope of vars in a switch is not what I thought. TY TY
