### ISSUE TITLE
staticcheck CLI Outputs to specify severity level (error, warning or ignored)

### ISSUE THREAD

**Issue by alexchao26** [dominikh/go-tools#1040]
Output from staticcheck currently summarizes the numbers of each severity at the bottom, but not per test.

It can be hand rolled via grep/awk but would be nice to include in the outputs and perhaps make things a little more human readable in CI pipelines.

Currently:
```
$ staticcheck -f stylish -fail="all,-ST1003,-SA1019" ./... 
/redacted_directory/run.go
  (11, 2)  SA1019  package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead. 

/redacted_directory/utils.go
  (13, 2)  SA1019  package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead. 

 ✖ 2 problems (0 errors, 2 warnings, 0 ignored)
```

Proposed:
```
$ staticcheck -f stylish -fail="all,-ST1003,-SA1019" ./... 
/redacted_directory/run.go
  warning (11, 2)  SA1019  package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead. 

/redacted_directory/utils.go
  warning (13, 2)  SA1019  package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead. 

 ✖ 2 problems (0 errors, 2 warnings, 0 ignored)
```
or something to that effect with the severity included at each check.

I'm happy to work on this if it's worth adding in.

**Comment by dominikh** [comment]
I'm not sure it's worth adding tbqh. Virtually every line of output will be a `warning`. Errors are reserved for failed compilation and similar problems; checks don't produce errors. And ignored problems obviously don't show up by default.

**Comment by alexchao26** [comment]
> I'm not sure it's worth adding tbqh. Virtually every line of output will be a `warning`. Errors are reserved for failed compilation and similar problems; checks don't produce errors. And ignored problems obviously don't show up by default.

Fair enough, i recently added a config and CI step for staticcheck to an existing project and wanted a way to separate warnings (mostly stylistic things that haven't been resolved yet) and "real" errors.
