### ISSUE TITLE
Trim spaces in `-checks` flag

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#1043]
People seem to try `staticcheck -checks="foo, bar, baz"`, which fails because we split on the comma and don't strip the leading spaces.

**Comment by ainar-g** [comment]
Just as a thought, perhaps in a future release this option could begin to work like the traditional Unix-ey ones, where each consecutive use adds another value to the array?  That is, this:

```none
--checks='all,-ST*,-S*'
```

Could maybe become this:

```none
-c 'all' -c '-ST*' -c '-S*'
```

**Comment by dominikh** [comment]
That seems rather atypical for Go tooling.
