### ISSUE TITLE
staticcheck: panic on go1.8.typealias

### ISSUE THREAD

**Issue by menghanl** [dominikh/go-tools#105]
staticcheck panics with 

```
panic: internal error: strconv.Atoi: parsing "8.typealias": invalid syntax
```

The panic happens at:
https://github.com/dominikh/go-tools/blob/master/lint/lintutil/util.go#L125

I think the reason is, in `dev.typealias`, `"go1.8.typealias"` is included in `ReleaseTags`:
https://go.googlesource.com/go/+/dev.typealias/src/go/build/build.go#294

**Comment by dmitshur** [comment]
Is this issue still relevant, or should it be closed?

The `dev.typealias` branch is 2 years old, with `go1.8.3` as the latest Go version merged into it. The README [says](https://github.com/dominikh/go-tools#system-requirements) that only the last two versions of Go are supported, which are Go 1.12 and 1.11, not 1.8.

**Comment by dominikh** [comment]
It's still relevant insofar as we should still fix the underlying issue, in case Go introduces another such version. Maybe we'll have `go1.14.try`?
