### ISSUE TITLE
detect function that returns an error that's not checked

### ISSUE THREAD

**Issue by lolopinto** [dominikh/go-tools#1057]
since go doesn't have exceptions, it's easy for a function that returns an error to be missed by callers

e.g. 
```golang
func foo() error {
  return nil
}

func bar() {
  foo()  // should be flagged!
 // do something else.
}

func bar2() {
  // yay!
  if err := foo(); err != nil {
    log.Fatal(err) 
 }
 // do something else.
}
```

**Comment by dominikh** [comment]
That is [errcheck's](https://github.com/kisielk/errcheck) domain. It does not fit into Staticcheck because it has too many false positives in the real world.
