### ISSUE TITLE
Global variables utilized by concurrent code

### ISSUE THREAD

**Issue by dpanic** [dominikh/go-tools#1058]
Hi,

It would be good to have SAST check which will detect any GLOBAL variables used with concurrent Go code.

This will detect possible race conditions.

I know there is ```go -race```, problem is that is DAST test during runtime. It will not detect race conditions on code which is not executed.

I can help in doing some code.

**Comment by dpanic** [comment]
Detection of GLOBAL VARIABLES is usable as it, even without checking where is used.

**Comment by dominikh** [comment]
This is out of scope for Staticcheck, which must have a very low rate of false positives and must perform efficiently.

Detecting race conditions statically is an ongoing field of research and currently either requires manual annotations or has inherent false positives, and is fairly expensive on top of that.

Simply flagging global variables used in a concurrent context is not a satisfactory substitute; there are various patterns that allow correct shared use of global variables, and we cannot detect all of them, leading us back to false positives.

You might be interested in [Chronos](https://github.com/amit-davidson/Chronos), a (limited) static race detector for Go.
