### ISSUE TITLE
cmd/gosimple/README.md: Improperly formatted Markdown table.

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#106]
See https://github.com/dominikh/go-tools/blob/master/cmd/gosimple/README.md#checks:

![image](https://cloud.githubusercontent.com/assets/1924134/26324175/badceccc-3eff-11e7-956c-cd83df3f5f2a.png)

Regression introduced in https://github.com/dominikh/go-tools/commit/cb2d2807f11f387b47cea8bd3b2ae84f137ff7b1?short_path=4a63aed#diff-4a63aed4656e7da2f77e0c36b4abe255 6 days ago.

**Comment by dominikh** [comment]
Fucking markdown tables.

**Comment by dominikh** [comment]
Fixed.

**Comment by shurcooL** [comment]
For posterity, it was fixed in e94d1c1a34c6b61d8d06c7793b8f22cd0dfcdd90.
