### ISSUE TITLE
[staticcheck] FR: var ctx context.Context

### ISSUE THREAD

**Issue by mattysweeps** [dominikh/go-tools#1085]
Feature Request:

Add a new lint rule to static check for context.Context declarations without an assignment.
Stems from the limitations of `SA1012` discussed in #1084 

```
var ctx context.Context
```
Fixed:
```
ctx := context.TODO()
```

Allow exceptions in test files and packages, as it's common for BDD test frameworks, such as Ginkgo, to declare a global `ctx` and assign it before each test.

**Comment by dominikh** [comment]
I'll merge this issue into #1084 to make discussion easier.

**Comment by mattysweeps** [comment]
Without the current limitations of `SA1012`, does this provide value on its own?

**Comment by dominikh** [comment]
I don't think so, no. I believe it is too opinionated as a purely stylistic check and the following shouldn't be forbidden:

```
var ctx context.Context
if cond {
  ctx = foo
} else {
  ctx = bar
}
```
