### ISSUE TITLE
New check: add check for simplifying `w.Write([]byte(fmt.Sprintf(...)))` to `fmt.Fprintf(w, ...)`

### ISSUE THREAD

**Issue by tdakkota** [dominikh/go-tools#1091]
The
```go
w.Write([]byte(fmt.Sprintf(...)))
```
pattern is inefficient and overcomplicated, can be easily replaced with
```go
fmt.Fprintf(w, ...)
```

This pattern is very popular [(Sourcegraph search)](https://sourcegraph.com/search?q=context:global+Write%28%5B%5Dbyte%28fmt.Sprintf+lang:go+-file:%28%5E%7C/%29vendor/+-file:_test%5C.go%24&patternType=literal).

**Comment by dominikh** [comment]
Related: #477. And see the concerns I've expressed in that issue. I think this would be fine to add to `quickfix`, but not `simple`.
