### ISSUE TITLE
License does not appear as MIT license on github

### ISSUE THREAD

**Issue by pabloem** [dominikh/go-tools#1094]
I believe the license text is the exact text from the MIT license (https://opensource.org/licenses/MIT) - but it just happens that Github won't show it as MIT - which is not a problem, but it forces people to check the license before adopting the project.

**Comment by dominikh** [comment]
https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/ has fixed this:
![image](https://user-images.githubusercontent.com/39825/170629608-b038031b-3943-408f-be4f-d6796d52eb79.png)
