### ISSUE TITLE
Question: how to enforce length of a line?

### ISSUE THREAD

**Issue by BoraBak** [dominikh/go-tools#1098]
I want to enforce the length of the line, i.e. the number of characters per line. For example 120 characters.

Also, I probably missing here something but the usage of `staticcheck.conf` is not working for me. I created the configuration file `staticcheck.conf` according to the [example](https://staticcheck.io/docs/configuration#example-configuration) but it's not being enforced. For example, `ST1016 – Use consistent method receiver names` is not being enforced even though I intentionally made a weird receiver that is distinguished from the other. And more cases that I checked.

**Comment by dominikh** [comment]
> I want to enforce the length of the line, i.e. the number of characters per line. For example 120 characters.

Staticcheck cannot and will not do that.

> Also, I probably missing here something but the usage of staticcheck.conf is not working for me

Please file a separate issue (or, better yet, a [discussion](https://github.com/dominikh/go-tools/discussions)) and provide enough details to make it actually possible to debug that. Directory structure, config contents, Staticcheck invocation and so on.
