### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nrevanna** [dominikh/go-tools#1129]
Latest version of staticcheck

```go get -u honnef.co/go/tools/cmd/staticcheck
# honnef.co/go/tools/go/loader
../../../honnef.co/go/tools/go/loader/loader.go:330:48: err.Line undefined (type config.ParseError has no field or method Line)
Makefile:171: recipe for target '/home/nrevanna/go/bin/staticcheck' failed
make: *** [/home/nrevanna/go/bin/staticcheck] Error 2
Makefile:405: recipe for target 'build-ubuntu-code' failed
make: *** [build-ubuntu-code] Error 2
```

git blame tells me this change is the culprit
59ec3d72 go/loader/loader.go (Dominik Honnef 2021-11-07 04:52:02 +0100 330)                     Pos:  fmt.Sprintf("%s:%d", err.Filename, err.Line),

May be Line is not part of err anymore?

**Comment by dominikh** [comment]
It seems that your build system is not using Go modules. You still have to respect the dependencies specified in `go.mod`, however. The code builds correctly with version v0.4.1 of `github.com/BurntSushi/toml`. The master branch, on the other hand, seems to have broken backwards compatibility.

**Comment by dominikh** [comment]
Also, upstream seems to have fixed the issue in https://github.com/BurntSushi/toml/commit/dcab1c6c8e42cfd8d4ebc085554815678d7b1a2b

**Comment by nrevanna** [comment]
Thanks @dominikh
