### ISSUE TITLE
S1021 prevents from assigning comment to variable

### ISSUE THREAD

**Issue by cedricvanrompay** [dominikh/go-tools#1130]
In VS Code with the Go tools, the following will cause VS Code to show the comment about variable `myVar` when you hover your mouse over it:

```go
// myVar does this and that
var myVar string
myVar = "value"
```

![rect904](https://user-images.githubusercontent.com/2635438/142402611-3d7999f9-d35c-47bb-83f0-9c0651ac1afa.png)

This code triggers `go-staticcheck`'s rule S1021 telling me to write it like this:

```go
// myVar does this and that
myVar := "value"
```

However with this form the comment is not attached to the variable any more.

One solution is simply to disable S1021, but I can see two better solutions:

- make `go-staticcheck` notice when the variable declaration is used to attach a comment to the variable
- make whatever part of the official go tools is responsible for this nice "attach comment" feature able to do it on a `:=` assignation

**Comment by dominikh** [comment]
IMO this should be fixed in whatever is responsible for displaying the comment. With gopls enabled that'd be gopls; I have no idea what VS Code uses without gopls, but it's not us.

**Comment by cedricvanrompay** [comment]
@dominikh OK. Closing the issue, then.
