### ISSUE TITLE
Add a simplify rule for multiple math.Abs

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#1135]
I recently found some code that did the following using `math.Abs`:
```go
math.Abs(a + b) / math.Abs(c + d)
```

I think this should have been flagged as it can be shortened to the following without change of behaviour, essentially removing one call to math.Abs (yes, I checked that the compile doesn't optimize this away already):
```go
math.Abs((a + b) / (c + d))
```

This pattern also applies to multiplications:
```go
math.Abs(a + b) * math.Abs(c + d)
```

Can be changed to:

```go
math.Abs((a + b) * (c + d))
```

This does however not apply to addition and subtractions, which is very important to mention.

Feel free to change the name of this issue. I couldn't come up with anything better.

**Comment by ainar-g** [comment]
Do these conversions hold up with the variables being combinations of `NaN`, `+Inf`, and `-Inf`?  At first glance, they should, but with IEEE 754 one can never be sure, heh.

**Comment by dgryski** [comment]
Yes, this is a safe optimization: http://herbie.uwplse.org/demo/76cb02ce0e6619c0f31b2ed07d175b48a2da919b.57c41e4aef8644c1f8e8f3a277c1c6a6f77413c8/graph.html

**Comment by dominikh** [comment]
I'm sorry, but this is out of scope for Staticcheck, for two reasons:

1. This seems like an optimization that should be performed by the compiler, not by the user.
2. Unlike the other optimizations in Staticcheck, this optimization will not lead to strictly better code. That is, when the performance doesn't matter, the user may choose one style over the other for clarity.

**Comment by Jacalz** [comment]
No worries, I just try to suggest improvements to code bases here whenever I find something in code reviews, in the hopes of benefitting others as well :)

Should I open an issue over at golang/go or is it not worth it?

**Comment by dominikh** [comment]
> Should I open an issue over at golang/go or is it not worth it?

I don't know the answer to that, sorry.

**Comment by dgryski** [comment]
My guess is that the cost of the floating point multiplication/division far outweighs the cost of the Abs making it not a useful optimization.

**Comment by Jacalz** [comment]
That was my initial thought as well but I guess that it doesn't hurt to open a bug and let the Go developers decide on that 🤷‍♂️
