### ISSUE TITLE
Allow disabling or enabling checks on top of the default ones

### ISSUE THREAD

**Issue by dsidirop** [dominikh/go-tools#1140]
For example I want to disable check S1000 while honoring the defaults of staticheck. Currently and as far as I can tell I simply can't achieve that. So I have to resort to writing something like:

staticcheck -checks="all,[default options here derived from the docs],-S1000"

I guess it would help if I could just write:

staticcheck -checks="defaults,-S1000"

or something to that effect.

**Comment by dominikh** [comment]
You can use `staticcheck -checks="inherit,-S1000"` – as long as no `staticcheck.conf` files override checks, this will inherit from the default configuration. Otherwise it will inherit from the configuration.
