### ISSUE TITLE
SA1020 claims "invalid port or service name" with ListenAndServe("", nil)

### ISSUE THREAD

**Issue by wesleym** [dominikh/go-tools#1147]
**Repro case:**

```
package main

import "net/http"

func main() {
	http.ListenAndServe("", nil)
}
```

**Expected behaviour:** staticcheck reports no findings in this code.

**Actual behaviour:** staticcheck finds [SA1020 - Using an invalid host:port pair with a `net.Listen`-related function ](https://staticcheck.io/docs/checks#SA1020) on the single line in the body of main.

**Why this is a false positive:** staticcheck assumes that a valid addr must always have at least a colon and port/service name. However, the empty string is also valid and works the same as the addr `:http`.

**Evidence:**

1. The [http package overview](https://pkg.go.dev/net/http#pkg-overview) doesn't specify the format of addr. It does imply a relationship between the package-level [http.ListenAndServe](https://pkg.go.dev/net/http#ListenAndServe) function and the [http.Server.ListenAndServe](https://pkg.go.dev/net/http#Server.ListenAndServe) method, the latter of which takes its serving address from [http.Server](https://pkg.go.dev/net/http#Server).Addr.
2. The package-level [http.ListenAndServe](https://pkg.go.dev/net/http#ListenAndServe) also doesn't specify the definition of addr.
3. [http.Server](https://pkg.go.dev/net/http#Server) has documentation for when the Addr field has an address 'in the form "host:port"', as well as the empty string.

Unless there is documentation to the contrary, this implies that http.ListenAndServe should accept an addr of the same form as http.Server.ListenAndServe.Addr, including its handling of the empty string. This also works in practice because http.ListenAndServe is a convenience function that [builds up an http.Server using the provided addr for http.Server.Addr](https://cs.opensource.google/go/go/+/go1.17.5:src/net/http/server.go;l=3183).

**Suspected location in staticcheck codebase:** https://github.com/dominikh/go-tools/blob/f4e86b7e8fe18dd83869d1176825537abfabd602/staticcheck/rules.go#L258 - the current code expects the address passed to always be splittable by [net.SplitHostPort](https://pkg.go.dev/net#SplitHostPort), and this is not the case when the provided string is the empty string.

**Other code affected:**

* http.ListenAndServeTLS

http.Server.ListenAndServe and http.Server.ListenAndServeTLS are not affected as they do not accept an addr argument.

**Please make sure to include the following information in your issue report:**

- The output of 'staticcheck -version'
  > `staticcheck.exe 2021.1 (v0.2.0)`
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
  > `flag provided but not defined: -debug`...
- The output of 'go version'
  > `go version go1.17.4 windows/amd64`
- The output of 'go env'
  > ```set GO111MODULE=
  > set GOARCH=amd64
  > set GOBIN=
  > set GOCACHE=C:\Users\Wesley\AppData\Local\go-build
  > set GOENV=C:\Users\Wesley\AppData\Roaming\go\env
  > set GOEXE=.exe
  > set GOEXPERIMENT=
  > set GOFLAGS=
  > set GOHOSTARCH=amd64
  > set GOHOSTOS=windows
  > set GOINSECURE=
  > set GOMODCACHE=C:\Users\Wesley\go\pkg\mod
  > set GONOPROXY=
  > set GONOSUMDB=
  > set GOOS=windows
  > set GOPATH=C:\Users\Wesley\go
  > set GOPRIVATE=
  > set GOPROXY=https://proxy.golang.org,direct
  > set GOROOT=C:\Program Files\Go
  > set GOSUMDB=sum.golang.org
  > set GOTMPDIR=
  > set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
  > set GOVCS=
  > set GOVERSION=go1.17.4
  > set GCCGO=gccgo
  > set AR=ar
  > set CC=gcc
  > set CXX=g++
  > set CGO_ENABLED=1
  > set GOMOD=C:\Users\Wesley\Source\Degap\server\go.mod
  > set CGO_CFLAGS=-g -O2
  > set CGO_CPPFLAGS=
  > set CGO_CXXFLAGS=-g -O2
  > set CGO_FFLAGS=-g -O2
  > set CGO_LDFLAGS=-g -O2
  > set PKG_CONFIG=pkg-config
  > set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Wesley\AppData\Local\Temp\go-build2000798515=/tmp/go-build -gno-record-gcc-switches
  > ```
- Exactly which command you ran
  > Automatically run from VS Code.
  > ```Version: 1.63.0 (user setup)
  > Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
  > Date: 2021-12-07T06:26:56.179Z
  > Electron: 13.5.2
  > Chromium: 91.0.4472.164
  > Node.js: 14.16.0
  > V8: 9.1.269.39-electron.0
  > OS: Windows_NT x64 10.0.22000
  > ```
  >
  > Go extension version `v0.30.0`
- Output of the command and what's wrong with the output
  > `invalid port or service name in host:port pair (SA1020)` `go-staticcheck`
- Where we can read the code you're running staticcheck on
  (GitHub repo, link to playground, code embedded in the issue, ...)
  > See "Repro case" above

**Comment by dominikh** [comment]
Will fix.
