### ISSUE TITLE
Unexported types from exported functions

### ISSUE THREAD

**Issue by affanshahid** [dominikh/go-tools#1149]
Why doesn't staticcheck warn on returning unexported types from exported functions. For example:

```go
struct foo {}

func NewFoo() *foo {} // should this not be a warning?
```

Is this not an anti-pattern?

**Comment by dominikh** [comment]
Because we don't believe that this is universally wrong, and we don't attempt to flag everything that _might_ be wrong, only things that are definitely wrong.
