### ISSUE TITLE
Report missing godoc comments

### ISSUE THREAD

**Issue by knweiss** [dominikh/go-tools#115]
I'm not sure if `megacheck` is the right command for this but I would love to see an optional feature that reports missing `godoc` comments (at least for exported functions).

Or is there already an existing tool for this functionality that I'm not aware of?

**Comment by shurcooL** [comment]
I believe this is one of the primary uses of `golint`.

**Comment by knweiss** [comment]
@shurcooL Ah, `golint` is what I was missing. Thank you!

**Comment by bufdev** [comment]
Can this be revived in light of https://github.com/golang/go/issues/38968

**Comment by dominikh** [comment]
@bufdev Yes. This is on my todo list.

**Comment by sbward** [comment]
Came here to say I was surprised when suddenly VSCode had stopped reporting missing godoc comments on my exported types and values. That's when I noticed the default linter is now `staticcheck`! It's been almost a year since the last comment on this issue -- please re-open it soon 👍
