### ISSUE TITLE
New Check: Remind to handle functions which return an error.

### ISSUE THREAD

**Issue by vidhanio** [dominikh/go-tools#1151]
Sometimes, users may forget to handle errors. For example,

```go
package something

import "errors"

func ReturnsAnError() error {
	return errors.New("handle me plz")
}
```

```go
package main

import "something"

func main()
	something.ReturnsAnError() // Forgot to handle error! :(
}
```

This could be solved by a message showing that this function returns an error they forgot to handle. In cases where the user intentionally does not want to handle the error, they would be forced to make it explicit, using `_` (Similar to how staticcheck asks you to make it explicit you meant `time.Millisecond` when using `time.Sleep()`)

```go
package main

import "something"

func main()
	_ := something.ReturnsAnError() // Forgot to handle error, but it is explicit and we know the user meant to not handle it.
}
```

**Comment by dominikh** [comment]
This is out of scope for Staticcheck. See 
- https://github.com/dominikh/go-tools/issues/1057
- https://github.com/dominikh/go-tools/issues/57#issuecomment-482840444

**Comment by vidhanio** [comment]
Interesting, thanks!
