### ISSUE TITLE
Support regex for dot-imports whitelist

### ISSUE THREAD

**Issue by SamuelCabralCruz** [dominikh/go-tools#1159]
I think it would be interesting to support regex like import paths to validate proper usage of dot imports whitelist.

**Comment by dominikh** [comment]
> I think it would be interesting

A feature needs to be useful, not interesting. I don't think that supporting regular expressions for the `dot_import_whitelist` setting would be useful, or appropriate. There are very few packages that should ever be dot-imported, that list of packages should be explicit and it shouldn't contain more entries than necessary.
