### ISSUE TITLE
Exported function with unexported type parameters

### ISSUE THREAD

**Issue by mmcloughlin** [dominikh/go-tools#1163]
Why does `staticcheck` not flag exported functions taking arguments with unexported types? Is the argument similar to #1149?

The specific code I was looking at is:

https://github.com/mit-plv/fiat-crypto/blob/c60f9a6f40c7b380a3012ee36805918bfbd7de38/fiat-go/64/curve25519/curve25519.go#L570

Requested information:

```
mbm@xps ~/D/m/f/f/f/6/curve25519 (master)> staticcheck -version
staticcheck 2021.1.2 (v0.2.2)
mbm@xps ~/D/m/f/f/f/6/curve25519 (master)> staticcheck -debug.version
staticcheck 2021.1.2 (v0.2.2)

Compiled with Go version: go1.17.6
Main module:
	honnef.co/go/tools@v0.2.2 (sum: h1:MNh1AVMyVX23VUHE2O27jm6lNj3vjO5DexS4A1xvnzk=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
mbm@xps ~/D/m/f/f/f/6/curve25519 (master)> go version
go version go1.17.6 linux/amd64
```

**Comment by dominikh** [comment]
If we allow functions to return values of unexported types, then it's only reasonable we also allow passing these values back into functions.

More generally, it's not something that we want to have an opinion on. We can't say that such code is universally wrong.

**Comment by mmcloughlin** [comment]
Can you explain why you might deliberately decide to do this? Specifically: exported function taking an unexported type argument _and_ the unexported type cannot be created by any exported functions?

In this case it has the (presumably unintended) effect that the function can only be called using a literal value, not a variable. In other cases it would render the function uncallable outside the package. Actually, I wonder if there's ever a use case for a function that can be passed around by external users (as a callback) but not actually called directly. That would be bizarre.

**Comment by dominikh** [comment]
> Can you explain why you might deliberately decide to do this?

With a concrete example that isn't unidiomatic? No, I can't. But Staticcheck isn't in the business of forbidding code that I failed to imagine. Your callback example is particularly intriguing. Point being, we can't flag such code and be confident that the user made a mistake.

As a probably acceptable and useful compromise, we could flag public APIs that make use of unexported types as part of the planned code-review related checks. See https://github.com/dominikh/go-tools/issues/1102 for more information on that.
