### ISSUE TITLE
Unused does not detect unused public functions / methods across subpackages

### ISSUE THREAD

**Issue by not-rusty** [dominikh/go-tools#1164]
As the title says, if I have this folder structure:

```
# package server
- ./server.go
- ./handlers/handler.go
- ./go.mod
- ./go.sum
```

And:

```go
// ./handlers/handler.go
package handlers

func Test() string {
    return "test"
}

// ./server.go
package main

func main() {
     // Do nothing
}
```

The handlers.Test function is not reported to be unused on the main package. Is this expected behaviour? I could forget to remove some unused functions like the `handlers.Test`, and the linter would not complain.

**Comment by dominikh** [comment]
This is working as expected. The default behavior would never be able to flag unused exported identifiers; it doesn't know if a package is supposed to be imported by third party users. Staticcheck used to have a flag to opt into flagging exported identifiers, but this was removed for technical reasons (which are documented in 5cfc85b70e7b778eb76fd7338e538d7c9af21e4e if you care) and there is currently no alternative.

**Comment by alarbada** [comment]
I mean, I haven't programmed this linter, but "it looks like it should be easy", at least for types, functions and variables. For methods I guess you need the ast.

**Comment by tombh** [comment]
Yeah even something like grepping for capitalised tokens that only appear once in the codebase would get me a long way. It Should Be Easy™️ 😁

**Comment by tombh** [comment]
Et voila: https://github.com/SenorWoolyLLC/gopls-unused

I threw something together using the Golang LSP. It's extremely slow, but at least methodical.

**Comment by miparnisari** [comment]
So, to summarize, this linter **can't** flag unused exported functions — it only flags **unexported** functions, and unused exported **struct fields**.

https://pkg.go.dev/golang.org/x/tools/cmd/deadcode helps here.

```
deadcode -test -generated ./...
```
