### ISSUE TITLE
Support Go 1.18 beta

### ISSUE THREAD

**Issue by Al2Klimov** [dominikh/go-tools#1165]
Not sure if it’s just me or it’s actually not supported, yet: https://github.com/Al2Klimov/icingadb/runs/4774014380?check_suite_focus=true

**Comment by nezorflame** [comment]
It's not just you.
Downloading and running the `latest` version locally gives this error:
```
~ install honnef.co/go/tools/cmd/staticcheck@latest
~ staticcheck
-: cannot import "internal/cpu" (unknown iexport format version 2), export data is newer version - update tool (compile)
-: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool (compile)
-: cannot import "internal/goos" (unknown iexport format version 2), export data is newer version - update tool (compile)
-: cannot import "math/bits" (unknown iexport format version 2), export data is newer version - update tool (compile)
```
If you install the latest commit from `master`, then the error count reduces to this:
```
~ install honnef.co/go/tools/cmd/staticcheck@master
~ staticcheck
-: cannot import "internal/abi" (predeclared type missing from cache: 31), export data is newer version - update tool (compile)
```

**Comment by dominikh** [comment]
d5c28addcbbbafca0b9a0f9ad8957912e9371015 should fix the immediate issue. Note that Staticcheck will still not work on any code that (transitively) uses generics. Support for that will land around the time Go 1.18 releases.
