### ISSUE TITLE
staticcheck request/suggestion: detect missing line feed (\n) on fmt.Printf()

### ISSUE THREAD

**Issue by HeCorr** [dominikh/go-tools#1170]
Hello!

This one gets me a lot.. I write `fmt.Printf("key=%s", value)` (forgetting the `\n`) and end up with something like this in my terminal:

![image](https://user-images.githubusercontent.com/75134774/149676658-3d049f65-86f9-4152-9e7c-1c081d2cf0bc.png)

Which despite being very interesting to look at, is highly undesirable.  :)

So it would be awesome to have a check for that missing line feed.

Sorry in advance if there's a similar issue requesting this or a check that already does that.

Thanks!

**Comment by dominikh** [comment]
Unfortunately we cannot differentiate format strings that are missing a newline from format strings that intentionally don't have a newline. As such, we cannot flag this.

**Comment by HeCorr** [comment]
But isn't it possible to disable specific checks? 🤔

If it was intentionally omitted and the warning bothers the developer, they can simply disable that check like any other. Isn't that the point?

**Comment by dominikh** [comment]
> But isn't it possible to disable specific checks? 

Yes. However, that is meant for rare occurrences and special requirements, such as code generators producing weird code. That doesn't mean that we're free to add very opinionated checks or checks with non-negligible rates of false positives. Staticcheck's goal is to flag code that is clearly wrong, not code that _might be wrong_. In other words, it errs on the side of false negatives, not false positives.

For example, a set of regexps¹ ran against the Go project finds 1123 calls to `fmt.Printf` with string literals as the first argument. Of these, 282 calls do not include a newline character. We can assume that the majority of these calls are correct. That's a false positive rate of 25%. We don't want to be wrong every fourth time.

If you think that this is a rule you want to and can enforce in your own projects, then I would recommend looking into semgrep or ruleguard to maintain your own rule.

¹: Calls found via `/fmt\.Printf\(".+", /`, calls not including newlines found by rejecting `/\n/`

**Comment by dominikh** [comment]
I also recommend the paper [Lessons from Building Static Analysis Tools at Google](https://research.google/pubs/pub46576/) for some insights into the problem of false positives and how they affect developer productivity/acceptance of static analysis.

**Comment by HeCorr** [comment]
Fair enough. Thank you for the response and resources.  :)
