### ISSUE TITLE
False positive on package.Constant and //lint:ignore SA1029 not being ignored

### ISSUE THREAD

**Issue by mikeschinkel** [dominikh/go-tools#1176]
This is while using `golangci-lint` with version `1.30.0` built from `45b90f6` on `2020-08-03T03:10:34Z`
I don't know how to run `staticcheck` directly in order to get the version.  
If I should have posted this bug elsewhere I apologize and would appreciate a redirect.

**Also:**

- **Version:** `go version go1.17.3 darwin/amd64`
- **Command:** `export $(GOENV) && GOOS=$(GOOS) golangci-lint run`

**Output:**
```
internal/api/auth_test.go:16:40: SA1029: should not use built-in type string 
as key for value; define your own type to avoid collisions (staticcheck)
	ctx := context.WithValue(r.Context(), api.IdentityKey, id)
	                                      ^
make: *** [lint] Error 1
```

**`go env`:**
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mikeschinkel/Library/Caches/go-build"
GOENV="/Users/mikeschinkel/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mikeschinkel/go/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mikeschinkel/go/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/mikeschinkel/go/go1.17.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/mikeschinkel/go/go1.17.3/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fg/1dfmwyrx3wxbhj5lbdqpt7bw0000gn/T/go-build3591735648=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

This is the code that is failing.

```
package api_test

import (
	"context"
	"fmt"
	"net/http"
	"testing"

	"github.com/example/example/api"
)

func TestLintIgnoreSA1029(t *testing.T)  {
	var identity *idvault.Identity
	var r *http.Request

	//lint:ignore SA1029 False positive False positive False positive
	ctx := context.WithValue(r.Context(), api.IdentityKey, identity)
	fmt.Printf("%v",ctx)
}
```
The same output is generated with or without the `//lint:ignore SA1029...` comment, and `api.IdentityKey` is just a constant so to be it seems to be a false positive anyway.

**Comment by dominikh** [comment]
`//lint:ignore` directives are specific to the `staticcheck` command. golangci-lint uses its own, different, directive for ignoring problems.

Also, if that constant is untyped or of type `string`, then it's not a false positive. It's precisely the thing the check aims to flag. See the mentions of "collision" in https://pkg.go.dev/context#Context and https://staticcheck.io/docs/checks/#SA1029

**Comment by mikeschinkel** [comment]
@dominikh — Thanks for the quick reply.  The reason I posted here is because `golangci-list` output `(staticcheck)` with the error, so I assumed it was running your tool under the hood.

As for it not being false positive, I realize now that I misunderstood what the check was doing. Thank you for clarifying.

**Comment by dominikh** [comment]
golangci-lint runs the checks that are part of Staticcheck, but it doesn't run our CLI. Most linters for Go are implemented using the [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis) API for the individual checks, and these can be used by any conforming go/analysis runner. But runners can implement additional behavior on top, such as ways to ignore problems, enable/disable individual checks and so on.

I'll close this issue. Let me know if you have any other questions.

**Comment by mikeschinkel** [comment]
@dominikh — Thank you for the clarification about `golangci-list`.  

And by declaring a new type and using that for the key as you suggested I was able to satisfy the check, e.g.:

```
package api

type ContextValueKey string
const IdentityKey ContextValueKey = "identity"
```

Posting here in case it helps others in the future.
