### ISSUE TITLE
Issue templates should capitalize Staticcheck

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#1178]

**Comment by ainar-g** [comment]
Just to be clear, is “Staticcheck” (as opposed to “staticcheck” and “StaticCheck”) the official spelling of the name?  I'd like to know, because there's some documentation I'd need to update.

**Comment by dominikh** [comment]
The overall project's name is Staticcheck. The name of the CLI is `staticcheck`.

**Comment by dominikh** [comment]
For example: "golangci-lint incorporates Staticcheck, but I'd prefer it if everyone ran `staticcheck` instead."
