### ISSUE TITLE
Cutstom go installation confusing the unused tool

### ISSUE THREAD

**Issue by ncw** [dominikh/go-tools#118]
Something about my go installation is confusing `unused`.  (I haven't tried the other tools.)

```
$ unused -v github.com/ncw/stressdisk 2>&1 | head
/home/ncw/go/src/github.com/ncw/directio/direct_io.go:20:2: could not import log (cannot find package "log" in any of:
	/usr/local/go/src/log (from $GOROOT)
	/home/ncw/go/src/log (from $GOPATH))
/home/ncw/go/src/github.com/ncw/directio/direct_io.go:21:2: could not import unsafe (cannot find package "unsafe" in any of:
	/usr/local/go/src/unsafe (from $GOROOT)
	/home/ncw/go/src/unsafe (from $GOPATH))
/home/ncw/go/src/github.com/ncw/directio/direct_io_unix.go:8:2: could not import os (cannot find package "os" in any of:
	/usr/local/go/src/os (from $GOROOT)
	/home/ncw/go/src/os (from $GOPATH))
[snip 1000s of lines of similar!]
```

However that is not my $GOROOT...

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ncw/go"
GORACE=""
GOROOT="/opt/go/go1.8"
GOTOOLDIR="/opt/go/go1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build351700478=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

I don't have the GOROOT environment variable set.

```
$ env | grep GO
GOPATH=/home/ncw/go
```

Setting it with `export GOROOT="/opt/go/go1.8"` fixes the problem, but it shouldn't be necessary IMHO as all the [current advice seems to be to never set GOROOT](https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really) and runtime.GOROOT](https://golang.org/pkg/runtime/#GOROOT) should always return the correct value even when the environment variable isn't set, shouldn't it?

A quick grep through the code doesn't find anything interesting happening with GOROOT, so perhaps this isn't a directly a go-tools problem...

**Comment by dominikh** [comment]
The Go tool doesn't require setting GOROOT (normally) because a value gets built into the binaries and the runtime package at build time. The same applies to custom tools, which are built when you go get/go install them. That is, when you installed any of my tools, the current value of `runtime.GOROOT` was baked into my tool. You'll either have to set the environment variable (which is unfortunate) or reinstall the tool (which is also unfortunate).

We can't shell out to `go env`, either, because the user may not be using the Go tool, but an alternative build system.

**Comment by ncw** [comment]
I see!  Probably what happened is that I had the old tools compiled with a different GOPATH. Running running `gometalinter --install --update` fixed the problem.

> We can't shell out to `go env`, either, because the user may not be using the Go tool, but an alternative build system.

I would have thought that would be a sensible default with a flag to disable?

**Comment by dominikh** [comment]
> I would have thought that would be a sensible default with a flag to disable?

I don't think so. I'd rather not have a "what build system are you using?" kind of flag (and a boolean flag is just a watered down version of that.). Especially because all editors, and gometalinter-like tools, would need to pass on that flag.

**Comment by dominikh** [comment]
I'm going to close this issue. I don't think there's anything we can do here.

**Comment by ncw** [comment]
That is fine with me. Thanks for a great tool.
