### ISSUE TITLE
Provide darwin/arm64 binaries as part of the release

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#1183]
Right now the releases include linux/arm64 binaries but not darwin/arm64. Now that these kind of machines are getting more common, it would be helpful if you included them in the release bundle.

**Comment by dominikh** [comment]
Will do for the next release, although I'm always surprised that people actually use the binaries instead of just `go install`.

**Comment by cespare** [comment]
In my case I've got tooling scripts which run fixed versions of various tools including staticcheck and know how to download them when needed. These run on machines which may or may not even have Go installed.

**Comment by dominikh** [comment]
> These run on machines which may or may not even have Go installed

Note that Staticcheck doesn't work without Go installed.

**Comment by cespare** [comment]
True! I could update the script to install from source. It dates back to ~Go 1.11 when it was a little more annoying to do so.
