### ISSUE TITLE
Generic compatibility question regarding bazel/rules_go

### ISSUE THREAD

**Issue by fandw** [dominikh/go-tools#1193]
Hi, I'm having some compatibility issues between bazel/rules_go and go-tools. With rules_go, the imported packages don't necessarily exist under GOROOT or GOPATH, instead they are pulled in at build time. This will cause an error in unused/staticcheck:
```
/home/.../example.go:4:2: could not import github.com/schollz/progressbar (cannot find package "github.com/schollz/progressbar" in any of:
	/home/.../bazel-server-mirror/external/go_1_16_linux_amd64_tar_gz/go/src/github.com/schollz/progressbar (from $GOROOT)
	/home/.../go/src/github.com/schollz/progressbar (from $GOPATH))
couldn't load packages due to errors: adhoc
```
Is there a way to bypass/ignore this error?

**Comment by dominikh** [comment]
Quoting the response I sent via email:

> Hi Daiwei,
> 
> I'm not too familiar with Bazel, but it's my understanding that there
> are roughly two ways of approaching this problem: You either rely
> entirely on rules_go (and something like [1]) and don't use the
> 'staticcheck' binary at all (which does mean you lose access to
> 'unused'), or you have Bazel synthesize a GOPATH for you and use
> Staticcheck on that. I don't know how to do that, but I've seen projects
> like gVisor do it[2].
> 
> Having Staticcheck ignore imports wouldn't work. We depend on full
> access to type information and source code for our analyses. We also
> call 'go' under the hood, which has to be able to successfully compile
> packages. If that fails, most of our own code won't execute in the first
> place.
> 
> I hope this helps somewhat.
> 
> Best regards,
> Dominik
> 
> [1]: https://github.com/sluongng/staticcheck-codegen
> [2]: https://gvisor.dev/contributing/#using-gopath
