### ISSUE TITLE
Feature: 1st Party Docker Image?

### ISSUE THREAD

**Issue by benyanke** [dominikh/go-tools#1196]
I plan to use this tool within my CI workflows, and I presume many others will as well. It would be great to have a first-party docker image as part of the project's releases, so that it can be dropped-in to CI workflows.

**Comment by dominikh** [comment]
To be honest I don't see the need. Staticcheck can be trivially installed with a single `go install` command, and any CI that wants to use Staticcheck presumably already uses Go, which is also Staticcheck's only external dependency. I don't see how a Docker image would simplify things.

We do have an action for GitHub Actions at https://github.com/dominikh/staticcheck-action, which simplifies some of the GitHub Actions specific parts, such as caching.

**Comment by Twi** [comment]
Try this:
```Dockerfile
FROM golang:alpine
ADD https://github.com/dominikh/go-tools/releases/download/2021.1.2/staticcheck_linux_amd64.tar.gz /staticcheck.tgz
RUN tar xzvf /staticcheck.tgz \
 && rm /staticcheck.tgz \
 && mv staticcheck/staticcheck /usr/local/bin
CMD /usr/local/bin/staticcheck -- $(go list ./... | grep -v tempfork)
```
