### ISSUE TITLE
What does that errror message mean

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [dominikh/go-tools#120]
referring to #119 

Why do I get this message 

```
This tool has moved! Check out its new location at https://github.com/dominikh/go-tools/
```

That is somewhat distracting if the install is 
```
go get -u honnef.co/go/tools/cmd/...
```

That is a different address.

**Comment by morriswinkler-simplesurance** [comment]
Sorry for opening more then one issue, but i am a bit confused by that.

**Comment by mvdan** [comment]
Dup of #108.

**Comment by morriswinkler-simplesurance** [comment]
I suggest something like:

```
This tool has moved! 
To Update : go get -u honnef.co/go/tools/cmd/[tool]
Github repository @ https://github.com/dominikh/go-tools/
```

something along those lines.

It is not the best idea to have the repo on github and make them go getable from a different URL.
Since 99.9999999% of repos would be hosted and go getted at the same place, 

maybe https://github.com/go-gitea/gitea or https://github.com/go-gitea/gitea could be a sollution for you guyes.

**Comment by mvdan** [comment]
Why are you posting the same in two separate threads?

Also, what you say about 99.9999999% of repos is false. Plenty of Go packages don't share clone and import paths. For one, all `golang.org/x` packages. But also plenty of third-party ones like `k8s.io/...` and this very one.

The warning message gives you an HTTP link, not a `go get` line nor an import path. It's not safe to assume that the same path will work as an import path.

**Comment by morriswinkler-simplesurance** [comment]
Ok, i apologized already for posting in two different issues, then 👍 

When I wrote this 99.... thing I was thinking about the golang.org repros, but heck they wrote an own server to take care of it, if you click for example on https://golang.org/pkg/fmt/#Print you end up: https://golang.org/src/fmt/print.go?s=6273:6320#L214. 

So bad example, and well the standard library ahs become a small part of go code out there, but heck I just stop here. And you decide from here on, it is your tool and your repo.

But still, it is confusing.
