### ISSUE TITLE
Release with Go 1.18 support?

### ISSUE THREAD

**Issue by zeisss** [dominikh/go-tools#1210]
Our currently pipeline contains `staticcheck`.  With Go 1.18 we currently see some parsing errors, which #1165 addresses in January already. 

Go has been released last week and is now also available in Homebrew.

Is there any plan to tag a new go-tools/staticcheck release?

**Comment by ainar-g** [comment]
There's already a pinned issue about that.  See #1166.

[Elsewhere][1], Dominik has said that the release is probably going to be finished in about a week.

[1]: https://twitter.com/dominikhonnef/status/1503793590991994882
