### ISSUE TITLE
Can't install staticcheck v0.3.0 with Go 1.16

### ISSUE THREAD

**Issue by bestbeforetoday** [dominikh/go-tools#1238]
```bash
% go1.16.13 install honnef.co/go/tools/cmd/staticcheck@latest
../../go/pkg/mod/honnef.co/go/tools@v0.3.0/go/ir/builder.go:36:2: //go:build comment without // +build comment
```
Works fine with go 1.17.

I see staticcheck only supports the last two Go versions and perhaps with Go 1.18 now being out, maybe you want to explicitly prevent installation with Go 1.16. Unless there are other breaking changes with Go 1.16, this seems like it should be  easy to avoid by adding the old style build tag comment in addition to the new one.

**Comment by ainar-g** [comment]
> I see staticcheck only supports the last two Go versions […]

It's not just Staticcheck, as the Go project itself only supports the last two minor releases.  See the “[Go Release Cycle][1]” article on the Go wiki.  Go 1.16 is EOL.

[1]: https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance

**Comment by dominikh** [comment]
> Unless there are other breaking changes with Go 1.16, this seems like it should be easy to avoid by adding the old style build tag comment in addition to the new one

It would be a lucky accident if this is the only issue. 

Generally speaking, Staticcheck releases support the last two versions of Go and we may make use of new APIs, drop support for old behavior, etc. Like Ainar points out, the same applies to Go itself, and large portions of the Go ecosystem. I'm not inclined to explicitly support versions of Go that are outdated.

**Comment by bestbeforetoday** [comment]
Gotcha. Thank you for the confirmation. 👍
