### ISSUE TITLE
SA5011 triggers based on assert check - better way to disable

### ISSUE THREAD

**Issue by duaneg3** [dominikh/go-tools#1253]
I have the following code:

(1) helpers.MyAssert(rr!=nil,"")
(2) new_aget := rr.FileType == protos.FileType_AGET
(3) new_stream := (rr.FileType & protos.FileType_STREAM_OPEN) == protos.FileType_STREAM_OPEN

The assert check is causing the next two lines (and any subsequent line which uses to rr) to fail SA5011.
I probably do not need the assert check, but it seems wrong for a link checker to require one to remove assertion checks.

Putting a lint override on every subsequent line which uses rr  (i.e. lines (2) and (3) and others) is a messy solution.
Could you add a lint override which disables a comparison from being used in the lint check (i.e. lint exception just on line (1))?

Hence one would just need to do something like the following:

//lint:ignore SA5011  ignore this comparison
helpers.MyAssert(rr!=nil,"")

To turn off all the static check failures involving rr generated from the nil comparison of rr on this line.

func MyAssert(test bool, msg string) {
	if !test {
		_, fn, line, _ := runtime.Caller(1)
		log.Printf("ERROR %s:%d  %s\n", fn, line, msg)
		os.Exit(4)
	}
}

I saw a somewhat similar issue flagger here:
SA5011 triggers when nil check is inside another function #832

**Comment by dominikh** [comment]
Please answer the questions from the issue template, in particular the ones regarding the versions of Go and Staticcheck you're using. Based on https://github.com/dominikh/go-tools/commit/e317c2471688a3b60d0224f2ba91a9da34b8badd this shouldn't be happening in the latest release of Staticcheck.

**Comment by duaneg3** [comment]
go version
> go version go1.16.4 linux/amd64
I can't run staticcheck on the command line ...

Since I wrote a custom assert routine, I check for nil in an if statement ...

**Comment by duaneg3** [comment]
Closed by mistake.
I can work around the issue by using the following:

if (rr==nil){
  // work around for linter SA5011 false error
 helpers.MyAssert(rr!=nil,"") 
 break    // leave flow before rr is used and generates false SA5011 error
}

**Comment by duaneg3** [comment]
Updated to go version go1.18.1 linux/amd64
and no longer seem to see the issue
