### ISSUE TITLE
unused whole-program

### ISSUE THREAD

**Issue by 89z** [dominikh/go-tools#1281]
I am working on cleaning up someone else's code, and so I want to removed unused functions, even exported ones.

I have tests that call the functions I care about, so I want to remove anything else that's not needed.

It seems this used to be possible at one point, is it no longer?

**Comment by dominikh** [comment]
Beginning with Staticcheck 2020.2, there is no longer a whole-program mode. The reasons for that are briefly explained [in the release notes](https://staticcheck.io/changes/2020.2/#unused-whole-program). 

We may add this functionality back at some point (likely as a standalone tool), but there is no timeline for that. 

You may try using Staticcheck 2020.1, which still has the mode, but note that it may not work with newer versions of Go, and that for best results, you should delete Staticcheck's cache before each use (which is at ~/.cache/staticcheck by default on Linux), or you may run into false positives.

**Comment by 89z** [comment]
Do you know of a way to mark everything private? I can do this:

~~~
gofmt -w -r 'SomeFunction -> someFunction' *.go
~~~

but I have to do it for every function.
