### ISSUE TITLE
staticcheck: trim the cache

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#1283]
On some CI machines the staticcheck cache has grown to many GB. I took at look at the code and saw that the cache code is copied from the Go tool. However, [Cache.Trim](https://github.com/dominikh/go-tools/blob/95631861333b070dcbf63d8c1b78ef01225c204d/lintcmd/cache/cache.go#L299) is never called (and I can see that there is no `trim.txt` in the cache directory).

Is this intentional? I'm guessing it's a bug.

I'm using v0.3.0 but I don't think the behavior has changed since then.

**Comment by dominikh** [comment]
That would be a bug. Will investigate.

**Comment by dominikh** [comment]
It looks like we lost the call to Trim in 5cfc85b70e7b778eb76fd7338e538d7c9af21e4e.

**Comment by dominikh** [comment]
Fixed on master (which is Go 1.18 only). Will be backported to a bugfix release in a couple days.

**Comment by cespare** [comment]
Thanks!

**Comment by cespare** [comment]
> Will be backported to a bugfix release in a couple days.

@dominikh ping on this. Looks like this fix isn't in any release yet?

**Comment by dominikh** [comment]
@cespare Thanks for the ping. It's now part of https://github.com/dominikh/go-tools/releases/tag/v0.3.3
