### ISSUE TITLE
simple: string(buf.Bytes()) -> buf.String() where buf is bytes.Buffer

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#129]
I've written and committed the following diff:

```diff
 out, err := format.Source(buf.Bytes())
 if err != nil {
-	return err
+	log.Println(err)
+	out = []byte("// gofmt error: " + err.Error() + "\n\n" + string(buf.Bytes()))
 }
```

Luckily, before pushing it, I spotted that `string(buf.Bytes())` could be simplified to `buf.String()`.

I've seen at least one other person do this as well, see https://github.com/neelance/graphql-go/pull/98#discussion_r124367951.

I would imagine this could also apply for `[]byte(buf.String())` -> `buf.Bytes()`.

**Comment by bradleyfalzon** [comment]
- It appears a common infraction is when printing a *http.Response's body.
- `bufio` package has a case: https://github.com/golang/go/blob/a1e7fb4eed7fbb002d2fabbd6a809a1a49dca711/src/bufio/bufio_test.go#L645-L646
- HashiCorp has an infraction where the buffer's string output is used in the strings package, which could use bytes package instead and gain some performance by skipping the string conversion completely https://github.com/hashicorp/consul/blob/da0408c2419ff806008c7e6bf449b287b1053a39/api/kv.go#L255
