### ISSUE TITLE
False positive (truncated) (compile) when using constants from a package

### ISSUE THREAD

**Issue by firelizzard18** [dominikh/go-tools#1300]
This is fine:

```go
	const x = 0.05
	const y = 10000
	big.NewInt(x * y)
```

But the exact same code fails with "cannot use &lt;variable> (untyped float constant 500) as uint64 value in struct literal (truncated) (compile)" if the constants are defined in a package:

```go
	big.NewInt(pkg.X * pkg.Y)
```

And the most frustrating of all, there's no way to disable this! `lint:ignore truncated` and `lint:ignore compile` do nothing.

**Comment by dominikh** [comment]
Those are errors from the compiler or the type checker, not Staticcheck. There's nothing for us to do here if your code is invalid.

**Comment by firelizzard18** [comment]
It compiles perfectly fine. This code is in a test and there are zero issues with it running.

**Comment by dominikh** [comment]
So both `go build` and `go test -c` finish successfully?

**Comment by dominikh** [comment]
I can reproduce the issue with the `github.com/AccumulateNetwork/accumulate/test/e2e` package.

**Comment by dominikh** [comment]
The upstream issue for this is https://github.com/golang/go/issues/53803

**Comment by firelizzard18** [comment]
Thank you for looking into this. I won't object if you want to close this issue since it's not your bug.
