### ISSUE TITLE
Can not 

### ISSUE THREAD

**Issue by knight-hjh** [dominikh/go-tools#1301]
Please make sure to include the following information in your issue report:

- The output of 'staticcheck -version'
hjh@hjh-Precision-3640-Tower:~/gowork/bin$ staticcheck -version
staticcheck 2019.2.3
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
staticcheck 2019.2.3

Compiled with Go version: go1.18.2
Main module:
	honnef.co/go/tools@v0.0.1-2019.2.3 (sum: h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/tools@v0.0.0-20201023174141-c8cfbd0f21e6 (sum: h1:rbvTkL9AkFts1cgI78+gG6Yu1pwaqX6hjSJAatB78E4=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
- The output of 'go version'
go version go1.18.2 linux/amd64
- The output of 'go env'
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/hjh/gowork/bin"
GOCACHE="/home/hjh/.cache/go-build"
GOENV="/home/hjh/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hjh/gowork/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hjh/gowork"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build733342578=/tmp/go-build -gno-record-gcc-switches"
- Exactly which command you ran
go install honnef.co/go/tools/cmd/staticcheck@2022.1
- Output of the command and what's wrong with the output
nothing
- Where we can read the code you're running Staticcheck on
  (GitHub repo, link to playground, code embedded in the issue, ...)

![image](https://user-images.githubusercontent.com/38315608/178998645-6125c676-7760-4697-85f3-49705a316278.png)
when I update the staticcheck. after serveral seconds. when I run `staticcheck -version` in a new terminal. The version is still 2019.
![image](https://user-images.githubusercontent.com/38315608/178999463-c384059d-71be-4511-a7ef-6d93972a0cab.png)
Appreciate If you have some suggestions.

**Comment by knight-hjh** [comment]
![image](https://user-images.githubusercontent.com/38315608/179001674-d0800885-e84b-43d5-858d-5f8df2e5ee98.png)
This the actual error. I think maybe the staticcheck version is not right,

**Comment by dominikh** [comment]
This is probably a PATH problem of some sort. Please see https://go.dev/help for a better source of help with this.
