### ISSUE TITLE
remove ST1006

### ISSUE THREAD

**Issue by 89z** [dominikh/go-tools#1302]
I just got hit with this today:

~~~
receiver name should be a reflection of its identity; don't use generic names
such as "this" or "self" (ST1006)
~~~

I can appreciate this idea, but I dont know if it makes the code any better. For example, the source code in this very repo, uses a single letter in several places:

https://github.com/dominikh/go-tools/blob/555b2d3292b4793777c72aca3757a60e1b084ab1/pattern/lexer.go#L131-L163

I dont see how a single letter better reflects the receiver compared to `this` or `self`.

<https://wikipedia.org/wiki/This_(computer_programming)>

**Comment by 89z** [comment]
also, it is used a few times in the standard library:

https://cs.opensource.google/search?q=func.%5C(self%5Cs&sq=&ss=go%2Fgo
https://cs.opensource.google/search?q=func.%5C(this%5Cs&sq=&ss=go%2Fgo

**Comment by dominikh** [comment]
> I can appreciate this idea, but I dont know if it makes the code any better

This rule isn't our invention; it is part of the official style guide. See https://github.com/golang/go/wiki/CodeReviewComments#receiver-names.

> I dont see how a single letter better reflects the receiver compared to this or self.

Quoting the aforementioned document:

> In Go, the receiver of a method is just another parameter and therefore, should be named accordingly. The name need not be as descriptive as that of a method argument, as its role is obvious and serves no documentary purpose. It can be very short as it will appear on almost every line of every method of the type; familiarity admits brevity.

In other words, the receiver is named similar to a combination of a parameter and a local variable.

> also, it is used a few times in the standard library:

All but one of these results are test fixtures. They also have methods called `foo` and types called `MyType`. These are not appropriate names for actual APIs. The one non-fixture match, in `src/math/rand/rand_test.go` was authored some time in or before 2011. Needless to say, Go's style wasn't at all finalized yet in 2011.
