### ISSUE TITLE
New rule: testable examples must have an `output` comment

### ISSUE THREAD

**Issue by jamietanna** [dominikh/go-tools#1309]
As highlighted in https://github.com/golangci/golangci-lint/issues/3084, this would be a handy rule to have, allowing us to flag incorrectly set up testable examples.

**Comment by dominikh** [comment]
Not all examples are meant to be run during testing. People write examples that only exist to be shown as part of documentation. See for example the various examples in https://pkg.go.dev/net/http#pkg-examples. Therefore this is not a rule suitable for Staticcheck.
