### ISSUE TITLE
Error must be checked before other code run

### ISSUE THREAD

**Issue by hesining** [dominikh/go-tools#1316]
``` go
package main

import (
        "errors"
        "fmt"
)

func AAA() error {
        return errors.New("error here")
}

func BBB() (v int, err error) {
        err = AAA() //lint must return if err != nil
        v = 1
        v++
        return
}

func main() {
        fmt.Println(BBB())
}
```

If function AAA return err != nil but code continue run, can I get a lint?

**Comment by shmsr** [comment]
In this case, `func AAA` always returns `err != nil`. So even if you do:
```go
func BBB() (v int, err error) {
        err = AAA()
        if err != nil {
                // handle err
        }
        v = 1
        v++
        return
}
```

So, always `err != nil` will be hit. Doesn't make much sense. Can you please provide a better example?

**Comment by dominikh** [comment]
This is out of scope for Staticcheck. The function `BBB` provided by OP isn't inherently wrong. It doesn't discard the error since it returns it via the named return parameter. Staticcheck has no way of knowing if the function as written is right or not.
