### ISSUE TITLE
`cdk.out` Directory Not Being Excluded from Checks

### ISSUE THREAD

**Issue by MarkCaro** [dominikh/go-tools#1319]
`staticcheck -version`:
staticcheck 2022.1.3 (v0.3.3)

`staticcheck -debug.version`:
staticcheck 2022.1.3 (v0.3.3)

`go version`:
go version go1.19.1 windows/amd64

`go env`:
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\MY_USERNAME\AppData\Local\go-build
set GOENV=C:\Users\MY_USERNAME\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\MY_USERNAME\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\MY_USERNAME\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\MY_USERNAME\AppData\Local\Temp\go-build1862175120=/tmp/go-build -gno-record-gcc-switches

**_Issue Description:_**

I have an AWS CDK project with the following structure:

    /my-project
        /cdk.out

`staticcheck` is reporting issues from the `/cdk.out` directory, but it should be excluded from checks because it's a CDK asset stating directory.

**_Exactly which command you ran:_**
`staticcheck ./...`

**_Output of the command and what's wrong with the output:_**
`staticcheck` reported issues inside the `/cdk.out` directory.
Below is an example:

>cdk.out\asset.0f59e4f9a491da3c8abf179cf77f4bd7b4daddb839712755c72ef0466eec81b0\main.go:24:2: var downloader is unused (U1000)

**_Where we can read the code you're running Staticcheck on:_**
I can't share the code because it's proprietary, but it should be reproducible in any project.

**_Proposal:_**
Can you add an option in `staticcheck.conf` to let us exclude directories?

**Comment by dominikh** [comment]
How do you exclude `cdk.out` from commands such as `go test ./...` or `go vet ./...`?

**Comment by MarkCaro** [comment]
@dominikh I've seen answers online that use `grep` on Linux to exclude directories, but I haven't found anything for Windows.

As for excluding tests in `/cdk.out`, I don't run `go test ./...` from the project's root folder. 
I run it inside the `/lambda` folder, so the command doesn't see tests in `/cdk.out` (the two folders are on the same level).

I don't run `go vet` manually because I use VS Code, which does it automatically.

In the meantime, a workaround I did is to just delete `cdk.out` whenever it's triggering any issues.

**Comment by ainar-g** [comment]
@MarkCaro, fyi, PowerShell's equivalent of `grep -e cdk.out -v` is something like `Select-String -Pattern 'cdk.out' -NotMatch`.

**Comment by dominikh** [comment]
So, my stance here is that I don't want to introduce a solution custom to Staticcheck, which is why I pointed at the other tools. In that vein, the primary solution is to use `grep -v`, or the lovely PowerShell equivalent.

> I don't run go test ./... from the project's root folder

Why is that not an option for Staticcheck?

> I don't run go vet manually because I use VS Code, which does it automatically.

You can run Staticcheck from VS Code, too.

One Staticcheck-specific workaround, which I don't necessarily recommend, would be to place a `staticcheck.conf` file in the `cdk.out` directory [that specifies that no checks should be run](https://staticcheck.io/docs/configuration/options/#checks).
