### ISSUE TITLE
U1000 with any unused internal

### ISSUE THREAD

**Issue by 89z** [dominikh/go-tools#1320]
~~~
staticcheck.exe 2022.1.3 (v0.3.3)
~~~

If I have layout like this:

~~~
go.mod
hello.go
internal\internal.go
~~~

Internal looks like this:

~~~go
package internal

const World = 1
~~~

and hello looks like this:

~~~go
package hello
import "hello/internal"

func Greet() int {
   return internal.World
}
~~~

With this setup, StaticCheck returns nothing, as expected:

~~~
staticcheck.exe ./...
~~~

but if I change hello:

~~~go
package hello

func Greet() int {
   return 1
}
~~~

I still get nothing from StaticCheck. I would expect it to report that `World` is not used, like this:

~~~
const World is unused (U1000)
~~~

**Comment by 89z** [comment]
Note I understand that StaticCheck ignores exported items, but technically no one can access the items outside of the package, so I think StaticCheck should be reporting anything internal that is not actually used, regardless if its exported or not

**Comment by dominikh** [comment]
This is conceptually no different from "normal" exported identifiers. Internal trees merely limit who can import a package. As such the reasons for the removal of whole-program mode in 5cfc85b70e7b778eb76fd7338e538d7c9af21e4e apply here, too.

This is also not something we could do without a whole-program mode, as `staticcheck ./...` and `staticcheck ./foo; staticcheck ./bar; ...` are the same, and just by looking at the internal package we cannot tell whether it is used by other packages or not.
