### ISSUE TITLE
Flag usage of {strings, bytes}.Index with single character constant literal

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#1322]
Though manual code review, it was been apparent to me that the usage of `strings.Index(str, "c")` and `bytes.Index(str, []byte('c')` (or even `[]byte("c")` for the latter) is very much a common thing. The usage of `{strings,bytes}.IndexByte(str, 'c')` would be a better choice in this case.

I believe that this would be a good check for staticcheck as the percentage of false positives will be minimal; if we only consider the ones with constant string or byte literals.

I would like this to then catch both declared constants as well as literals passed directly to the function, if possible.

**Comment by dgryski** [comment]
Note that `strings.Index` with a single character string dispatches to `IndexByte` already.

**Comment by dominikh** [comment]
See https://github.com/dominikh/go-tools/issues/1007#issue-899684879 and https://github.com/dominikh/go-tools/commit/440ad19b0e9cf67333d7ba95f934a4e7f8a899cc for why we're not making that suggestion.
