### ISSUE TITLE
purity analyzer calls ExportObjectFact on a function from another package ->  crash

### ISSUE THREAD

**Issue by adonovan** [dominikh/go-tools#1327]
gopls includes the purity analyzer, and we have observed a crash in it on our builder:
https://storage.googleapis.com/go-build-log/515e3de2/openbsd-amd64-70_80afd8ab.log
```

panic: internal error: in analysis fact_purity of package golang.org/lsptests/rename/issue42134: Fact.Set(func golang.org/lsptests/rename/issue42134.min(a int, b int) int, *purity.IsPure): can't set facts on objects belonging another package [recovered]

goroutine 94667 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.actionImpl.func9.1()
	/tmp/workdir/gopath/src/golang.org/x/tools/gopls/internal/lsp/cache/analysis.go:371 +0x167
panic({0xd831a0, 0xc008d386f0})
	/tmp/workdir/go/src/runtime/panic.go:884 +0x213
golang.org/x/tools/gopls/internal/lsp/cache.actionImpl.func4({0x1130c38, 0xc004cdeba0}, {0x11216a0?, 0x16e2490})
	/tmp/workdir/gopath/src/golang.org/x/tools/gopls/internal/lsp/cache/analysis.go:317 +0x1fd
honnef.co/go/tools/analysis/facts/purity.purity.func1.1()
	/tmp/workdir/gopath/pkg/mod/honnef.co/go/tools@v0.3.3/analysis/facts/purity/purity.go:83 +0x49
honnef.co/go/tools/analysis/facts/purity.purity.func1(0xc003869180)
	/tmp/workdir/gopath/pkg/mod/honnef.co/go/tools@v0.3.3/analysis/facts/purity/purity.go:167 +0x47f
honnef.co/go/tools/analysis/facts/purity.purity(0xc000b848f0)
	/tmp/workdir/gopath/pkg/mod/honnef.co/go/tools@v0.3.3/analysis/facts/purity/purity.go:170 +0x182
golang.org/x/tools/gopls/internal/lsp/cache.actionImpl.func9(0xc0029d7c30, 0xc000b848f0?, 0x0?, 0xc0029d7c10, 0xdce360?)
	/tmp/workdir/gopath/src/golang.org/x/tools/gopls/internal/lsp/cache/analysis.go:378 +0x7b
golang.org/x/tools/gopls/internal/lsp/cache.actionImpl({0x11282c0, 0xc0052d0980}, 0xc007389680, {0xc004bdaa00, 0x1, 0x1?}, 0x169a2c0, 0xc0028f7a40)
	/tmp/workdir/gopath/src/golang.org/x/tools/gopls/internal/lsp/cache/analysis.go:379 +0xa6c
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).actionHandle.func1({0x11282c0?, 0xc0052d0980?}, {0xec0fc0?, 0xc007389680?})
	/tmp/workdir/gopath/src/golang.org/x/tools/gopls/internal/lsp/cache/analysis.go:166 +0x5a
golang.org/x/tools/internal/memoize.(*Promise).run.func2.1()
...
```

The cause is that the purity analyzer is recursively calling check on functions called by the package:

https://github.com/dominikh/go-tools/blob/v0.3.3/analysis/facts/purity/purity.go#L124

and each call to check exports an object fact for the checked function:

https://github.com/dominikh/go-tools/blob/v0.3.3/analysis/facts/purity/purity.go#L83

even for functions outside package being analyzed. This violates a precondition of ExportObjectFact, causing some driver implementations such as gopls to crash.

The fix is to check the package matches Pass.Pkg before calling ExportObjectFact. Perhaps  the gopls driver would be more robust if it simply discarded such facts rather than panicked.

**Comment by dominikh** [comment]
Hm, shouldn't line 70 in that file handle the case of functions in other packages? `check` only exports facts after line 81, and line 70 returns if the function is from a different package. It should, anyway.

**Comment by adonovan** [comment]
You're absolutely right--sorry for impugning your code when the bug was in ours.

In light of this point, the crash can be explained as yet another consequence of a known bug in the gopls driver, which returns stale versions of results of other analyzers such as buildir and inspector, leading to inconsistencies between syntax and types (and other data structures).
