### ISSUE TITLE
Feature: enforce map guard when it's necesarry 

### ISSUE THREAD

**Issue by mattysweeps** [dominikh/go-tools#1328]
The following code sample highlights an issue where a map reference was unchecked (did not check ok == true) resulting in a nil pointer panic. https://go.dev/play/p/XwjkvaEshlu

I looked at golangci-lint's linters but couldn't tell if this is already solved by existing linters. I tested with golangci-lint 1.50.0 with flags --max-issues-per-linter 0 --enable-all --verbose but did not see any lint results related to the unsafe map usage.

I checked [staticcheck's docs](https://staticcheck.io/docs/checks) and found related lint rules:

- SA5000	Assignment to nil map
- S1036	Unnecessary guard around map access

But no rule to enforce the guard when it's necessary (inverse of S1036)

**Comment by dominikh** [comment]
I'm afraid this is out of scope for Staticcheck. We cannot tell if another code path or convention guarantees that the key exists in the map, rendering the guard unnecessary. Eagerly enforcing the use of guards would thus lead to false positives. Staticcheck only aims to flag code that is guaranteed to be problematic, not that _could_ be problematic.
