### ISSUE TITLE
staticcheck: cgo: SA4001 False Positive

### ISSUE THREAD

**Issue by pquerna** [dominikh/go-tools#133]
I think there are conditions under which SA4001 is being triggered, but the suggested fix isn't viable under `cgo`:

```
main.go:8:35: &*x will be simplified to x. It will not copy x. (SA4001)
```

example:

```
package main

// #cgo LDFLAGS: -framework CoreFoundation
// #include <CoreFoundation/CoreFoundation.h>
import "C"

func main() {
	_ = C.CFArrayCreateMutable(C.kCFAllocatorDefault, 0, &C.kCFTypeArrayCallBacks)

	// this is a compile error:
	// _ = C.CFArrayCreateMutable(C.kCFAllocatorDefault, 0, C.kCFTypeArrayCallBacks)
}
```

**Comment by dominikh** [comment]
I do not see any occurrence of `&*` in the code you quoted. While it is possible that we mess up on code rewritten by cgo, I'd like you to confirm that this is indeed the code that triggered the warning. And if so, could you write a minimal example reproducing the issue that only depends on the libc? I don't run OS X and thus don't have those headers.

**Comment by shurcooL** [comment]
I can confirm the above program, despite not having `&*` in the visible source code, produces the following output with latest version of `staticcheck`:

```
$ staticcheck
main.go:8:35: &*x will be simplified to x. It will not copy x. (SA4001)
```

**Comment by pquerna** [comment]
The following gist reproduces the error for me:

https://gist.github.com/pquerna/f890b37c54ab7a60dced5705ebd3589d

It's definitely possible to reduce this more I think, this is mostly just doing what `CFArrayCreateMutable` was doing but without macOS dependencies

**Comment by dominikh** [comment]
Thank you, that should do.
