### ISSUE TITLE
err is never used (SA4006)  go-staticcheck

### ISSUE THREAD

**Issue by adityaw24** [dominikh/go-tools#1331]
err is used, but not with the output

		var req *http.Request
		var err error

		req, err = http.NewRequest(http.MethodPost, endpoint, bytes.NewBuffer(body))
		req.Header.Add("SenderService", "Port")
		_, err = client.Do(req)

		if err != nil {
			utils.PushLogf("[ERROR_EMAIL] => sendEmail() : ", err)
		} else {
			utils.PushLogf("[SUCCESS_SEND_EMAIL] => sendEmail() : ", data)
		}

		return err == nil, err

**Comment by dominikh** [comment]
Please follow the [issue template](https://github.com/dominikh/go-tools/issues/new?assignees=&labels=false-positive%2C+needs-triage&template=1_false_positive.md&title=) and provide all the information it is asking for. Please provide a self-contained piece of code that compiles and demonstrates the problem.
