### ISSUE TITLE
Question about conventional usage regarding SA6002

### ISSUE THREAD

**Issue by mholt** [dominikh/go-tools#1336]
Just wanted to ask for your advice regarding the most conventional way to handle SA6002, `argument should be pointer-like to avoid allocations`

I have a pool:

```
var pool = sync.Pool{
	New: func() any {
		return make([]byte, 512)
	},
}
```

which results in this warning here:

```
buf := pool.Get().([]byte)
```

because it is not a pointer. I've read the previous issues and linked CL:

- https://github.com/dominikh/go-tools/issues/302
- https://github.com/dominikh/go-tools/issues/1078
- https://github.com/dominikh/go-tools/issues/1042
- https://go-review.googlesource.com/c/go/+/24371

and it's clear to me that a slice is not a pointer. However, now I have a pointer to a slice, which is almost never used in Go.

Should I really be dereferencing this thing everywhere?

It also makes the slice harder to work with, i.e. `*buf[:n]` isn't valid syntax, so I need to use `(*buf)[:n]` which is... fine. :upside_down_face: 

And the `New` function now looks like this:

```
New: func() any {
	buf := make([]byte, 512)
	return &buf
},
```

This just feels so... wrong... to me.

Do you have a recommendation for a better way to pool byte slices? Or is this really the way we're expected to do it? I just need some reassurance as this goes against my decade of conventional Go wisdom.

Is the pool completely ineffective if we use `[]byte` instead of `*[]byte`? I'm normally OK with shuffling `[]byte` values around instead of pointers. Can you help me understand exactly what I'm losing by using `[]byte`?

PS. Thanks for staticcheck, it's awesome every day.

**Comment by dominikh** [comment]
Using a non-pointer doesn't render the pool entirely ineffective, but it means that every time we put an element back into the pool, Go allocates to create the interface value. We deem this a misuse, because if you're using sync.Pool you probably want to avoid unnecessary allocations.

Pointers to slices are incredibly awkward, but I think this pattern from crypto/tls should work most of the time (either via the `defer`, or more manually.)

```
        outBufPtr := outBufPool.Get().(*[]byte)
        outBuf := *outBufPtr
        defer func() {
                // You might be tempted to simplify this by just passing &outBuf to Put,
                // but that would make the local copy of the outBuf slice header escape
                // to the heap, causing an allocation. Instead, we keep around the
                // pointer to the slice header returned by Get, which is already on the
                // heap, and overwrite and return that.
                *outBufPtr = outBuf
                outBufPool.Put(outBufPtr)
        }()
```

**Comment by mholt** [comment]
Thank you! That's great information.

Why does it do `*outBufPtr = outBuf`? Why not just use what the existing `outBufPtr` var?
