### ISSUE TITLE
New style check "mixing pointer and value receivers"

### ISSUE THREAD

**Issue by nikolaydubina** [dominikh/go-tools#1337]
## what?

similar to https://github.com/nikolaydubina/smrcptr

## why?

Go has rules on how it can automatically select value and method receivers, which is complex and can lead to bugs. 

Official Go [guideline](https://github.com/golang/go/wiki/CodeReviewComments#receiver-type) recommends:

> Don't mix receiver types. Choose either pointers or struct types for all available methods.

Google Go style guide: https://google.github.io/styleguide/go/decisions#receiver-type

## approach

Probably similar to https://github.com/dominikh/go-tools/blob/master/stylecheck/lint.go#L295

I can implement in free time too.

🙇🏻‍♂️

**Comment by dominikh** [comment]
This is out of scope for Staticcheck on account of false positives; I don't think the guideline is universally true. It would certainly flag some exported APIs in the Go standard library.

**Comment by ainar-g** [comment]
This wouldn't be as straightforward because some interfaces *de facto* require a value or a pointer receiver.  Most notably, the (un)marshaling ones.  See #911 and the issues mentioned there.
