### ISSUE TITLE
Homebrew: does not pass test on Go 1.20

### ISSUE THREAD

**Issue by andig** [dominikh/go-tools#1342]
The test is:

    (testpath/"test.go").write <<~EOS
      package main
      import "fmt"
      func main() {
        var x uint
        x = 1
        fmt.Println(x)
      }
    EOS
    json_output = JSON.parse(shell_output("#{bin}/staticcheck -f json test.go", 1))
    assert_equal json_output["code"], "S1021"

`cannot import \"internal/goarch\" (unknown bexport format version -1 (\"u\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x003\\x00\\x00\\x005\\x00\\x00\\x007\\x00\\x00\\x008\\x00\\x00\\x00e\\x00\\x00\\x00j\\x00\\x00`

Not sure if this is really a `staticcheck` or a `homebrew` issue. Please close if off-topic here.

Refs https://github.com/Homebrew/homebrew-core/pull/117643

**Comment by dominikh** [comment]
I cannot deduce which version of Staticcheck you're using, but the latest release isn't expected to work with Go 1.20rc1 – for that you will need to use the master branch for now. A new Staticcheck release isn't planned until Go 1.20 releases.

**Comment by andig** [comment]
Thank you. Seems homebrew will need to pin 1.19 for time being.

**Comment by billinghamj** [comment]
@dominikh Go 1.20 has now been released. We're working on the release PR for Homebrew (https://github.com/Homebrew/homebrew-core/pull/122082) - are you ready to release the new version?

**Comment by dominikh** [comment]
@billinghamj A new version will be released tomorrow.
