### ISSUE TITLE
(SA4006)go-staticcheck

### ISSUE THREAD

**Issue by icza** [dominikh/go-tools#1346]
The following code gives a false positive:

	v := time.Now().Second() == 1

	var r io.Reader
	if time.Now().Day() == 1 {
		r = &bytes.Buffer{}
	}
	if _, ok := r.(*bytes.Buffer); ok {
		if v {
			return
		}
	}

Output:

> this value of v is never used (SA4006)go-staticcheck

Versions:

```
$ staticcheck -version
staticcheck 2022.1.3 (v0.3.3)

$ staticcheck 2022.1.3 (v0.3.3)

Compiled with Go version: go1.19
Main module:
	honnef.co/go/tools@v0.3.3 (sum: h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=)
Dependencies:
	github.com/BurntSushi/toml@v0.4.1 (sum: h1:GaI7EiDXDRfa8VshkTj7Fym7ha+y8/XxIgD2okUIjLw=)
	golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e (sum: h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=)
	golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 (sum: h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=)
	golang.org/x/sys@v0.0.0-20211019181941-9d821ace8654 (sum: h1:id054HUawV2/6IGm2IV8KZQjqtwAOo2CYlOToYqa0d0=)
	golang.org/x/tools@v0.1.11-0.20220513221640-090b14e8501f (sum: h1:OKYpQQVE3DKSc3r3zHVzq46vq5YH7x8xpR3/k9ixmUg=)

$ go version
go version go1.19.3 linux/amd64
```

I use VSCode, static check is run automatically on save.

**Comment by dominikh** [comment]
That's confusing for sure (see #954), but it's technically not a false positive if that code is the entirety of a function, because the last two if statements and the `return` statement are irrelevant as we're going to return at the end of the function, anyway.

That is, while your code triggers SA4006, the following code doesn't:

```
func foo() {
	v := time.Now().Second() == 1

	var r io.Reader
	if time.Now().Day() == 1 {
		r = &bytes.Buffer{}
	}
	if _, ok := r.(*bytes.Buffer); ok {
		if v {
			return
		}
	}
	println("we got here.")
}
```

**Comment by icza** [comment]
OK, that makes sense. My example was a simplification of a more complex code.

However, the following code is a variant of it, and it still gives a false positive:

	var r io.Reader
	rs := []io.Reader{r}
	if time.Now().Day() == 1 {
		rs = append(rs, &bytes.Buffer{})
	}
	if time.Now().Weekday() == 1 {
		rs = append(rs, &bufio.Reader{})
	}

	v := time.Now().Second() == 1

	for _, r := range rs {
		switch r.(type) {
		case *bytes.Buffer, *bufio.Reader:
			if time.Now().Day() == 1 {
				fmt.Println("hi")
				if v {
					break
				}
			}
		}
	}

Here it does matter if `v` is used because it breaks from the loop, and more iterations will be executed, hence the number of printed `"hi"` messages matters.
