### ISSUE TITLE
staticcheck: don't flag infinite recursion for goroutines

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#135]
```
func fn() {
	go fn()
}
```

gets flagged with

```
infinite recursive call (SA5007)
```

but that's not true, because the goroutine gets its own stack. 

Discovered by Jud White

**Comment by shurcooL** [comment]
Isn't that still infinite recursion? Or is it a false positive when there is more code inside `fn` that performs logic (potentially exiting early)?

**Comment by dominikh** [comment]
Infinite recursion isn't a problem in itself (it might be, but it doesn't have to) any more than an infinite loop is. The reason we warn about infinite recursion is that Go doesn't implement TCO, and thus you will eventually run out of memory. However, that problem doesn't apply to spawning new goroutines.
