### ISSUE TITLE
False positive U1000?

### ISSUE THREAD

**Issue by MaximMolchanov** [dominikh/go-tools#1372]
Let's say we have two files:
```
package main

func foo() int {
	return 0
}

func main() {
}
```

and

```
//go:build sometag

package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestFoo(t *testing.T) {
	assert.Equal(t, 0, foo())
}
```

Is `foo()` unused?

```
$ staticcheck -f binary > tmp1
$ staticcheck -tags=sometag -f binary > tmp2
$ staticcheck -merge tmp1 tmp2
main.go:3:6: func foo is unused (U1000)
```

But is it?

We can move `foo()` to the second file, but is it correct to mark it as unused in such case? If yes, then why do we need merge at all?

**Comment by MaximMolchanov** [comment]
Anyway if we say that if function is used only in tests is still unused, then without tag:
```
package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestFoo(t *testing.T) {
	assert.Equal(t, 0, foo())
}

```

It also should be unused, right? But it is not:
```
$ staticcheck 
$ 
```

**Comment by dominikh** [comment]
I'll have to investigate this. At first glance the behavior in your first comment seems incorrect.
