### ISSUE TITLE
unused - nolint directives should work transitively on call chains

### ISSUE THREAD

**Issue by sergei-dyshel** [dominikh/go-tools#1373]
Using `golangci-lint`  version v1.51.2. Consider the following code:
```go
package lego

func a() {}

func b() {
	a()
}

func c() {
	b()
}
```
There is an `a -> b -> c` call chain here, where `a` and `b` are called by `c` only.  In this example all of `a`, `b`, `c` will be reported as unused.  But if I only mark `c` with `//nolint:unused` directive, then `a` and `b` will be still reported as unused.  I think this is  incorrect behavior and it makes sense to transitively extend `nolint` to dependent callees like `a` and `b`.

**Comment by dominikh** [comment]
This works correctly with the official `staticcheck` command and Staticcheck's own `//lint:ignore` directive:

```
package lego

func a() {}

func b() {
	a()
}

//lint:ignore U1000 For some reason we want to keep this.
func c() {
	b()
}

func d() {}
```

```
$ staticcheck foo.go
foo.go:14:6: func d is unused (U1000)
```

What you are describing is a shortcoming in golangci-lint.
