### ISSUE TITLE
False "this value of boolValue is never used (SA4006)" in loop

### ISSUE THREAD

**Issue by cgang** [dominikh/go-tools#1380]
staticcheck 2023.1.2 (v0.4.2) reports following warning:
> check.go:7:6: this value of boolValue is never used (SA4006)

with following code:
```
package foo

func Func(f func(int) (bool, error)) {
	var err error
	for i := 0; i < 5; i++ {
		var boolValue bool
		if boolValue, err = f(i); err == nil {
			return
		} else if boolValue {
			continue
		}
	}
}
```
go version go1.20.1 linux/amd64

staticcheck -debug.version

staticcheck 2023.1.2 (v0.4.2)

Compiled with Go version: go1.20.1
Main module:
        honnef.co/go/tools@v0.4.2 (sum: h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=)
Dependencies:
        github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
        golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
        golang.org/x/mod@v0.7.0 (sum: h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=)
        golang.org/x/sys@v0.3.0 (sum: h1:w8ZOecv6NaNa/zC8944JTU3vz4u6Lagfk4RPQxv92NQ=)
        golang.org/x/tools@v0.4.1-0.20221208213631-3f74d914ae6d (sum: h1:9ZNWAi4CYhNv60mXGgAncgq7SGc5qa7C8VZV8Tg7Ggs=)

**Comment by dominikh** [comment]
The diagnostic isn't very clear (see #954), but it is correct. Whether or not your else branch executes, the behavior is the same: the loop will go for another iteration or terminate. 

```
for i := 0; i < 5; i++ {
	var boolValue bool
	if boolValue, err = f(i); err == nil {
		return
	} else if boolValue {
		continue
	}
}
```

is semantically equivalent to the following, because we can say that a loop body implicitly ends with `continue`:

```
for i := 0; i < 5; i++ {
	var boolValue bool
	if boolValue, err = f(i); err == nil {
		return
	} else if boolValue {
		continue
	}
	continue
}
```

which itself is equivalent to

```
	for i := 0; i < 5; i++ {
		var boolValue bool
		if boolValue, err = f(i); err == nil {
			return
		}
	}
```

which clearly demonstrates why the value assigned to `boolValue` doesn't matter.
