### ISSUE TITLE
"build system did not supply embed configuration" for stdlib package

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#1381]
When running staticcheck against my project (github.com/kevinburke/rest) I get the following error:

```
-: # crypto/internal/nistec
../../../../go/src/crypto/internal/nistec/p256_asm.go:322:3: invalid go:embed: build system did not supply embed configuration (compile)
```

I'm running Go tip (commit b94dc384cabf75e7e8703265cd80f5324f84b642) on a Mac, and staticcheck tip (commit cc140e9b3719aadd3b628b7a7b00523681c8b34d). I'm not sure if this is an error that should be filed against the standard library and unfortunately don't have time to investigate further.

**Comment by kevinburke** [comment]
mentioning @filosottile since I believe you added the crypto/internal/nistec package

**Comment by dominikh** [comment]
I doubt this is the fault of the package author. Bisection points to https://github.com/golang/go/commit/c0ac33c00614a2f36c88671ef7c520d246cd8bc9, which at least looks like it fits. I'll have to investigate further to find out if this is a bug in cmd/go or if go/packages needs to be adapted.

**Comment by dominikh** [comment]
This is now tracked upstream at https://github.com/golang/go/issues/58885.

**Comment by dominikh** [comment]
Fixed by https://github.com/golang/go/commit/6615324f79bf16e1c81951c9a18e51d1908f2698
