### ISSUE TITLE
Panic while using unused -exported-is-used flag

### ISSUE THREAD

**Issue by rprtr258** [dominikh/go-tools#1385]
I'm trying to find unused exported symbols using `unused` linter. I've seen https://github.com/dominikh/go-tools/issues/227 which says to use `-exported` flag. `unused --help` didn't show `-exported` flag, but showed `-exported-fields-are-used` and `-exported-is-used`. So it seemed to me that I need to run
```bash
go run -mod=mod honnef.co/go/tools/cmd/unused -exported-is-used=false ./...
```

But this gives
```
new node, remapping 0 -> 1
new node, remapping 1 -> 2
panic: object "int" has no path but also no column information

goroutine 1 [running]:
honnef.co/go/tools/unused.(*SerializedGraph).Merge(0xc000175c80, {0xc00046c000, 0x11, 0xc0000124e8?})
	/home/rprtr258/.gvm/pkgsets/go1.19.5/global/pkg/mod/honnef.co/go/tools@v0.4.3/unused/serialize.go:52 +0xdfe
main.main()
	/home/rprtr258/.gvm/pkgsets/go1.19.5/global/pkg/mod/honnef.co/go/tools@v0.4.3/cmd/unused/unused.go:69 +0x445
```

The project I am running `unused` is just single test `main.go`:
```go
package main

import "fmt"

var unusedGlobalVar int
var UnusedGlobalVar2 int
var usedGlobalVar int
var UsedGlobalVar2 int

type unusedStruct struct{}
type UnusedStruct2 struct{}
type usedStruct struct{}
type UsedStruct2 struct{}

func unusedFunc()  {}
func UnusedFunc2() {}
func usedFunc()    {}
func UsedFunc2()   {}

func init() {
	usedFunc()
	UsedFunc2()
}

func main() {
	fmt.Println(usedGlobalVar, UsedGlobalVar2, usedStruct{}, UsedStruct2{})
}
```

**Comment by dominikh** [comment]
`cmd/unused` is a prototype that shouldn't have been pushed to the master branch. The only supported way to run the check is via `staticcheck`, and flagging unused exported API is not yet supported. The issue you're referring to is outdated. There used to be an `unused` tool, and it used to support finding exported API, but that hasn't been the case for many years. https://staticcheck.io/changes/2020.2/#unused-whole-program documents when and why flagging exported API has been removed.

It may be added back in the future, but there is no roadmap for that.
