### ISSUE TITLE
 when i run staticcheck $() command i have this problem

### ISSUE THREAD

**Issue by faridjabbar** [dominikh/go-tools#1387]
when i run staticcheck $() command i have this problem :
-: # github.com/ugorji/go/codec
open ../../../go/pkg/mod/github.com/ugorji/go/codec@v1.1.7/helper.go: no such file or directory (compile)
-: cannot import "internal/cpu" (unexpected escape sequence in export data), possibly version skew - reinstall package (compile)
-: cannot import "internal/goarch" (unknown bexport format version -1 ("u\x01\x00\x00\x00\x00\x00\x00\x003\x00\x00\x005\x00\x00\x007\x00\x00\x008\x00\x00\x00e\x00\x00\x00j\x00\x00\x00\x97\x00\x00\x00\xc4\x00\x00\x00\xf1\x00\x00\x00\xf1\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x15\x00\x00\x00:\x00\x00\x00H\x00\x00\x00M\x00\x00\x00P\x00\x00\x00U\x00\x00\x00_\x00\x00\x00h\x00\x00\x00{\x00\x00\x00\xa7\x00\x00\x00\xac\x00\x00\x00\xb2\x00\x00\x00\xb6\x00\x00\x00\xc0\x00\x00\x00\xc5\x00\x00\x00\xcc\x00\x00\x00\xd6\x00\x00\x00\xdb\x00\x00\x00\xe2\x00\x00\x00\xeb\x00\x00\x00\xf2\x00\x00\x00\xfb\x00\x00\x00\x01\x01\x00\x00\t\x01\x00\x00\x13\x01\x00\x00\x1e\x01\x00\x00+\x01\x00\x003\x01\x00\x008\x01\x00\x00?\x01\x00\x00H\x01\x00\x00O\x01\x00\x00X\x01\x00\x00^\x01\x00\x00e\x01\x00\x00l\x01\x00\x00u\x01\x00\x00{\x01\x00\x00\x82\x01\x00\x00\x86\x01\x00\x00\x8c\x01\x00\x00\x98\x01\x00\x00\xa1\x01\x00\x00\xa6\x01\x00\x00\xad\x01\x00\x00\xb4\x01\x00\x00\xb9\x01\x00\x00\xc3\x01\x00\x00\xc7\x01\x00\x00\xae\x02\x00\x00\xb1\x02\x00\x00\xb6\x02\x00\x00\xbb\x02\x00\x00\xc5\x02\x00\x00\xcd\x02\x00\x00\xd5\x02\x00\x00\xdd\x02\x00\x00\xe5\x02\x00\x00\xed\x02\x00\x00\xf5\x02\x00\x00\xfd\x02\x00\x00\x05\x03\x00\x00\r\x03\x00\x00\x15\x03\x00\x00\x1d\x03\x00\x00%\x03\x00\x00-\x03\x00\x005\x03\x00\x00=\x03\x00\x00E\x03\x00\x00M\x03\x00\x00U\x03\x00\x00]\x03\x00\x00e\x03\x00\x00m\x03\x00\x00u\x03\x00\x00}\x03\x00\x00\x85\x03\x00\x00\x8d\x03\x00\x00\x95\x03\x00\x00\x9d\x03\x00\x00\xa5\x03\x00\x00\xad\x03\x00\x00\xb5\x03\x00\x00\xbd\x03\x00\x00\xc5\x03\x00\x00\xcd\x03\x00\x00\xd5\x03\x00\x00\xdd\x03\x00\x00\xe5\x03\x00\x00\xed\x03\x00\x00\xf5\x03\x00\x00\xfd\x03\x00\x00\x05\x04\x00\x00\r\x04\x00\x00\x15\x04\x00\x00\x1d\x04\x00\x00%\x04\x00\x00-\x04\x00\x004\x04\x00\x007\x04\x00\x00:\x04\x00\x00=\x04\x00\x00@\x04\x00\x00N\x04\x00\x00Z\x04\x00\x00h\x04\x00\x00v\x04\x00\x00\x84\x04\x00\x00\x92\x04\x00\x00\xa1\x04\x00\x00\xb1\x04\x00\x00\xbf\x04\x00\x00\xcd\x04\x00\x00\xdb\x04\x00\x00\xe9\x04\x00\x00\xf7\x04\x00\x00\x05\x05\x00\x00\x13\x05\x00\x00!\x05\x00\x00/\x05\x00\x00=\x05\x00\x00K\x05\x00\x00Y\x05\x00\x00g\x05\x00\x00u\x05\x00\x00\x83\x05\x00\x00\x91\x05\x00\x00\x9f\x05\x00\x00\xad\x05\x00\x00\xbb\x05\x00\x00\xc9\x05\x00\x00\xd7\x05\x00\x00\xe5\x05\x00\x00\xf3\x05\x00\x00\x01\x06\x00\x00\x0f\x06\x00\x00\x1d\x06\x00\x00+\x06\x00\x009\x06\x00\x00G\x06\x00\x00U\x06\x00\x00c\x06\x00\x00q\x06\x00\x00\u007f\x06\x00\x00\x8d\x06\x00\x00\x9b\x06\x00\x00\xa9\x06\x00\x00\xb7\x06\x00\x00\xb8\x06\x00\x00\xbc\x06\x00\x00\xbd\x06\x00\x00\xbe\x06\x00\x00\xbf\x06\x00\x00\xc0\x06\x00\x00\xc1\x06\x00\x00\xc2\x06\x00\x00\xc3\x06\x00\x00\xc4\x06\x00\x00\xc5\x06\x00\x00\xc6\x06\x00\x00\xc7\x06\x00\x00\xc8\x06\x00\x00\xc9\x06\x00\x00\xca\x06\x00\x00\xcb\x06\x00\x00\xcc\x06\x00\x00\xcd\x06\x00\x00\xce\x06\x00\x00\xcf\x06\x00\x00\xd0\x06\x00\x00\xd1\x06\x00\x00\xd2\x06\x00\x00\xd3\x06\x00\x00\xd4\x06\x00\x00\xd5\x06\x00\x00\xd6\x06\x00\x00\xd7\x06\x00\x00\xd8\x06\x00\x00\xd9\x06\x00\x00\xda\x06\x00\x00\xdb\x06\x00\x00\xdc\x06\x00\x00\xdd\x06\x00\x00\xde\x06\x00\x00\xdf\x06\x00\x00\xe0\x06\x00\x00\xe1\x06\x00\x00\xe2\x06\x00\x00\xe3\x06\x00\x00\xe4\x06\x00\x00\xe5\x06\x00\x00\xe6\x06\x00\x00\xe7\x06\x00\x00\xef\x06\x00\x00\xf7\x06\x00\x00\xff\x06\x00\x00\a\a\x00\x00\x0f\a\x00\x00\x17\a\x00\x00\x1f\a\x00\x00'\a\x00\x00/\a\x00\x007\a\x00\x00?\a\x00\x00G\a\x00\x00O\a\x00\x00W\a\x00\x00_\a\x00\x00g\a\x00\x00o\a\x00\x00w\a\x00\x00\u007f\a\x00\x00\x87\a\x00\x00\x8f\a\x00\x00\x97\a\x00\x00\x9f\a\x00\x00\xa7\a\x00\x00\xaf\a\x00\x00\xb7\a\x00\x00\xbf\a\x00\x00\xc7\a\x00\x00\xcf\a\x00\x00\xd7\a\x00\x00\xdf\a\x00\x00\xe7\a\x00\x00\xef\a\x00\x00\xf7\a\x00\x00\xff\a\x00\x00\a\b\x00\x00\x0f\b\x00\x00\x17\b\x00\x00\x1f\b\x00\x00'\b\x00\x00/\b\x00\x007\b\x00\x00?\b\x00\x00G\b\x00\x00O\b\x00\x00goarchinternal/goarch$GOROOT/src/internal/goarch/goarch.goArchFamilyTypeAMD64ARMARM64ArchFamilyBigEndianDefaultPhysPageSize$GOROOT/src/internal/goarch/zgoarch_amd64.goamd64GOARCHI386Int64AlignIs386IsAmd64IsAmd64p32IsArmIsArm64IsArm64beIsArmbeIsLoong64IsMipsIsMips64IsMips64leIsMips64p32IsMips64p32leIsMipsleIsPpcIsPpc64IsPpc64leIsRiscvIsRiscv64IsS390IsS390xIsSparcIsSparc64IsWasmLOONG64MIPSMIPS64MinFrameSizePCQuantumPPC64PtrSizeRISCV64S390XStackAlignWASM.\x03\x00\x06\x00\x06\x01\x06\x02\x06\x03\x06\x04\x06\x05\x06\x06\x06\a\x06\b\x06\t\x06")), possibly version skew - reinstall package (compile)
-: cannot import "internal/goos" (unknown bexport format version -1 ("u\x01\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00\x1b\x00\x00\x00\x1d\x00\x00\x00\x1e\x00\x00\x001\x00\x00\x004\x00\x00\x00G\x00\x00\x00Z\x00\x00\x00m\x00\x00\x00m\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x11\x00\x00\x00:\x00\x00\x00@\x00\x00\x00D\x00\x00\x00I\x00\x00\x00R\x00\x00\x00Z\x00\x00\x00e\x00\x00\x00n\x00\x00\x00t\x00\x00\x00}\x00\x00\x00\x82\x00\x00\x00\x86\x00\x00\x00\x8d\x00\x00\x00\x93\x00\x00\x00\x9b\x00\x00\x00\xa4\x00\x00\x00\xab\x00\x00\x00\xb4\x00\x00\x00\xd5\x00\x00\x00\xdb\x00\x00\x00\xe4\x00\x00\x00\xe9\x00\x00\x00N\x01\x00\x00Q\x01\x00\x00V\x01\x00\x00[\x01\x00\x00e\x01\x00\x00m\x01\x00\x00u\x01\x00\x00}\x01\x00\x00\x85\x01\x00\x00\x8d\x01\x00\x00\x95\x01\x00\x00\x9d\x01\x00\x00\xa5\x01\x00\x00\xad\x01\x00\x00\xb5\x01\x00\x00\xbd\x01\x00\x00\xc5\x01\x00\x00\xcd\x01\x00\x00\xd5\x01\x00\x00\xdd\x01\x00\x00\xe5\x01\x00\x00\xed\x01\x00\x00\xf5\x01\x00\x00\xfd\x01\x00\x00\x00\x02\x00\x00\x03\x02\x00\x00\x06\x02\x00\x00\x16\x02\x00\x00$\x02\x00\x002\x02\x00\x00@\x02\x00\x00N\x02\x00\x00\\\x02\x00\x00j\x02\x00\x00x\x02\x00\x00\x86\x02\x00\x00\x94\x02\x00\x00\xa2\x02\x00\x00\xb0\x02\x00\x00\xbe\x02\x00\x00\xcc\x02\x00\x00\xda\x02\x00\x00\xe8\x02\x00\x00\xf6\x02\x00\x00\x04\x03\x00\x00\x12\x03\x00\x00\x13\x03\x00\x00\x14\x03\x00\x00\x15\x03\x00\x00\x16\x03\x00\x00\x17\x03\x00\x00\x18\x03\x00\x00\x19\x03\x00\x00\x1a\x03\x00\x00\x1b\x03\x00\x00\x1c\x03\x00\x00\x1d\x03\x00\x00\x1e\x03\x00\x00\x1f\x03\x00\x00 \x03\x00\x00!\x03\x00\x00\"\x03\x00\x00#\x03\x00\x00$\x03\x00\x00%\x03\x00\x00-\x03\x00\x005\x03\x00\x00=\x03\x00\x00E\x03\x00\x00M\x03\x00\x00U\x03\x00\x00]\x03\x00\x00e\x03\x00\x00m\x03\x00\x00u\x03\x00\x00}\x03\x00\x00\x85\x03\x00\x00\x8d\x03\x00\x00\x95\x03\x00\x00\x9d\x03\x00\x00\xa5\x03\x00\x00\xad\x03\x00\x00\xb5\x03\x00\x00\xbd\x03\x00\x00goosinternal/goos$GOROOT/src/internal/goos/zgoos_darwin.godarwinGOOSIsAixIsAndroidIsDarwinIsDragonflyIsFreebsdIsHurdIsIllumosIsIosIsJsIsLinuxIsNaclIsNetbsdIsOpenbsdIsPlan9IsSolaris$GOROOT/src/internal/goos/unix.goIsUnixIsWindowsIsZos\x14\x03\x00\x06\x00\x06\x01\x06\x02\x06\x03\x06\x04\x06\x05\x06\x06\x06\a\x06\b\x06\t\x06")), possibly version skew - reinstall package (compile)
-: cannot import "math/bits" (unknown bexport format version -1 ("u\x01\x00\x00\x00\x00\x00\x00\x00\x81\x00\x00\x00\x83\x00\x00\x00\x85\x00\x00\x00\x88\x00\x00\x00\xc0\x00\x00\x00\xe7\x00\x00\x00\x1f\x01\x00\x00W\x01\x00\x00\x8f\x01\x00\x00\xbe\x01\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00")), possibly version skew - reinstall package (compile)
-: cannot import "unicode/utf8" (unknown bexport format version -1 ("u\x01\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00@\x00\x00\x00A\x00\x00\x00C\x00\x00\x00^\x00\x00\x00w\x00\x00\x00\x92\x00\x00\x00\xad\x00\x00\x00\xc8\x00\x00\x00\xce\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x10\x00\x00\x000\x00\x00\x001\x00\x00\x008\x00\x00\x00<\x00\x00\x00=\x00\x00\x00A\x00\x00\x00K\x00\x00\x00Q\x00\x00\x00Y\x00\x00\x00_\x00\x00\x00q\x00\x00\x00u\x00\x00\x00\x83\x00\x00\x00\x87\x00\x00\x00\x88\x00\x00\x00\x9e\x00\x00\x00\xa8\x00\x00\x00\xba\x00\x00\x00\xc4\x00\x00\x00\xcc\x00\x00\x00\xcd\x00\x00\x00\xd0\x00\x00\x00\xd1\x00\x00\x00\xd6\x00\x00\x00\xd7\x00\x00\x00\xdc\x00\x00\x00\xdd\x00\x00\x00\xe1\x00\x00\x00\xe7\x00\x00\x00\xe9\x00\x00\x00\xeb\x00\x00\x00\xf6\x00\x00\x00\x02\x01\x00\x00\x03\x01\x00\x00\x04\x01\x00\x00\x05\x01\x00\x00\t\x01\x00\x00\r\x01\x00\x00\x1d\x01\x00\x00$\x01\x00\x00-\x01\x00\x00>\x01\x00\x00G\x01\x00\x00N\x01\x00\x00P\x01\x00\x00X\x01\x00\x00d\x01\x00\x00p\x01\x00\x00x\x01\x00\x00y\x01\x00\x00\x81\x01\x00\x00\x82\x01\x00\x00\x8b\x01\x00\x00\x8f\x01\x00\x00\x93\x01\x00\x00\x99\x01\x00\x00\x9e\x01\x00\x00\xa7\x01\x00\x00\xb2\x01\x00\x00?\x02\x00\x00n\x02\x00\x00s\x02\x00\x00}\x02\x00\x00\x83\x02\x00\x00\x8b\x02\x00\x00\x93\x02\x00\x00\x9b\x02\x00\x00\xa3\x02\x00\x00\xab\x02\x00\x00\xb3\x02\x00\x00\xbb\x02\x00\x00\xc3\x02\x00\x00\xcb\x02\x00\x00\xd3\x02\x00\x00\xdb\x02\x00\x00\xe3\x02\x00\x00\xeb\x02\x00\x00\xf3\x02\x00\x00\xfb\x02\x00\x00\x03\x03\x00\x00\v\x03\x00\x00\x13\x03\x00\x00\x1b\x03\x00\x00#\x03\x00\x00+\x03\x00\x003\x03\x00\x00;\x03\x00\x00C\x03\x00\x00K\x03\x00\x00S\x03\x00\x00[\x03\x00\x00a\x03\x00\x00h\x03\x00\x00o\x03\x00\x00u\x03\x00\x00x\x03\x00\x00~\x03\x00\x00\xae\x03\x00\x00\xb4\x03\x00\x00\xba\x03\x00\x00\xbd\x03\x00\x00\xc0\x03\x00\x00\xc6\x03\x00\x00\xcc\x03\x00\x00\xd2\x03\x00\x00\xd5\x03\x00\x00\xd8\x03\x00\x00\xe0\x03\x00\x00\xe7\x03\x00\x00")), possibly version skew - reinstall package (compile)
../../../go/pkg/mod/github.com/ugorji/go/codec@v1.1.7/helper.go:1:0: no such file or directory (compile)

what should I do ?

**Comment by jamespfennell** [comment]
One of my Go projects uses staticcheck and CI started failing out of the blue with the same error as posted here. The failure is not in staticcheck per se, but rather in installing staticcheck.

I have [a minimal failing CI run here](https://github.com/jamespfennell/transiter/actions/runs/4537554100/jobs/7995523309). This CI run just installs Go and then tries to install staticcheck version 2022.1 and this fails.

If I use staticcheck version 2023.1 the error goes away, which is what I'm going to do. Maybe the OP is also running an old version of staticcheck. To me this seems like a bug in Go, and my Googling pulled up this issue: https://github.com/golang/go/issues/51836.

### The output of 'go version'

```
go version go1.20.2 linux/amd64
```

### The output of 'go env'

```
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org/,direct"
  GOROOT="/opt/hostedtoolcache/go/1.20.2/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.20.2/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.20.2"
  GCCGO="gccgo"
  GOAMD64="v1"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/transiter/transiter/go.mod"
  GOWORK=""
  CGO_CFLAGS="-O2 -g"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-O2 -g"
  CGO_FFLAGS="-O2 -g"
  CGO_LDFLAGS="-O2 -g"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2692770615=/tmp/go-build -gno-record-gcc-switches"
```

### Exactly which command you ran

```\
go install honnef.co/go/tools/cmd/staticcheck@2022.1
```

### Output of the command and what's wrong with the output

```
go: downloading honnef.co/go/tools v0.3.0
go: downloading golang.org/x/tools v0.1.11-0.20220316014157-77aa08bb151a
go: downloading golang.org/x/exp/typeparams v0.0.0-20220218215828-6cf2b201936e
go: downloading github.com/BurntSushi/toml v0.4.1
go: downloading golang.org/x/sys v0.0.0-20211019181941-9d821ace8654
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3
-: cannot import "internal/cpu" (unexpected escape sequence in export data), possibly version skew - reinstall package (compile)
-: cannot import "internal/goarch" (unknown bexport format version -1 ("u\x01\x00\x00\x00\x00\x00\x00\x003\x00[truncated by jamespfennell@]\x00\x005\x00\x00goarchinternal/goarch$GOROOT/src/internal/goarch/goarch.goArchFamilyTypeAMD64ARMARM64ArchFamilyBigEndianDefaultPhysPageSize$GOROOT/src/internal/goarch/zgoarch_amd64.goamd64GOARCHI386Int64AlignIs386IsAmd64IsAmd64p32IsArmIsArm64IsArm64beIsArmbeIsLoong64IsMipsIsMips64IsMips64leIsMips64p32IsMips64p32leIsMipsleIsPpcIsPpc64IsPpc64leIsRiscvIsRiscv64IsS390IsS390xIsSparcIsSparc64IsWasmLOONG64MIPSMIPS64MinFrameSizePCQuantumPPC64PtrSizeRISCV64S390XStackAlignWASM.\x03\x00\x06\x00\x06\x01\x06\x02\x06\x03\x06\x04\x06\x05\x06\x06\x06\a\x06\b\x06\t\x06")), possibly version skew - reinstall package (compile)
-: cannot import "math/bits" (unknown bexport format version -1 ("u\x01\x00\x00\x00\x00\x00\x00\x00\x81\x00\x00\x00\x83\x00\x00\x00\x85\x00\x00\x00\x88\x00\x00\x00\xc0\x00\x00\x00\xe7\x00\x00\x00\x1f\x01\x00\x00W\x01\x00\x00\x8f\x01\x00\x00\xbe\x01\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00")), possibly version skew - reinstall package (compile)
```
