### ISSUE TITLE
staticcheck: detect unclosed io.Closer

### ISSUE THREAD

**Issue by jabley** [dominikh/go-tools#139]
[I was looking for something like Java's FindBugs for Go](https://groups.google.com/d/msg/golang-nuts/P6734K9VzNc/MBDvTfkhDQAJ).

I was going to try doing something based on [errcheck](https://github.com/kisielk/errcheck), but this seems like a better home rather than me doing a thing on my own.

```go
res, err := http.Get("http://www.google.com/robots.txt")
if err != nil {
	log.Fatal(err)
}
// This is missing a defer res.Body.Close() or similar
return ioutil.ReadAll(res.Body)
```

**Comment by dominikh** [comment]
Bit of a long-term goal because it isn't a trivial problem. (We need whole-program analysis, as well as culling of infeasible paths, to make sure we don't get swamped with false positives. It loosely falls in the same category as detecting misuse of mutexes.)

**Comment by bradleyfalzon** [comment]
This would be a significant feature, for the above example, but also to detect unclosed `sql.Rows` which causes issues only hours or days after being deployed into production.
