### ISSUE TITLE
comparing two pointer

### ISSUE THREAD

**Issue by AhmedEmad92** [dominikh/go-tools#1390]
It's better to give warning if you are checking two pointers with if condition 
like 
var a *string
var b *string 
if a==b{
// do something
}
it's better to give warning that comparing two pointers ....

**Comment by dominikh** [comment]
I'm sorry, but there are plenty of good reasons for comparing pointers for equality. This is not a good fit for Staticcheck.

As an aside, there is probably no reason for you to have pointers to strings in the first place.
