### ISSUE TITLE
staticcheck: mark ignoring of time.Time.Add result

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#1396]
I've seen this mistake in both code reviews of other people's code as well as, shamefully, in my own code.  Writing:

```go
updateTime.Add(someDuration)
```

instead of:

```go
updateTime = updateTime.Add(someDuration)
```

`Add` sounds like it could in theory alter the receiver, except for the fact that the receiver is not a pointer.  The same probably goes for `Round`, `Sub`, and `Truncate`.

**Comment by dominikh** [comment]
This should already be getting flagged as of 2013.1 / a278fff2940105ed41f3cc7953b4732aa93c25ff.

**Comment by ainar-g** [comment]
Yeah, I've just noticed it, but for some reason it didn't get triggered in my case.  I'm investigating.  Perhaps it has something to do with the fact that the latest case was in benchmarks.

**Comment by ainar-g** [comment]
Yep, `staticcheck` reports the one in the test, but not the one in the benchmark:

```go
package main_test

import (
	"testing"
	"time"
)

func f(time.Time) {}

func TestMain(t *testing.T) {
	now := time.Now()

	for i := 0; i < 100; i++ {
		now.Add(1 * time.Second)
		f(now)
	}
}

func BenchmarkMain(b *testing.B) {
	now := time.Now()

	for i := 0; i < b.N; i++ {
		now.Add(1 * time.Second)
		f(now)
	}
}
```

**Comment by ainar-g** [comment]
> Yes, the check isn't active in benchmarks.

I see.  Because of the nature of benchmarks and the fact that not all people use sink values?  If so, then I guess this issue could be closed.

**Comment by dominikh** [comment]
> and the fact that not all people use sink values?

Exactly.

I'll close this issue.
