### ISSUE TITLE
new-check: same error variable nil-checked twice w/o being reassigned

### ISSUE THREAD

**Issue by jxsl13** [dominikh/go-tools#1401]
Hi,
I have an idea for a static check that might help find other underlying issues or bugs in the code.
Should be a linter warning.
It seems to happen often that you copy and paste somewhat redundant error checking code that must be slightly modified to fit your surrounding code but you actually forget to do that necessary modification and in the end.
When both code blocks (original & pasted) are part of the same function, you check the same error at least twice without reassigning a new value to that reused error variable (err).

Would be great if this was checked.
Thanks for the great work.

**Comment by dgryski** [comment]
The `nilness` tool handles this.

https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness

**Comment by jxsl13** [comment]
is there like a vs code integration for that ?
