### ISSUE TITLE
SA5008 - Invalid struct tag: JSON tag customized option

### ISSUE THREAD

**Issue by FGYFFFF** [dominikh/go-tools#1402]
**staticcheck -version**:staticcheck 2023.1.3 (v0.4.3)
**problem**
When I customize a JSON tag for 'required', staticcheck will report a error, like blow:
```
	type CurrencyData struct {
		Amount *string `form:"amount,required" json:"amount,required" protobuf:"bytes,1,req,name=amount" query:"amount,required"`
	}
```
And staticcheck will report :
```
unknown JSON option "required" (SA5008)
```

Why are all unofficial json options reporting errors?

**Comment by dominikh** [comment]
The `json` struct tag is owned by `encoding/json`, and other packages should use their own tags. However, we do support additional tags introduced by popular alternatives to `encoding/json` that reuse the `json` tag. These need to be added on a case-by-case basis.
