### ISSUE TITLE
staticcheck runs slow on one machine, fast on another

### ISSUE THREAD

**Issue by cedws** [dominikh/go-tools#1403]
I have two machines here, my personal M1 MacBook and my work M1 MacBook. I'm running `staticcheck` in same repo, in a fresh dev environment with only Visual Studio Code, the Go extension, and the required CLI tooling installed. I created new macOS users on both machines specifically for debugging this issue.

On my personal MacBook, staticcheck completes in ~200ms:

```
$ time ~/go/bin/staticcheck
~/go/bin/staticcheck  0.19s user 0.27s system 270% cpu 0.170 total
```

On my work MacBook, it is significantly worse, at almost 2s:

```
$ time ~/go/bin/staticcheck
~/go/bin/staticcheck  0.22s user 0.37s system 31% cpu 1.888 total
```

The machines have the same version:

```
staticcheck 2023.1.3 (v0.4.3)

Compiled with Go version: go1.20.4
Main module:
        honnef.co/go/tools@v0.4.3 (sum: h1:o/n5/K5gXqk8Gozvs2cnL0F2S1/g1vcGCAx2vETjITw=)
Dependencies:
        github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
        golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
        golang.org/x/mod@v0.7.0 (sum: h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=)
        golang.org/x/sys@v0.3.0 (sum: h1:w8ZOecv6NaNa/zC8944JTU3vz4u6Lagfk4RPQxv92NQ=)
        golang.org/x/tools@v0.4.1-0.20221208213631-3f74d914ae6d (sum: h1:9ZNWAi4CYhNv60mXGgAncgq7SGc5qa7C8VZV8Tg7Ggs=)
```

Same Go version also:

```
go version go1.20.3 darwin/arm64
```

I'm testing with this repo, but it happens with any Go repository: https://github.com/cedws/iapc

Unfortunately, I believe this slowness is causing Visual Studio Code to save files with a huge delay on my work MacBook, so it's really annoying to do any development work. I also tried Sublime Text but it uses the same language server which calls staticcheck and I haven't been able to figure out how to disable it. I tried this `staticcheck.conf` in the root of the repo but it makes no difference:

```
checks = []
```

**The only key difference I can think of between the machines is that my work MacBook has Falcon installed, which is a so called "endpoint protection" anti-malware bullshit. That could have something to do with it, but I have no way to prove this.**

How can I get more information about what staticcheck is getting held up on?

Thanks.

**Comment by dominikh** [comment]
The first step would be to see if this is specific to Staticcheck. I suspect that most of the time is spent running `go list`. If you run `staticcheck` with the environment variable `GOPACKAGESDEBUG=1` set, then the first couple of lines will print the `go list` commands that get invoked, and how long they took.

If `go list` reproduces the slowdown, then I'm afraid I can't be of much more help, as I'm not familiar with debugging these issues on macOS. I'd look for the macOS equivalent to `strace` and look for the time taken by syscalls, or the equivalent to `perf` and look at what's happening in kernel space.

If `go list` doesn't reproduce it then we can discuss further.

Instead of creating new users ad nauseam you can wipe/move aside the relevant caches; which should be found in `$HOME/Library/Caches`, called `go-build` and `staticcheck`.

> The only key difference I can think of between the machines is that my work MacBook has Falcon installed

I can't speak to Falcon specifically, but I've heard of _some_ macOS "endpoint protection" software induce slowdowns like this, and worse.

**Comment by cedws** [comment]
These are the results:

On work machine:

```
2023/05/13 21:11:16 94.063084ms for GOROOT= GOPATH= GO111MODULE=off GOPROXY= PWD=/Users/connor.edwards/Documents/Git/iapc go list -e -f {{context.ReleaseTags}} -- unsafe
2023/05/13 21:11:16 178.060584ms for GOROOT= GOPATH= GO111MODULE= GOPROXY= PWD=/Users/connor.edwards/Documents/Git/iapc go list -f "{{context.GOARCH}} {{context.Compiler}}" -- unsafe
2023/05/13 21:11:17 1.592970042s for GOROOT= GOPATH= GO111MODULE= GOPROXY= PWD=/Users/connor.edwards/Documents/Git/iapc go list -e -json=Name,ImportPath,Error,Dir,GoFiles,IgnoredGoFiles,IgnoredOtherFiles,CFiles,CgoFiles,CXXFiles,MFiles,HFiles,FFiles,SFiles,SwigFiles,SwigCXXFiles,SysoFiles,TestGoFiles,XTestGoFiles,CompiledGoFiles,Export,DepOnly,Imports,ImportMap,TestImports,XTestImports,Module -compiled=true -test=true -export=true -deps=true -find=false --
```

On personal machine:

```
2023/05/13 21:11:17 9.8125ms for GOROOT= GOPATH= GO111MODULE=off GOPROXY= PWD=/Users/connor.edwards/Documents/Projects/iapc go list -e -f {{context.ReleaseTags}} -- unsafe
2023/05/13 21:11:17 10.004708ms for GOROOT= GOPATH= GO111MODULE= GOPROXY= PWD=/Users/connor.edwards/Documents/Projects/iapc go list -f "{{context.GOARCH}} {{context.Compiler}}" -- unsafe
2023/05/13 21:11:18 93.501083ms for GOROOT= GOPATH= GO111MODULE= GOPROXY= PWD=/Users/connor.edwards/Documents/Projects/iapc go list -e -json=Name,ImportPath,Error,Dir,GoFiles,IgnoredGoFiles,IgnoredOtherFiles,CFiles,CgoFiles,CXXFiles,MFiles,HFiles,FFiles,SFiles,SwigFiles,SwigCXXFiles,SysoFiles,TestGoFiles,XTestGoFiles,CompiledGoFiles,Export,DepOnly,Imports,ImportMap,TestImports,XTestImports,Module -compiled=true -test=true -export=true -deps=true -find=false --
```

As you suspected, `go list` is the culprit. I'll close this issue since from this it's clearly nothing to do with staticcheck, but I appreciate your help.

In the meantime, do you know of a way I can stop gopls from running staticcheck? That might make the situation a bit more bearable for me while I get IT to add an exclude rule to test if it really is Falcon.

Thanks again.

**Comment by dominikh** [comment]
When talking about VSCode, there are two ways to run Staticcheck: , via the `"go.lintTool": "staticcheck"` setting, and via gopls. When doing it via gopls, gopls doesn't actually invoke the Staticcheck process. Instead it bundles our checks and runs them like any other check in gopls, with no additional file I/O or calls to `go list` occurring, only incurring additional CPU cost.

Using `staticcheck` as the `go.lintTool` in VSCode, on the other hand, does invoke our binary.
