### ISSUE TITLE
staticcheck: ineffective assignment SA4005 when modifying value receiver

### ISSUE THREAD

**Issue by bradleyfalzon** [dominikh/go-tools#141]
Hi,

Just getting a report of an ineffective assignment SA4005 that I don't believe is ineffective? I agree it's strange code, but I don't think there's an ineffective assignment here: https://play.golang.org/p/oO-za7AcGh

```go
package main

import "fmt"

// T is t
type T struct {
        X bool
        F string
}

// Modify modifies T.F to say modified, then calls EchoF.
func (t T) Modify() {
        if t.X {
                t.X, t.F = true, "modified"
        }
        t.EchoF()
}

// EchoF prints F.
func (t T) EchoF() {
        fmt.Println(t.F)
}

func main() {
        t := T{X: true, F: "original"}

        t.EchoF()  // output: original
        t.Modify() // output: modified
        t.EchoF()  // output: original
}
```

I understand I'm modifying a copy, but I'm then using that copy in `EchoF`. Is there an actual issue here or is this a false positive?

**Comment by dominikh** [comment]
The check is broken. It will be easier to rewrite the check from scratch than to fix it, as the current implementation is from a time when I had a much weaker understanding of SSA.

The false positive happens because one block is assigning to multiple fields of the same value, and the single read (`t.EchoF()` reads `t`) only marks one of those writes as okay. This happens because of an explicit check in the code, but I can't tell if the check was an attempt at optimizing the check, or if removing it will break some other case.

**Comment by dominikh** [comment]
Reminder to myself to either rewrite or disable the check *soon*. It is hitting more bugs (see referenced issue in "bork")

**Comment by dominikh** [comment]
We have temporarily disabled the check in 8ed405e.

**Comment by dominikh** [comment]
Closing in favor of #786.

**Comment by yury-kozlov** [comment]
> am here to understand what an ineffective assignment means

The assignment may be ineffective when trying to assign field of a value receiver instead of pointer receiver.

**Comment by yeshwanthjampala** [comment]
package main

import (
	"fmt"

	"github.com/dop251/goja"
	"github.com/dop251/goja_nodejs/console"
	"github.com/dop251/goja_nodejs/require"
)

type Hooks struct {
	OnNewEmail         []*goja.Value
	BeforeSendingEmail []func(e *Email)
}

type Email struct {
	Subject  string
	Body     string
	Priority int
	To       []string
}

func (h Hooks) Init() {
	h.OnNewEmail = make([]*goja.Value, 0)
	h.BeforeSendingEmail = make([]func(e *Email), 0)
}

func (h *Hooks) TriggerNewEmailEvent(email *Email, vm *goja.Runtime) {

	eobj := makeEmailJSObject(vm, email)

	for _, newEmail := range h.OnNewEmail {
		var newEmailCallBack func(*goja.Object)
		vm.ExportTo(*newEmail, &newEmailCallBack)
		newEmailCallBack(eobj)
	}
}

func makeEmailJSObject(vm *goja.Runtime, email *Email) *goja.Object {
	obj := vm.NewObject()
	obj.Set("subject", email.Subject)
	obj.Set("body", email.Body)
	obj.Set("to", email.To)
	obj.Set("reply", func(body string) {
		fmt.Printf("Replying:\n%s\n", body)
	})
	obj.Set("setPriority", func(p int) {
		fmt.Printf("Set email priority to %d\n", p)
	})

	obj.Set("moveTo", func(folder string) {
		fmt.Printf("Moving email to folder %s\n", folder)
	})

	return obj
}

func WorkWithHooks() {
	var hooks Hooks
	hooks.Init()

	vm := goja.New()

	new(require.Registry).Enable(vm)
	console.Enable(vm)

	obj := vm.NewObject()

	obj.Set("RegisterHook", func(hook string, fn goja.Value) {
		switch hook {
		case "onEmailReceived":
			hooks.OnNewEmail = append(hooks.OnNewEmail, &fn)
			fmt.Println("Registered onEmailReceived Hook ")
		}

	})

	vm.Set("myemail", obj)

	script := `
		console.log("JS code started ")
		
		myemail.RegisterHook("onEmailReceived", iGotEmail)

		function iGotEmail(newEmail)
		{
			console.log("newEmail, subject %s ", newEmail.subject,  newEmail.to)
			
			if(newEmail.subject.startsWith("URGENT:"))
			{
				newEmail.setPriority(5)
				
				newEmail.reply("Hello,\n Received your email. We will respond on priority basis. \n\nThanks\n")
				return
			}
			else if(newEmail.to.includes("sales@website"))
			{
				newEmail.moveTo("Sales")
				return
			}
		}
	`
	prg, err := goja.Compile("", script, true)
	if err != nil {
		fmt.Printf("Error compiling the script %v ", err)
		return
	}

	_, err = vm.RunProgram(prg)

	email1 := &Email{
		Subject: "URGENT: Systems down!",
		Body:    "5 of your systems are down at the moment",
		To:      []string{"some@one.cc"},
	}

	fmt.Println("Triggering the urgent email event ")
	hooks.TriggerNewEmailEvent(email1, vm)

	email2 := &Email{
		Subject: "New order received!",
		Body:    "You got new order for 1k blue widgets!",
		To:      []string{"sales@website"},
	}

	fmt.Println("Triggering the sales email event ")
	hooks.TriggerNewEmailEvent(email2, vm)
}

output errors:
1)ineffective assignment to field Hooks.OnNewEmail (SA4005)go-staticcheck
2)ineffective assignment to field Hooks.BeforeSendingEmail (SA4005)go-staticcheck
3)this value of err is never used (SA4006)go-staticcheck

**Comment by dominikh** [comment]
All valid errors.
