### ISSUE TITLE
Unused linter does not work on const () block

### ISSUE THREAD

**Issue by Greendomisi** [dominikh/go-tools#1414]
**- The output of 'staticcheck -version'**
- staticcheck 2022.1 (v0.3.0)
**- The output of 'staticcheck -debug.version' (it is fine if this command fails)**
- staticcheck 2022.1 (v0.3.0)

Compiled with Go version: go1.20.4
Main module:
        honnef.co/go/tools@v0.3.0 (sum: h1:2LdYUZ7CIxnYgskbUZfY7FPggmqnh6shBqfWa8Tn3XU=)
Dependencies:
        github.com/BurntSushi/toml@v0.4.1 (sum: h1:GaI7EiDXDRfa8VshkTj7Fym7ha+y8/XxIgD2okUIjLw=)
        golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e (sum: h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=)
        golang.org/x/mod@v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 (sum: h1:kQgndtyPBW/JIYERgdxfwMYh3AVStj88WQTlNDi2a+o=)
        golang.org/x/sys@v0.0.0-20211019181941-9d821ace8654 (sum: h1:id054HUawV2/6IGm2IV8KZQjqtwAOo2CYlOToYqa0d0=)
        golang.org/x/tools@v0.1.11-0.20220316014157-77aa08bb151a (sum: h1:ofrrl6c6NG5/IOSx/R1cyiQxxjqlur0h/TvbUhkH0II=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
**- The output of 'go version'**
- go version go1.20.4 linux/amd64
**- The output of 'go env'**
- GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="gitlab.gardoc.ru"
GONOSUMDB="gitlab.gardoc.ru"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="gitlab.gardoc.ru"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/sdk/go1.20.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/sdk/go1.20.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2651701482=/tmp/go-build -gno-record-gcc-switches"
**- Exactly which command you ran**
- golangci-lint run $pkgpath -E unused
**- Output of the command and what's wrong with the output**
- Nothing is on the output, It should indicate unused constants in const ( constant1 = "1" constant2 = "2" constant3 = "3" ...) block
-->

**Comment by dominikh** [comment]
If one constant in a block of constants is used, then the entire block is considered used. This is intentional.

**Comment by cespare** [comment]
Woah, just ran into this and it was a pretty big surprise.
