### ISSUE TITLE
staticcheck: SA5011 false positive during nil pointer dereference

### ISSUE THREAD

**Issue by opensaucerer** [dominikh/go-tools#1428]
I have the following code in the screenshot below being marked as possibly nil pointer dereference but I believe I am doing all nil checks and none would be nil by the time the `offset` code line is executed.

- The output of 'staticcheck -version'
```shell
staticcheck 2022.1.3 (v0.3.3)
```
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```shell
staticcheck 2022.1.3 (v0.3.3)

Compiled with Go version: go1.18.1
Main module:
        honnef.co/go/tools@v0.3.3 (sum: h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=)
Dependencies:
        github.com/BurntSushi/toml@v0.4.1 (sum: h1:GaI7EiDXDRfa8VshkTj7Fym7ha+y8/XxIgD2okUIjLw=)
        golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e (sum: h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=)
        golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 (sum: h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=)
        golang.org/x/sys@v0.0.0-20211019181941-9d821ace8654 (sum: h1:id054HUawV2/6IGm2IV8KZQjqtwAOo2CYlOToYqa0d0=)
        golang.org/x/tools@v0.1.11-0.20220513221640-090b14e8501f (sum: h1:OKYpQQVE3DKSc3r3zHVzq46vq5YH7x8xpR3/k9ixmUg=)
```
- The output of 'go version'
```shell
go version go1.18.1 linux/amd64
```
- The output of 'go env'
```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/magician/.cache/go-build"
GOENV="/home/magician/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/magician/go/pkg/mod"
GONOPROXY="github.com/lighthouse-web3"
GONOSUMDB="github.com/lighthouse-web3"
GOOS="linux"
GOPATH="/home/magician/go"
GOPRIVATE="github.com/lighthouse-web3"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/magician/Downloads/sauce/task/save/go.mod"
GOWORK="/home/magician/Downloads/sauce/task/save/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1111520644=/tmp/go-build -gno-record-gcc-switches"
```
- Exactly which command you ran
`stactic check automatic linting in vscode`
- Output of the command and what's wrong with the output
- Where we can read the code you're running Staticcheck on
![image](https://github.com/dominikh/go-tools/assets/59074379/2c688338-dc0c-4343-aba3-dbadce63a6de)

**Comment by opensaucerer** [comment]
I thought to change the positioning and the false positive is gone. Does this mean staticcheck is unable to see beyond the most recent lines above a pointer deference?
![image](https://github.com/dominikh/go-tools/assets/59074379/82523837-6968-4bd5-92df-735c88016e71)

**Comment by dominikh** [comment]
I'm sorry, but screenshots of excerpts of code are useless for trying to reproduce this problem. Either provide all the relevant source code, or if you can't share that, provide a minimal, self-contained example that reproduces the problem.
