### ISSUE TITLE
simple: flag variations of `fmt.Println(fmt.Sprintf(...))`

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#143]
Similar to the existing fmt.Errorf check.

**Comment by shurcooL** [comment]
How does this relate to #100?

**Comment by dominikh** [comment]
I don't think the concerns expressed in #100 apply here. There is no scenario (that I can think of) in which `fmt.Println(fmt.Sprintf(...))` is used to be consistent with previous lines, where the previous lines shouldn't also be rewritten.

**Comment by shurcooL** [comment]
When you said "variations of fmt.Println(fmt.Sprintf(...))", I understood that to mean `fmt.Println(fmt.Sprintf(...))` and some other variations involving fmt.Println/fmt.Sprintln, hence my question.

Is this issue about just `fmt.Println(fmt.Sprintf(...))`? If so, what did you mean by the phrase "variations of"?

**Comment by dominikh** [comment]
`(P|Fp|Sp)rint(ln)?`
