### ISSUE TITLE
S1017: diagnostics can be confusing for `else if`, and may make code less consistent

### ISSUE THREAD

**Issue by arp242** [dominikh/go-tools#1447]
I have the following code to remove UTF-16 and UTF-8 BOMs (which really shouldn't be present, but in reality are):

	if strings.HasPrefix(data, "\xff\xfe") || strings.HasPrefix(data, "\xfe\xff") { // UTF-16
		data = data[2:]
	} else if strings.HasPrefix(data, "\xef\xbb\xbf") { // UTF-8
		data = data[3:]
	}

And staticcheck gives the following warning:

	parse.go:52:9: should replace this if statement with an unconditional strings.TrimPrefix (S1017)

However, this:

	if strings.HasPrefix(data, "\xff\xfe") || strings.HasPrefix(data, "\xfe\xff") {
		data = data[2:]
	}
	data = strings.TrimPrefix(data, "\xef\xbb\xbf")

or:

	data = strings.TrimPrefix(data, "\xff\xfe")
	data = strings.TrimPrefix(data, "\xfe\xff")
	data = strings.TrimPrefix(data, "\xef\xbb\xbf")

are not identical: `\xff\xfe\xef\xbb\xbf` will be removed, whereas the original won't.

This check should probably only apply to simple `if strings.HasPrefix(..) { slice[..] }` checks, and not `else if`.

In this case it's probably not super-harmful to just remove all those sequences, although I'd prefer to be exact about it. And I can imagine some other cases where it might matter more, like:

    s := "tag:foo"
    if strings.HasPrefix(s, "tag:") {
        s = s[4:]
    } else if strings.HasPrefix(s, "category:") {
        s = s[9:]
    }

This is with staticcheck 2023.1.3 (v0.4.3)

**Comment by dominikh** [comment]
In the example you provided, the diagnostic points to the second if statement (the `else if`), implying the following alternative:

```
if strings.HasPrefix(data, "\xff\xfe") || strings.HasPrefix(data, "\xfe\xff") { // UTF-16
	data = data[2:]
} else {
	data = strings.TrimPrefix("\xef\xbb\xbf") // UTF-8
}
```

That does seem a bit awkward, but it _is_ logic-preserving. I'll refile this as a noisy positive, i.e. a suggestion that is correct but not necessarily helpful.

**Comment by arp242** [comment]
Ah, right so 😅 I'm not sure why I didn't "see" that option; probably because writing it like that is just not how I would ever do it, and it seems worse than the original to me.

**Comment by dominikh** [comment]
> and it seems worse than the original to me.
Agreed.
