### ISSUE TITLE
Please provide quick build instructions.

### ISSUE THREAD

**Issue by gl-yziquel** [dominikh/go-tools#1451]
Hi.

I'd really like to have staticcheck build **from source** (and not being installed in any prepackaged way). I do not see instructions for that in the README. The `dist/build.sh` requires an (unclear) revision argument, and fails at line 65 [i.e. `SYSTEMS=(windows linux freebsd)`] because of a parenthesis that is unexpected.

Please provide some clear instructions.

I like to build from source. The go ecosystem seems pretty hostile to the "build from source" approach.

**Comment by dominikh** [comment]
> I'd really like to have staticcheck build from source

```
go get honnef.co/go/tools/cmd/staticcheck@latest
```

Or

```
git clone ...
cd go-tools
go build ./cmd/staticcheck
```

> The go ecosystem seems pretty hostile to the "build from source" approach.

Go has a very simple to use build system, and how to use it is one of the first things Go programmers learn.

**Comment by gl-yziquel** [comment]
Well, yes... it just leaves me confused all the time... For instance:

```console
mini-me@virtucon ~/h/c/go-tools (master)> go build ./cmd/staticcheck
go: build output "staticcheck" already exists and is a directory
```

That's typically the kind of thing I've tried before opening this issue.

**Comment by dominikh** [comment]
Use `-o` to write the binary to a different path, or build from a directory that doesn't already have a directory named the same as the tool you're trying to build. `cd cmd/staticcheck; go build`

**Comment by gl-yziquel** [comment]
OK. Thanks. It did work.

I honestly however do find the way the go ecosystem builds things very much free form, and I find it very unsettling. Lack of predictability, in a sense.

But thank you for taking the time to dispell some misconceptions I had on go.
