### ISSUE TITLE
ST1000: Slightly too strict about wording

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#1452]
This is with staticcheck 2023.1.6.

I have a package like this:

```
// Package foobar, shared between baz and qux, does bleep bloop.
package foobar
```

Staticcheck reports

```
foobar.go:1:1: package comment should be of the form "Package foobar ..." (ST1000)
```

I think that in addition to a space, a comma should be fine after the name of the package.

It's hard to construct other examples besides space and comma, but I suppose you could do

    // Package foobar---an excellent package, to be sure---does bleep bloop.

Maybe just narrow the check to only look for `^Package foobar\b` or something along those lines?

**Comment by dominikh** [comment]
SGTM

**Comment by cespare** [comment]
TYVM!
