### ISSUE TITLE
Add option for unsed to mark only write as used.

### ISSUE THREAD

**Issue by maranqz** [dominikh/go-tools#1453]
Hello, I want to write a linter that finds writing in public variables and fields if they are marked as read-only.

Could I add option `FieldReadsAreUses`, `VariablesReadsAreUses`, and VariablesWritesAreUses`, which will work as `FieldWritesAreUses`?

`FieldReadsAreUses` marks fields as "used" which were read.

`VariablesReadsAreUses` marks  variables as "used"which were read.

`VariablesWritesAreUses` marks variables as "used" which were written.

**Comment by dominikh** [comment]
I don't think I would want to maintain these flags, as they're not something that would be needed for any of the checks in Staticcheck.
