### ISSUE TITLE
go.mod linting

### ISSUE THREAD

**Issue by matthewmueller** [dominikh/go-tools#1457]
Thanks creating staticcheck, it really helps keep code clean.

I was wondering if you considered expanding into also linting `go.mod` and potentially `go.sum` files?

I think it'd be nice to check that replaces don't reference a relative outside the module for example.

**Comment by dominikh** [comment]
I wouldn't really know what to check for in `go.mod` files — I don't think there's anything to do for `go.sum` files that `go mod tidy` isn't doing.

> I think it'd be nice to check that replaces don't reference a relative outside the module for example.

That's a somewhat common pattern used with nested modules, though.

**Comment by matthewmueller** [comment]
Thanks for your response and good point. It might be hard to distinguish between nested modules that use replace to point to a parent module

The main use case I'm trying to resolve is blocking `replace`s that point to the local filesystem from getting merged and pushed up.

Probably out of scope for this library.
