### ISSUE TITLE
quickfix: simplify `!(x op y)`

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#146]
`!(x op y)` can be simplified by negating `op`. For example, `!(x == y)` would become `x != y`.

**Comment by shurcooL** [comment]
Valid, but possible false positives. Sometimes, for consistency, it makes more sense to stick with `!(x == y)`.

I don't have examples, but can look if you need them.

Hard to say how many false positives though.

**Comment by dominikh** [comment]
> I don't have examples, but can look if you need them.

I'd appreciate that.

**Comment by dominikh** [comment]
On second thought, this doesn't warrant a warning by gosimple/is too prone to false positives. It should be offered as an automated refactor by editors, though.

**Comment by dominikh** [comment]
Reopening under the quickfix label.
