### ISSUE TITLE
lint:file-ignore SA4024 not working

### ISSUE THREAD

**Issue by lublak** [dominikh/go-tools#1509]
Currently i use antlr to generate some parser for me.
It uses some auto generated gotos:
![grafik](https://github.com/dominikh/go-tools/assets/44057030/c3a22083-e202-43cf-b9a7-a6f35adc0216)
So i use the header option to add a header to my file:
![grafik](https://github.com/dominikh/go-tools/assets/44057030/0d01f86a-cacc-4473-9923-96557ea8cdb3)
It works fine:
![grafik](https://github.com/dominikh/go-tools/assets/44057030/600b73c8-df7f-4403-a837-31a11cfc275e)
Nevertheless, the linter displays the warning:
![grafik](https://github.com/dominikh/go-tools/assets/44057030/c7803722-ec6e-423f-9eee-048c1b7830fe)

vscode:
![grafik](https://github.com/dominikh/go-tools/assets/44057030/2b8ca699-202d-4cce-aced-91cea23692f7)

**Comment by dominikh** [comment]
SA4024 flags impossible comparisons of `len` and `cap` against `0`, not unreachable code. In fact, no Staticcheck analysis emits a diagnostic titled `unreachable code`.

Flagging unreachable code is a native gopls check, so you are probably using that.

**Comment by lublak** [comment]
Ah thanks for the clarification. :)
Sry for wasting your time.
