### ISSUE TITLE
simple: single line if err check if no values used out of if statement

### ISSUE THREAD

**Issue by a-urth** [dominikh/go-tools#151]
Its seems to be idiomatic go, afaik.
If it seems valid option I could start poking around how to implement that.

```go
// no value except error
err := smth()
if err != nil {
    //do stuff
}

// or value omitted
_, err := smth()
if err != nil {
    // do stuff
}

// value is used only in if statement
val, err := smth()
if err != nil {
    send(val)
}
```
vs
```go
if err := smth(); err != nil {
    // do stuff
}

if _, err := smth(); err != nil {
    // do stuff
}

if val, err := smth(); err != nil {
    send(val)
}
```

**Comment by dominikh** [comment]
I'm afraid that this boils down to personal taste and depends on too many factors, such as line length and previous lines of code. Suggesting this change would be too opinionated, and not really be a simplification of code.
