### ISSUE TITLE
Add to `SA1008` check for method calls

### ISSUE THREAD

**Issue by lasiar** [dominikh/go-tools#1519]
SA1008 checks for write to map directly, but doesn't check method calls if argument is constant.

```go
v := http.Header{}

// Before 
v.Get("Test-HEader")
v.Set("Test-HEader", "value")
v.Add("Test-HEader", "value")
v.Del("Test-HEader")
v.Values("Test-HEader")

// After 
v.Get("Test-Header")
v.Set("Test-Header", "value")
v.Add("Test-Header", "value")
v.Del("Test-Header")
v.Values("Test-Header")
```

I wrote simple linter: https://github.com/lasiar/canonicalHeader.

I can implement this here if it needed.

**Comment by dominikh** [comment]
The method calls do canonicalize the keys, therefore both the before and after behave identically. One might argue that this is a stylistic issue, but we don't want to enforce a particular way of spelling the keys.
