### ISSUE TITLE
errcheck: do not require error checking of result Close() for io.ReadCloser

### ISSUE THREAD

**Issue by nightlyone** [dominikh/go-tools#152]
The result of Close is for an io.ReadCloser is irrelevant in real code, since we just signal that we want to stop reading from the underlying resource.

It is most annoying to flag `defer req.Body.Close()` in this kind of code:
```go
resp, err := http.Get("http://example.com/")
if err != nil {
	// handle error
}
defer resp.Body.Close() // <-- errcheck reports this as "error return value not checked (defer resp.Body.Close())"
```

if too complex to implement for all usages `io.ReadCloser` of interfaces, not flagging this specific case would increase usefulness of this check a lot.

**Comment by dominikh** [comment]
First things first: my errcheck isn't currently a released, or production-ready tool, so use at your own risk.

Secondly, yes, the plan is to make errcheck aware of concrete types and impossible errors. However, the generic `io.ReadCloser` isn't a candidate. It is perfectly fine for an `io.ReadCloser` to return a non-nil error on closing. HTTP response bodies may be a candidate, I haven't looked into that yet.

**Comment by nightlyone** [comment]
Sorry @dominikh , mixed it up with https://github.com/kisielk/errcheck so I will complain over there :smile: 

You can close the issue, if you like.
