### ISSUE TITLE
The commit b3ee554011ba07e55a74da8c2e46de2accf60ec1 is missing from the release.2023.1 branch

### ISSUE THREAD

**Issue by ldez** [dominikh/go-tools#1522]
The commit https://github.com/dominikh/go-tools/commit/b3ee554011ba07e55a74da8c2e46de2accf60ec1 is missing inside the `release.2023.1` branch.

Related to https://github.com/dominikh/go-tools/issues/1397
Related to https://github.com/golangci/golangci-lint/issues/4662

**Comment by ldez** [comment]
I feel like the issue has been fixed, so I closed it.

**Comment by dominikh** [comment]
Thank you.
