### ISSUE TITLE
audit staticcheck for GODEBUG=gotypesalias=1 support

### ISSUE THREAD

**Issue by adonovan** [dominikh/go-tools#1523]
Go 1.22 introduced the `types.Alias` type, but did not start creating instances of them, unless `GODEBUG=gotypesalias=1`. Go 1.23 will start creating instances of them, unless `GODEBUG=gotypesalias=0`. The effective default value of GODEBUG is determined by the version of the `go` directive in the go.mod file of the application. It is inevitably an incompatible change.

Staticcheck will need to handle `types.Alias` values. In most cases, it is sufficient to ensure that every type switch and type assertion that tests for a particular `types.Type` removes any `Alias` constructors, either by calling `Unalias` or `Underlying` as the situation requires. (You may find [this package](https://pkg.go.dev/golang.org/x/tools/internal/aliases) useful during the transition.) In some cases, for example when a name or source location is required, the application can do a better job by not discarding aliases, but handling them with additional logic.

You may find it helpful to:
- look at some of the CLs attached to the issues below to get a feel for what is involved;
- run the analyzer in https://go.dev/cl/575057, which detects all the type switches and assertions that need to be audited;
- set up an additional CI (e.g. GitHub Actions) build with GODEBUG=gotypesalias=1.

Let us know if we can help.

(In due course, aliases will support type parameters, like Named types. We expect this change will be straightforward since it is compatible.)

Related:
- https://github.com/golang/go/issues/64581
- https://github.com/golang/go/issues/65294

cc @findleyr

**Comment by rfindley** [comment]
cc @findleyr

**Comment by adonovan** [comment]
(Updated; sorry about that. Feel free to delete your note to unsubscribe.)

**Comment by dominikh** [comment]
Thanks for the detailed description and resources. I'll get started on this as soon as possible.
