### ISSUE TITLE
No check for unnecessary `nil` check on a map followed by a `len` check of the same map

### ISSUE THREAD

**Issue by ChrisHines** [dominikh/go-tools#1527]
Considering staticcheck identifies unnecessary nil checks for slices followed by a `len` check, I am surprised it doesn’t seem to do the same for maps.

I was just reviewing some code that is essentially:

```
type obj struct {
    m map[uint64]bool
}

func (o *obj) method() {
    if o.m != nil && len(o.m) > 0 {
        // start goroutine to process elements of `o.m`
    }
}
```

I was expecting staticcheck to flag the o.m != nil part as unnecessary, but it isn’t.

**Comment by arp242** [comment]
> am surprised it doesn’t seem to do the same for maps.

It does, what doesn't work is using a selector like `o.m` (for maps or slices). FYI.
