### ISSUE TITLE
Report generator

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#153]
Generate HTML (and Markdown?) reports of issues found. The main purpose of these reports should be the assessment of a project's quality. A quick mock up looks like this:

![](http://stuff.fork-bomb.org/2017-08-04_03h-01m-55s.png)

The final version should support sorting, filtering, grouping by packages, and possibly an inline code view.

**Comment by dominikh** [comment]
HTML generation has been implemented in the closed-source branch in 036c794.

**Comment by shurcooL** [comment]
Closed-source branch? 😱

I didn't know parts of go-tools were closed source. Where can I learn more about that?

**Comment by dominikh** [comment]
@shurcooL No official announcement yet, but the gist of it is this: in the future, there'll be two branches of go-tools: open source and closed source. The latter will contain premium features that cost money. Issues with the paid-feature label are features that will be part of the paid version.
