### ISSUE TITLE
Missing checks for `_test.go` files

### ISSUE THREAD

**Issue by sanjit-bhat** [dominikh/go-tools#1534]
### Setup

I made a package with the following files. Note that `Foo` and `main` are the exact same.

`main.go`:
```go
package main

func main() {
	err := true
	if err != false {
		panic("")
	}
	if 1 != 1 {
		panic("")
	}
}
```

`main_test.go`:
```go
package main

func Foo() {
	err := true
	if err != false {
		panic("")
	}
	if 1 != 1 {
		panic("")
	}
}
```

Output:
```bash
> staticcheck -f stylish ./...
main.go
  (5, 5)  S1002   should omit comparison to bool constant, can be simplified to err
  (8, 5)  SA4000  identical expressions on the left and right side of the '!=' operator

main_test.go
  (8, 5)  SA4000  identical expressions on the left and right side of the '!=' operator
```

### Problem

Staticcheck properly identifies error `SA4000` across both files, but it only identifies error `S1002` in `main.go`, not `main_test.go`. I searched through the docs and couldn't figure out what's causing this. Any help would be greatly appreciated, thanks!

### Other requested info
```
staticcheck version: 2023.1.7 (v0.4.7)
go version: go1.22.2 darwin/arm64
```

**Comment by dominikh** [comment]
This is working as intended. S1002 does not apply to code in tests because it would lead to noisy positives when using the `if got != want` pattern, which some people also use on bools, for reasons of consistency.

**Comment by sanjit-bhat** [comment]
Ah, it makes sense why the default has `S1002` not running on tests.

I've seen others run into this confusion as well, so maybe we could do one of the following (or something else)?
1. Add documentation in [the checks page](https://staticcheck.io/docs/checks/) to state that a certain check doesn't run on tests.
2. Add an option to enable all checks to run on tests.

**Comment by sanjit-bhat** [comment]
Actually, disregard my above suggestion. I grep'd the codebase for all checks that use `code.IsInTest`, and it seems reasonable why they're not run on test files. I doubt anyone would want to be warned / change the default.
