### ISSUE TITLE
SA1015 (time.Tick leak) will become obsolete with Go 1.23

### ISSUE THREAD

**Issue by stapelberg** [dominikh/go-tools#1558]
https://staticcheck.io/docs/checks#SA1015 will become obsolete with Go 1.23. 

See https://pkg.go.dev/time@master#Tick, which states:

> Before Go 1.23, this documentation warned that the underlying Ticker would never be recovered by the garbage collector, and that if efficiency was a concern, code should use NewTicker instead and call Ticker.Stop when the ticker is no longer needed. As of Go 1.23, the garbage collector can recover unreferenced tickers, even if they haven't been stopped. The Stop method is no longer necessary to help the garbage collector. There is no longer any reason to prefer NewTicker when Tick will do.

I’m not entirely sure what the process is here. Can we turn SA1015 into a no-op for Go 1.23+? How exactly would we gate on that? 

Thanks

**Comment by ccoVeille** [comment]
Thanks for reporting this great news, BTW.

I totally missed it

**Comment by dominikh** [comment]
I hope the commit answers the question of how.
