### ISSUE TITLE
unused: whole const block is considered used when it contains used consts

### ISSUE THREAD

**Issue by magnushiie** [dominikh/go-tools#1574]
unused linter marks entire block used when some constant is used within a const ( ... ) block:

```go
const (
	x = 1 // ok
	Z = 1
)
const (
	y = 1 // unused
)
```

In the above example, because `Z` is public and `x` is in the same block, `x` is also considered used (incorrectly) while `y` is correctly reported as unused.

<details>

```console
$ staticcheck -version
staticcheck 2023.1.7 (v0.4.7)

$ staticcheck -debug.version
staticcheck 2023.1.7 (v0.4.7)

Compiled with Go version: go1.22.0
Main module:
        honnef.co/go/tools@v0.4.7 (sum: h1:9MDAWxMoSnB6QoSqiVr7P5mtkT9pOc1kSxchzPCnqJs=)
Dependencies:
        github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
        golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
        golang.org/x/mod@v0.12.0 (sum: h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=)
        golang.org/x/sys@v0.11.0 (sum: h1:eG7RXZHdqOJ1i+0lgLgCpSXAp6M3LYlAo6osgSi0xOM=)
        golang.org/x/tools@v0.12.1-0.20230825192346-2191a27a6dc5 (sum: h1:Vk4mysSz+GqQK2eqgWbo4zEO89wkeAjJiFIr9bpqa8k=)

$ go version
go version go1.22.0 linux/amd64
```
</details>

**Comment by dominikh** [comment]
This is working as intended. See https://github.com/dominikh/go-tools/blob/d0a0c6521c9caf7ab90e19205990ebba45cee788/unused/unused.go#L133-L137 and https://github.com/dominikh/go-tools/issues/365.

**Comment by magnushiie** [comment]
I understand the concern with protocol declarations. My issue was caused by `gofumpt`, which insists all constants must be grouped.

**Comment by ojarva** [comment]
Not having an option to disable "if anything in constants group is used, then the rest is fine as well" really sucks. Especially considering what was mentioned about gofumpt's default settings around grouping.

That ensures very unfortunate false negatives that are not reported.

**Comment by dominikh** [comment]
Staticcheck's focus is on minimizing false positives, not maximizing true positives.

**Comment by silverwind** [comment]
Imho there should be an option `const-group-require-all-used` to let the user decide this behaviour.
