### ISSUE TITLE
High performance static detection

### ISSUE THREAD

**Issue by li-jin-gou** [dominikh/go-tools#1590]
# context
  - I currently use code generation to generate code for tens of thousands of repositories and use go vet to do static code inspections.
```
go vet -stdmethods ./...
```
But I found that the flame graph is all about the overhead of go vet for compile, which is up to 70%.

I found the description of staticcheck, it is very fast, can staticcheck detection replace vet and have high performance?

**Comment by dominikh** [comment]
Staticcheck is not a replacement for `go vet`, nor is it faster than `go vet`.

**Comment by timothy-king** [comment]
(vet maintainer here. If you have had a 70% increase in vet running time, please file an issue here  https://github.com/golang/go/issues/new/choose .)
