### ISSUE TITLE
Quick fix 1002 suggests use of tagged switch statement inappropriately

### ISSUE THREAD

**Issue by seh** [dominikh/go-tools#1613]
Consider the following code, which I admit could use `strings.Cut` instead:
```go
// Variable "c" is of type string.
// We wish to split it on an embedded space character, if any.
switch i := strings.IndexByte(c, ' '); {
case i == -1:
	return c, "", nil
case i == 0:
	return "", "", errors.New("value starts with a space character")
default:
	return c[:i], c[i+1:], nil
}
```
My LSP implementation—_gopls_—reports the following:
> could use tagged switch on i [default]

It then offers a quick fix: "Replace with tagged switch". If I accept that suggestion, though, the resulting code is invalid, since I lose access to the "i" variable used in the return statement in the default case.
```go
// Note the extra "i" here.
switch i i := strings.IndexByte(c, ' '); {
case -1:
	return c, "", nil
case 0:
	return "", "", errors.New("value starts with a space character")
default:
	// We can no longer use "i" here.
	return c[:i], c[i+1:], nil
}
```
Note also the strange insertion of an extra "i" in [the initial simple statement](https://go.dev/ref/spec#Expression_switches).

It seems that there are three things wrong here:
- The recommendation is unjustified, as we can't eliminate the "i" variable, given its use in the return statement.
- The applied fix changes the first two case clauses, but leaves the default case clause with dangling references to a nonexistent variable.
- The applied fix mangles the initial simple statement.

I don't know whether any of these are to blame on Emacs's _lsp-mode_ that's making use of _gopls_.

**Comment by dominikh** [comment]
I reckon the intended rewrite is `switch i := strings.IndexByte(c, ' '); i {` which AFAICT would be correct. I'll have to check tomorrow if we emit a broken quickfix, or if this is an instance of https://github.com/golang/go/issues/63930.

**Comment by dominikh** [comment]
2739fd00045db18f8a2cc46bfb2530cfc9e627b2 fixes this. It will take a release of Staticcheck and a release of gopls for this to reach users, however.

**Comment by seh** [comment]
Thank you for the fast diagnosis and correction!

I'm going to rewrite the original function to use `strings.Cut`, but I'm glad that its current state allowed us to find this burr to sand off.
