### ISSUE TITLE
SA4023: docs references Go blog article using wrong link

### ISSUE THREAD

**Issue by jkitajima** [dominikh/go-tools#1614]
The documentation for [SA4023](https://staticcheck.dev/docs/checks/#SA4023) includes a reference to a Go blog post with parentheses at the end. However, the closing parenthesis is mistakenly included within the link itself, causing it to redirect to [here](https://go.dev/doc/articles/laws_of_reflection.html\)).

<img width="866" alt="image" src="https://github.com/user-attachments/assets/cd74cde0-082e-44b3-ae0a-38dc53d1e587">

Not a big deal but just pointing out.

**Comment by dominikh** [comment]
Thanks for letting me know.
