### ISSUE TITLE
SA2000 misses real bugs

### ISSUE THREAD

**Issue by lpxz** [dominikh/go-tools#1623]
I would like to bring to your attention that SA2000 in staticcheck misses real bugs.

If you run staticcheck against the following, it fails to find the bug. If you comment the fmt.Print in front of wg.Add(), it finds the bug. In general, as long as there is some code between `go func(){ `and `wg.Add()`, SA2000 fails to fire alarm.

```
// main.go
package main

import (
	"fmt"
	"sync"
)


func  somefunc() error {
   var  wg sync.WaitGroup
   go func() {
        fmt.Println("hi")
	wg.Add(1)
	defer wg.Done()
    }()
   return nil
}

func main(){
   fmt.Println("starting")
   somefunc()
}
```
$ go install honnef.co/go/tools/cmd/staticcheck@latest
$ staticcheck main.go

[SA2000 code](https://github.com/dominikh/go-tools/blob/cdd14abaf8eddb869706f0eb52df2a6c82d95b40/staticcheck/sa2000/sa2000.go#L35) explains why.
I wrote a linter to address this. 

But before I make a PR, want to check with you if such improvement is welcome or considered negligible. Thanks

**Comment by dominikh** [comment]
SA2000 is written in a way that reduces the potential for false positives. Allowing other code to run before the call to wg.Add could lead to more false positives.

Staticcheck in general errs on the side of false negatives to avoid false positives.
