### ISSUE TITLE
lint: add flag for checking dependencies

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#164]
Currently, our tools run on the explicitly provided packages. Add a flag (`-deps` or `-r(ecursive)` maybe) that also checks all transitive dependencies. This is to ensure that the entire code base is free of issues. Some users may want to run this all the time, some only when adding/updating a dependency. Checking dependencies shouldn't add much of a cost: we already load these packages, and that's the most expensive step.

We probably shouldn't check the standard library, though. It has a lot of "funky" code and interactions with internals that cause a higher than average number of false positives.

Another question is whether the tests of dependencies should also be checked.

**Comment by dominikh** [comment]
Update in 2019, the following is no longer true:

> Checking dependencies shouldn't add much of a cost: we already load these packages, and that's the most expensive step.

We can now apply aggressive caching to dependencies and can reuse export data, but have to load packages we wish to check from source. However, we can drop the source from memory after we're done checking a package, so this will primarily affect runtime, not memory use.

**Comment by myitcv** [comment]
This would in effect be equivalent to the `-deps` flag to `go list`, correct?

For those people in favour of this proposal, I'd be interested in understanding whether the magic `all` package (see `go help packages`) satisfies/doesn't satisfy their needs:

```
When using modules, "all" expands to all packages in the main 
module and their dependencies, including dependencies
needed by tests of any of those.
```

There was some discussion about `all` and `std` in https://github.com/golang/go/issues/26317 FYI

**Comment by dominikh** [comment]
> This would in effect be equivalent to the -deps flag to go list, correct?

Aside from the fact that we'd filter out the standard library, yes.

> For those people in favour of this proposal, I'd be interested in understanding whether the magic all package (see go help packages) satisfies/doesn't satisfy their needs:

Do keep in mind that `all` will only work in module mode.

**Comment by dominikh** [comment]
I'm going to close this. Go modules are gaining in popularity, and there's little point in inventing our own flag when `all` already exists. Yes, we'll check parts of the standard library, but we also have caching nowadays, so we'll only check stdlib once.

We may have to tweak some checks to produce fewer false positives on the standard library, however. The standard library causes above average rates of false positives because it's special. As a trivial example, the `testing` package assigns to testing.B.N. We can track those issues separately.
