### ISSUE TITLE
lint: confusing package names

### ISSUE THREAD

**Issue by alexkappa** [dominikh/go-tools#166]
Hi @dominikh,

Thank you for the awesome tools! I am trying to add staticheck as a [Code Climate](https://codeclimate.com/) Analysis Engine.

So far I managed to make it work for single package codebases where the entire codebase is one package. When trying on multi package codebases it is no longer able to distinguish files that are not part of the root or first package.

For example, running staticcheck on `github.com/alexkappa/exp` outputs error similar to the following.

```
Running staticcheck: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine staticcheck:stable failed with status 2 and stderr 
/go/src/github.com/alexkappa/exp/parse/ast.go:1:1: package parse; expected exp
/go/src/github.com/alexkappa/exp/parse/ast_test.go:1:1: package parse; expected exp
/go/src/github.com/alexkappa/exp/parse/lex.go:4:1: package parse; expected exp
/go/src/github.com/alexkappa/exp/parse/lex_test.go:3:1: package parse; expected exp
/go/src/github.com/alexkappa/exp/parse/parse.go:3:1: package parse; expected exp
/go/src/github.com/alexkappa/exp/parse/parse_test.go:3:1: package parse; expected exp
[redacted]
```

And this is the snippet of code that uses staticcheck to perform static analysis on these files.

```
loader := &loader.Config{
  ParserMode:  0,
  AllowErrors: true,
}
loader.CreateFromFilenames(pkgPath, filenames...)
program, err := loader.Load()
if err != nil {
  fmt.Fprintf(os.Stderr, "Error loading program: %s\n", err)
  os.Exit(1)
}

checker := staticcheck.NewChecker()
linter := lint.Linter{Checker: checker}
problems := linter.Lint(program)
```

I am pretty sure I am doing something wrong, and I hope you can guide me a little. I could not figure it out based on the `lint` or `lintutil` packages just yet, but I'm still looking.

If you have any pointers I'd greatly appreciate it.

Thanks,
Alex

**Comment by dominikh** [comment]
Walking you in detail through package loading in Go would take a while, but I recommend reading https://github.com/golang/example/tree/master/gotypes

In short, CreateFromFilenames creates a single package from a list of files, it is akin to `go build file1.go file2.go`. If you want to load multiple packages, you need to use a function like `Import`.

Alternatively, if providing your own loader.Program isn't a requirement, and you just want to programmatically run the linters, look at the code in `cmd/{staticcheck,gosimple,megacheck}/*.go` – these tools use `lintutil` to take care of all the package loading and linter invocation logic.

**Comment by alexkappa** [comment]
Thanks for the feedback @dominikh, I'll definitely read up on the gotypes examples!

I don't necessarily need to provide my own `loader.Program` and indeed all I want is to run the linters programmatically. The reason I didn't use `lintutil` is because from my understanding it takes package names as arguments, whereas my starting point is a list of files (supplied by the engine).

**Comment by dominikh** [comment]
If Code Climate feeds you a list of files, your best bet is to turn these into the respective import paths as soon as possible, as that is how Go refers to packages. I'm assuming that you have a working GOPATH, in which case you could just strip the GOPATH prefix and the base name from the path, to be left with the import path.

I'm not sure exactly what files Code Climate passes to you, whether it's all the files in the repo, or just those that changed, but in either case you need to process whole packages, not individual files. Only compiling a subset of files of a package will not work, which is another reason for working with import paths.

**Comment by alexkappa** [comment]
Well I may might have been a bit wrong that cc feeds me a list of files, thats how they built their [`golint`](https://github.com/codeclimate-community/codeclimate-golint/blob/master/codeclimate-golint.go#L39) engines so that was my reference.

As `staticheck` needs to process all the files I do a `gotool.ImportPaths([]string{"./..."})` and filter out the files from codeclimate later on to report issues on. Do you think `./...` is a reasonable choice for this?

A picture is worth a thousand words so if you are interested [here's the piece in question](https://github.com/alexkappa/codeclimate-staticcheck/blob/master/codeclimate-staticcheck.go#L43-L50) 😄 .

It is almost there after I iron out a few issues I get while running it on larger projects.

Really appreciate your help @dominikh , thanks a lot!

**Comment by dominikh** [comment]
`./...` may or may not work. In theory, using `./...` and post-processing the output does work. In practice, some of your dependencies may have subpackages that do not compile, in which case the linters will abort.

**Comment by alexkappa** [comment]
Yeah you're right. I've tried switching to inferring package names from files as you suggested and it seems much more reasonable.

**Comment by dominikh** [comment]
@alexkappa Can we close this issue?

**Comment by alexkappa** [comment]
Yes of course, thanks so much your help!
