### ISSUE TITLE
consider detecting consecutive mutually-exclusive if statements that are tempting to refactor into single if/else statement, when doing so introduces variable shadowing

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#168]
This is a user report of a refactor I nearly applied without noticing the unintended behavior change it would introduce. The motivation is that sharing this can potentially lead to a helpful check. It may not.

I was adding a new feature, and while doing so, I saw the following code:

```Go
rc, err := s.fetchCommit(ctx, *c.URL)
if err, ok := err.(*github.ErrorResponse); ok && err.Response.StatusCode == http.StatusNotFound {
	continue
}
if err != nil {
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
commits[*c.SHA] = rc
```

When I saw that with a fresh pair of eyes, it looked like code that could benefit from a minor refactor to simplify it.

Namely, it's not possible for both if statements to run. Either none, or at most one of them would run. So, the code could be simplified into an if/else if version like this, to better convey that at most one of the two cases will ever run:

```Go
rc, err := s.fetchCommit(ctx, *c.URL)
if err, ok := err.(*github.ErrorResponse); ok && err.Response.StatusCode == http.StatusNotFound {
	continue
} else if err != nil {
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
commits[*c.SHA] = rc
```

Luckily, I spotted the mistake that doing so would introduce. It would change behavior in an unintended way, because the first if case shadows the `err` variable from `fetchCommit` (which has type `error`) with a `*github.ErrorResponse` one.

I didn't get any messages from `megacheck` before or after.

Is there anything useful that can be done to help other people who may run into this situation?

FWIW, my planned fix is to combine the two if statements (so that I'm not tempted yet again in the future to refactor and make this mistake again), but avoid shadowing. E.g.:

<details><br>

```Go
rc, err := s.fetchCommit(ctx, *c.URL)
if e, ok := err.(*github.ErrorResponse); ok && e.Response.StatusCode == http.StatusNotFound {
	continue
} else if err != nil {
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
commits[*c.SHA] = rc
```

</details>

**Comment by dominikh** [comment]
I couldn't yet think of a way to flag this. Flagging the original code is not an option. It's neither incorrect (staticcheck) nor something that can objectively be simplified (gosimple).

We could've (in the future) flagged the refactored version, if the condition had said just `ok` instead of `ok && ...` – in that case, the second `if` would've been impossible. However, the way you have refactored it, there is no way for us to tell that it is wrong, and there are valid inputs that hit your `else if` branch.

There is a class of algorithms that check whether two pieces of code have the same behaviour, to verify the correctness of refactors. Of course the problem of "are two programs identical" can be reduced to the Halting problem, and I personally don't think that there is a satisfying "best effort" middle ground for that problem, unlike for bug finding.

**Comment by shurcooL** [comment]
Thanks for the detailed analysis. I was afraid that it would be hard to be able to implement something helpful here. The `ok && ...` indeed ruins one chance of making the unintended code reportable.

That said, one comment. You said:

> Flagging the original code is not an option.

Isn't it true that the code is slightly suboptimal in a way, because both if cases are mutually exclusive, yet it's written in a way that suggests they may not be?

I know `lint` makes suggestions for code like this:

```Go
    ...
    if cond {
        return x
    } else {
        foo()
        bar()
        baz()
    }
}
```

```
main.go:11:9: if block ends with a return statement, so drop this else and outdent its block
```

Which is also valid code, yet it's suboptimal, because it can be written in an alternative way which happens to be extremely easy to convert to, is shorter and simpler, and provides more clarity on the potential outcomes:

```Go
    ...
    if cond {
        return x
    }
    foo()
    bar()
    baz()
}
```

I see this situation as somewhat equivalent, with the big exception that there may not be an easy, obvious way to refactor the code to make it simpler/shorter in all situations. Unfortunately.

**Comment by dominikh** [comment]
"Suboptimal", in this instance, is very subjective. There is a lot of code with consecutive, yet mutually exclusive, if conditions out there, to the point that it can be considered an established style. I know that my code contains them, and I remember seeing them in the Go standard library, too.

Furthermore, even if we considered it objectively suboptimal, what alternative would we suggest? The intuitive – your initial – alternative is incorrect. And I consider your second alternative 

```
rc, err := s.fetchCommit(ctx, *c.URL)
if e, ok := err.(*github.ErrorResponse); ok && e.Response.StatusCode == http.StatusNotFound {
	continue
} else if err != nil {
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
```

to be less readable than two consecutive if statements.

**Comment by shurcooL** [comment]
> "Suboptimal", in this instance, is very subjective. There is a lot of code with consecutive, yet mutually exclusive, if conditions out there, to the point that it can be considered an established style. I know that my code contains them, and I remember seeing them in the Go standard library, too.

This is true.

Thanks for consideration. I think we can mark this as `unfortunate` and `wontfix` or so. I don't have further thoughts on this at this time.

> what alternative would we suggest? 

Another alternative could be to use a longer variable name for `err` returned from `fetchCommit`, to make it clear that the second `if err != nil` is intentional and there isn't a `something, err := foo()` line missing just before it:

```Go
rc, fetchCommitError := s.fetchCommit(ctx, *c.URL)
if err, ok := fetchCommitError.(*github.ErrorResponse); ok && err.Response.StatusCode == http.StatusNotFound {
	continue
}
if fetchCommitError != nil {
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", fetchCommitError)
}
commits[*c.SHA] = rc
```

But how that compares to other alternatives is clearly just very subjective too.

**Comment by shurcooL** [comment]
Another alternative could be a `switch`. However, it is not pretty because of the inability to have the type assertion happen in the `case` statement where it's being changed (not without creating a helper function or so):

```Go
rc, err := s.fetchCommit(ctx, *c.URL)
switch e, ok := err.(*github.ErrorResponse); {
case ok && e.Response.StatusCode == http.StatusNotFound:
	continue
case err != nil:
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
commits[*c.SHA] = rc
```

With a helper it could be more readable, but requiring a helper of course adds to the overall cost:

```Go
rc, err := s.fetchCommit(ctx, *c.URL)
switch {
case isStatusNotFound(err):
	continue
case err != nil:
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
commits[*c.SHA] = rc
```

**Comment by dominikh** [comment]
Summarizing, I think this problem boils down to having to apply your own judgement and not being able to rely on a tool. If we could fully automate programming, we'd be the richest men on earth.

**Comment by shurcooL** [comment]
How could I forget yet another alternative, the two-level nesting one:

```Go
rc, err := s.fetchCommit(ctx, *c.URL)
if err != nil {
	if err, ok := err.(*github.ErrorResponse); ok && err.Response.StatusCode == http.StatusNotFound {
		continue
	}
	return nil, nil, nil, 0, fmt.Errorf("fetchCommit: %v", err)
}
commits[*c.SHA] = rc
```
