### ISSUE TITLE
unused: unused exported field in package main used via reflection

### ISSUE THREAD

**Issue by bradleyfalzon** [dominikh/go-tools#17]
Unused detected a field in an anonymous struct as unused when not set in the Go program, but it was used in a template.

I had an example, where I was using a value in a header template that was being imported by all templates, the template had a condition if the value was empty it would substitute another value for it. The zero value was useful.

Because the template was a part of the header and used by all templates, all handlers were required to pass a struct that defined the value (and they all did, except one), but unused reported it as being unused.

I've since refactored the code slightly to embed the required pages but thought I'd raise this if this is a condition that should've been handled differently.

```go
package main

import (
        "html/template"
        "log"
        "os"
)

func main() {
        p := struct {
                Name string
        }{}
        t, err := template.New("foo").Parse(`Hello, {{.Name}}!`)
        if err != nil {
                log.Fatal(err)
        }
        err = t.ExecuteTemplate(os.Stdout, "foo", p)
        if err != nil {
                log.Fatal(err)
        }
}
```

**Comment by dominikh** [comment]
This isn't caused because of the anonymous struct, but because the struct is defined in package main. We currently assume that all exported fields are used, unless they're in package main, in which case they need to be accessed directly. We're not taking reflection into account here and probably should.

**Comment by dominikh** [comment]
(Similarly, it fails for non-main packages if using whole program analysis, the `-exported` flag)

**Comment by shurcooL** [comment]
I was about to report a false positive bug against `cmd/unused`, but I believe it's the same as this one. Feel free to move it out into a separate issue if you discover otherwise.

```Go
package main

import (
	"encoding/json"
	"os"
)

func main() {
	var m struct {
		UsedInOutput string
	}
	printJSON(m)

	// Output:
	// github.com/shurcooL/play/31
	// {
	// 	"UsedInOutput": ""
	// }
}

// printJSON prints v as JSON encoded with indent to stdout. It panics on any error.
func printJSON(v interface{}) {
	w := json.NewEncoder(os.Stdout)
	w.SetIndent("", "\t")
	err := w.Encode(v)
	if err != nil {
		panic(err)
	}
}
```

```bash
$ go run main.go
{
	"UsedInOutput": ""
}
$ unused
main.go:10:3: field UsedInOutput is unused (U1000)
$ binstale unused
unused
	up to date: honnef.co/go/tools/cmd/unused
```

**Comment by dominikh** [comment]
Fixed in master.
