### ISSUE TITLE
staticcheck: check alignment of variables used in atomic accesses

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#171]
(Copied from https://github.com/dominikh/go-staticcheck/issues/15, originally by @dgryski)

From `sync/atomic`:

```
On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned.
```

This should be possible to diagnose statically and warn about.

**Comment by dgryski** [comment]
Dup of https://github.com/golang/go/issues/11891

**Comment by dgryski** [comment]
Fix in `vet` with https://github.com/golang/tools/commit/24cd39ecf74570612483b772d45cf9d53d908340

**Comment by dominikh** [comment]
Better late than never, right?
