### ISSUE TITLE
staticcheck: CheckDubiousSyncPoolSize needs a whitelist :(

### ISSUE THREAD

**Issue by tamird** [dominikh/go-tools#18]
https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/data.go#L552:L581

TL;DR in some cases, we have no choice but to put an interface value in a `sync.Pool`, and this lint should not complain about that. Case in point is `hash.Hash`.

**Comment by dominikh** [comment]
To be honest I am inclined to remove the check. It does catch some unnecessary allocations, but so do `go test` and pprof... staticcheck, on the other hand, is a bit zealous about it, and has no way of telling if the allocations are really an issue or not (and we will not add annotations to teach it).

/cc @bradleyfalzon who implemented the check
/cc @dgryski who has experience with the check on an internal code base and could tell us how useful the check was

**Comment by bradleyfalzon** [comment]
Certainly if there's false positive, IMHO staticcheck should not continue the check, especially if it doesn't catch a major bug.

However, as the check is already marked as dubious, and if it's just a matter of excluding interfaces from the check, it looks straight forward to add an if condition (or add to the existing) checking the argument is not an interface using `!types.IsInterface(arg.Value.Value.Type())` or similar, I'd be happy to PR that.

But it's then up to @dominikh if he wants to continue maintaining this.

For the record, implemented via https://github.com/dominikh/go-staticcheck/pull/11 and discussed in https://github.com/dominikh/go-staticcheck/issues/10 but the go vet inclusion discussion has more information https://github.com/golang/go/issues/16311.

**Comment by dominikh** [comment]
I'll close this issue. The reported bug has been fixed, and we'll keep the check for now.
