### ISSUE TITLE
quickfix: constant 1-byte substr in strings.Index should recommend strings.IndexByte

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#192]
You can replace `strings.Index(s, ":")` with `strings.IndexByte(s, ':')` for a performance improvement. The second argument must be one byte in length to make this optimization.

**Comment by kevinburke** [comment]
Here's the preamble for Index

```
// Index returns the index of the first instance of substr in s, or -1 if substr is not present in s.
func Index(s, substr string) int {
	n := len(substr)
	switch {
	case n == 0:
		return 0
	case n == 1:
		return IndexByte(s, substr[0])
	case n == len(s):
		if substr == s {
			return 0
		}
		return -1
	case n > len(s):
		return -1
```

TBH if any of those cases are provable at compile time, could issue a warning

**Comment by kevinburke** [comment]
You can do the same for bytes.Index with a second argument that's a single byte

**Comment by kevinburke** [comment]
same for strings.LastIndex, strings.LastIndexByte, and same API's for bytes

```patch
-       i := strings.LastIndex(name[:length], "/")
+       i := strings.LastIndexByte(name[:length], '/')
```

**Comment by mvdan** [comment]
To play the devil's advocate, at some point the compiler should become clever enough to realise when you pass a single-byte string to `Index` and inline the `IndexByte` version instead. At that point, I'm not sure if a warning would be particularly useful.

**Comment by ainar-g** [comment]
This could theoretically "uglify" code like

```
var (
	i1   = strings.Index(s, "1")
	i23  = strings.Index(s, "23")
	i456 = strings.Index(s, "456")
)
```

I'm not sure if there is code like this in the wild, just putting it out there.

**Comment by dominikh** [comment]
Unlikely to be a part of staticcheck, but may become a part of in-editor quick fixes/suggestions.

**Comment by dominikh** [comment]
Related: https://github.com/golang/go/issues/22148

**Comment by kevinburke** [comment]
haha alright, never mind!

**Comment by dmitshur** [comment]
As a data point, I wrote this today:

```Go
i := bytes.LastIndex(text, []byte("#"))
```

By chance, I realized I could use `bytes.LastIndexByte` to simplify it:

```Go
i := bytes.LastIndexByte(text, '#')
```

(Because '#' is an ASCII rune.)
