### ISSUE TITLE
gosimple: simplify sort.Sort(sort.StringSlice(a)) and sort.Sort(sort.IntSlice(a))

### ISSUE THREAD

**Issue by opennota** [dominikh/go-tools#194]
`sort.Sort(sort.StringSlice(a))` -> `sort.Strings(a)` if a is []string
`sort.Sort(sort.IntSlice(a))` -> `sort.Ints(a)` if a is []int

**Comment by opennota** [comment]
Also `sort.Sort(sort.Float64Slice(a))`.

**Comment by dominikh** [comment]
Implemented in 6217a4b and refined in follow-up commits.
