### ISSUE TITLE
gosimple: S1026: there could be a reason to create a copy of a string

### ISSUE THREAD

**Issue by opennota** [dominikh/go-tools#196]
docs/checks/S1026 states:

> Strings in Go are immutable. Since they cannot be modified, there is no reason for creating copies of them. Avoid constructs such as string([]byte(str)) and "" + str.

Let's suppose that `str` is a substring of a very big string and that that big string has no references apart from `str`. In this case Go couldn't release the memory used by the big string, and thus making a copy of `str` could help.

``` go
str := "very big string ..."
str = str[:1] // runtime couldn't release the memory
...
str = "" + str // after that runtime could release the memory
```

**Comment by mvdan** [comment]
Is this really that common? I've never encountered this need. And if I was to keep large chunks of bytes in memory, I'd probably use `[]byte`.

Another thing that comes to mind is that this is an internal compiler/runtime detail. Go could be clever enough to free unused parts of some structures. I believe there are open tickets for some of these already, such as how maps currently grow but never shrink. The same could apply to strings, especially given how the compiler knows they're immutable.

It appears to me like this would be better handled in Go itself than in your code. Whether or not the check should be disabled until Go is smart enough is another topic.

**Comment by dominikh** [comment]
I'll probably disable the check, for now. They are indeed valid, in-use patterns for copying strings for GC purposes, and there doesn't seem to be a better way of copying strings, either.

Of course one could argue that `[]byte` should be used instead, but that doesn't make our suggestion less wrong.
