### ISSUE TITLE
Timeout for downloading staticcheck

### ISSUE THREAD

**Issue by Shikkic** [dominikh/go-tools#197]
Hey, I think there might be an outage or something with `honnef.co` that is preventing `honnef.co/go/tools/cmd/staticcheck` from being downloaded?

```
package honnef.co/go/tools/cmd/staticcheck: unrecognized import path "honnef.co/go/tools/cmd/staticcheck" (https fetch: Get https://honnef.co/go/tools/cmd/staticcheck?go-get=1: dial tcp 104.154.119.211:443: i/o timeout)
```

Starting getting this out of nowhere today.

**Comment by dominikh** [comment]
Blame Google. Working on resolving it as we speak.

**Comment by Shikkic** [comment]
@dominikh Awesome, thanks for letting me know 👍

**Comment by proshik** [comment]
@dominikh Thanks

**Comment by dominikh** [comment]
Should be fixed for now. I'm sorry for the inconvenience this has caused.
