### ISSUE TITLE
gosimple: simplify fmt.Sprintf("%d", n)

### ISSUE THREAD

**Issue by opennota** [dominikh/go-tools#198]
`fmt.Sprintf("%d", n)` -> `fmt.Sprint(n)` if `n` is of an int type.

**Comment by dominikh** [comment]
I'm not sure that's a suggestion we should make. The original version is more explicit about its intent, and can be checked by `go vet` for correctness.

/cc @shurcooL

**Comment by shurcooL** [comment]
Not always applicable, the original form may be used for consistency, e.g.:

```Go
s += fmt.Sprintf("...%d", n)
s += fmt.Sprintf("..%d", n)
s += fmt.Sprintf(".%d", n)
s += fmt.Sprintf("%d", n)
```

Also, it has addition alternative simplifications possible, e.g., `strconv.Itoa`.

**Comment by opennota** [comment]
> Also, it has addition alternative simplifications possible, e.g., strconv.Itoa.

That's two letters longer than `fmt.Sprint`. I'd prefer `fmt.Sprint` unless it's performance critical. And we already have imported `fmt`.

**Comment by dominikh** [comment]
> That's two letters longer than fmt.Sprint

We are not in the code golf business.

**Comment by dominikh** [comment]
I'm going to close this issue. It's not a simplification I want to add to gosimple.
