### ISSUE TITLE
gosimple: skip generated files?

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#20]
It doesn't really make sense for gosimple to complain about generated code. The suggestions made by gosimple do not address issues of correctness, and generating code is oftentimes easier when ignoring certain quality standards that apply to hand-written code. Suggestions like `for {}` instead of `for true {}` really don't improve generated code.

/cc @tamird because of S1013 ignores in cockroachdb.
/cc @shurcooL for his opinions on generated code

**Comment by shurcooL** [comment]
> It doesn't really make sense for gosimple to complain about generated code.

I agree, the best default behavior is to skip generated files (and after golang/go#13560 is resolved, they can be detected without false positives).

It'd probably be nice and fair to allow not skipping them it via an option (not on by default).

Complaining about generated files can be useful, but only for the people who control the generator code. Changing the generator is the only viable way of changing generated code. For other people, it's just noise.
