### ISSUE TITLE
gosimple: ignore checks for all packages/files

### ISSUE THREAD

**Issue by esinek** [dominikh/go-tools#200]
How can I instruct the cmd line tools to ignore specific checks for all packages? I want to reduce the noise from (e.g. S1002) and focus on more serious issues first.
`-ignore` looks like it's only available for specific files. The following still checks S1002.
`gosimple -ignore '*.*:S1002' -tests=false ./...`

**Comment by ainar-g** [comment]
`-ignore` uses `filepath.Match`, so no fancy `**` expansion. It seems like the only option is something like

    gosimple -ignore '*:S1002 */*:S1002 */*/*:S1002 */*/*/*:S1002 */*/*/*/*:S1002' ./...

Repeat ad nauseam. Alternatively,

    gosimple -ignore "$(go list ./... | sed 's#$#/*:S1002#')" ./...

**Comment by dominikh** [comment]
Let's add a special case for `*:Sxxxx` to mean all packages.
