### ISSUE TITLE
structlayout README.md missing image

### ISSUE THREAD

**Issue by ahamilton55** [dominikh/go-tools#201]
The structulayout command README.md file is missing an image for the SVG.

I'm happy to fix it but I'm not sure if you'd like to delete it or if there is a preferred local location in the repo that you'd prefer to have an image stored in. I'd be happy to update it either way but it also isn't a big issue either.

Seen at the below link at the bottom of the file:
https://github.com/dominikh/go-tools/tree/master/cmd/structlayout

**Comment by dominikh** [comment]
Fixed. Thanks for letting me know.
