### ISSUE TITLE
detect duplicate checks for the same err

### ISSUE THREAD

**Issue by kevinburkeotto** [dominikh/go-tools#202]
Consider the following code:

```go
package main

import (
	"fmt"
	"log"
	"strconv"
)

func main() {
	a, err := strconv.Atoi("32")
	if err != nil {
		log.Fatal(err)
	}
	b, _ := strconv.Atoi("unnkown")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("a", a, "b", b)
}
```

I believe this is an error: the user probably meant to check the second error, but forgot to re-fill-in the blank during debugging.

Megacheck does not currently warn that this is a problem. It seems like we could either alert on an error check right after a function call that does not assign `err`, or alert if `err` is checked twice without being altered.

**Comment by ainar-g** [comment]
Looks like a dup of #193.

**Comment by kevinburkeotto** [comment]
sure, close enough
