### ISSUE TITLE
all: support line-based ignores of checks

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#205]
Much like the Go team, we've refused adding linter directives to source code. in the fear that they'd clutter up the code. Instead, we've provided file-level ignores, passed via a command line flag. The idea was to "banish" odd code to its own file.

In reality, however, this led to ignore lists not being kept up to date, and to ignores being applied too broadly. Furthermore, such ignores provide valuable information to humans, too. When reading odd but correct code, a human benefits from comments like "this looks weird, but it's correct, because ..." just as tools do.

Some of the distaste for those directives likely comes from linters that have a high rate of false positives and unwanted advice, requiring a lot of ignores to be used. In our case, we'll treat those directives as a last resort, when neither editing the code, nor improving the checks, is a viable option.

Due to our lack of descriptive names for checks, and to add value to the perceived noise of linter directives, our directive will have a mandatory field for human-readable comments, to explain why a particular check is being ignored. 

The directives will look as follows:

```
//lint:ignore CheckID1[,CheckID2,...,CheckIDN] These checks trigger falsely because ...
```

~~The comments will apply to the line on which they appear – this is in contrast to compiler directives such as `go:noinline`, and the general notion of `go/ast` that associates comments with the AST node that follows. The reason for our deviation is to allow comments on function declarations without showing up in godoc, as well as to enforce a 1-to-1 mapping of line numbers in linter output and position of the comments. This approach does, however, have a significant downside, in that only a single directive can appear per line. This may conflict with other tools that make the same decision, as well as with future directives we may want to add. It also prevents us from having distinct directives per ignored check.~~

A concrete example:

```
// fn does something.
//lint:ignore SA4009 the argument is kept for backwards compatibility, but immediately forced to the only valid value.
func fn(x int) {
  x = 42
  fmt.Println(x)
}
```

Not part of this issue, but also worth considering, is a directive such as `lint:ignorefile` to encode file-wide ignores. This directive could eventually replace most uses of the `-ignore` flag.

**Comment by dominikh** [comment]
@tamird As a contributor to a project with a fair number of ignore patterns, do you have any input on this feature? Would this be something you'd use?

**Comment by ainar-g** [comment]
@dominikh I am not @tamird, but he reviewed some of my changes on `github.com/lib/pq`. When we integrated megacheck into the TravisCI build, we had to ignore two warnings, SA1019 and S1024, both because we need to keep backwards compatibility with Go 1.5. See [here](https://github.com/lib/pq/blob/44669ae07e6e602f20599c0239aadfee55f00056/.travis.yml#L56). An interesting possibility would be a directive or a flag to tell megacheck, that we might use deprecated and non-optimal code for backwards compatibility.

**Comment by tamird** [comment]
@dominkh yeah, we would use it. My preference would be an annotation
attached to the code that needs be ignored by a check, similar to what
Rubocop allows.

**Comment by tamird** [comment]
Just read the description; looks great.

**Comment by dominikh** [comment]
@ainar-g For S1024, you can use the `-go 1.5` flag
