### ISSUE TITLE
staticcheck: missing problem code

### ISSUE THREAD

**Issue by gyuho** [dominikh/go-tools#206]
Hi,

We are using problem code to suppress some warnings

45d689e7d122f228b80eba27806cd9a9ced2d4ce outputs

> auth/store_test.go:641:4: the goroutine calls T.Fatal, which must be called in the same goroutine as the test (SA2002)

0f833e3689d09347b80256c7f81ffbd786ea79df outputs

> auth/store_test.go:641:4: the goroutine calls T.Fatal, which must be called in the same goroutine as the test

Is there any option to make `(SA2002)` appear in the output?

Thanks!

**Comment by gyuho** [comment]
Seems like this is affected by https://github.com/dominikh/go-tools/commit/d5e608c29c78f1ceb5205d0b4793bfd802c3c783 which removes `j.check` in the output?

**Comment by dominikh** [comment]
Yup, that was an accident.

**Comment by gyuho** [comment]
Thanks!
