### ISSUE TITLE
all: maintain a mapping of deprecated stdlib identifier to Go version

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#207]
The tools have a `-go <version>` flag to skip checks and simplifications that are not valid for the specific Go version. For example, S1024, which suggests time.Until, is only valid starting with Go 1.8.

For deprecated symbols, we cannot do this. If the installed stdlib is newer than the targeted Go version, it will contain deprecation comments, which don't specify since when the symbol has been deprecated.

We should maintain an internal list that maps deprecated symbols to the Go version in which they were deprecated. That way, we can omit warnings for symbols that weren't yet deprecated in the targeted version of Go.

/cc @ainar-g

**Comment by ainar-g** [comment]
@dominikh Sorry, I couldn't check it sooner. Should this work in 2017.2? Because it doesn't seem to:

    ~/go/src/github.com/lib/pq$ megacheck -version
    megacheck 2017.2
    ~/go/src/github.com/lib/pq$ megacheck -go 1.5 ./...
    conn_test.go:1212:4: driver.Execer is deprecated: Drivers should implement ExecerContext instead (or additionally).  (SA1019)
    conn_test.go:1213:4: driver.Queryer is deprecated: Drivers should implement QueryerContext instead (or additionally).  (SA1019)
    conn_test.go:1558:13: driver.Queryer is deprecated: Drivers should implement QueryerContext instead (or additionally).  (SA1019)

**Comment by dominikh** [comment]
@ainar-g That's a bug. We're not handling package-level objects correctly. Will be fixed in a bug fix release.

**Comment by dominikh** [comment]
Fixed in 2017.2.1.
