### ISSUE TITLE
unused: support the NoCopy pattern

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#214]
The Go standard library internally introduced the idea of a "no copy" sentinel value that structs could embed. The presence of the sentinel would signal to `go vet` that copying of the struct is forbidden.

This idea leaked to other people. For example, CockroachDB has its own `util.NoCopy` type that is embedded in various types. Currently, this triggers `unused field` warnings. We can adopt `go vet`'s notion of the sentinel by handling the following kind of type specially: A struct type with no fields and exactly one method `func Lock()` where the function body is empty. This type, as well as fields of that type, will always be considered used.

**Comment by tamird** [comment]
This is not totally done; see https://github.com/dominikh/go-tools/commit/4500e3fb8e663dd622b99cf8301eddb5b44d5f10#commitcomment-26745283. Would be good to reopen this in the meantime.
