### ISSUE TITLE
redundant import alias check

### ISSUE THREAD

**Issue by aultimus** [dominikh/go-tools#216]
Is there any type of check that catches redundant alias in imports

ie. simplifies:
```
	assert "github.com/stretchr/testify/assert"
```
to
```
	 "github.com/stretchr/testify/assert"
```
?

Thanks

**Comment by dominikh** [comment]
Not in my tools, no. https://github.com/alexkohler/unimport implements such a check, though. 

It's likely not a check I want to implement, either.

**Comment by shurcooL** [comment]
> It's likely not a check I want to implement, either.

Why not? I would find such a limited check useful. I don't find the other checks done by `unimport` useful for my needs (they're too aggressive).

**Comment by dominikh** [comment]
I don't find it a very useful check, for two reasons: the infrequency with which this occurs and the absolutely negligible impact it has, both in terms of correctness and simplicity.

**Comment by dominikh** [comment]
FWIW, it might be worth suggesting this to the gopls people.
