### ISSUE TITLE
Write a web frontend for the linters

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#22]
We would like to provide a frontend for the linters that allows for a complete workflow. It should allow ignoring individual false positives, do incremental runs, track metrics across version control revisions, etc.

Random ideas in no particular order:

- Display explanations of checks
- Group results by checks/files

**Comment by shurcooL** [comment]
Would you expect it to allow the code to change underneath in between the runs, or is the code assumed not to change during a session?

**Comment by dominikh** [comment]
I don't know much about the details yet. One feature I'd like to have, however, is working on older git commits, without having to check them out (by reading the git data, and using https://godoc.org/golang.org/x/tools/go/buildutil#OverlayContext)

With that functionality in place, it would also be simple enough to provide a stable snapshot of the working directory and operate on that, and require explicit reloads to see new changes to the files.

**Comment by bradleyfalzon** [comment]
I'd be interested to see how you do this, I've done something similar when using go/build by setting the readfile and readdir funcs https://github.com/bradleyfalzon/apicompat/blob/master/apicompat.go#L311-L318 and reading from git https://github.com/bradleyfalzon/apicompat/blob/master/vcs.go#L66-L119

These weren't great implementations though, so I'd be interested to see what you do.

**Comment by shurcooL** [comment]
Got it.

Like Bradley, I, too, have similar code for `build.Context` from a VCS-backed VFS that is [powering gotools.org](https://gotools.org/github.com/shurcooL/gtdo?rev=563c50baf632448dbce89d2e223d2a405a8586b1#main.go-L754-L787). It's currently bad Go code, but I want to get around to cleaning it up sometime.

**Comment by bradleyfalzon** [comment]
Another issue that I'd be interested in knowing how you'd solve, if you're checking out different versions of code, how will you handle also obtaining the dependencies for each version? As I'd expect they could change between revisions, they could be required by go-tools to build and they could use an external vendoring tool to fetch.

**Comment by dominikh** [comment]
I am going to close this issue. We have basic HTML report generation in the Pro branch, and that's likely as far as I will go. There are existing tools, such as Sonarqube, which implement all the features I would want from a web UI and aren't tied to a single programming language or suite of tools.

Instead of pouring a lot of time into our own frontend, I will write a plugin for Sonarqube.
