### ISSUE TITLE
staticcheck: "argument should be pointer-like" when the type is unsafe.Pointer

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#224]
For example:

```
package p

import (
        "sync"
        "unsafe"
)

var pool sync.Pool

func F(p unsafe.Pointer) {
        pool.Put(p)
}
```

```
$ megacheck .
f.go:11:10: argument should be pointer-like to avoid allocations (SA6002)
```

This seems wrong, given that `unsafe.Pointer` is really just a named pointer type:

    type Pointer *ArbitraryType

**Comment by dominikh** [comment]
We handle named pointers correctly. We do not, however, handle unsafe.Pointer correctly. 

Do note that the documentation for unsafe is just an approximation, similar to the documentation for builtin. It is not based on the actual Go type system. The unsafe package can be best understood as a set of intrinsics that the compiler handles specially, to allow circumventing the type system. As such, unsafe.Pointer is *not* expressed as a named pointer type in the type system -- if it were, what would its underlying type be? In go/types, unsafe.Pointer is treated as one of the basic types.

We just have to add unsafe.Pointer to our list of allowed types.
