### ISSUE TITLE
Vendor our dependencies

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#228]
At the least we'll want to vendor github.com/kisielk/gotool – our behaviour depends too much on having an up-to-date version of gotool installed. 

We should also vendor those parts of x/tools that we aren't going to rewrite/fork.

**Comment by shurcooL** [comment]
This is especially important since your installation instructions don’t include ‘-u‘ flag for ‘go get‘ command.

**Comment by dominikh** [comment]
Thanks to Go modules, this is no longer relevant.
