### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by josecordaz** [dominikh/go-tools#230]
When I try to run 

`go get honnef.co/go/tools/cmd/unused`

Fails in:

package honnef.co/go/tools/cmd/unused: unrecognized import path "honnef.co/go/tools/cmd/unused" (https fetch: Get https://honnef.co/go/tools/cmd/unused?go-get=1: x509: certificate signed by unknown authority)

**Comment by dominikh** [comment]
The certificate is issued by Let's Encrypt. Considering its popularity, you probably want to look into trusting their CA. All modern certificate bundles already include it, so you may have to update your system.

**Comment by josecordaz** [comment]
Perfect, thanks @dominikh
