### ISSUE TITLE
staticcheck: Does not work if only specifying one file in a package

### ISSUE THREAD

**Issue by peter-edge** [dominikh/go-tools#232]
```
$ go vet ./pkg/protoc/protoc.go
$ golint ./pkg/protoc/protoc.go
$ staticcheck ./pkg/protoc/protoc.go
/path/to/pkg/protoc/protoc.go:71:29: undeclared name: downloader
```

`downloader` is in `/path/to/pkg/protoc/downloader.go`. This works with other linting tools as shown above.

**Comment by dominikh** [comment]
Unlike these tools, staticcheck requires full type information and works on packages, not files. In that way, its command line is like that of `go build` or `go run`. When you specify file names, you're creating an ad hoc package consisting of exactly those files, which will lead to errors if these files around self-contained and valid. https://staticcheck.io/docs/#running-the-tools describes this behavior.

I recommend that you always run staticcheck on entire packages, not files.

**Comment by peter-edge** [comment]
Shouldn’t this be enforced then? This is installed in w0rp/ale, for example, and causes errors.

Can you please reopen this? I think we should have a discussion about not allowing files to be specified.

**Comment by dominikh** [comment]
We follow the same rules as `go build` with regard to specifying packages, and I do not intend to deviate from them. Running on individual files *can* be useful, such as when testing small, one-file programs, or files that are marked as `+build ignore` but serve a purpose (for example crypto/tls/generate_cert.go).

The output of `go help packages` applies to my tools.

It is unfortunate that w0rp/ale is using my tools incorrectly. Other tools, such as gometalinter and Emacs's flycheck have no trouble with this. And ale [seems to be in the progress of fixing things](https://github.com/w0rp/ale/issues/936), too.
