### ISSUE TITLE
unused: support setup/teardown methods from gopkg.in/check.v1

### ISSUE THREAD

**Issue by dzbarsky** [dominikh/go-tools#233]
This comes from using the http://gopkg.in/check.v1 package (it discovers/calls these with reflection, see https://github.com/go-check/check/blob/c02a90fcd86096d06ad2bae0b795d4747b26b088/check.go#L55)

(this is when running with -exported flag)

It also marks as unused code used only from setup/teardown. Would it be possible to teach the tool to specialcase these?

**Comment by dominikh** [comment]
It would be possible, but I'll have to think about whether I want to do it.

**Comment by dzbarsky** [comment]
https://github.com/dominikh/go-tools/pull/235 is a demo that solves this use case and the other issue I filed

**Comment by dzbarsky** [comment]
Have you decided how you feel about this? (We have been using this heuristic across 30million LOC to great success)

**Comment by dominikh** [comment]
I'll likely implement it in time for the next feature release.
