### ISSUE TITLE
Static Check Tool Not producing errrors

### ISSUE THREAD

**Issue by apandit24** [dominikh/go-tools#236]
I was running staticcheck tool on go program but it is not able to detect errors such as blank if 

**My program**
: package main
import "fmt"
func main() {
   fmt.Println("Hello,World!")
   var b int
   for b := 0; b < 10; b++ {
   		if(b<10) {
   			
   		}	
   }
}

I am running static check from command line
**Command**: staticcheck filename.go 

Please help me out i am unable to understand since it is not giving any o/p

**Comment by dominikh** [comment]
The input file doesn't compile. An input file that actually compiles will complain about empty branches. There's nothing to do here, closing.
