### ISSUE TITLE
gosimple: suggest changing "break someLabel" with "break" when possible 

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#240]
This has happened a few times to me, such as when a switch was removed inside a for loop and the break labels stopped being necessary.

The check itself should be fairly simple - the question is to what extent would it be too pedantic. Perhaps labels can be used in long pieces of code to help readability, for example.

**Comment by dominikh** [comment]
I've recently found myself appreciating labels that weren't strictly necessary just because they improved readability. I don't think this check is worth the potential noise.
