### ISSUE TITLE
staticcheck: flag "defer" in TestMain

### ISSUE THREAD

**Issue by klauspost** [dominikh/go-tools#251]
A `defer` in TestMain scope will never execute since `TestMain(*testing.M)` is [expected to use `os.Exit`](https://golang.org/pkg/testing/#hdr-Main).

What we want to detect is:

```Go
func TestMain(m *testing.M) {
	defer testTearDown() // never called
	os.Exit(m.Run())
}
```
However, detecting it is pretty tricky, since there can be valid constructions like this:

```Go
func TestMain(m *testing.M) {
	errC := 0
	defer func() { os.Exit(errC) }()
	defer testTearDown()
	errC = m.Run()
}
```

So the best rule I can come up with is to detect a defer in the same scope as `os.Exit()`. At least that should catch accidental use of defer in TestMain.

**Comment by dominikh** [comment]
With some extra work, we could extend this check to all functions. Any function¹ that has both defers and unconditional calls to os.Exit (i.e. every path through the function will call os.Exit) is wrong.

¹: from an SSA point of view, anonymous functions exist outside of their surrounding function. They're just functions that additionally take a pointer to a set of local variables (the closure.) That allows us to only consider functions, not scopes, as defers do not care about block scopes.

**Comment by shurcooL** [comment]
> A defer in TestMain scope will never execute since TestMain(*testing.M) is expected to use os.Exit.

Unless there’s a panic before `os.Exit` runs.

**Comment by dominikh** [comment]
@shurcooL has a valid point. I'm not sure we should implement this check. The following seems like a valid pattern:

```
func TestMain(m *testing.M) {
	defer testTearDown()
	ret := m.Run()
	testTearDown() 
	os.Exit(ret)
}
```

**Comment by klauspost** [comment]
Yeah. Back to manual checking. I will re-open if I come up with a better pattern
