### ISSUE TITLE
utility idea: print code defining an identifier

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#252]
Random idea for a possibly useful command line utility: `./dump github.com/example/foo.SomeIdentifier` which prints the code of the identifier, such as a function declaration (+ function body), a struct, a field, ...

Might be useful for integration with scripts, or quick debug sessions in a shell.

This is similar to `godoc -src`, except we'd support a wider range of identifiers with a better input syntax.

**Comment by shurcooL** [comment]
> except we'd support a wider range of identifiers with a better input syntax.

Just checking, are you familiar with the input syntax of `go doc` (as opposed to `godoc`)? As of Go 1.5, it was reworked (based on https://github.com/robpike/doc experiment) to accept a more flexible input syntax. See https://golang.org/cmd/doc/ for what it accepts.

If it happens to be close enough to what you're imagining, reusing it would make it easier to use your tool for anyone familiar with `go doc` syntax.

**Comment by dominikh** [comment]
`[<pkg>.]<sym>[.<methodOrField>]` would be the syntax we'd use. Which happens to be supported by go doc.

**Comment by dominikh** [comment]
`go doc` can print source code, and does basically exactly what our tool would do. Closing.
