### ISSUE TITLE
simple: add check for python style map sums 

### ISSUE THREAD

**Issue by frioux** [dominikh/go-tools#274]
https://play.golang.org/p/ZU-Ys77Q766

Basically, I have run into many variations of:

```golang
			if _, ok := found[x]; ok {
				found[x] += y
			} else {
				found[x] = y
			}

```

and even surprised some people who have been writing Go for years, when pointing out that thanks to zero values the above is totally superfluous, and that the following is totally sufficient.  (Or at least I can't think of a type where it is not.)

```golang
			found[x] += y
```

Note that I think `= 1` and `++` should be detected, but presumably as a special case, unless `++` desugars to `+= 1`.

**Comment by dgryski** [comment]
Related https://github.com/golang/go/commit/7395083136539331537d46875ab9d196797a2173

**Comment by frioux** [comment]
Here's another example I ran into:

```golang
	for _, logFilePath := range logFilesOnDisk {
		if _, ok := fileOffsets[logFilePath]; !ok {
			fileOffsets[logFilePath] = 0
		}
	}
```

The following is shorter and faster:

```golang
	for _, logFilePath := range logFilesOnDisk {
		fileOffsets[logFilePath] += 0
	}
```

(both maps are `map[string]int`)

**Comment by dominikh** [comment]
I assume you meant to use a constant other than `0`, because for the specific case of `0`, the whole loop can be optimized to `{}`.

**Comment by opennota** [comment]
> because for the specific case of `0`, the whole loop can be optimized to `{}`.

I don't think so: https://play.golang.org/p/Zp1uLfvqHAs

**Comment by dominikh** [comment]
Fair enough.

**Comment by dominikh** [comment]
I've implemented a check for https://github.com/dominikh/go-tools/issues/274#issue-305318761 but decided against adding one for https://github.com/dominikh/go-tools/issues/274#issuecomment-380996668 – personally I find the explicit version more readable, and I'm probably not the only one who'd want to argue with a check suggesting otherwise.
