### ISSUE TITLE
go get honnef.co/go/tools/cmd/staticcheck failed

### ISSUE THREAD

**Issue by luowqn** [dominikh/go-tools#275]
Hi,Can you help me ?
`[root@localhost node_exporter]# go get honnef.co/go/tools/cmd/staticcheck
package honnef.co/go/tools/cmd/staticcheck: unrecognized import path "honnef.co/go/tools/cmd/staticcheck" (https fetch: Get https://honnef.co/go/tools/cmd/staticcheck?go-get=1: net/http: TLS handshake timeout)`
What should i do to solve it?

**Comment by shurcooL** [comment]
Have you tried again a few more times? That error message sounds like a temporary network issue.

**Comment by wliyongfeng** [comment]
try `go get -insecure honnef.co/go/tools/cmd/unused`

**Comment by dominikh** [comment]
There hasn't been any feedback, and the issue was most likely flaky networking. Closing.

**Comment by GivenZeng** [comment]
I got the same error output while i ran this command in Dockerfile. 
![image](https://user-images.githubusercontent.com/18550585/51734618-06b75a80-20c0-11e9-89de-1b9f922e92c9.png)

**Comment by fortytw2** [comment]
@GivenZeng what's the output of `curl -vv -XGET -L 'https://honnef.co/go/tools/cmd/staticcheck?go-get=1' > /dev/null
` for you?

**Comment by GivenZeng** [comment]
![image](https://user-images.githubusercontent.com/18550585/52896519-4deac400-3204-11e9-8a94-1f1941951849.png)

**Comment by GivenZeng** [comment]
and my dockerfile is followed

```FROM golang:1.10
RUN apt-get update 
RUN apt-get install -y mysql-client 
RUN apt-get update && apt-get install -y autoconf automake libtool curl make g++ unzip unzip
RUN curl -OL https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip
RUN unzip -o protoc-3.5.0-linux-x86_64.zip -d /usr/local bin/protoc
RUN rm protoc-3.5.0-linux-x86_64.zip
RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
RUN go get honnef.co/go/tools/cmd/staticcheck```
