### ISSUE TITLE
simple: S1010: also omit first index if it's zero

### ISSUE THREAD

**Issue by Quasilyte** [dominikh/go-tools#277]
**Proposal**: make [S1010](https://staticcheck.io/docs/gosimple#S1010) handle first default index in addition to second default index.

From [slice expressions](https://golang.org/ref/spec#Slice_expressions):

>  For convenience, any of the indices may be omitted. A missing low index defaults to zero; a missing high index defaults to the length of the sliced operand: 
```
a[2:]  // same as a[2 : len(a)]
a[:3]  // same as a[0 : 3]
a[:]   // same as a[0 : len(a)]
```

Quick search shows that default first index is used more frequently inside Go core:
```
go/src $ grep -nr '\[:' | wc -l
3840
go/src $ grep -nr '\[0:' | wc -l
642
go/src $ grep -nr '\[0 :' | wc -l
93
```

Most likely it's not very smart to fix all occurrences in the standard library, but it may be
useful for new projects and Go developers that don't know that `[:x]` and `[0:x]` is equivalent.

**Comment by dominikh** [comment]
It's common to use an explicit `0` in code like this:

```
a = data[0:4]
b = data[4:8]
c = data[8:12]
```

which is why we don't make that suggestion.

**Comment by Quasilyte** [comment]
@dominikh, thanks for example.
It would be annoying if gosimple would change code like that, I agree.

The main reason why I opened this is to provide an issue that is simple to find if someone else will have similar question.

**Comment by dominikh** [comment]
Alright. I'm going to close this issue as it isn't actionable. We can point people to it if the question comes up again.
