### ISSUE TITLE
staticcheck: recommend RuneCountInString over len([]rune(s))

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#279]
As the title says.

Pro: it's faster.
Con: it doesn't always matter; the compiler may optimize it one day.

**Comment by fortytw2** [comment]
Perhaps this is a better check for simple than staticcheck?

**Comment by dominikh** [comment]
@fortytw2 I feel like `len` is actually simpler. No import, no function call, …

**Comment by dominikh** [comment]
Related: https://github.com/golang/go/issues/24923

**Comment by egonelbre** [comment]
The question is how many places exist where rune count is the actual thing that people wanted?

I would suspect that in most cases people want the number of characters and not the number of runes.

**Comment by dominikh** [comment]
No longer relevant, it gets optimized by the compiler now: https://go-review.googlesource.com/c/go/+/108985

**Comment by Zyl9393** [comment]
Disregard that this is a terrible idea, but would the following yield the same results for all strings `s` as the other methods?

```golang
runeCount := 0
for range s {
    runeCount++
}
return runeCount
```
