### ISSUE TITLE
staticcheck: report io.Reader and io.Writer violations

### ISSUE THREAD

**Issue by dsnet** [dominikh/go-tools#283]
The lack of memory ownership and immutability in the Go type system is achieved via documented restrictions that programmers are expected to follow. The two most common interfaces `io.Reader` and `io.Writer` should have the following properties:
* For both `Read` and `Write`, user code should never cause the input to escape.
* For `Write`, user code should never mutate the input slice.

**Comment by dominikh** [comment]
> For both Read and Write, user code should never cause the input to escape

I don't think we can check for that without causing false positives.

> For Write, user code should never mutate the input slice

[SA1023](https://staticcheck.io/docs/checks#SA1023) flags simple modifications of the passed-in buffer – it currently detects direct writes to elements, and uses of append, if they happen directly on the parameter. We could improve it in the future and e.g. catch the parameter passing through a function (such as bytes.Split) before being modified. That's an open to-do in the check.

I am going to close this issue, as I think it has been addressed.
