### ISSUE TITLE
unused: detect exported identifiers which are only used in their package's tests

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#289]
When refactoring a well unit-tested codebase, I always have this issue. A function or type are not used in the project any more, but they are not marked as unused because they have unit tests. I have to manually inspect the code with e.g. `git grep` to make sure that the identifiers aren't used anywhere else.

It would be really nice if `unused` could help me in such situations.

**Comment by dominikh** [comment]
You can use `unused -tests=false` to exclude tests.

**Comment by ainar-g** [comment]
How did I miss that. Thanks! Closing.
