### ISSUE TITLE
gorename fails renaming when net/http is imported

### ISSUE THREAD

**Issue by RiccardoManfrin** [dominikh/go-tools#291]
go version go1.10.1 linux/amd64

When I import "net/http" gorename (being invoked from vscode) stops working with the following error:

`Rename failed: /usr/lib/go-1.10/src/net/C:18:25: expected type, found '=' (and 2 more errors) gorename: couldn't load packages due to errors: net `

I thought I could find the `/usr/lib/go-1.10/src/net/C` file but it just doesn't exist, neither locally nor in repo.

**Comment by dominikh** [comment]
Your `gorename` has been built with an old version of Go, before type aliases were added to the language. Reinstall `gorename` (and all other outdated tools) and the error will go away.

As an aside, `C` is a synthetic file, part of how cgo is handled internally by go/loader. It doesn't exist on disk.

**Comment by RiccardoManfrin** [comment]
Thanks .. I should have posted elsewhere (that's why I closed) but thanks.. I'll update and see
