### ISSUE TITLE
honnef.co: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by ryanatallah** [dominikh/go-tools#292]
I am running `go get honnef.co/go/tools/cmd/megacheck` from inside a docker container (of a CI pipeline), which returns the following error message:

> package honnef.co/go/tools/cmd/megacheck: unrecognized import path "honnef.co/go/tools/cmd/megacheck" (https fetch: Get https://honnef.co/go/tools/cmd/megacheck?go-get=1: x509: certificate has expired or is not yet valid)

**Comment by derekcollison** [comment]
Yep same here. You may be able to use -insecure on your go get command.

**Comment by dominikh** [comment]
The issue should be resolved now. I'm so sorry for the inconvenience. I'm making sure this will not happen again.
