### ISSUE TITLE
attempts to import from external package tests

### ISSUE THREAD

**Issue by party79** [dominikh/go-tools#295]
Since 2d8aba914b22304cdf60efb578c638933149a084 it appears that running `megacheck` at least is attempting to import from the tests of the external packages which is causing it to fail.

eg am getting:
```sh
cannot find package "gopkg.in/gemnasium/logrus-airbrake-hook.v2" in any of:
	/Users/sanatised/go/src/sanatised/sanatised/sanatised/vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (vendor tree)
	/usr/local/Cellar/go/1.10.3/libexec/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (from $GOROOT)
	/Users/sanatised/go/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (from $GOPATH)
```

Note that I'm not using that package and it is only imported from `github.com/sirupsen/logrus/example_hook_test.go`

**Comment by dominikh** [comment]
I will have to think about this. In the past, we only loaded tests of directly specified packages, now we load tests of all packages.

The options are:

1. keep doing what we're doing
2. revert to the old way
3. attempt to load tests, but don't fail if doing so isn't possible.

**Comment by rgeronimi** [comment]
This issue is making megacheck unusable on large projects, as it pulls unwanted dependencies through the test files of third-party libraries. In our case we use `github.com/cespare/xxhash` which, for benchmark reasons, references several other hash libraries in its test suite. Bringing back these unwanted dependencies into the scope of our project is undesirable.

**Comment by luna-duclos** [comment]
3 seems like a very reasonable approach

**Comment by dominikh** [comment]
@rgeronimi makes a convincing argument. We'll go with option 2 for now (since it's easier and faster to implement), and revisit option 3 when `go/packages` becomes a thing.
