### ISSUE TITLE
staticcheck: failure on "go get"

### ISSUE THREAD

**Issue by AndrewRickert** [dominikh/go-tools#296]
The following command no longer seems to function:

 `go get -u github.com/dominikh/go-tools/cmd/staticcheck`

On my local machine I get an X.509 error.

> package honnef.co/go/tools/lint/lintutil: unrecognized import path "honnef.co/go/tools/lint/lintutil" (https fetch: Get https://honnef.co/go/tools/lint/lintutil?go-get=1: x509: certificate signed by unknown authority)
package honnef.co/go/tools/staticcheck: unrecognized import path "honnef.co/go/tools/staticcheck" (https fetch: Get https://honnef.co/go/tools/staticcheck?go-get=1: x509: certificate signed by unknown authority)

The same is true for the original address:

`go get honnef.co/go/tools/cmd/staticcheck`

> package honnef.co/go/tools/cmd/staticcheck: unrecognized import path "honnef.co/go/tools/cmd/staticcheck" (https fetch: Get https://honnef.co/go/tools/cmd/staticcheck?go-get=1: x509: certificate signed by unknown authority)

And in the bitbucket pipeline where I run 'go get' to get the static check tool, I get the following response:

```
go get honnef.co/go/tools/cmd/staticcheck
# honnef.co/go/tools/lint/lintutil
```
`/go/src/honnef.co/go/tools/lint/lintutil/util.go:273: undefined: types.SizesFor`

**Comment by dominikh** [comment]
The certificates are signed by Let's Encrypt; make sure that your local certificate store includes their certificates. 

types.SizesFor was added in Go 1.9 – the current version of Go is Go 1.10, and we support the current and previous version of Go (much like the tools in x/tools) – you'll need to update your Go version.

**Comment by AndrewRickert** [comment]
Thanks @dominikh.
