### ISSUE TITLE
golang tip issue

### ISSUE THREAD

**Issue by tiger5226** [dominikh/go-tools#297]
Here is a travis job build https://travis-ci.org/lbryio/chainquery/builds/402079969 that fails on the tip of golang. It has been failing for the past couple of days. You can see from the history. Are you aware of any issues?

It is also failing in different parts too. Different packages each time. I restarted the build a couple of times. 

I wanted to be proactive, and report the issue here just in case.

**Comment by dominikh** [comment]
I was not aware of any tip specific issues, no.

Just to make sure: does the package `github.com/davecgh/go-spew/spew` actually exist in the tree, at either of the paths mentioned in the error message? And is spew a direct dependency, or a transitive one?

**Comment by tiger5226** [comment]
There were a few examples, as I ran it a number of times with different imports offending. The common theme is that they are all imports of testing files. These are all vendored transitive ones.

**Comment by tiger5226** [comment]
I also briefly reviewed the golang commits over the past 48 hours, but nothing stood out like a sore thumb. They may find the problem in their own testing, so I will update if it starts passing again on the tip.

**Comment by dominikh** [comment]
This looks a lot like https://github.com/dominikh/go-tools/issues/295, but that would've affected all versions of Go, not just tip.

**Comment by tiger5226** [comment]
agreed. Maybe some recent golang changes exacerbated the problem.
In new news, the nightly build passed on the tip. Not sure why or if this is random somehow. https://travis-ci.org/lbryio/chainquery/jobs/402528283

**Comment by dominikh** [comment]
The two build jobs in https://travis-ci.org/lbryio/chainquery/builds/402079969 started at vastly different times.

The Go 1.10 job started at July 11, 6:22:11, but the Go tip job started at July 10, 8:45:06 – no idea why that difference is so large, but it does span the duration in which #295 applied.

**Comment by dominikh** [comment]
@tiger5226 ping

**Comment by tiger5226** [comment]
Sorry, I didn't see a question so I did not response. I agree that is a big difference. Are you suggest maybe it was a travis build issue?

**Comment by dominikh** [comment]
Because the two jobs ran at two different times, they used two different versions of staticcheck. One of the versions had a bug (https://github.com/dominikh/go-tools/issues/295), which is why it failed. The failure wasn't specific to go tip. I assume you haven't seen any more failures since then.

**Comment by tiger5226** [comment]
That is a nice find! I have not seen anymore failures. I am sorry for taking up that much of your time.

**Comment by dominikh** [comment]
Absolutely not a problem.
