### ISSUE TITLE
staticcheck: functions returning interfaces and untyped nil checking

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#298]
This might be an extension of #285, so feel free to close.

Another real-life bug, which I think we can relatively easily detect.

https://play.golang.org/p/gwmUi0EY7wO

Here, `f` never returns an *untyped* `nil`. Yet, `main` checks the result of `f` against untyped `nil`, which of course always returns `false`. This causes trouble later, if the implementation of `m` doesn't account for null pointers.

I think that we can detect functions that return interfaces, but never an explicit `nil`, and then mark places where the callers check the results against `nil` as erroneous and always false.

* * *

A more general approach would be to try and always mark places where an interface value can be a pointer, and the implementation of the methods doesn't account for null pointers, but that is way more complex and noisy, since basically any interface can be implemented incorrectly in this way. But this one, I think, is pretty solid.

**Comment by dominikh** [comment]
@dgryski brought up another situation that is likely free of false positives: returning typed nils for errors. In that case, we could probably even flag functions that only _sometimes_ return typed nils.

**Comment by dominikh** [comment]
Closed by 146f620c9673a52224cc21f8d8ac03025c47a654.
