### ISSUE TITLE
detect append in a loop

### ISSUE THREAD

**Issue by josharian** [dominikh/go-tools#30]
a la https://github.com/golang/go/commit/99df7c9caa19d99747c4766be171c9487c9645cf

**Comment by shurcooL** [comment]
This is already implemented, see `gosimple` and its S1011 check.

| Check | Description                                                                 | Suggestion                              |
|-------|-----------------------------------------------------------------------------|------------------------------------------------------------------------|
| S1011 | A loop appending each element of `s2` to `s1`                               | `append(s1, s2...)` 

Source: https://github.com/dominikh/go-tools/tree/master/cmd/gosimple#checks.

```
$ git checkout 99df7c9^
$ gosimple crypto/tls
goroot/src/crypto/tls/common.go:949:2: should replace loop with varDefaultCipherSuites = append(varDefaultCipherSuites, topCipherSuites...) (S1011)
...
$ gosimple cmd/link/internal/ld
goroot/src/cmd/link/internal/ld/deadcode.go:257:3: should replace loop with names = append(names, markextra...) (S1011)
```
