### ISSUE TITLE
simple: skip "empty branch" check if there are any comments

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#301]
It's too prone to false positives. For example, I recently commented out a line of test code with a TODO:

```
offs := node.Pos().Offset()
if offs >= lastOffs {
        lastOffs = offs
} else {
        // TODO: revisit; breaks with heredocs
        //t.Errorf("comment offset goes back")
}
```

I can't see a simpler/better way to do it, and this way seems perfectly fine to me.

**Comment by ainar-g** [comment]
I assume `t` is a `*testing.T` there? Then I would write something like

```go
offs := node.Pos().Offset()
if offs >= lastOffs {
        lastOffs = offs
} else {
        t.Log("TODO: revisit; breaks with heredocs")
        // t.Errorf("comment offset goes back")
}
```

**Comment by mvdan** [comment]
I didn't know gosimple was less reliable by design. Either of the proposed alternatives seem fine as well. I'll just ignore the warning :)

**Comment by Deleplace** [comment]
I also experience false positives. In my case they are not "TODOs" and "commented out LOCS", they are documentation.

```
	if cached, ok := cache.Lookup(id); ok {
		return cached, true
	} else {
		// Even if the value was cached, it may has
		// been evicted anytime so we can't rely on it.
		// This is fine, in this case we will have to
		// query the DB, this is just slower.
	}
```

**Comment by ainar-g** [comment]
<p>@Deleplace&#x2003;Your&#xA0;code can be simplified&#xA0;to:</p>

<pre><code>if cached, ok := cache.Lookup(id); ok {
&#x09;return cached, true
}

// Even if the value was cached, it may has
// been evicted anytime so we can't rely on it.
// This is fine, in this case we will have to
// query the DB, this is just slower.

// …</code></pre>

<p>Which&#xA0;also removes the&#xA0;warning.</p>

**Comment by Deleplace** [comment]
@ainar-g I write the "else" block on purpose, for legibility, because I want the code to look like "First deal with everything related to the cache, which is a possible short path that returns early", and everything below is the "nominal code".

I acknowledge that your refactoring follows the Go common style and that "The point of a common style is that it overrides personal preference" so I'll happily give up my personal preference because I see high value in having a common style.

**Comment by ainar-g** [comment]
<p>@Deleplace&#x2003;Ah, I&#xA0;see.&#x2003;You can currently do
something like&#xA0;this:</p>

<pre><code>if 1 == 2 {
&#x09;return 1
} else
//lint:ignore SA9003 This is documentation.
{
&#x09;// One does not actually equal two.  This can happen in
&#x09;// some parallel universes that we have to support.  Go
&#x09;// on and return zero.
}

return 0</code></pre>

<p>It's uglier, obviously, but keeps the if-else structure.</p>

**Comment by TafThorne** [comment]
I had what I was suspecting to be a false positive from a staticcheck run inside a golangci-lint run.  The case I am seeing is not exactly covered here so I will post it by reusing the starting example: 

```go
offs := node.Pos().Offset()
if offs >= lastOffs {
        lastOffs = offs
} else if offs < firstOffs {
        offs = firstOffs
} else {
        // Not bigger than or smaller than expected so everything is OK!  
}
```
My issue with this being flagged is that the `else` clause is there with an explicit comment to show that the author thought about a chain of `if {} else if {}` and explicity consider the "default" drop through case.  If we miss that case you have to assume that they did think about handling it and nothing was needed.  I expect that the `else` is actually compilled out so has 0 performance impact normally.  

Now I could re-write this as:

```go
offs := node.Pos().Offset()
if offs >= lastOffs {
        lastOffs = offs
} else if offs < firstOffs {
        offs = firstOffs
} 
// else { Not bigger than or smaller than expected so everything is OK! }
```
Which would achive a similar thing.  However other checking tools I am also running currently complain that this leaves an -unhandled case in an if else if sequence.  

So my final compromise is:

```go
offs := node.Pos().Offset()
if offs >= lastOffs {
        lastOffs = offs
}
if offs < firstOffs {
        offs = firstOffs
} 
```
Which is clear, it has not chain so there is no default else path to consider but it also means doing two checks when one would be enough.  Probably only a very small performance hit in many cases but still not ideal to me.

Within my company we have people that would say you should put the else on the end and some that say it is just a style thing so it does not matter and some that say you should not do it as it is extra code.  I can see from this thread that in many cases a compromise has been reached.  I did feel it worth checking if the difference between a basic if else and a chain of them was considered.  

Sorry for a necro post but it was directly related.
