### ISSUE TITLE
Suppress "argument should be pointer-like" warnings for slices

### ISSUE THREAD

**Issue by yasushi-saito** [dominikh/go-tools#302]
```
package main

import "sync"

var pool = sync.Pool{New: func() interface{} { return nil }}

func main() {
	pool.Put([]byte{'a', 'b'})
}
```
test.go:8:10: argument should be pointer-like to avoid allocations (SA6002)

Slice is a pointer itself, so staticcheck shouldn't complain about it.

**Comment by dominikh** [comment]
A slice is not a pointer. A slice is a struct consisting of three fields: length, capacity, and a pointer to data. 

Please see http://staticcheck.io/docs/staticcheck#SA6002

**Comment by vipcxj** [comment]
@dominikh I know a slice is not a pointer, but is it be safe to managed by a pool directly?

**Comment by dominikh** [comment]
@vipcxj Any type is safe to put in a pool. Only pointer types avoid allocations when doing so. See https://staticcheck.dev/docs/checks#SA6002.

**Comment by vipcxj** [comment]
@dominikh  The structure overhead of slice itself is supposed to be cheap right, it's the data it points to that matters. So if instead of using the slice pointer, just use slice, will the data pointed to by slice be double allocated?

**Comment by frankli0324** [comment]
> Only pointer types avoid allocations when doing so.

there are people who don't use Pool to *avoid* allocations, but to *reduce* allocations. I find an extra 24 B/op acceptable for me.

```go
unsafe.Sizeof(reflect.SliceHeader{}) == 24
```
