### ISSUE TITLE
megacheck: allow exclusion of tests per tool

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#304]
Right now megacheck has a `-tests` flag, which is shared across all three tools. But I always want `unused` to skip tests, in order to find objects that are only used in tests (see #289), but still have `simple` and `staticcheck` check my tests. Right now I have to call `unused` separately with `-tests false`, which obviously means that the check time is almost doubled.

**Comment by dominikh** [comment]
I feel like `-tests=false` isn't _really_ what you want to use for unused, as that won't flag any unused identifiers that are declared in tests.

We should probably flag identifiers declared in non-test files that are only used from tests, even with `-tests=true`.

**Comment by dominikh** [comment]
And that would be https://github.com/dominikh/go-tools/issues/94
