### ISSUE TITLE
Add check for unused returned error

### ISSUE THREAD

**Issue by nicholasjackson** [dominikh/go-tools#31]
Hi,

I would like to add a check for blank identifiers like the example below:

```go
data, _ := json.Marshal(myStruct)
```

This is based on advice from @ardan-bkennedy

Would this be best placed in the staticchecker or simple, my mind says staticchecker?

**Comment by mdlayher** [comment]
You may be looking for: https://github.com/kisielk/errcheck.

**Comment by nicholasjackson** [comment]
Yep that is the tool i am looking for thanks, will close this issue.
