### ISSUE TITLE
staticcheck: SA1019: ignore deprecated objects used in external tests

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#317]
We already ignore deprecated objects that are used in the same package and its tests, but not if the tests are external.

**Comment by sourabh-upadhyay** [comment]
@dominikh I am running staticcheck on my project, but the `Deprecated:` warning is not reported. Is there any reason why?

Or what should I do to allow them?

**Comment by ainar-g** [comment]
@sourabh-upadhyay, this is probably not the issue you are looking for.  Please make sure that your `Deprecated` directive is in a paragraph of its own, see https://github.com/dominikh/go-tools/issues/926#issuecomment-774541386.

**Comment by dominikh** [comment]
I cannot reproduce this, and according to the git history, ever since the first implementation of the check we've been checking for `*_test`
