### ISSUE TITLE
deprecated: make intra-package deprecated usage checking configurable

### ISSUE THREAD

**Issue by Quasilyte** [dominikh/go-tools#323]
Right now, there is no way to make `deprecated` to warn on deprecated usages inside the package that defined them.

@IAD, could you elaborate on this one a little bit, since motivation is missing from the story that is known to me?

**Comment by IAD** [comment]
Hello. One of the popular code organization structure is a mono-repository. In this case would be good to add a command line parameter to allow internal check https://github.com/dominikh/go-tools/blob/next/staticcheck/lint.go#L2348

additionally would be good to lint deprecated usages in tests too

**Comment by dominikh** [comment]
So, what I'm trying to understand is why the monorepo matters. The exception in the code is for identifiers used within the same package, not the same repository.

**Comment by IAD** [comment]
@dominikh we are talking about the same. After an investigation, I see that staticcheck handles comments with messages like
```
// Deprecated: {some}
```
but don't handle
```
// deprecated: {some}
// Deprecated
// Deprecated:
// Deprecated Use
```

**Comment by dominikh** [comment]
That's correct. `// Deprecated: <message>` is the official way of deprecating things, and the only format we support. It's also the only format you should use, to guarantee interoperability with tools.

**Comment by IAD** [comment]
clear, we have a confusion when editors(Jetbrains idea) handle different forms of `deprecated` as valid deprecated comments(visually marked as crossed out). Probably we need a linter to validate special comments that looks like special

**Comment by dominikh** [comment]
> Probably we need a linter to validate special comments that looks like special

That falls outside my responsibility I'm afraid, since such a check would be prone to false positives.

Consider the following example:

```
// Foo finds deprecated objects.
// Deprecated objects are defined as ...
func Foo() {}

**Comment by Quasilyte** [comment]
@IAD, is your problem with different "deprecated" comments format or does you still need unused linter to check for usages inside the same package that defined those symbols?
These are 2 different issues.

**Comment by IAD** [comment]
thank you @Quasilyte  , @dominikh  for the help, the issue completely solved(we have to pay more attention to code style guidelines).
