### ISSUE TITLE
keyify: an option to overate over a complete file or package

### ISSUE THREAD

**Issue by kortschak** [dominikh/go-tools#327]
At the moment keyify will add keys to a given source instance of a struct literal. I think it would be useful to be able to add keys to all instances of unkeyed literals in a file or package. The use case for this is repairing code that will not run on GAE because of its strict requirement for keyed structs.

**Comment by dominikh** [comment]
Can you point me to the relevant GAE documentation that mentions this restriction? And I assume this only pertains to struct types defined in imported packages?

**Comment by kortschak** [comment]
It's now clear that this was the behaviour, though I have not had any responses about whether it still is. It seems that the vetting that's done (or was done) is `go vet -composites` which complains of use of unkeyed composite struct literals from imported packages.
