### ISSUE TITLE
gosimple: handle parenthesis in S1009 

### ISSUE THREAD

**Issue by Quasilyte** [dominikh/go-tools#337]
Today I found code like this (simplified):
```go
func foo(xs []int) bool {
	return (xs == nil) || (len(xs) == 0)
}
```
It does not trigger `gosimple` S1009.
Removing parenthesis helps (code below triggers a warning):
```go
func foo(xs []int) bool {
	return xs == nil || len(xs) == 0
}
```
I think gosimple could try to unparen expressions and try matching again to handle such cases.

**Comment by dominikh** [comment]
I'll close this in favour of the more general #315
