### ISSUE TITLE
unused: interaction with stringer

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#338]
Quoting @dgryski from Slack:

```
So, we have a bunch of constants declared like

type Foo int
const (
   unknownFoo Foo = iota
   FooThing1
   FooThing2
   ...
)

and then we use stringer generate String() for Foo.

Now, unknownFoo isn't explicitly used on its own in our code, but it does find its way into the stringer table so that zero-valued Foo's are printed as unknownFoo instead of stringer's default Foo(0).
```

I think we want to ignore the unused `unknownFoo`, since it serves a purpose.

**Comment by seebs** [comment]
that looks like a PEG grammar file.

also, as a further note: i'd prefer not to suppress the warning entirely, because the same warning about one of the later rules *does* appear to indicate an actual possible issue with the grammar.

**Comment by dgryski** [comment]
It's not a PEG grammar, it's just a regular set of constants for which 0 is an invalid value.

**Comment by seebs** [comment]
Ahh, 'k. I was seeing this in a nearly-identically structured list, complete with the 0 case being unknown, and the type embedded in the name. I guess that's just idiomatic.

**Comment by dominikh** [comment]
Fixed in master.
