### ISSUE TITLE
gosimple: simplify comma-ok type assertions in if statements.

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#34]
This is a potential check to consider. I imagine it would belong to `gosimple`, but I'll let you triage.

According to https://golang.org/ref/spec#Type_assertions:

> For an expression `x` of interface type and a type `T`, the primary expression
>
> ```Go
> x.(T)
> ```
>
> asserts that `x` is not nil and that the value stored in `x` is of type `T`. [...] The value of `ok` is `true` if the assertion holds.

Therefore, if statements that have this kind of "shape":

```Go
if _, ok := x.(T); x != nil && ok {
```

Can be simplified to:

```Go
if _, ok := x.(T); ok {
```

Here's a real world case example I found that triggered the idea.

https://github.com/google/go-github/blob/2a4b92075e5c5e42e/examples/basicauth/main.go#L40

I imagine this will occur with low-medium frequency, more so in code written by people less experienced with Go.

**Comment by dominikh** [comment]
The question is, is this a simplification, or is the original code indicative of a bug? Consider this piece of code:

```
i := interface{}((*T)(nil))
if _, ok := i.(*T); i != nil && ok {
	println("hi")
}
```

Is the `i != nil` comparison merely redundant, or should it have been 

```
i := interface{}((*T)(nil))
if t, ok := i.(*T); t != nil && ok {
	println("hi")
}
```

instead?

**Comment by shurcooL** [comment]
> The question is, is this a simplification, or is the original code indicative of a bug?

In the general case, I don't think that question can be answered conclusively.

For every possible opportunity to simplify code, one of two situations is possible:

- the person didn't realize the same behavior could be expressed with simpler code
- or, perhaps the person wanted to have different behavior from the current behavior, but inadvertently failed to achieve that without realizing it

If you want to be very precise, I imagine the best you can do is is to explain that in the check warning text.

Or you can pick the more expected likely scenario and people should understand that every simplification check is a possible bug (unintended behavior), and every bug is a possible invalid simplification attempt.

**Comment by shurcooL** [comment]
Thank you @dominikh!
