### ISSUE TITLE
gosimple: redundant breaks

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#35]
```
switch a {
case b:
    foo()
    break
case c:
    bar()
}
```

Breaks are implicit, so I don't see how a `break` at the end of a switch case block could ever be useful. Similar to a `return` at the end of a func that has no named return values.

**Comment by shurcooL** [comment]
> Similar to a `return` at the end of a func that has no named return values.

Is that already done anywhere?

**Comment by mvdan** [comment]
Was about to ask the same - probably my fault for not filing separate issues.

**Comment by dominikh** [comment]
Find out and file an issue if not :)

**Comment by mvdan** [comment]
Done: https://github.com/dominikh/go-tools/issues/64
