### ISSUE TITLE
go vendor, go modules and macos mojave

### ISSUE THREAD

**Issue by lc-chrisbarton** [dominikh/go-tools#353]
Hi,

On a new installation of macos mojave (disk wiped) we get the following error when using go 1.11 in modules mode

```go
go mod vendor
go: honnef.co/go/tools@v0.0.0-20180728063816-88497007e858: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: x509: certificate signed by unknown authority)
go: error loading module requirements
```

```shell
echo $?
1
```

```shell
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tom/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tom/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tom/lc-api/src/xxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d4/41hkn63x07g9pc3m624tsj1m0000gp/T/go-build817824147=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by dominikh** [comment]
Make sure your systems accept certificates signed by Let's Encrypt.

**Comment by dominikh** [comment]
https://github.com/Homebrew/brew/issues/4870 one wonders if Mojave broke something (git in our case though, not SVN like in the linked issue)

**Comment by lc-chrisbarton** [comment]
Thanks for getting back so fast. We use Let's Encrypt for our services and have no problems, see attached screenshots
![lets-encrypt-not-working](https://user-images.githubusercontent.com/31261535/46310856-07157c80-c61d-11e8-8bfb-c49644ba4fc1.png)
![lets-encrypt-working](https://user-images.githubusercontent.com/31261535/46310860-0a106d00-c61d-11e8-8779-a1b126f0e5dc.png)

**Comment by lc-chrisbarton** [comment]
BTW it works on another machine but that machine has Xcode installed instead of just the Xcode commands line tools auto-installed by brew. We will install the full version of Xcode and post back the results

**Comment by dominikh** [comment]
I don't see why it would accept one LE certificate but not another. Our certificates were generated a week apart and look otherwise identical.

**Comment by lc-chrisbarton** [comment]
Installing full version of Xcode makes no difference

**Comment by lc-chrisbarton** [comment]
Apologies, this issue is due to our corporate firewall flagging the domain as hosting a virus "stuff.fork-bomb.org
![screen shot 2018-10-02 at 4 25 39 pm](https://user-images.githubusercontent.com/31261535/46327980-14545a80-c661-11e8-9675-651b7f7b59cb.png)
". We have opened a ticket with the party responsible for our firewall and will update this ticket ASAP

**Comment by lc-chrisbarton** [comment]
HI, we received a response from the party responsible for our corporate filewall and so is it safe to treat this as a false positive i.e. there is not malware hosted at stuff.fork-bomb.org despite it being flagged as hosting such content? Thanks in advance

"The Fortigate looks at name of the website as well as the IP it’s on. In this case, honnef.co is a valid website with no issues, but the IP that it resolves to has been flagged as ‘Phishing’. So it could be hosted on a hosting provider that is also hosting phising websites. I can create an exception for this website if you’d like?"

**Comment by dominikh** [comment]
The website is hosted on DigitalOcean, so I have no idea who used this IP before. None of my domains (honnef.co, staticcheck.io, *.fork-bomb.org) hosts any questionable content.

**Comment by lc-chrisbarton** [comment]
Thanks
