### ISSUE TITLE
unused: don't flag fields as unused for structs addressed through an unsafe.Pointer

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#355]
(I feel like we've discussed this before, but I couldn't find an issue. Sorry if this is a duplicate.)

Right now if you have an unexported struct with unexported fields that you use for unsafe purposes the fields get marked as U1000.

For instance, we have some code which deals with Linux capabilities and needs to mirror some kernel structs. It's basically this code:

https://github.com/syndtr/gocapability/blob/d98352740cb2c55f81556b63d4a1ec64c5a319c2/capability/syscall_linux.go#L14-L39

Unused marks the capHeader.version field as unused (in our code that field is never referenced).

(I assume you get the idea but if it's not clear I'll make exact repro code.)

I think that if you define a struct S, if there's ever code that does `unsafe.Pointer(&s)` (where s is an S) then all of S's fields should be assumed used.

**Comment by dominikh** [comment]
I don't think we've talked about this before. Your solution makes sense.

**Comment by dominikh** [comment]
(We've previously talked about this at https://github.com/dominikh/go-unused/issues/37. The check I implemented there looks for `(T)(unsafe.Pointer(v)`, it doesn't consider `x = unsafe.Pointer(v)`. Will fix.)

**Comment by dominikh** [comment]
This is fixed in master.

**Comment by cespare** [comment]
Awesome, thanks!
