### ISSUE TITLE
staticcheck -ignore doesn't ignore

### ISSUE THREAD

**Issue by jadekler** [dominikh/go-tools#356]
```
$ staticcheck -ignore "trace/trace_test.go:SA4010" ./...
trace/trace_test.go:135:25: this result of append is never used, except maybe in other appends (SA4010)
```

Any idea what I might be doing wrong?

**Comment by dominikh** [comment]
`-ignore` expects a full import path. For example, `-ignore honnef.co/go/tools/ssa/dom.go:SA4010`

As an aside, you probably don't want to ignore SA4010. It shouldn't have any false positives.

**Comment by jadekler** [comment]
Ah! Thanks. SA4010 is being ignored because the usage is in an example (not real code).
