### ISSUE TITLE
Catch unnecessary strings.HasPrefix/strings.HasSuffix calls

### ISSUE THREAD

**Issue by andy-js** [dominikh/go-tools#359]
This is a feature request more than a bug.

It would be nice of megacheck produced a warning for code that does:

```
if strings.HasPrefix(something, somethingElse) {
    something = strings.TrimPrefix(somethng, somethingElse)
}
```

And:

```
if strings.HasSuffix(something, somethingElse) {
    something = strings.TrimSuffix(something, somethingElse)
}
```

And:

```
if strings.Contains(something, somethingElse) {
    something = strings.Replace(something, somethingElse, replacement, -1)
}
```

There's probably a few more too, but I can't think of them right now.

**Comment by dmitshur** [comment]
Have you seen https://staticcheck.io/docs/gosimple#S1017?

**Comment by andy-js** [comment]
It does not complain about these snippets.

**Comment by dominikh** [comment]
S1017 is (currently) concerned with using predicates and manual slicing, not predicates and TrimPrefix/Suffix.
