### ISSUE TITLE
Recommend strings.EqualFold

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#366]
Recommend strings.EqualFold over strings.ToLower() == strings.ToLower()

**Comment by ainar-g** [comment]
Oh wow. Up to 7x performance gain:

```
BenchmarkEqual/ToLower-4        	   20000	     71212 ns/op
BenchmarkEqual/ToUpper-4        	   20000	     70004 ns/op
BenchmarkEqual/EqualFold-4      	  200000	     10574 ns/op
```

**Comment by dominikh** [comment]
Inspired by https://blog.digitalocean.com/how-to-efficiently-compare-strings-in-go/ which has more extensive benchmarks

**Comment by ksurent** [comment]
Anyone working on this? If not, I'd be interested in giving it a try.

**Comment by dominikh** [comment]
@ksurent Feel free to. But as you can tell from your other PR, I may take a while to review and merge it.
