### ISSUE TITLE
Unused - False positive on composable private interfaces

### ISSUE THREAD

**Issue by esenac** [dominikh/go-tools#370]
Hi, I have a private interface composed of two other private ones:
```
type domainGetterSaver interface {
	domainGetter
	domainSaver
}

type domainSaver interface {
	Save(string, string) error
}

type domainGetter interface {
	Get(string) (string, error)
}
```
This interface is then uses as a field in a struct and its methods are invoked in struct's methods.
```
type Service struct{
   gs domainGetterSaver
}
...
func (s Service) Save(){
  s.gs.Save("a","b")
}
...
func (s Service) Get(){
  s.gs.Get("c")
}
```
Running `megacheck` linter, the following errors pop out:
```
type `domainGetter` is unused" severity="error" source="megacheck"
type `domainSetter` is unused" severity="error" source="megacheck"
```

**Comment by esenac** [comment]
@ainar-g thanks for helping me. 
@dominikh I see the fix is in `next` branch, is there a plan for merging it in master? 
Thanks!

**Comment by dominikh** [comment]
Soon(tm). Some time in 2018.

**Comment by esenac** [comment]
Ok, thanks again.
