### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by untuned** [dominikh/go-tools#372]
`go get -u honnef.co/go/tools/`
`go: honnef.co/go/tools@v0.0.0-20180920025451-e3ad64cb4ed3: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: read tcp XXX.XXX.XXX.XX:XXXXX->138.197.72.227:443: read: connection reset by peer)`
`go: error loading module requirements`

**Comment by dominikh** [comment]
Is this still an issue? Seems like a temporary networking issue at DigitalOcean to me.

**Comment by untuned** [comment]
> 
> 
> Is this still an issue? Seems like a temporary networking issue at DigitalOcean to me.

Yes, still not working for me.

**Comment by ainar-g** [comment]
Works fine here in Moscow, Russia.

**Comment by dominikh** [comment]
I am going to close this issue. Nobody else has reported any connection issues.
