### ISSUE TITLE
staticcheck does not pick up S1002 failure

### ISSUE THREAD

**Issue by sebrandon1** [dominikh/go-tools#380]
https://staticcheck.io/docs/checks#S1002

```
func thisIsATest() string {

	badBool := false

	if badBool == true {
		return "bad"
	}

	return "good"
}
```

`megacheck` would have found the `badBool == true` comparison but it seems like staticcheck is not performing the same.

**Comment by dominikh** [comment]
Based on `thisIsATest` I am guessing that this code is from unit tests? If so, S1002 no longer flags code in tests, see #320 for details on why.

We should update the docs, though.

**Comment by sebrandon1** [comment]
Ah, yes.  The code I'm hitting that has a clear violation of S1002 is in a test file.  Good to know!  I couldn't find any reason why it wouldn't be working in the docs.
