### ISSUE TITLE
U1000 triggers for packages using cgo

### ISSUE THREAD

**Issue by jhenstridge** [dominikh/go-tools#384]
staticcheck produces spurious "unused function" warnings for packages that use cgo.  For example, consider the following trivial Go package:

    package example
    
    import "C"

If I run staticcheck on it, I get the following output:

    $ ./bin/staticcheck example
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:12:6: func _Cgo_ptr is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:15:5: var _Cgo_always_false is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:17:6: func _Cgo_use is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:18:6: type _Ctype_void is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:21:6: func _cgo_runtime_cgocall is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:24:6: func _cgo_runtime_cgocallback is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:27:6: func _cgoCheckPointer is unused (U1000)
    /tmp/gopackages428934073/go-build/example/_cgo_gotypes.go:30:6: func _cgoCheckResult is unused (U1000)

This was using Go 1.10.4 and current master of staticcheck as of today (rev 3f1c8253).

**Comment by dominikh** [comment]
This is fixed on master, and will be part of the upcoming 2019.1.1 release.
