### ISSUE TITLE
Interaction of ST1016 and generated code

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#389]
Suppose we have two files in a package:

a.go
```
package p

type S struct{}

func (x S) F()
```

b.go
```
// Code generated by tool x. DO NOT EDIT.

//lint:file-ignore ST1016 blah

package p

func (y S) G()
```

This will still be flagged by ST1016:

    a.go:5:12: methods on the same type should have the same receiver name (seen 1x "x", 1x "y") (ST1016)

I would also have to add a further `lint-file` directive to a.go in order to make it go away.

I think that if we're ignoring ST1016 in b.go, then all the receiver names therein should be ignored for the purpose of evaluating ST1016. WDYT?

If you agree with that, what do you think about ignoring all generated code in general for ST1016 (cf. #87) so I wouldn't need the file-ignore at all?

This is otherwise a great check and once we resolve this I think we'll enable it globally, even though it's not a default.

**Comment by dominikh** [comment]
The idea looks good at a glance, but the current framework doesn't really support that kind of logic. The way ignores work is a simple filter over all reports, filtering based on file name, and line number for non-file ignores. The actual check doesn't know if a receiver comes from a file that should be ignored or not. And if it did, that would interact poorly with the `-show-ignored` flag, unless we pass that through, too. But that's breaking at least one abstraction…

**Comment by cespare** [comment]
Ah. That makes sense. I suppose the fact that this check is totally "non-local" makes it pretty different from most other checks (except, e.g., ST1000 which is also disabled by default).

**Comment by cespare** [comment]
WDYT about suppressing ST1016 for generated code, at least? As it is today, if you use a generator that uses inconsistent receiver names (or two different generators, as I'm doing) then you can get packages that have receiver name disagreement entirely within generated code. By just ignoring ST1016 reports for generated code (as you do for SA9003), it would fix this particular case without getting into the trickiness you mentioned.

**Comment by dominikh** [comment]
That is a fair point. The receiver names in generated code only show up in documentation, in which case you may choose to complain to the author of the code generator. Will do.

**Comment by dominikh** [comment]
Another thing worth considering is grouping receiver names by file, and only checking for consistency within a single file.

**Comment by dominikh** [comment]
With 27a660a4b58b40c032f1dd332053c0e4c537496c, we completely ignore receivers in generated code. Receivers in generated code may disagree with each other. Receivers in non-generated code may disagree with receivers in generated code. We only flag conflicting receiver names that occur in non-generated code.

For now we still collect names from all (non-generated) files and do not group by file.

**Comment by cespare** [comment]
That works perfectly for me. Thanks!
