### ISSUE TITLE
staticcheck: consider automatically ignoring ST1005 for generated code

### ISSUE THREAD

**Issue by JrCs** [dominikh/go-tools#395]
Can you ignore automatically ST1005 errors (ST1005  error strings should not be capitalized) for generated code

**Comment by fortytw2** [comment]
Why should generated code be exempt from having proper errors within it?

**Comment by JrCs** [comment]
For example: i use go-swagger to create my web api server and it generate code with error strings capitalized.

**Comment by dominikh** [comment]
Then go-swagger should be fixed to comply with Go's best practices.

**Comment by dominikh** [comment]
To answer your edit: See https://staticcheck.io/docs/#ignoring-problems on how to ignore problems. There's also https://github.com/dominikh/go-tools/issues/386

**Comment by JrCs** [comment]
Ok @dominikh, but in case of file generated i can't add linter directives in them (because they are generated)

**Comment by dominikh** [comment]
You can wrap the generator, or you can convince them to add the directive, or better yet, to produce better code.

**Comment by dgryski** [comment]
@JrCs Have you filed a bug upstream with go-swagger about fixing the generated code?

**Comment by JrCs** [comment]
@dgryski no

**Comment by Liooo** [comment]
Had the same problem. quick dirty fix would be to add `//lint:ignore..` on top of go-swagger template https://goswagger.io/generate/templates.html

**Comment by JrCs** [comment]
@Liooo thanks for the PRs
