### ISSUE TITLE
What's the motivation for ST1015?

### ISSUE THREAD

**Issue by dmitshur** [dominikh/go-tools#396]
In order to have a better understanding, I'd like to ask what is the rationale behind the ST1015 check?

```
default case should be first or last in switch statement (ST1015)
```

The commit message of 076b5cbb05413519271282598f128e406f4da1ec does not provide motivation.

It triggered on some of my code that looked like this:

```Go
switch i {
case 0:
    // ... handle first
default:
    // ... handle middle
case len(x)-1:
    // ... handle last
}
```

If I know the motivation behind the check, it'll help me decide how to proceed. Thanks!

**Comment by dominikh** [comment]
The idea is to have `default` in a standard place, so that it's possible at a glance to determine whether a switch has a default case or not. This is especially useful for cases with dozens of cases.

**Comment by dmitshur** [comment]
Thank you for answering.
