### ISSUE TITLE
Basic install instructions

### ISSUE THREAD

**Issue by alicebob** [dominikh/go-tools#406]
Hi!

It would be great if https://staticcheck.io/docs/ would have the basic installation instructions. Yes, it's only a simple `go install github.com/dominikh/go-tools/cmd/staticcheck`, but still I have to figure out which exact subdir I need.

**Comment by iwittkau** [comment]
I use this script to install a released version:

```bash
export GO111MODULE=off
go get -u -d honnef.co/go/tools/cmd/...
cd $GOPATH/src/honnef.co/go/tools
git checkout release.2019.1
go install honnef.co/go/tools/cmd/...
```

```text
$ staticcheck -version
staticcheck 2019.1
``` 

Otherwise you end up with 

```text
$ staticcheck -version
staticcheck (no version)
``` 

You can also grab a binary from the [Releases](https://github.com/dominikh/go-tools/releases) page.

**Comment by dominikh** [comment]
We have installation instructions at https://staticcheck.io/docs/#installation now.
