### ISSUE TITLE
Add more default acronyms

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#409]
- [x] SIP
- [x] RTP
- [x] AMQP
- [x] DB
- [x] TS

**Comment by ainar-g** [comment]
The ones I add to almost all projects are:

* AMQP
* DB
* TS

Also, it would be nice if the `initialisms` setting merged the new ones with the default ones, instead of replacing them, as well as warn when you add the same thing twice, but those are minor inconveniences.

**Comment by dominikh** [comment]
@ainar-g as far as merging is concerned: `initialisms = ["inherit", "MY", "OWN", "ONES"]` will merge the new ones with the inherited set. it inherits from configs higher up the package tree, and ultimately the default configuration if all of the configs inherit.

**Comment by ainar-g** [comment]
Didn't think that `"inherit"` can be used in there as well. Awesome! This probably should be added to the example configuration in the docs, but I'll leave it to you to decide :-)

**Comment by ainar-g** [comment]
I assume that the list was made based on golint's `commonInitialisms` map from [here](https://github.com/golang/lint/blob/master/lint.go#L771). Are “LHS” and “RHS” excluded because there aren't enough hits in the wild?

**Comment by dominikh** [comment]
@ainar-g I think they are excluded because I disagreed with them being on the list.

**Comment by dominikh** [comment]
Closing this issue. If people want to propose new acronyms they should file new issues.
