### ISSUE TITLE
SA4006 false positive when in loop

### ISSUE THREAD

**Issue by jasonhancock** [dominikh/go-tools#411]
The following contrived code:

```
package main

func main() {
	m := make(map[string]interface{})

	for {
		_, ok := m["foo"].(string)
		if !ok {
			continue
		}
		if true {
			if _, ok = m["source"].(string); !ok {
				continue
			}

			if _, ok = m["filepath"].(string); !ok {
				continue
			}
		}
	}
}
```

generates:
```
foo.go:16:10: this value of ok is never used (SA4006)
```

If the for loop is removed and `s/continue/return/`, no issue is detected:

```
package main

func main() {
	m := make(map[string]interface{})

	_, ok := m["foo"].(string)
	if !ok {
		return
	}
	if true {
		if _, ok = m["source"].(string); !ok {
			return
		}

		if _, ok = m["filepath"].(string); !ok {
			return
		}
	}
}
```

**Comment by dominikh** [comment]
It's not exactly a false positive. The outcome of the flagged type assertion is irrelevant, because all it does is a `continue`. Being the last statement in a loop, however, the next thing to happen is a `continue`, anyway.

**Comment by jasonhancock** [comment]
I guess the message reported is what threw me off track. Closing.

**Comment by dominikh** [comment]
The fact we're matching this is a side effect of mild optimizations (really clean-up) that are done on the SSA form. It eliminates the `if !ok` check, which is why `ok` is considered unused. The fact it points at actual issues in your code is a nice side-effect, at the cost of worse messages.
