### ISSUE TITLE
S1021 false positive in one common circumstance

### ISSUE THREAD

**Issue by peterbourgon** [dominikh/go-tools#415]
I use the following pattern extensively.

```go
var h http.Handler
h = api.MyBaseHandler(db)
h = LoggingMiddleware(logger)(h)
h = InstrumentingMiddleware(metrics, upstream)(h)
h = arbitraryInterceptor{w: myWriter, next: h}
```

S1021 complains that it should be formatted as

```go
var h http.Handler = api.MyBaseHandler(db)
h = LoggingMiddleware(logger)(h)
// ...
```

which subverts the purpose.

I propose that S1021 fires only when it detects a declaration followed by a single assignment, not if the variable in the declaration is re-assigned multiple times in sequence.

**Comment by ainar-g** [comment]
I've had similar experience and can confirm that this check can be dubious.

**Comment by dominikh** [comment]
@ainar-g do you have any examples that are different from Peter's?
@peterbourgon will fix.

**Comment by ainar-g** [comment]
@dominikh My example was something like

```go
var q string
q = `SOME SQL QUERY`
// Execute the query.
q = `SOME OTHER SQL QUERY`
// Execute the other query.
```

Where I had to switch the first `q =` to `q :=`, which shoots me in the foot when I reorder the queries.
