### ISSUE TITLE
U1000 false positive on nested anonymous structs

### ISSUE THREAD

**Issue by henrahmagix** [dominikh/go-tools#416]
I was playing around with using anonymous nested structs for building up some json data and found a false-positive for U1000, called from `staticcheck` at 466a0476246c45c74e011a03de704d72dc83da2d.

(I admit the resulting experiment is _really_ unreadable and highly unlikely to be actually used anywhere! Go really doesn't want you to nest anonymous structs...)

```
$ staticcheck .
main.go:11:4: field B is unused (U1000)
main.go:18:5: field C is unused (U1000)
```
```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	data := struct {
		A struct {
			B struct { // field `B` is unused (U1000)
				C string
			}
		}
	}{
		A: struct {
			B struct {
				C string // field `C` is unused (U1000)
			}
		}{
			B: struct {
				C string
			}{
				C: "foo",
			},
		},
	}

	result, err := json.Marshal(data)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(result))
}
```

Result from run:
```
$ go run .
{"A":{"B":{"C":"foo"}}}
```

**Comment by dmitshur** [comment]
Related issues: #262, #203.

**Comment by dominikh** [comment]
This is fixed in master.
