### ISSUE TITLE
Flag exported functions like New() or Make() if their return type isn't "correct"

### ISSUE THREAD

**Issue by abenz1267** [dominikh/go-tools#420]
Hi,

would it be sane to flag functions that either start with 'New' or 'Make' if their according return type is/isn't a pointer? So New...() *MyStruct = good. New...() MyStruct = bad, should be Make...() and vice-versa.

Regards

**Comment by ainar-g** [comment]
Why is a pointer the only correct type to return from `New` and when did this distinction start? Did I miss the memo? Neither [Effective Go](https://golang.org/doc/effective_go.html#composite_literals), nor [The Style Guide](https://github.com/golang/go/wiki/CodeReviewComments) mention anything like this. And what about returning interfaces?

**Comment by abenz1267** [comment]
It's a common convention throughout the whole Go language and it's libraries, as you can also clearly see in the links you posted. It's not something that's spelled out directly, but the fact is there. Therefore this distinction started with the development of Go. No need to be snarky :).

What about returning interfaces? Interfaces are pointer types. So there's that.

**Comment by ainar-g** [comment]
I overdid the snark, I apologize and hope I didn't hurt any feelings. But still, I don't think I've noticed this pattern before. in the std there are [`reflect.New`](https://golang.org/pkg/reflect/#New) that returns a struct, and then there is [`crc64.MakeTable`](https://tip.golang.org/pkg/hash/crc64/#MakeTable) that returns a pointer.

**Comment by abenz1267** [comment]
Well, the question is how common this is and if it's considered something a linter should make you aware of. A linter complains about stuff that isn't set in stone. Just like this example. So the question stands: if it's a common pattern throughout the std. library (i mean..sure... i haven't done a complete analysis :D ), big libraries and it enforces more consistent naming across libraries, shouldn't a linter make you aware? Maybe the opinions on this simply aren't strong enough or i indeed have a wrong perception.

**Comment by dominikh** [comment]
I do not think that such a check would be based on community consensus. I, for one, do not believe there to be a pointer-based distinction between New and Make. It certainly wouldn't be consistent and up for debate. 

To me, the difference between New and Make is the complexity of the operation; just filling out a structure versus causing computations or side-effects. And even that is probably just my personal take on it (though it is somewhat in line with how the built-ins `new` and `make` behave.)
