### ISSUE TITLE
stylecheck: optional check against package-scoped variables?

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#421]
Dave Cheney [in his article](https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables) argued that it should be completely possible to write in Go without package-scoped (aka “global”) variables. I use this style in my project, but I am wondering, if discouraging package-scoped variables is something that should be added to stylecheck. “No” is a perfectly acceptable answer, and if that is so, I will probably just create a bash script to find those variables and scream at the developer.

**Comment by dominikh** [comment]
Quoting Dave:

> Even though this post was just a thought experiment, it’s clear that forbidding all package scoped variables is too draconian to be workable as a language precept. Addressing the bespoke uses of private var usage may prove impractical from a performance standpoint, would be akin to pinning a “kick me” sign to ones back and inviting all the Go haters to take a free swing.

That, combined with the fact that I like "global" variables, makes this an extremely low priority for me.

That aside, there is the real issue of our users. Yes, we can have opt-in checks, and yes, our configuration system has the notion of "all default checks", but it also has the notion of "all checks", and users are prone to accidentally using "all", turning on all of the optional checks unwittingly. I'd hate to recommend removing all globals to someone who accidentally enabled the check – they might actually listen to the tool!

**Comment by ainar-g** [comment]
Now that I think about it, this is indeed too much of a personal preference. Thanks for responding. Closing the issue for now.
