### ISSUE TITLE
stylecheck: consider marking uses of invisible symbols, such as zero-width space

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#423]
(This is probably more of an ST check, although I do think that it _could_ be an SA check, since it can introduce bugs.)

```go
a, b := "a", "​a"
fmt.Println(a == b)
```

This will print `false`, because `b` contains a zero-width space in it. Could be a very tricky thing to debug. If someone really needs a zero-width space in a string, they may as well spell it as `"\u200ba"` and save people debugging time.

**Comment by dominikh** [comment]
We'll make it an ST check.

**Comment by dominikh** [comment]
@ainar-g Here's a trophy for you: https://github.com/minio/minio/pull/7378
