### ISSUE TITLE
Tweak GOGC

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#425]
Go is a garbage collected language, its memory usage will be higher than actual memory usage. By default up to a factor of 2x. This can lead to out of memory situations even though we would technically be fine. Transient spikes and GC running at unfortunate times can lead to too high memory targets. If we used 3 GB of memory on the last GC, the next GC will run once we hit 6 GB. This is problematic if the system only has 5 GB and we create a lot of short-lived garbage.

We can trade some CPU time for lower memory usage by setting GOGC to a lower value, forcing more frequent garbage collection.

See https://github.com/dominikh/go-tools/issues/394#issuecomment-454604993 for graphs and https://fosdem.org/2019/schedule/event/gogc/ for a talk on the topic.

We will set GOGC in cmd/staticcheck. Tools like golangci-lint may want to do the same, but we obviously won't do it for them.

**Comment by jirfag** [comment]
thank you for the idea! It may be interesting for you: golangci-lint `GOGC` tweaking trade-off is [here](https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint)
