### ISSUE TITLE
Add flag to output absolute path

### ISSUE THREAD

**Issue by stamm** [dominikh/go-tools#43]
I'm wondering if is it possible to add flags to output absolute path instead of relative.
I use vim with plugin called Neomake. It can execute linters like yours. But it expect absolute path

**Comment by stamm** [comment]
I added pull request about it. Please, take a look: https://github.com/dominikh/go-tools/pull/44

**Comment by bradleyfalzon** [comment]
Note, neomake shouldn't require absolute paths, as I have it working with gometalinter in github.com/neomake/neomake/pull/795 and gometalinter works with relative paths. Specifically I think it's this line that adds base path to make relative path absolute https://github.com/neomake/neomake/pull/795/files#diff-8d275594f8173d629ed92ab8d0d43eafR61

**Comment by dominikh** [comment]
How does neomake deal with other tools, such as `go build`, that use relative paths and do not provide such a flag?

Tools like neomake should really be able to understand relative paths, considering they are relative to the current working directory and thus very easy to deal with.

**Comment by stamm** [comment]
Ou, thanks, @bradleyfalzon!
Code from pull request is works for me
Just need to add to all makers
```
'cwd': '%:h',
'mapexpr': 'neomake_bufdir . "/" . v:val',
```
@dominikh Yeap, you're right. BTW, thanks for great tooling!
