### ISSUE TITLE
staticcheck: cgo: SA4000 false positive on generated `0 == 0`

### ISSUE THREAD

**Issue by sergefdrv** [dominikh/go-tools#430]
This code

```go
package pkg

// void foo(void **p) {}
import "C"
import "unsafe"

func Foo() {
	var p unsafe.Pointer

	C.foo(&p)
}
```

gives a false positive error `identical expressions on the left and right side of the '==' operator (SA4000)` pointing beyond the end of the line `C.foo(&p)`.

The reason is that `cgo` generates the following Go code

```go
// Code generated by cmd/cgo; DO NOT EDIT.

//line test.go:1:1
package pkg

// void foo(void **p) {}
import _ "unsafe"
import "unsafe"

func Foo() {
	var p unsafe.Pointer

	func() { _cgoBase0 := /*line :10:8*/&p; _cgo0 := _cgoBase0; _cgoCheckPointer(_cgoBase0, 0 == 0); _Cfunc_foo(_cgo0); }()
}
```

So `staticcheck` actually complains on `0 == 0` expression generated by `cgo`.

**Comment by sergefdrv** [comment]
I was thinking for a moment that this can be a fault of `cgo` generating the offending code. But it might actually be a [bit more complicated](https://github.com/golang/go/commit/1d18f66dc82088a3a3d39410866157e3e1e44554#diff-8fb23a4fb8ff2ead87879c34ff012343R1039).

**Comment by ainar-g** [comment]
When will the evils of shadowing end?

**Comment by dominikh** [comment]
> When will the evils of shadowing end?

Part of me wishes for a way to refer to outer scopes, and the universe scope, explicitly. But I worry that would only make things worse :-)

**Comment by ainar-g** [comment]
@dominikh You can kind–of–sort–of do that. See [my comment on the Go issue tracker](https://github.com/golang/go/issues/31109#issuecomment-477608851). Stinky, but works.

**Comment by sergefdrv** [comment]
@dominikh Thanks!
