### ISSUE TITLE
unsupported version of go: exit status 2: flag provided but not defined: -compiled

### ISSUE THREAD

**Issue by letronje** [dominikh/go-tools#432]
Tried it with go 1.10.8 , gave this error

**Comment by ainar-g** [comment]
Go 1.10 is unsupported. The Go Project supports only two latest releases, IIRC.

**Comment by dominikh** [comment]
More specifically, `golang.org/x/tools/go/packages` recently removed support for Go 1.10 – the last commit in `golang.org/x/tools` that supports 1.10 is `c5e06eb4cd0c26e155eece9f6ad4abbb0acb3318^` (which is `36c10c0a621fb2fede4686e8ae7bb1d900735d53`)
