### ISSUE TITLE
stylecheck: suggest replacing time.(*Time).Add(24*time.Hour) with time.(*Time).AddDate(0, 0, 1)

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#433]
Arguably, `t.AddDate(0, 0, 2)` looks and reads better than `t.Add(2*24*time.Hour)`.

**Comment by dominikh** [comment]
Add and AddDate are not interchangeable: https://play.golang.org/p/HbmmMDmfV4-

**Comment by ainar-g** [comment]
The evils of DST shall never end. Closing.
