### ISSUE TITLE
Add flag for explaining checks

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#436]
The staticcheck command should have a flag that explains checks so that users don't have to use the website. Example:

```
$ staticcheck -explain SA1006
Printf with dynamic first argument and no further arguments

Using fmt.Printf with a dynamic first argument can lead to
unexpected output. The first argument is a format string, where
certain character combinations have special meaning. If, for
example, a user were to enter a string such as "Interest rate: 5%"
and you printed it with fmt.Printf(s), it would lead to the
following output: "Interest rate: 5%!(NOVERB)".

Similarly, forming the first parameter via string concatenation
with user input should be avoided for the same reason. When
printing user input, either use a variant of fmt.Print, or use
the %s Printf verb and pass the string as an argument.

Available since
    2017.1 
```

What should the flag be? `-explain` is self-explanatory, but rather long. `-e` is short, but harder to discover. As far as I know we can't overload `-h` to accept both `-h` (display help) and `-h SA1006` (explain check).

**Comment by ainar-g** [comment]
Not only is `--explain` self-explanatory (heh), but it also matches the behaviour of rustc, the Rust compiler. Although I myself am a fan of subcommands, but we don't have a «staticcheck check» (which also stutters), so I don't think we should have a «staticcheck explain».

If you're going through with this, don't forget to put a note about it into the human-readable output. Something like

    Use "staticcheck --explain <error code>" to learn more.

**Comment by dominikh** [comment]
Yeah, subcommands aren't an option. I don't want to go down that road.

> don't forget to put a note about it into the human-readable output

Good point.
