### ISSUE TITLE
Not Compatible with Go 1.10

### ISSUE THREAD

**Issue by tlainevool** [dominikh/go-tools#440]
The latest unused.go uses the Var.Embedded() from Go's types package (https://github.com/dominikh/go-tools/blob/master/unused/unused.go#L1281)

This method is not in Go 1.10, so the build fails.

**Comment by dominikh** [comment]
We, like official Go tools, support the last two versions of Go. Currently that is Go 1.11 and Go 1.12. In fact, one of our crucial dependencies, go/packages, has already dropped support for Go 1.10, so even if we didn't use Embedded, we'd still not be compatible with Go 1.10.
