### ISSUE TITLE
Latest changes to "unused" is incorrectly identifying things as unused.

### ISSUE THREAD

**Issue by jhump** [dominikh/go-tools#441]
I use `staticcheck` in my CI checks for numerous Go projects. Last night, it began emitting errors in one project that are not real.

Since it's a bug in staticcheck, not a real issue, I'm hesitant to add comments to ignore the issues into my code as a work-around. And I'm also hesitant to just skip the staticcheck invocation in CI as a work-around because of the great value I get from the static analysis (though it seems I may have to do one or the other, at least temporarily). Maybe this is something that could be fixed with a quick turn around?

Anyhow, here's the failing build:
https://travis-ci.org/jhump/protoreflect/jobs/518638145

It's pointing to [here](https://github.com/jhump/protoreflect/blob/master/desc/descriptor_unsafe.go#L12) and [here](https://github.com/jhump/protoreflect/blob/master/dynamic/message_factory.go#L100) as declarations that are unused. However they are definitely used ([here](https://github.com/jhump/protoreflect/blob/master/desc/descriptor.go#L522) and [here](https://github.com/jhump/protoreflect/blob/master/dynamic/message_factory.go#L104), respectively).

**Comment by dominikh** [comment]
> Since it's a bug in staticcheck, not a real issue, I'm hesitant to add comments to ignore the issues into my code as a work-around

Definitely don't do that. Bugs like that should be fixed.

10572299276af2ea5e9f80acabf6ec99ca6d3b98 and 9cba8c652c11ec88e3462ae55e33a201a56b4679 fix the two issues reported by you. Let me know if you run into any more issues.

**Comment by jhump** [comment]
@dominikh, thanks tremendously for the super-fast turn-around!
