### ISSUE TITLE
staticcheck: SA4006 not working?

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#453]
```sh
$ cat foo.go
package main

import "fmt"

func main() {
        var a int
        a = 1
        a = 2
        fmt.Println(a)
}
$ staticcheck -checks "*" foo.go
$
```

I think I distinctly remember that such code used to trigger [SA4006](http://staticcheck.io/docs/checks#SA4006). Am I misremembering something?

**Comment by dominikh** [comment]
At the moment, SA4006 only recognizes function calls not constants, as it operates on SSA form and we apply constant propagation when building SSA form. That is, it will detect an unread `a = fn()` but not an unread `a = 1`. That is currently the major difference between SA4006 and the ineffassign tool.

This is https://github.com/dominikh/go-tools/issues/191
