### ISSUE TITLE
gosimple: suggest simplification of foo, _ := someMap[key]

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#46]
The existance of the `_` doesn't change anything, `foo` will still be set to the zero value if they key doesn't exist. It can always be simplified to `foo := someMap[key]`.

**Comment by mvdan** [comment]
Now that I think about it, this is a plain AST rule so would probably qualify for `gofmt -r`. Still valuable to `gosimple` though, I would assume.

**Comment by dominikh** [comment]
Yes, gosimple includes simplifications that are purely AST based.
