### ISSUE TITLE
staticcheck: check for int(rand.Float64())

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#462]
math/rand.Float64 returns a value in [0, 1) meaning converting it to int will always result in 0. The same extends to all float and integer type combinations.

First check whether this bug actually occurs in the real world; this idea was inspired by seeing https://errorprone.info/bugpattern/RandomCast

**Comment by dominikh** [comment]
Related: math/rand.Intn(1)

**Comment by mostynb** [comment]
> Related: math/rand.Intn(1)

Which seems like a degenerate base case- the whole point of generating a random value is for it to be non-deterministic (unless using a deterministic seed).  The question is if this appears in error and/or appears intentionally in real-world code.

**Comment by dominikh** [comment]
>  The question is if this appears in error and/or appears intentionally in real-world code.

I cannot imagine this would ever occur intentionally _with a literal 1_. It may happen with constants due to build constraints.
