### ISSUE TITLE
staticcheck: how to make 'go list' use '-mod=vendor' flag?

### ISSUE THREAD

**Issue by tormoder** [dominikh/go-tools#463]
I'm using the `-mod=vendor` flag for all `go` commands inside a Docker container.
The main reason is to currently avoid authentication against private repositories.

When running staticcheck inside the container it shells out to `go list` (via `go/packages`?) to determine packages/files. But this results in `go: error loading module requirements` since it can't access the private repositories.

Is there any way to make `go list` use the `-mod=vendor` flag for this case?

**Comment by dominikh** [comment]
Setting the environment variable GOFLAGS (`export GOFLAGS="-mod=vendor"`) should solve the issue for you. Note that GOFLAGS is handled by the `go` command itself, not us or go/packages. You may choose to only export that variable for invocations of staticcheck, or to set it generally and forego having to specify `-mod=vendor` in all your normal `go` invocations.

**Comment by tormoder** [comment]
Thank you!
