### ISSUE TITLE
staticcheck: flag duplicate imports

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#467]

**Comment by markusthoemmes** [comment]
@dominikh need a helping hand here? I argued that `golint` [should do that already](https://github.com/golang/go/issues/29289), but no movement there.

**Comment by dominikh** [comment]
@markusthoemmes if you're itching to write a check, feel free to! But as far as "a helping hand" is concerned, reviewing a PR is at least as much work as writing the check myself.

FWIW, if nobody else does, I'll likely write the check soon (in 0-∞ days)

**Comment by dominikh** [comment]
Closed by #537.
