### ISSUE TITLE
U1000 is not reported when identifier is used only by its own test

### ISSUE THREAD

**Issue by dmitshur** [dominikh/go-tools#475]
Consider a package with a single .go file:

```Go
package p

func Foo() error {
	return nil
}

func bar() error {
	return nil
}
```

`staticcheck` correctly reports that `bar` is unused:

```
$ staticcheck 
p.go:7:6: func bar is unused (U1000)
```

Now consider if both `Foo` and `bar` have tests:

```Go
package p

import "testing"

func TestFoo(t *testing.T) {
	got := Foo()
	if got != nil {
		t.Error("got a non-nil error:", got)
	}
}

func TestBar(t *testing.T) {
	got := bar()
	if got != nil {
		t.Error("got a non-nil error:", got)
	}
}
```

`staticcheck` no longer reports `bar` as unused:

```
$ staticcheck 
$ echo $?
0
```

That makes it harder to tell that an identifier with test coverage is no longer used. Perhaps it's possible to treat a test named `TestSomething` as not using an identifier or type `something` or `Something` for the purposes of U1000.

**Comment by ainar-g** [comment]
See #289, #304, and #94.

**Comment by dominikh** [comment]
In my experience, tests are rarely named after exact identifiers, especially when they test individual methods. I can only suggest running staticcheck with tests disabled. See also the issues Ainar linked.

**Comment by dmitshur** [comment]
> I can only suggest running staticcheck with tests disabled.

I didn't realize that would help (I thought it would just not report problems in tests). Thanks, that sounds good.
