### ISSUE TITLE
simple: replace WriteString(fmt.Sprint*(...)) with fmt.Fprint*

### ISSUE THREAD

**Issue by buyology** [dominikh/go-tools#477]
In the same vein as `S1028` and related to #143, use of `io.StringWriter` in conjunction with `fmt.Sprint*` can be simplified if swapped out for the corresponding `fmt.Fprint*`

From some real life code just seen:

```go
buf.WriteString(fmt.Sprintf("Filename: `%s`\n", d.Filename))
```

Simpler:

```go
fmt.Fprintf(&buf, "Filename: `%s`\n", d.Filename)
```

**Comment by dominikh** [comment]
One concern with this is consistency. Say someone wrote this:

```
buf.WriteString("static string")
buf.WriteString(fmt.Sprintf(...))
```

should the second call be replaced with an Fprintf? Personally I'd argue that using Fprintf for the second call would be a bad change, breaking consistency of the code.

We could check surrounding code (e.g. the entire function) for `buf.WriteString` calls that do not use Sprintf, and bail from the check. But I am not convinced this will work perfectly.

Maybe this check belongs in the _quickfix_ category, a set of purely optional code changes that is only surfaced in editors (via gopls), and not on the CLI. I will have to think more about this.

**Comment by mvdan** [comment]
I just ran into this too, so it gets my plus one, even if it's just a quickfix suggestion.

**Comment by dominikh** [comment]
Mostly implemented now, but https://github.com/dominikh/go-tools/issues/1097 exists.
