### ISSUE TITLE
unrecognized import path "honnef.co/go/tools"

### ISSUE THREAD

**Issue by sgaurav00719** [dominikh/go-tools#492]
I am getting following error on running `go get` command.

error: 
`go: honnef.co/go/tools@v0.0.0-20190102054323-c2f93a96b099: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: Forbidden)` 

I tried insecure flag too. But it doesn't seem to work.

**Comment by dominikh** [comment]
What's the full output of `curl -v 'https://honnef.co/go/tools?go-get=1'`?

**Comment by sgaurav00719** [comment]
Here is the output of `curl -v 'https://honnef.co/go/tools?go-get=1'` :

`* allocate connect buffer!
* Establish HTTP proxy tunnel to honnef.co:443
> CONNECT honnef.co:443 HTTP/1.1
> Host: honnef.co:443
> User-Agent: curl/7.64.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 403 Forbidden
< Content-Type: text/html
< Server: Zscaler/5.6
< Cache-Control: no-cache
< Content-length: 14342
< 
* Received HTTP code 403 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 403 from proxy after CONNECT`

**Comment by dominikh** [comment]
Your connection is going through some proxy, which is preventing the connection to honnef.co – you'll have to talk to your network admin about that.

**Comment by dominikh** [comment]
Timed out.
