### ISSUE TITLE
Detect misspelling

### ISSUE THREAD

**Issue by yasushi-saito** [dominikh/go-tools#501]
Can we have a check equivalent to

https://github.com/client9/misspell

I find this check quite useful, but the misspell codebase is pretty dated and I'd rather want to use staticcheck as the all-in-one checker.

**Comment by dominikh** [comment]
I don't think that a spell checker is something I want to write or maintain. One of staticcheck's guiding principles is to minimize the number of false positives. And the primary way we do that is by flagging things we know are wrong, not by flagging things we can't prove are right. Spell checking, on the other hand, works the opposite way. Words it can't recognize get flagged, even though they may be valid words. 

The naive approach of spell checking (comparing with a dictionary of words) would have me maintaining and adding to the dictionary constantly. Less naive approaches would require me to implement complex algorithms for understanding grammar. I don't want to do either of those things.
