### ISSUE TITLE
Throw an error if `//lint:ignore U1000` does not have associated comment

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#515]
My first attempt at getting staticcheck to ignore a file I wrote this near the top of the file:

```go
//lint:file-ignore U1000
```

This is ignored by staticcheck because there is no comment associated with the ignore check, so it still errors. That's extremely confusing.

Better would be to throw an error ("invalid ignore directive: must have comment") or permit me to include ignore checks without comments.

**Comment by kevinburke** [comment]
Updates golang/dep#2178

**Comment by dominikh** [comment]
This is a bug, and a regression on the master branch. 2019.1 correctly complained about malformed linter directives:

> ../../../sandbox/foo/foo.go:4:2: malformed linter directive; missing the required reason field?

Will fix.
