### ISSUE TITLE
staticcheck: flag 2^<lit>

### ISSUE THREAD

**Issue by seebs** [dominikh/go-tools#516]
Saw a thing floating around about someone writing `i < (2^32) - 1)` in C, and a bit of poking reveals that it's a fairly common typo in Go. I'm pretty sure that `2^N` will nearly always be an error -- in particular, if I were going to xor something with 2, I'd write `x^2`. (Which might also be a typo, but it seems to be less common in that direction?)

So maybe this should be a check.

**Comment by dominikh** [comment]
Examples from real code, via @dgryski:

```
lastwindow := uint32(2 ^ 32 + 1)
const maxPacketLen = 2 ^ 15
go.googlesource.com/go/test/fixedbugs/issue15175.go:52: return a1 >> (((2 ^ 2) >> (v1 | 2)) + 0)
github.com/vitessio/vitess/go/vt/topo/memorytopo/memorytopo.go:175:        generation: uint64(rand.Int63n(2 ^ 60)),
```

**Comment by dgryski** [comment]
```
k8s.io/heapster/vendor/github.com/prometheus/client_golang/prometheus/go_collector.go:214:				eval:    func(ms *runtime.MemStats) float64 { return float64(ms.LastGC*10 ^ 9) },
```

**Comment by dominikh** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90885

**Comment by ainar-g** [comment]
<p>If&#xA0;this check is implemented, please also&#xA0;flag <code>10
^ N</code>.&#x2003;I&#xA0;may or&#xA0;may not&#xA0;have seen such
code&#xA0;recently.</p>

**Comment by dgryski** [comment]
@ainar-g My semgrep repo has semgrep and ruleguard checks for this. :)

**Comment by dominikh** [comment]
I'm merging this issue into #326
