### ISSUE TITLE
quickfix: unnecessary use of anonymous fields in selectors

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#52]
```
type AnonType struct {
    Message string
}

type TopType struct {
    AnonType
}

func foo(t TopType) {
    _ = t.AnonType.Message
}
```

`t.AnonType.Message` can be `t.Message`. I see no reason why the former would be desirable.

**Comment by shurcooL** [comment]
> `t.AnonType.Message` can be `t.Message`. I see no reason why the former would be desirable.

Are you saying that should apply in the general case, or only when `TopType` is a struct that contains only one field, and that field is an embedded struct?

**Comment by mvdan** [comment]
I mean in general, as long as the behaviour is the same. Do you mean to imply that it wouldn't be the case if it was helpful to be specific, e.g. when field names are very similar?

**Comment by shurcooL** [comment]
I _suspect_ that there will be false positive suggestions that users will not want to apply.

I don't have any counter-examples off the top of my head. But I haven't tried to search for them.

**Comment by mvdan** [comment]
I agree that this could have false positives. For example, if a struct has `t.foo` and `t.AnonType.Foo`, you probably don't want to use `t.Foo` and cause confusion.

**Comment by dominikh** [comment]
Reopening under the quickfix label.
