### ISSUE TITLE
simple: flag the use of net/http.CanonicalHeaderKey when using net/http.Headers methods

### ISSUE THREAD

**Issue by markusthoemmes** [dominikh/go-tools#520]
When using `Header.Get` or `Header.Set` the keys will be canonicalized automatically. We could flag

```golang
req.Header.Set(http.CanonicalHeaderKey(headerName), headerValue)
req.Header.Get(http.CanonicalHeaderKey(headerName), headerValue)
```

**Comment by dominikh** [comment]
Sounds good. Same goes for the Del method.

**Comment by dominikh** [comment]
@markusthoemmes out of curiosity, did you encounter this pattern in the wild?

**Comment by markusthoemmes** [comment]
@dominikh Yes I did, fixed a bunch of those over at knative/serving the other day and thought this would be neat to be enforced by a linter.
