### ISSUE TITLE
quickfix: suggest to replace strings.Index("x") by strings.IndexByte('x') where x is ASCII

### ISSUE THREAD

**Issue by martisch** [dominikh/go-tools#525]

**Comment by ainar-g** [comment]
It seems like `strings.Index` [already defers](https://github.com/golang/go/blob/3259bc441957bf74f069cf7df961367a3472afb2/src/strings/strings.go#L1032) to `strings.IndexByte` in case the string has a length of one. I can see such rule firing in a code like this:

```
var (
	x = strings.Index(foo, "xxx")
	y = strings.Index(foo, "yy")
	z = strings.Index(foo, "z")
)
```

Which would be worse off (to me personally) with `Index` replaced by `IndexByte`.

**Comment by martisch** [comment]
`strings.Index(foo,` "xxx")` does not fit since "xxx" is not a single ASCII rune/byte

The overhead of Index vs IndexByte is considerable in loops.

**Comment by ainar-g** [comment]
I see, thanks. If the performance difference is noticeable, then I guess it may be worth it.

**Comment by dominikh** [comment]
Code consistency (the argument made by Ainar) is definitely the major hurdle to adding this check. In cases like these, it is very difficult to get the right balance between helpful suggestions and making code less readable. And it's difficult to guess the right context for consistency. Is it okay to mix Index and IndexByte in the same block? in the same parent block? in the same function? the same file? Users have different opinions on that.

**Comment by martisch** [comment]
I am closing the issue In the context of the decision to apply or not apply to not hurt readability being to complex to being offset by the gains.

**Comment by dominikh** [comment]
Reopening, flagging as a check we can add as part of the quickfix category, for when staticcheck runs inside gopls and can display code suggestions.
