### ISSUE TITLE
go get @2019.2 fails because of gax-go

### ISSUE THREAD

**Issue by agalal** [dominikh/go-tools#528]
Building `staticcheck` using version 2019.2 or later fails due to a problem in `github.com/googleapis/gax-go/`. This problem is mentioned earlier in an [issue][1] on the `googleapis` repo.

```bash
$ go version
go version go1.12 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/<user>/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/<user>/go"
GOPROXY=""
GORACE=""
GOROOT="/home/<user>/go1.12"
GOTMPDIR=""
GOTOOLDIR="/home/<user>/go1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/<user>/.../go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build015411844=/tmp/go-build -gno-record-gcc-switches"
```
Output of `go get` on version `2019.1.1`:
```
$ go get honnef.co/go/tools/cmd/staticcheck@2019.1.1
go: finding honnef.co/go/tools/cmd/staticcheck 2019.1.1
go: finding honnef.co/go/tools/cmd 2019.1.1
go: finding honnef.co/go/tools 2019.1.1
```
Output of `go get` on version `2019.2`:
```
$ go get honnef.co/go/tools/cmd/staticcheck@2019.2
go: finding honnef.co/go/tools/cmd/staticcheck 2019.2
go: finding honnef.co/go/tools/cmd 2019.2
go: finding honnef.co/go/tools 2019.2
go: github.com/googleapis/gax-go/v2@v2.0.0: missing github.com/googleapis/gax-go/go.mod and .../v2/go.mod at revision v2.0.0
panic: error loading module requirements

goroutine 1 [running]:
cmd/go/internal/mvs.Downgrade.func2(0xc00002c720, 0x1f, 0xc00012c754, 0x6)
	/usr/local/go/src/cmd/go/internal/mvs/mvs.go:317 +0x659
cmd/go/internal/mvs.Downgrade(0xc000268af8, 0x4, 0x0, 0x0, 0xac32e0, 0xc0001a0070, 0xc000673240, 0x1, 0x1, 0x415acf, ...)
	/usr/local/go/src/cmd/go/internal/mvs/mvs.go:349 +0x617
cmd/go/internal/modget.runGet(0xe3ab00, 0xc000096170, 0x1, 0x1)
	/usr/local/go/src/cmd/go/internal/modget/get.go:446 +0x1ed6
main.main()
	/usr/local/go/src/cmd/go/main.go:219 +0x837
```
[1]: https://github.com/googleapis/gax-go/issues/83

**Comment by dominikh** [comment]
I'm not sure what to do here. Staticcheck doesn't depend on gax-go or anything that transitively depends on gax-go (I hope.) This seems to be squarely an issue in either Go or gax-go for projects that use gax-go themselves?

**Comment by ainar-g** [comment]
I don't have this issue in an empty module:

<details>
<summary>Click to view logs</summary>
<pre>
/tmp/src/foo $ go mod init foo
go: creating new go.mod: module foo
/tmp/src/foo $ GO111MODULE=on GOPATH="/tmp" go get honnef.co/go/tools/cmd/staticcheck@2019.2
go: finding honnef.co/go/tools/cmd/staticcheck 2019.2
go: finding honnef.co/go/tools/cmd 2019.2
go: finding honnef.co/go/tools 2019.2
go: downloading honnef.co/go/tools v0.0.0-2019.2
go: finding github.com/kisielk/gotool v1.0.0
go: finding github.com/google/renameio v0.1.0
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/rogpeppe/go-internal v1.3.0
go: finding golang.org/x/tools v0.0.0-20190621195816-6e04913cbbac
go: finding golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e
go: finding golang.org/x/crypto v0.0.0-20190510104115-cbcb75029529
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding gopkg.in/errgo.v2 v2.1.0
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/kr/pretty v0.1.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding golang.org/x/text v0.3.0
go: finding github.com/kr/text v0.1.0
go: finding github.com/kr/pty v1.1.1
go: downloading golang.org/x/tools v0.0.0-20190621195816-6e04913cbbac
go: downloading github.com/BurntSushi/toml v0.3.1
</pre>
</details>

OP probably has a dependency somewhere it their module that is triggered by `go get` for some reason.

**Comment by agalal** [comment]
> I don't have this issue in an empty module:

Correct, I tried with an empty module and I confirm the issue is not there. Hence, I am closing this issue.
