### ISSUE TITLE
staticcheck: consider removing CheckIneffectiveAppend

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#53]
CheckIneffectiveAppend (SA4010) doesn't seem all that useful when we also have CheckUnreadVariableValues (SA4006). The latter doesn't report results of append that are used in other appends only, but that doesn't seem that useful to begin with.

All actually unused results of append are already reported by SA4006, and if the user fixed those instances, a repeated run would also catch the ones that were missed before.

**Comment by mvdan** [comment]
This sounds like a good idea.

> The latter doesn't report results of append that are used in other appends only, but that doesn't seem that useful to begin with.

Wouldn't that be a false positive?

**Comment by dominikh** [comment]
> Wouldn't that be a false positive?

Not quite. Think of it as a iterative application of the check.

If you had this code:

```
func fn() {
  var x []int
  x = append(x, 1)
  x = append(x, 2)
}
```

then SA4010 would flag both appends, because the second append is pointless, and consequently the first append is pointless, too, because its only use was in the second append.

SA4006 doesn't do this, it just flags the result of the second append, because it isn't used anywhere.

While there is *some* value to doing it, not doing it would effectively point out the same amount of issues in code.
