### ISSUE TITLE
staticcheck: go-flags uses custom struct tag parsing, uses duplicate tags

### ISSUE THREAD

**Issue by yann-soubeyrand** [dominikh/go-tools#540]
Hi,

staticcheck reports a false positive for the rule SA5008 when using go-flags (https://godoc.org/github.com/jessevdk/go-flags). go-flags allows you to specify the available choices for a CLI parameter. To do this, you have to add a choice tag for each available choice. This leads staticheck to complain:
```
duplicate struct tag "choice" (SA5008)
```

- The output of 'staticcheck -version'
```
staticcheck (no version)
```

- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck (no version)

Compiled with Go version: go1.12.5
Built without Go modules
```

- The output of 'go version'
```
go version go1.12.6 linux/amd64
```

- The output of 'go env'
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/yann/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yann/Projets/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build200640234=/tmp/go-build -gno-record-gcc-switches"
```

- Exactly which command you ran
Inside a Makefile:
```
@GO111MODULE=off go get -u honnef.co/go/tools/cmd/staticcheck
staticcheck -tests ./...
```

- Output of the command and what's wrong with the output
```
staticcheck -tests ./...
internal/config/config.go:45:58: duplicate struct tag "choice" (SA5008)
internal/config/config.go:46:58: duplicate struct tag "choice" (SA5008)
```

The duplicate tag is intended (this is how go-flags works).

- Where we can read the code you're running staticcheck on
  (GitHub repo, link to playground, code embedded in the issue, ...)

For the moment, nowhere (it will be available soon).

Regards

**Comment by ainar-g** [comment]
This looks like a bad library design. In fact,[ it isn't even compatible](https://play.golang.org/p/b19fjNFQ69S) with `reflect.StructTag.Get`. Which leads me to believe they implemented their own custom struct tag parsing code. And at this point, you might as well do silly things like:

```go
type T struct {
	F int `The FitnessGram Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues.`
}
```

**Comment by dominikh** [comment]
The library does indeed implement its own parsing of struct tags (https://github.com/jessevdk/go-flags/blob/master/multitag.go). 

I don't consider this a false positive – libraries really should stick to the official reflect.StructTag semantics – but I am not opposed to adding an exception for this library. We can detect structs that are being passed to functions in the go-flags package. This will not catch cases where the type is defined in one package and the use of it is in another package, but I hope that's not a common pattern with this library. I'd rather not allow duplicate tags solely based on the tag's name.

**Comment by yann-soubeyrand** [comment]
I agree with you, it would be better if go-flags didn't do this.

For the technical solution to add an exception, I let you choose which is the better as I'm not familiar with the code of staticcheck and I therefore cannot have an informed opinion.

**Comment by dominikh** [comment]
Fixed in a446d37

**Comment by yann-soubeyrand** [comment]
Thanks for the reactivity!

The fix doesn't work in case of vendoring though ;-)

**Comment by dominikh** [comment]
@yann-soubeyrand fixed that also.

**Comment by yann-soubeyrand** [comment]
Thanks @dominikh!
