### ISSUE TITLE
staticcheck: SA4010: this result of append is never used, except maybe in other appends  (False positive)

### ISSUE THREAD

**Issue by WtfJoke** [dominikh/go-tools#544]
Hi there,

Im quite new to golang, but I think I found a false positive in my case:

```go
package main

func something() {
	var translations = map[string]string{
		"a": "translation",
		"b": "other"}
	names := make([]string, 0, len(translations))
	for _, v := range translations {
		names = append(names, v)
	}
}
```

- The output of 'staticcheck -version'
staticcheck_linux_amd64 2019.2.1
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck_linux_amd64 2019.2.1

Compiled with Go version: go1.12.5
Main module:
        honnef.co/go/tools@v0.0.0-2019.2.1 (sum: h1:fW1wbZIKRbRK56ETe5SYloH5SdLzhXOFet2KlpRKDqg=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
```
- The output of 'go version'
go version go1.12.7 linux/amd64
- The output of 'go env'
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/developer/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/developer/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build796517251=/tmp/go-build -gno-record-gcc-switches"
```

- Exactly which command you ran
staticcheck
- Output of the command and what's wrong with the output
`test.go:9:17: this result of append is never used, except maybe in other appends (SA4010)`
I think there shouldnt be an issue with this append.
- Where we can read the code you're running staticcheck on
At the beginning of this issue description

**Comment by dominikh** [comment]
This is not a false positive for the code that you presented. The values appended to `names` are never read. You don't read `names`, you don't return it, you don't pass it to another function. Your code has the same observable behavior as this code: `func something() {}`.

**Comment by WtfJoke** [comment]
Allright I see, when I print names, the check is successful.

Sorry for this and Thanks for clarification @dominikh
