### ISSUE TITLE
SA4010: false positive for slices backed by arrays

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#545]
Input:

```
func fn(x *[5]int) {
	y := x[:0]
	y = append(y, 1)
}
```

Incorrect report:

```
../../../sandbox/bar/bar.go:7:12: this result of append is never used, except maybe in other appends (SA4010)
```

We can special-case slices that are provably backed by arrays, but we will still produce false positives when we don't know the origin of a slice (e.g. if fn's signature was `x []int` instead.). Nobody that we know of has run into that false positive yet, so it's not a big concern. And one may argue that it's inherently bad code to write.

**Comment by fdcds** [comment]
This code is suggested by the Go documentation itself: https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating
