### ISSUE TITLE
staticcheck: flag funcs that return interfaces rather than structs?

### ISSUE THREAD

**Issue by dnwe** [dominikh/go-tools#549]
Could staticcheck do anything to safely flag up funcs (and especially NewXXX "constructors") that return an interface type rather than a concrete struct? It seems to be a commonly held idiom that your Go components should [accept interfaces and return structs](https://blog.chewxy.com/2018/03/18/golang-interfaces/) in the majority of cases, apart from a small number of exceptions (as seen in the std library) such as the net/http funcs that solely exist to return a pre-created [http.Handler](https://golang.org/pkg/net/http/#Handler).

**Comment by dominikh** [comment]
On the scale of "all code written in the world", the "small number of exceptions" would easily make this a check with a lot of false positives. This check would likely incorrectly flag an occurrence in every largish code base.

The standard library alone has 72 constructors (functions whose name begin with `New`) returning 21 different interface types.

Generally speaking, this is not an idiom that can be applied unconditionally. There are entire classes of APIs that only want to implement behavior, not structure, and thus return interfaces. In other words, this is something a human has to decide on a base by base case; a machine would make a poor judge.

<details>
<summary>Output of a prototypical check</summary>
Hits in std:
<pre><code>/usr/lib/go/src/compress/bzip2/bzip2.go:46:1: constructor returning interface (ST9999)
/usr/lib/go/src/compress/flate/inflate.go:796:1: constructor returning interface (ST9999)
/usr/lib/go/src/compress/flate/inflate.go:815:1: constructor returning interface (ST9999)
/usr/lib/go/src/compress/lzw/reader.go:239:1: constructor returning interface (ST9999)
/usr/lib/go/src/compress/lzw/writer.go:241:1: constructor returning interface (ST9999)
/usr/lib/go/src/compress/zlib/reader.go:70:1: constructor returning interface (ST9999)
/usr/lib/go/src/compress/zlib/reader.go:79:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/aes/aes_gcm.go:54:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/aes/cipher.go:32:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/aes/modes_test.go:28:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/aes/modes_test.go:31:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/aes/modes_test.go:34:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/aes/modes_test.go:37:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/cbc.go:45:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/cbc.go:105:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/cfb.go:53:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/cfb.go:60:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/ctr.go:35:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/gcm.go:84:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/gcm.go:94:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/gcm.go:106:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/cipher/ofb.go:21:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/crypto.go:82:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/des/cipher.go:29:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/des/cipher.go:73:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/hmac/hmac.go:70:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/md5/md5.go:113:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha1/sha1.go:120:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha256/sha256.go:180:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha256/sha256.go:187:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha512/sha512.go:224:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha512/sha512.go:231:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha512/sha512.go:238:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/sha512/sha512.go:245:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/tls/common.go:1012:1: constructor returning interface (ST9999)
/usr/lib/go/src/crypto/tls/tls.go:73:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/ascii85/ascii85.go:93:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/ascii85/ascii85.go:246:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/base32/base32.go:259:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/base32/base32.go:530:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/base64/base64.go:250:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/base64/base64.go:601:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/hex/hex.go:145:1: constructor returning interface (ST9999)
/usr/lib/go/src/encoding/hex/hex.go:174:1: constructor returning interface (ST9999)
/usr/lib/go/src/errors/errors.go:9:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/adler32/adler32.go:43:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/crc32/crc32.go:147:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/crc32/crc32.go:159:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/crc64/crc64.go:100:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/fnv/fnv.go:43:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/fnv/fnv.go:50:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/fnv/fnv.go:57:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/fnv/fnv.go:64:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/fnv/fnv.go:71:1: constructor returning interface (ST9999)
/usr/lib/go/src/hash/fnv/fnv.go:80:1: constructor returning interface (ST9999)
/usr/lib/go/src/internal/x/crypto/chacha20poly1305/chacha20poly1305.go:26:1: constructor returning interface (ST9999)
/usr/lib/go/src/internal/x/crypto/hkdf/hkdf.go:90:1: constructor returning interface (ST9999)
/usr/lib/go/src/internal/x/net/internal/nettest/stack.go:90:1: constructor returning interface (ST9999)
/usr/lib/go/src/internal/x/net/internal/nettest/stack.go:118:1: constructor returning interface (ST9999)
/usr/lib/go/src/math/rand/rand.go:44:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/http/export_test.go:85:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/http/filetransport.go:30:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/http/httputil/httputil.go:20:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/http/httputil/httputil.go:35:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/http/internal/chunked.go:29:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/http/internal/chunked.go:183:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/rpc/jsonrpc/client.go:37:1: constructor returning interface (ST9999)
/usr/lib/go/src/net/rpc/jsonrpc/server.go:37:1: constructor returning interface (ST9999)
/usr/lib/go/src/os/error.go:58:1: constructor returning interface (ST9999)
/usr/lib/go/src/runtime/trace/annotation.go:34:1: constructor returning interface (ST9999)
/usr/lib/go/src/testing/iotest/logger.go:30:1: constructor returning interface (ST9999)
/usr/lib/go/src/testing/iotest/logger.go:52:1: constructor returning interface (ST9999)
</code></pre>

Returned types:

<pre><code>context.Context
crypto/cipher.AEAD
crypto/cipher.Block
crypto/cipher.BlockMode
crypto/cipher.Stream
crypto/tls.ClientSessionCache
error
hash.Hash
hash.Hash32
hash.Hash64
io.ReadCloser
io.Reader
io.WriteCloser
io.Writer
math/rand.Source
net.Listener
net.PacketConn
net/http.Handler
net/http.RoundTripper
net/rpc.ClientCodec
net/rpc.ServerCodec
</code></pre>
</details>

**Comment by dnwe** [comment]
@dominikh thanks for spending the time to make a prototype check, that's good analysis thank you 👍
