### ISSUE TITLE
staticcheck: ignore generated code for the new ST102{0,1,2} checks

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#554]
I ran the new ST102{0,1,2} checks (which look for malformed doc comments) over my code.

The only problem I found was that it flagged a bunch of generated code. In this case, it is protobuf code, and the comments come from the proto files, an entirely different language with different conventions.

I think there's little value to checking doc comments in generated code, and we should skip these checks. (Perhaps we should skip all the ST???? checks in generated code?)

**Comment by dominikh** [comment]
> Perhaps we should skip all the ST???? checks in generated code?

We selectively ignore checks in generated code. Out of all the existing ST checks (ignoring ST1020–ST1022), the following checks do **not** ignore generated code: ST1000, ST1005, ST1008, ST1011, ST1012, ST1018. I believe that these checks should continue flagging generated code. Generated code shouldn't be exempt from rules such as not using invisible characters in string literals.

We may decide to also ignore ST1020–ST1022 in generated code. I will have to think about that.
