### ISSUE TITLE
staticcheck: don't flag virtually empty pure functions

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#56]
We shouldn't flag useless calls of pure functions when the function is empty. We should consider code like the following as empty, too:

```
func Relabel(path string, fileLabel string, relabel string) error {
	return nil
}
```

such functions are stubs and most likely only exist because more useful implementations are guarded by build tags.

**Comment by mvdan** [comment]
FYI, I implemented something very, very similar using ssa here: https://github.com/mvdan/unparam/blob/d2adb036915004d06ad1ffc8edbae3d762110cd6/main.go#L190

My implementation is a little more lax to allow for stuff like `log.Print` and `return []string{}`. For the purposes of `unparam`, I'd rather be conservative. You might or might not want that.
