### ISSUE TITLE
Getting an undefined error on go get

### ISSUE THREAD

**Issue by Maneshme** [dominikh/go-tools#561]
I was following the install instructions [here](https://staticcheck.io/docs/) on doing a go get, I'm getting the following errors.

`honnef.co/go/tools/internal/cache
..\internal\cache\default.go:76:15: undefined: os.UserCacheDir
honnef.co/go/tools/config
..\config\config.go:22:17: undefined: os.UserCacheDir
honnef.co/go/tools/ssa
..\ssa\builder.go:61:16: undefined: types.NewInterfaceType`

Can someone help me fix this issue

**Comment by ainar-g** [comment]
`os.UserCacheDir` appeared in Go 1.11. You're probably running an older version.
