### ISSUE TITLE
staticcheck doesn't know about pkg/plugin and/or buildmode=plugin

### ISSUE THREAD

**Issue by seebs** [dominikh/go-tools#576]
staticcheck 2019.2.3

```
staticcheck 2019.2.3

Compiled with Go version: go1.13
Main module:
        honnef.co/go/tools@v0.0.1-2019.2.3 (sum: h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
```

go version go1.13 linux/amd64

(go env long and irrelevant)

Code also mostly irrelevant. Any `package main` that has uncalled exported functions can produce this.

```
package main

func Foo() {
}
```

```
$ staticcheck
foo.go:3:6: func Foo is unused (U1000)
```

Now, why would I think that's an error? Because `pkg/plugin` could exist, and I have a plugin, and because it's a plugin, it has a function, which is looked up by something else, and the actual output is quite a few "is unused" messages, even though in *fact*, they're all used -- when the plugin is loaded by something else.

I have no idea how `staticcheck` could possibly fix this, except by adding `-buildmode` support, I guess?

**Comment by dominikh** [comment]
The only thing we can do here is treating exported functions in package main as used.
