### ISSUE TITLE
staticcheck: cgo and intermittent false reporting

### ISSUE THREAD

**Issue by tendervittles** [dominikh/go-tools#578]
```
$ staticcheck -debug.version
staticcheck 2019.2.2

Compiled with Go version: go1.13
Main module:
	honnef.co/go/tools@v0.0.1-2019.2.2 (sum: h1:TEgegKbBqByGUb1Coo1pc2qIdf2xw6v0mYyLSYtyopE=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
```

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tendervittles/.cache/go-build"
GOENV="/home/tendervittles/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tendervittles/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build018615117=/tmp/go-build -gno-record-gcc-switches"
```

```
$ cat staticcheck.conf
# staticcheck 2019.2.2

checks = ["all",
    "-S1002",  # Omit comparison with boolean constant
    "-ST1000", # Incorrect or missing package comment
    "-ST1003", # Poorly chosen identifier
    "-ST1005", # Incorrectly formatted error string
    "-ST1006", # Poorly chosen receiver name
    "-ST1016", # Use consistent method receiver names
    "-ST1017", # Don't use Yoda conditions
    "-U1000",  # Unused code
]
```

I run `staticcheck ./...` on my repo with the above conf.

After I began building staticcheck 2019.2.2 with go1.13, I started to get an intermittent warning on `ST1005`, which I'm ignoring.

It only happens in one spot, where the preceding and following lines are both cgo statements. I wasn't able to reproducible consistently, but I did intermittently see it on multiple hosts.

I've fixed the error string, but that behavior is strange.

**Comment by dominikh** [comment]
We're probably not finding the configuration file, due to the way cgo works (it acts as a preprocessor, and its output gets put in the build cache.) We have heuristics to handle this, but maybe they're incomplete. The intermittency of the problem may also point towards our own cache. 

Will investigate.

**Comment by dominikh** [comment]
@tendervittles I've so far been unable to reproduce the issue. Can you provide an actual example that triggers the issue? I'd be fine with a complete project + commit, too, in case it's open source.

**Comment by dominikh** [comment]
@tendervittles have you made any progress in constructing a reproducer?

**Comment by tendervittles** [comment]
@dominikh,

Unfortunately, I couldn't find a reproducer.
