### ISSUE TITLE
simple: Repeated parameter types aren't flagged

### ISSUE THREAD

**Issue by variadico** [dominikh/go-tools#586]
```
func foo(a int, b int, c int) {}
```

should simplify to

```
func foo(a, b, c int) {} 
```

**Comment by dominikh** [comment]
Thank you for the suggestion, but that's not a check I am willing to add. It's not a simplification that can be universally applied. There are cases where repeating the type adds more clarity to the function signature. Furthermore, I don't think that it's a simplification that significantly improves readability, which means it would create unwanted churn.
