### ISSUE TITLE
gosimple: incorrectly identifies redundant break statement

### ISSUE THREAD

**Issue by dmac** [dominikh/go-tools#59]
simpletest/simpletest.go:

```go
package main

import "fmt"

func main() {
loop:
	for {
		switch {
		default:
			fmt.Println("foo")
			break loop
		}
	}
}
```

```
$ gosimple ./simpletest
simpletest/simpletest.go:11:4: redundant break statement (S1023)
```

Some interesting points:

- This doesn't repro if the Println is removed.
- This doesn't repro if `for` is used instead of `switch`.

**Comment by shurcooL** [comment]
Related to #35 and f77185857abb073cdac0254ea9e660913e0bd126.
