### ISSUE TITLE
staticcheck: detect ineffective sorts

### ISSUE THREAD

**Issue by kevinburke1** [dominikh/go-tools#592]
I wrote this:

devices = sort.StringSlice(devices)

I assumed StringSlice was a method that sorted the array and returned the sorted array. It's actually a type, so this wasn't actually sorting the array.

It would be neat for staticcheck to detect errors like this! Eg. if you never call `.Sort()` on the return value.

**Comment by dominikh** [comment]
Sounds like a check we should implement.

The nice thing about `devices = sort.StringSlice(devices)` is that this can't possibly become useful later, unless `devices` was already of type sort.StringSlice – the assignment won't change its existing type. That is, this cannot occur:

```
devices = sort.StringSlice(devices)
devices.Sort() // nor sort.Sort(devices)
```

The same can't be said for `:=`, of course, so we'll still want to look at all uses of newly declared values. At the same time, I really hope that nobody writes code like this:

```
devices2 := sort.StringSlice(devices)
sort.Sort(devices2)
```

albeit valid, it's just confusing.
