### ISSUE TITLE
quickfix: suggest a switch instead of chained elifs

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#6]
```
if foo == a {
} else if foo == b || foo == c {
} else {
}
```

should be

```
switch foo {
case a:
case b, c:
default:
}
```

I'd say this should be suggested as soon as `foo ==` appears at least twice.

**Comment by mvdan** [comment]
Thought: this is tricker than it seems because of `break`. The tool can ignore chained elifs if there is a `break` in any of them. The other option is introducing labels, but them the code might get more complex.

**Comment by dominikh** [comment]
An implementation that bails when it sees a `break` should be a good enough start.

What remains to be decided is if this is an uncontroversial suggestion or not.

**Comment by mvdan** [comment]
I'd always prefer the switch version to avoid duplication and simplify adding new cases. The Go std seems to use the same strategy.

If you want to be extra safe, you can always bump the minimum for the check from two `foo ==` occurences to three.

**Comment by dominikh** [comment]
Changing scope to quickfix, in anticipation of in-editor fixes.
