### ISSUE TITLE
staticcheck: SA5000 is not working?

### ISSUE THREAD

**Issue by kmalloc** [dominikh/go-tools#643]
`
➜  ~ cat t3.go
package main

import "fmt"

var mm map[int]int

func main() {
    mm[2]=3
    fmt.Printf("%+v\n", mm)
}

➜  ~ ./staticcheck -checks all ./t3.go
➜  ~ 
➜  ~ ./staticcheck --version
staticcheck 2019.2.3

`

[SA5000](https://staticcheck.io/docs/checks#SA5000) doesn't seem to work. Am I making something wrong?

**Comment by dominikh** [comment]
SA5000 is only concerned with local variables that do not escape. For example:

```
package main

func main() {
	var m map[int]int
	m[2] = 3
}
```

```
$ staticcheck foo.go
foo.go:5:2: assignment to nil map (SA5000)
```

It is not generally decidable for global variables. Any function may affect the value of the global variable, including those in other packages.
