### ISSUE TITLE
funky "argument a is overwritten before first use" message

### ISSUE THREAD

**Issue by kevinburkemeter** [dominikh/go-tools#645]
I'm running staticcheck at f51cd49dbadb98d60043a445a177e72f0cc62e6b. I started writing a function then wanted to make sure it wasn't actually being used so I put a panic at the top. Here's a reduced case:

```go
package main

import "fmt"

func Foo(a, b string) {
	panic("unimplemented")
	if b == "" {
		a = "default value"
	}
	fmt.Println(a, b)
}

var _ = Foo
```

I get the following error message:

```
$ staticcheck ./...
main.go:5:10: argument a is overwritten before first use (SA4009)
	main.go:8:3: assignment to a
```

The message goes away if I remove the panic. I'm confused by this because it's perfectly legitimate to check an input argument for an empty value and then assign it a default. I would expect either no warning or an error message about "unreachable program statements after a panic" or something.

**Comment by dominikh** [comment]
The way `panic` affects this analysis is a bug, and this particular code shouldn't get flagged. Will fix.

Do note, however, that

> it's perfectly legitimate to check an input argument for an empty value and then assign it a default

isn't what your example is doing. It is checking one argument, but it is setting another. Nevertheless, this instance shouldn't get flagged – and doesn't get flagged without the panic – because it is only being set conditionally, in one branch.

**Comment by dominikh** [comment]
Merging into #281

**Comment by rromero96** [comment]
hey i have the same problem in the following code 
 ==============
func (s *service) Store(id int, codigotransaccion string, moneda string, monto float64, emisor string, receptor string, fechacreacion string) (Transaccion, error) {

	if len(transacciones) == 0 {

		id = 1
	} else {
		id = transacciones[len(transacciones)-1].ID + 1
	}
	transaccion, err := s.repository.Store(id, codigotransaccion, moneda, monto, emisor, receptor, fechacreacion)
	if err != nil {
		return Transaccion{}, err
	}
	return transaccion, nil
}
========
but i do not know how to clean this error in the terminal " argument id is overwritten before first use(SA4009)" can you help me please??
