### ISSUE TITLE
simple: suggest merging for with if-break

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#65]
```
for {
        if done() {
                break
        }
        println("bar")
}
```

could be

```
for !done() {
        println("bar")
}
```

This is only as long as an endless for is followed by an if with a simple boolean condition that only does a break. Note the negation of the expression.

Whether or not to do more complex if conditions, like `a || b`, is up to you. Negating those while keeping them simple might be trickier.

**Comment by dominikh** [comment]
After talking to people on Slack, I decided that this check would better fit into the `quickfix` category, as there may be valid reasons for not lifting into the loop condition. For example, if there are multiple paths breaking out of the loop, or if the same applied to surrounding loops.
