### ISSUE TITLE
Wrong certificate on honnef.co

### ISSUE THREAD

**Issue by legosx** [dominikh/go-tools#658]
I have an issue with dependency scanning of my repo which implicitly using your extension. The extension itself is working but scanning doesn't pass:
```
honnef.co/go/tools@v0.0.0-20190102054323-c2f93a96b099: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: x509: certificate is valid for *.netlify.com, netlify.com, not honnef.co)
```

Can it be that something is wrong with certificate of your website?

Thanks for your attention.

**Comment by appelsiini** [comment]
Yes, that does seem to be the case. The certificate's common name doesn't match with the domain name.

<img width="365" alt="Screenshot 2019-11-19 at 16 16 26" src="https://user-images.githubusercontent.com/8483111/69154047-f9a0a780-0ae7-11ea-8cda-929f66a02e28.png">

**Comment by scottgerring** [comment]
This is causing me problems also.

**Comment by MikeSchlosser16** [comment]
Likewise, same issue

**Comment by KarolJaksik** [comment]
I've encountered the same issue

**Comment by turkenh** [comment]
Same for me

**Comment by pulse-line-dev** [comment]
We encountered the same issue

**Comment by alinz** [comment]
My build failed because of this issue

**Comment by jozuenoon** [comment]
```bash
$ curl -vv -XGET -L 'https://honnef.co/go/tools?go-get=1' > /dev/null
Note: Unnecessary use of -X or --request, GET is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 134.209.226.211...
* TCP_NODELAY set
* Connected to honnef.co (134.209.226.211) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Unknown (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2769 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=ca; L=San Francisco; O=Netlify, Inc; CN=*.netlify.com
*  start date: Jul  3 00:00:00 2019 GMT
*  expire date: Jul  7 12:00:00 2020 GMT
*  subjectAltName does not match honnef.co
* SSL: no alternative certificate subject name matches target host name 'honnef.co'
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (21):
} [1 bytes data]
* TLSv1.3 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (51) SSL: no alternative certificate subject name matches target host name 'honnef.co'
```

**Comment by muratsplat** [comment]
Please could you resolve this problem? Our deployment pipelines were stuck by this problem

**Comment by krivyakin** [comment]
Is there any workaround for this problem until they fix it?

**Comment by tsal** [comment]
This is breaking the ability to install a number of packages - a big one being gorm.

**Comment by christian-kreuzberger-dtx** [comment]
Our pipelines are stuck aswell.

I'm not sure why we have this package even...

**Comment by tsal** [comment]
it also appears the /go/tools URI is giving a 404; the only work-around I can find is vendoring this github repo, which I really do not want to commit... can we maybe move the go.mod to point to the github.com path?

**Comment by Krenair** [comment]
Looks like it's now serving the right cert, from LE.

**Comment by alinz** [comment]
Highly recommend using GOPROXY to prevent these type of things to happen. Look into this https://arslan.io/2019/08/02/why-you-should-use-a-go-module-proxy/

I had to use `GOPROXY=https://proxy.golang.org go build ...` to get it to work

**Comment by dominikh** [comment]
This was a temporary mis-configuration of DNS. The fix should be propagating as we speak.

**Comment by skalp** [comment]
I've got this now :
go: honnef.co/go/tools@v0.0.0-20190102054323-c2f93a96b099: unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())

**Comment by phroggyy** [comment]
Working for me on go 1.13 (which runs on the proxy by default)

**Comment by krivyakin** [comment]
works on google cloud 1.11

**Comment by sliskonog** [comment]
I've got this now :
...(parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())

**Comment by teefax** [comment]
Putting `replace honnef.co/go/tools => github.com/dominikh/go-tools v0.0.0-20190102054323-c2f93a96b099` into the `go.mod` file fixed the issue for me

**Comment by tsal** [comment]
Thank you @teefax - this worked

**Comment by alinz** [comment]
@teefax I wouldn't recommend changing the mod file directly, as tidy and verify `go mod` commands might overwrite it. Use GOPROXY instead. GOPROXY is designed to handle this type of situations.

**Comment by sliskonog** [comment]
Thank you @teefax

**Comment by dominikh** [comment]
I'll summarize the situation:

An incorrect change in DNS caused the domain `honnef.co` to point to the wrong server, which wasn't yet fully set up for serving the domain, in particular the `go get` endpoints. For HTTPS, this manifested itself in an invalid TLS certificate. For HTTP, this manifested itself in a 404 error.

Anyone who is using the Go module proxy – which Go 1.13 uses by default – or who got lucky and never had their DNS servers see the incorrect update, will not have encountered this issue.

For anyone else, the issue will fully resolve itself once DNS has propagated the fixed records. If you are using modules, consider using the module proxy – it was in part designed to avoid situations like these. Alternately, you can employ go.mod's `replace` directive as a temporary workaround, to obtain sources directly from GitHub.

**Comment by mmacheerpuppy** [comment]
Also affected by this

**Comment by mmacheerpuppy** [comment]
Also affected by this in a deployment pipeline for a `go 1.12` stack. I am using go modules and govendor.

**Comment by thraaawn** [comment]
Works for us. Thanks for resolving this quickly.

**Comment by dominikh** [comment]
Hopefully it is working for everyone again. I am going to close this issue. Again my apologies for breaking your builds.

**Comment by mmacheerpuppy** [comment]
@dominikh Yep can confirm we're back 😄

**Comment by elyashivlavi** [comment]
Now I still have the same issue...
