### ISSUE TITLE
simple: suggest against "copying" of strings

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#66]
Too often I've seen people doing copies of strings when they never make sense.

Some common examples:

```
string([]byte(s))
fmt.Sprintf("%s", s)
"" + s
```

I'd argue `gosimple` should say that all of those could be just `s`. I can't think of a program that would break because of this.

**Comment by dominikh** [comment]
You must be working with some shockingly bad code/novice Gophers. I've never seen the first or third line of code. We do already catch the Sprintf one, though.

**Comment by mvdan** [comment]
Whoops, didn't know/check that the second was already caught.

I have to admit I haven't seen the third one yet, but it seems easy enough to spot and not too far off the rest. I've seen the first in a bunch of different codebases written by Gophers not familiar with the fact that strings are read-only.

**Comment by shurcooL** [comment]
> We do already catch the Sprintf one, though.

Is there anything that catches `fmt.Sprint(s)` where `s` type is `string`?

**Comment by dominikh** [comment]
@shurcooL I'll add it to the existing Sprint tests…
