### ISSUE TITLE
staticcheck doesn't know about my enumer

### ISSUE THREAD

**Issue by seebs** [dominikh/go-tools#660]
2019.2.3

```
package main

import "fmt"

//go:generate enumer -type=timeQuantum -trimprefix=timeQuantum -text -transform=caps -output enums_timequantum.go

type timeQuantum int

const (
	timeQuantumY timeQuantum = iota
	timeQuantumYM
	timeQuantumYMD
	timeQuantumYMDH
)

func main() {
	var t timeQuantum
	err := t.UnmarshalText([]byte("YMDH"))
	fmt.Printf("t: %d, err %v, %s\n", t, err, t)
}
```

The generated code is pretty straightforward -- it translates "YMDH" to 3.

Note that the sequence `timeQuantumYMDH`, while "unused", is affecting the behavior of the program in the expected manner.

I honestly don't have any clue how this could be reasonably detected and I should probably just use a linter comment but I feel like the stringer-type cases are just common enough to be worth bringing up. (`enumer` is a fork of stringer that, well. Does this.)

**Comment by ainar-g** [comment]
<p>
I think it's an issue with <code>enumer</code>.  Looking at their
<a href="https://github.com/alvaroloes/enumer/blob/455e9a94796c0e108c38e253b67307736fc4b200/golden_test.go">golden tests</a>
it seems that they don't use the actual constants there:
</p>

``` go
var _DayNameToValueMap = map[string]Day{
	_DayName[0:6]:   0,
	_DayName[6:13]:  1,
	_DayName[13:22]: 2,
	_DayName[22:30]: 3,
	_DayName[30:36]: 4,
	_DayName[36:44]: 5,
	_DayName[44:50]: 6,
}
```

<p>
Instead of:
</p>

``` go
var _DayNameToValueMap = map[string]Day{
	_DayName[0:6]:   Monday,
	_DayName[6:13]:  Tuesday,
	_DayName[13:22]: Wednesday,
	_DayName[22:30]: Thursday,
	_DayName[30:36]: Friday,
	_DayName[36:44]: Saturday,
	_DayName[44:50]: Sunday,
}
```

<p>
I don't know why the authors of the tool decided to use raw numbers.
</p>

**Comment by dominikh** [comment]
I'm inclined to agree with Ainar. The original `stringer` doesn't have this issue because it doesn't map from strings to constants. `enumer` does offer this mapping, so it probably should use the constants it maps to.

**Comment by seebs** [comment]
Thinking about it, though, it occurs to me that it's plausible to imagine a use case where it's practical to just omit the constant entirely; for instance, consider

```var DayNameLookup []string {
    _DayName[0:6], _DayName[6:13], ...
}```
where there's nothing to map *to*, we just use the index in the array as the value. Only works with contiguous values starting at zero, but that's super common for enum-like cases.

That said, for this specific one, agreed that enumer could do a better job.

**Comment by dominikh** [comment]
I am going to close this issue as WAI. Note that only one constant from the group of constants needs to be used to mark the entire group as used. If neither you nor the tool uses _any_ of the constants, one must wonder why the constants are being generated at all. In this specific case, it should be on the tool to actually use the constants.
