### ISSUE TITLE
SA1019: flag stuff in our own package

### ISSUE THREAD

**Issue by tharvik** [dominikh/go-tools#666]
Currently, SA1019 doesn't [warn for "Deprecated:" in own package](https://github.com/dominikh/go-tools/blob/32de78dc1c6c931f2bf017870750b0ca80006601/staticcheck/lint.go#L2839). I would argue that it should, at least it should have a flag to turn it on. Usually, when deprecating something, we only want to keep some tests to ensure the stability of the deprecated behavior but without actually using it. WDYT?

---

And now for the filling

- The output of 'staticcheck -version': `staticcheck 2019.2.3`
- The output of 'staticcheck -debug.version'
```
staticcheck 2019.2.3

Compiled with Go version: go1.13.4
Main module:
	honnef.co/go/tools@v0.0.1-2019.2.3 (sum: h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
```
- The output of 'go version': `go version go1.13.4 linux/amd64`
- The output of 'go env'
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tharvik/.cache/go-build"
GOENV="/home/tharvik/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tharvik/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR="/home/tharvik/tmp"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/home/tharvik/tmp/go-build902363245=/tmp/go-build -gno-record-gcc-switches"
```
- Exactly which command you ran: `~/.go/bin/staticcheck -checks SA1019`
- Output of the command and what's wrong with the output
  - Nothing, and that's the issue
- Where we can read the code you're running staticcheck on
  - I'm using it on https://github.com/dedis/onet but that's not really relevant

**Comment by dominikh** [comment]
Please see https://github.com/dominikh/go-tools/issues/508#issuecomment-500682935 for why intra-package use of deprecated APIs is currently permitted, and why we can't change that retroactively. The same argument applies to making it configurable, as such configuration would likely be too coarse (at best it can be local to a subtree of packages, which IMO is too coarse.)

¹: That's because `staticcheck.conf` applies to packages and all sub-packages rooted in the same directory.

**Comment by tharvik** [comment]
I see your point, thanks for the explanation.
