### ISSUE TITLE
Is staticcheck working with Go 1.14 (beta1) ?

### ISSUE THREAD

**Issue by pierrre** [dominikh/go-tools#669]
- The output of 'staticcheck -version'
```
staticcheck 2019.2.3
```

- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck 2019.2.3

Compiled with Go version: go1.14beta1
Main module:
	honnef.co/go/tools@v0.0.1-2019.2.3 (sum: h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
```

- The output of 'go version'
```
go version go1.14beta1 linux/amd64
```

- The output of 'go env'
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierre/.cache/go-build"
GOENV="/home/pierre/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pierre/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/pierre/.gimme/versions/go1.14beta1.src"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/pierre/.gimme/versions/go1.14beta1.src/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pierre/gosrc/github.com/xxx/yyy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build718020238=/tmp/go-build -gno-record-gcc-switches"
```

- Exactly which command you ran

I'm trying to use it with Go 1.14 beta1.
First, I tried with the official binary distribution (same as below), so I decided to compile from source instead.
I used this command: `cd /tmp && GO111MODULE=on GOBIN=/home/pierre/go/pkg/staticcheck/2019.2.3-mod go get -v honnef.co/go/tools/cmd/staticcheck@v0.0.1-2019.2.3`.

- Output of the command and what's wrong with the output
I'm running `/home/pierre/go/pkg/staticcheck/2019.2.3-mod/staticcheck -tests ./...`.
Sorry I can't share the code, because it's a private project, but there is nothing special.
It throws a lot of errors similar to:
```
-: could not analyze dependency bytes of github.com/xxx/yyy/zzz [github.com/xxx/yyy/zzz.test]: 
	could not analyze dependency errors of bytes: 
	could not analyze dependency internal/reflectlite of errors: 
	could not analyze dependency runtime of internal/reflectlite: 
	could not analyze dependency runtime/internal/atomic of runtime: 
	could not load export data: cannot import "runtime/internal/atomic" (unknown iexport format version 1), export data is newer version - update tool (compile)
```

FYI it was working perfectly fine with Go 1.13 and the binary release of staticcheck.

**Comment by dominikh** [comment]
This is fixed in the master branch of staticcheck (as of 7398d928b10cbeeef873ee02a66742af75a1d4e9, which pulls in golang/tools@db0687cefd95dc155728a53f4a5416d1aa1bcf1f)

We'll have to make a new release in time for Go 1.14.
