### ISSUE TITLE
Does this code have any effect?

### ISSUE THREAD

**Issue by jvmatl** [dominikh/go-tools#672]
While looking through stylecheck/lint.go to try to debug a false positive, I came across this: https://github.com/dominikh/go-tools/blob/master/stylecheck/lint.go#L53

As far as I can tell, that line just returns a string with no interesting side effects. So why does it get called outside the if statement?

(in case the line numbers change, I'm looking at this)

```
    if !strings.HasPrefix(strings.TrimSpace(f.Doc.Text()), prefix) {
        report.Report(pass, f.Doc, fmt.Sprintf(`package comment should be of the form "%s..."`, prefix))
    }
    f.Doc.Text()  // <<----- THIS LINE
```

**Comment by dominikh** [comment]
Looks like dead code that can be removed.
