### ISSUE TITLE
staticcheck: flag string(int)

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#682]
<p>
See
<a href="https://blog.golang.org/go1.15-proposals">here</a>
and
<a href="https://github.com/golang/go/issues/4483">here</a>.
<code>go vet</code> is going to get this check, so staticcheck probably
should too.  I tried to find an existing issue about it, but couldn't.
Currently, staticcheck says nothing about this code:
</p>

``` go
var n = 64
fmt.Println(string(n))
```

**Comment by dominikh** [comment]
You meant to link to golang/go#32479, not golang/go#4483.

As for adding this check to staticcheck, I'll wait and see how well its integration with `go vet` will go. There's still the chance that it will flag too much code and that the spec change won't be made, after all. Personally, I am torn on whether `string(int)` is a good idea or not.

**Comment by ainar-g** [comment]
`go vet` now warns against such conversions.  I guess this issue can be closed?

**Comment by dominikh** [comment]
>  I guess this issue can be closed?

Overlap between vet and Staticcheck exists. I will still add the check, assuming I start thinking that the check is a good idea.

**Comment by dominikh** [comment]
To this day I don't agree with the check existing in go vet. I'm going to close this issue.
