### ISSUE TITLE
stylecheck: ignore method receiver name matches from generated files

### ISSUE THREAD

**Issue by zikaeroh** [dominikh/go-tools#683]
Command run: `staticcheck -checks 'all,-ST1000' -unused.whole-program ./...`

Output line in question:

```
internal/bot/access_level.go:39:22: methods on the same type should have the same receiver name (seen 3x "a", 1x "i") (ST1016)
```

Repo is: https://github.com/hortbot/hortbot

This lint message is _technically_ correct, however the receiver name conflict comes from a file generated by `stringer` (which does not allow you to override the receiver name; a separate issue I may file on the Go issue tracker).

I think it's a good idea to throw away names discovered in generated files, as linter errors from generated files in general are thrown away already. The method receiver name check is unique in that a generated file's names can potentially cause a mismatch message in non-generated files.

Version/Go info (though I don't think it's helpful in this case):

```
staticcheck 2019.2.3

Compiled with Go version: go1.13.7
Main module:
	honnef.co/go/tools@v0.0.1-2019.2.3 (sum: h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/tools@v0.0.0-20190621195816-6e04913cbbac (sum: h1:MQEvx39qSf8vyrx3XRaOe+j1UDIzKwkYOVObRgGPVqI=)
go version go1.13.7 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/.cache/go-build"
GOENV="/home/jake/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jake/zikaeroh/hortbot/hortbot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build161958862=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dominikh** [comment]
This was fixed in https://github.com/dominikh/go-tools/commit/27a660a4b58b40c032f1dd332053c0e4c537496c and will be part of the next release of staticcheck.

**Comment by zikaeroh** [comment]
Wonderful, thank you. Clearly my searching skills failed me. :slightly_smiling_face:
