### ISSUE TITLE
gosimple: -apply option

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#7]
I don't know if you've considered this before. This would be insanely useful and probably feasible.

One tool that does this is unconvert:

```
 $ unconvert -h
[...]
  -apply
        apply edits to source files
```

One added difficulty that I can see is that you might be adding/removing lines, and thus might introduce new empty lines. I run into the same here when removing statements: https://github.com/mvdan/goreduce/issues/3

**Comment by mvdan** [comment]
Ah, was searching for the wrong string and missed https://github.com/dominikh/go-simple/issues/17. Feel free to close as dup.

**Comment by dominikh** [comment]
Closing, partly as a dup, but primarily because we're not likely to implement it. Transforming ASTs with go/ast is painful and not worth the effort.
