### ISSUE TITLE
staticcheck: missed SA4011 'Break statement with no effect. Did you mean to break out of an outer loop?!

### ISSUE THREAD

**Issue by cznic** [dominikh/go-tools#70]
`staticcheck` seems to miss the warning in [this code before the patch](https://github.com/cznic/cc/commit/94e51f0d6e7033b23187a7d01bfa6170982efc30).

**Comment by dominikh** [comment]
cases that only consist of a `break` and no other statement are never flagged, because some larger code bases put `break` in empty cases.

We should probably disable that special rule for the default branch in switches (not selects).

**Comment by dominikh** [comment]
Correction: I lied, we do not have such a special rule. We just don't inspect range loops. Will fix.
