### ISSUE TITLE
SA3000: disable check in Go 1.15

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#708]
Beginning with Go 1.15, calling os.Exit in TestMain will be optional. See https://github.com/golang/go/commit/2f54081adfc967836842c96619d241378400ece6

**Comment by josephzidell** [comment]
@dominikh Still getting an `SA3000` in go1.15

```bash
$ go version  
go version go1.15 darwin/amd64
```

**Comment by dominikh** [comment]
@josephzidell The change is only available in master, not the latest release. I've filed #824 and added cutting a new release to my todo list.

**Comment by josephzidell** [comment]
@dominikh Are you able to gain any traction on this?

**Comment by dominikh** [comment]
@josephzidell The 2020.1.6 release, made in October, includes this change.

**Comment by josephzidell** [comment]
@dominikh Unfortunately, this issue is still around with

```shell
➜  code git:(master) ✗ go version
go version go1.15.8 darwin/amd64
```

Here's an example of the error message
```shell
model/model_test.go:18:1: SA3000: TestMain should call os.Exit to set exit code (staticcheck)
func TestMain(m *testing.M) {
^
```

**Comment by dominikh** [comment]
@josephzidell that output does not look like it originates from running the `staticcheck` tool. What tool are you running, and what version of Staticcheck does it bundle?

**Comment by josephzidell** [comment]
@dominikh I'm using [golangci-lint](https://github.com/golangci/golangci-lint) which pulls in [`honnef.co/go/tools v0.0.1-2020.1.6`](https://github.com/golangci/golangci-lint/blob/master/go.mod#L80)

**Comment by dominikh** [comment]
Then this is a golangci-lint issue, which does not reproduce with Staticcheck proper. If I had to guess, I would say that they never initialize the `-go` flag of the analysis, which is used to determine which version of Go is being targeted. The check will flag missing calls to os.Exit when targeting a Go version older than Go 1.15:

```
$ staticcheck -go 1.15 .
$ staticcheck -go 1.14 .
bar_test.go:5:1: TestMain should call os.Exit to set exit code (SA3000)
```

Our own analysis runner initializes this value correctly. golangci-lint will have to, too.
