### ISSUE TITLE
S1007: catch const strings in addition to literals

### ISSUE THREAD

**Issue by andig** [dominikh/go-tools#710]
Afaiks S1007 (and potentially other checks around strings or even other types) only kicks in when the string is supplied in-place instead of passing in a const. It should work on consts, too. Noticed this when one occurance in my codebase was caught and I expected the other to show up, too.

So, not online match:

    regexp.MustCompile("\\d")

but also

    const pattern = "\\d"
    regexp.MustCompile(pattern)

**Comment by dominikh** [comment]
This is a duplicate of #513.
