### ISSUE TITLE
staticcheck: SA5011 believes log.Fatalln returns

### ISSUE THREAD

**Issue by FiloSottile** [dominikh/go-tools#713]
```
	csrPEM, _ := pem.Decode(csrPEMBytes)
	if csrPEM == nil {
		log.Fatalln("ERROR: failed to read the CSR: unexpected content")
	}
	if csrPEM.Type != "CERTIFICATE REQUEST" {
		log.Fatalln("ERROR: failed to read the CSR: expected CERTIFICATE REQUEST, got " + csrPEM.Type)
	}
```

https://github.com/FiloSottile/mkcert/blob/a21de51acfcff0e/cert.go#L207-L213

![image](https://user-images.githubusercontent.com/1225294/77239916-78047780-6bb6-11ea-99c4-a06a9af5173a.png)

```
Build info
----------
golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a h1:hKrQy/q8/Xivoqgw6nGiz1jqpn1WGBLDcWLZwW0983E=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.14 darwin/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/filippo/Library/Caches/go-build"
GOENV="/Users/filippo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/filippo"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/filippo/src/github.com/FiloSottile/mkcert/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cm/zzcl1fjx27sc8sf3s6sd_0vw0000gn/T/go-build700307488=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by dominikh** [comment]
I'm afraid that's a bug in gopls. It doesn't currently run analyzers in the correct way to propagate information like "does not return" to dependent packages. I know that upstream is vaguely aware of the issue, but I don't think it's on their immediate to-do list.

The same bug doesn't occur when you run the `staticcheck` tool manually.

**Comment by dominikh** [comment]
Related thread on Slack: https://gophers.slack.com/archives/C0VPK4Z5E/p1583777010298000

**Comment by FiloSottile** [comment]
Yeah, can confirm. Could you open an issue upstream? I'd do it but I don't think I understand the issue enough to open anything more than a placeholder.

**Comment by dominikh** [comment]
> Could you open an issue upstream?

Sure. Might take a day or two; I'll post a link.

**Comment by dominikh** [comment]
No upstream issue for now, but https://go-review.googlesource.com/c/tools/+/228119 – I believe the underlying issue is on @stamblerre's roadmap. To quote her as to the underlying cause:

> It's basically that we're trying to reduce memory usage so we type-check only the exports for dependencies - meaning we can't really get useful facts from go/analysis for dependencies so we just don't bother. It's unfortunate, but once we get through the current burning issues we'll spend some time handling the memory issues and hten we can figure out how to do analysis properly
