### ISSUE TITLE
staticcheck: promote sync.Pool check from SA9 (dubious) to SA6 (performance)

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#72]

**Comment by shurcooL** [comment]
> No description provided.

Can you provide a rationale for this issue?

**Comment by dominikh** [comment]
Dubious checks look for things that are probably wrong, but get easily "confused" by odd code and produce a higher than average amount of noise. 

A while ago, I've added the "performance" category (SA6xxx). These checks also produce more noise, but do so because they point out performance improvements, which aren't always desired.

The sync.Pool check is strictly about performance, so it would fit into SA6. Reasons against moving the check: People who are currently ignoring SA9000 would have to ignore SA6xxx instead, i.e. update their ignore lists. It is also possible that SA9000 isn't making useful performance advice in general, in which case it shouldn't be promoted to SA6 (yet). 

I copied Bradley because he wrote the check, and Dmitri because he might've had experience with the check.

**Comment by shurcooL** [comment]
Thanks, that helps.

> I copied Bradley because he wrote the check, and Dmitri because he might've had experience with the check.

This is also very useful to know.

I haven't had experience with this check (I haven't run into it).

Based on the rationale you've provided, I would be in favor of moving it, as long as "SA9000 is making useful performance advice in general" is true.

**Comment by bradleyfalzon** [comment]
I have no strong position on this, but only thought was about the performance category in general. Many people would run this tool in CI and would want staticcheck to break a build, the performance category begins to move away from the project's goal:

```
The tool shouldn't report any errors unless there are legitimate bugs - or very dubious constructs - in the code.
```

So, having this check moved to performance would make it simpler for those people to `-ignore *.go:SA6*`. Having said that, can you ignore the entire performance category, not just individual performance checks?

As for people currently ignoring SA9000, could we keep that reserved in some way to maintain that behaviour?

**Comment by dominikh** [comment]
- Yes, you can ignore checks based on globs. `SA6*` would work just fine.
- While we could add extra code to map SA9000 to the new ID, I would rather not do so. It adds more code, more complexity, and raises the question of how long we need to maintain the mapping before it's okay to remove it.

**Comment by dominikh** [comment]
Another data point: a user considered this check a false positive, because while valid results, they were undesired. In their case, storing slices in a pool was still plenty faster than not using a pool at all, and the extra ugliness of storing pointers to slices wasn't worth it.

I'm not sure if that's an argument for or against "promoting" the check, though... I'm leaning towards interpreting it as an argument for moving the check into the performance category – it makes it easier to ignore all performance related advice with a single ignore pattern.
