### ISSUE TITLE
staticcheck: skip some checks in example functions 

### ISSUE THREAD

**Issue by bradleyfalzon** [dominikh/go-tools#73]
Some example functions intentionally have incomplete implementations that can cause staticcheck to report issues.

Such as:

```go
package main

func ExampleTopic_Exists() {
    var m map[int]int
    _, ok := m[1]               // main.go:5:5: this value of ok is never used (SA4006)
    if !ok {                    // main.go:6:2: empty branch (SA9003)
        // TODO
    }
}
```

As mentioned by @dominikh some tests such as SA9003 and possibly SA4006 should ignore example functions.

**Comment by dominikh** [comment]
Done in c5a670c and ce5ccd9.
