### ISSUE TITLE
[SA1019] github.com/golang/protobuf/proto is still used by generated code

### ISSUE THREAD

**Issue by butonic** [dominikh/go-tools#732]
```
# go run honnef.co/go/tools/cmd/staticcheck -version                                   
staticcheck 2020.1.3
# go run honnef.co/go/tools/cmd/staticcheck -debug.version
staticcheck 2020.1.3

Compiled with Go version: go1.14.2
Main module:
        honnef.co/go/tools@v0.0.1-2020.1.3 (sum: h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1
        golang.org/x/tools@v0.0.0-20200130002326-2f3ba24bd6e7 (sum: h1:EBZoQjiKKPaLbPrbpssUfuHtwM6KV/vb4U85g/cigFY=)
# go version
go version go1.14.2 linux/amd64
# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jfd/.cache/go-build"
GOENV="/home/jfd/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jfd/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jfd/Repositories/ocis-hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build254383978=/tmp/go-build -gno-record-gcc-switches"
```
- Exactly which command you ran
```
# go run honnef.co/go/tools/cmd/staticcheck github.com/owncloud/ocis-hello/pkg/proto/v0
pkg/proto/v0/hello.pb.go:10:2: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
pkg/proto/v0/hello.pb.micro.go:8:2: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
pkg/proto/v0/hello.pb.web.go:14:2: package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
exit status 1
```
AFAICT google introduced a new go api for protocol buffers: https://blog.golang.org/protobuf-apiv2 but the generated code still uses `github.com/golang/protobuf/proto` which is correct, because google tried to make a seamless transition: https://github.com/golang/protobuf/issues/1032

In that thread @meling first reported problems with staticcheck: https://github.com/golang/protobuf/issues/1032#issuecomment-586029243

And it seems @GlenDC also ran into this issue and reported it: [Google protobuf package deprecated - protocolbuffers#7383](https://github.com/protocolbuffers/protobuf/issues/7383)

An example PR is https://github.com/owncloud/ocis-hello/pull/61 the branck is located at https://github.com/butonic/ocis-hello/tree/update-deps

Our build pipline is using drone and a failing build is documented at https://cloud.drone.io/owncloud/ocis-hello/186/1/5

I did update the protoc-gen-go to generate new go code: https://github.com/owncloud/ocis-hello/pull/61/files#diff-251ae76cdec9881313b569a5b3191f30R3 but as you can see, it still uses ` github.com/golang/protobuf/proto`

The Makefile contains the exact command to generate the code: https://github.com/butonic/ocis-hello/blob/update-deps/Makefile#L169-L173

I think ... this is a false positive ... but would be happy to be proven wrong.

**Comment by dominikh** [comment]
This was fixed in 7e758a3887f90d0ded5f0446112616758183866b
