### ISSUE TITLE
staticcheck: false positives in SA4006 (possible regression)

### ISSUE THREAD

**Issue by tamird** [dominikh/go-tools#74]
This appeared somewhere in https://github.com/dominikh/go-tools/compare/89a8bf9d...505866b9.

```shell
$ staticcheck github.com/cockroachdb/cockroach/pkg/{kv,sql,storage}
pkg/kv/txn_coord_sender.go:351:5: this value of distinctSpans is never used (SA4006)
pkg/sql/render.go:338:16: this value of hasStar is never used (SA4006)
pkg/sql/render.go:348:17: this value of hasStar is never used (SA4006)
pkg/storage/intent_resolver.go:388:49: argument wait is overwritten before first use (SA4009)
pkg/storage/replica.go:3468:3: this value of isConsistencyRelated is never used (SA4006)
pkg/storage/replica.go:3481:3: this value of isConsistencyRelated is never used (SA4006)
pkg/storage/replica.go:4759:3: this value of leaseOwner is never used (SA4006)
```

**Comment by dominikh** [comment]
Surfacing now because of 505866b99e2d1c2c645c0a103cc7c75417f6708a – we weren't checking anonymous functions in SA4006 before.

The bug itself is probably caused by 65bfbec, investigating further.

**Comment by dominikh** [comment]
Tracking at https://github.com/golang/go/issues/19622.

**Comment by fsouza** [comment]
I'm seeing a false positive with SA4006 here: https://github.com/fsouza/fake-gcs-server/blob/176cada3d21e2e544f94fbfc9a0373a58c29066d/fakestorage/upload.go#L80-L90

This only fails on Go 1.7 and 1.8, it passes on master: https://travis-ci.org/fsouza/fake-gcs-server/builds/240398110

**Comment by dominikh** [comment]
This has been fixed upstream.
