### ISSUE TITLE
staticcheck: check builtin len() < 0 conditionals

### ISSUE THREAD

**Issue by tendervittles** [dominikh/go-tools#750]
This is similar to [a previous request](https://github.com/dominikh/go-tools/issues/609).

For the builtin `len()` this could fail:

`if len(foo) < 0 { // Block will never run }`

**Comment by mwat56** [comment]
And while you're at it you could add `if 0 > len(foo) {…}` – for those who prefer Yoda style.

**Comment by dominikh** [comment]
We actively discourage Yoda style in [ST1017](https://staticcheck.io/docs/checks#ST1017) – but yes, considering this is a correctness check, we will likely check both variations.

**Comment by mwat56** [comment]
> We actively discourage Yoda style in [ST1017](https://staticcheck.io/docs/checks#ST1017) 

Yes, indeed. That's why I have to start all my source files with

    //lint:file-ignore ST1017 – …

(I use several other languages and I don't want to change my style for each of them.)

**Comment by dominikh** [comment]
This was added in df09c08ed66e57919560b3a4f897d8f030f58157
