### ISSUE TITLE
Print error if staticcheck configuration has an invalid check specified

### ISSUE THREAD

**Issue by bufdev** [dominikh/go-tools#765]
```
$ staticcheck -checks foo_bar ./...
$ echo $?
0
```

That's it :-)

**Comment by dominikh** [comment]
I will have to think about this. There may be circumstances under which the current behavior is desirable, for example as a way of forwards compatibility.

**Comment by bufdev** [comment]
The only way this would provide incompatibility would be if you deleted a check, which itself would be a breaking change.

**Comment by dominikh** [comment]
> The only way this would provide incompatibility would be if you deleted a check, which itself would be a breaking change.

Two things.

1) This is not just a matter of backwards compatibility, but forwards compatibility as well. If a project specifies a check X that only exists starting with version 2020.2, but a user is using 2020.1 to check said project, I'm not sure it should fail. My gut feeling tells me that it shouldn't.

2) We do remove checks from time to time, if we find unfixable flaws in them – usually this boils down to a check having false positives we didn't anticipate when we added the check. I would like to avoid unnecessary churn for my users in that case.

**Comment by tendervittles** [comment]
I also noticed this behavior, and thought it was intentional.

My company's CI sticks to official releases of staticcheck. I periodically pull in master on my host.

If I hit a false positive, or just a new check I want to ignore for now, I can update the staticcheck.conf in my repo without breaking CI. 

I use staticcheck.conf as the union of checks and ignores across multiple versions of the tool.

**Comment by dominikh** [comment]
Thanks for that data point, @tendervittles. It confirms by belief that we shouldn't turn this into a failure.

I'm still making up my mind on whether we should warn about it or not, but I am leaning towards not warning, either. It seems like it would produce unactionable noise for users like tendervittles.

**Comment by ainar-g** [comment]
Add the `--strict` flag to change the behaviour of the `--checks` flag :-D !

**Comment by dominikh** [comment]
😐

**Comment by dominikh** [comment]
I've decided that there is nothing to do here. Failing on unknown checks breaks forward compatibility. Warning on unknown checks makes the forward compatibility annoying to rely on.

We could consider modifying the `stylish` (and possibly `json`) output formats to include statistics on the number of checks executed/checks not known, but I'm not sure that's worth it, either.

I recognize that there is a real risk of running fewer checks than one intended, but I don't know of any good way to solve that issue.
