### ISSUE TITLE
unused doesn't take templates in to account

### ISSUE THREAD

**Issue by arp242** [dominikh/go-tools#766]
I have some functions that are referenced only in Go templates, and unused doesn't seem to take that in account:

    $ staticcheck -unused.whole-program ./...
    site.go:383:15: func Site.Display is unused (U1001)

    $ grep -r  Site.Display
    tpl/user.gohtml:<h1>Sign in at {{.Site.Display}}</h1>

I'm not sure if it's worth parsing templates for this to be honest, but it can be surprising.

I flagged this as "new feature" rather than "false positive in staticcheck" since that seemed like a better bit, as templates are not Go code.

**Comment by dominikh** [comment]
Beginning with 5cfc85b70e7b778eb76fd7338e538d7c9af21e4e this issue is no longer relevant, as unused's whole-program mode has been removed. This is a(n interesting) special case of the inherent impossibility of catching all dynamic uses of objects.
