### ISSUE TITLE
staticcheck: flag -0.0 literal

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#780]
The literal `-0.0` does not produce a value different from `0.0` in Go.

**Comment by mwat56** [comment]
> The literal `-0.0` does not produce a value different from `0.0` in Go.

Seems very exotic to me: Why would anybody write that?
I think we can safely save some electricity by omitting such a test.

**Comment by dgryski** [comment]
Signed zeroes are important in algorithms for numerical analysis.
