### ISSUE TITLE
staticcheck: flag ineffective field writes

### ISSUE THREAD

**Issue by seebs** [dominikh/go-tools#786]
If you have a method with a non-pointer receiver that writes to its receiver, and nothing reads the value written, that's probably an error. I think that functionally the receiver can be treated like local variables at that point.

https://play.golang.org/p/rYwuBtS0Rzb

(Example from irc, #go-nuts)

**Comment by dominikh** [comment]
We used to have this check, as SA4005. It was buggy and we "temporarily disabled" it (see #141 and 8ed405e85c65fb38745a8eafe01ee9590523f172). In 2018. And never remembered to fix the check.

Let's use this issue as the "add back SA4005" issue.
