### ISSUE TITLE
staticcheck seem to use a lot of RAM

### ISSUE THREAD

**Issue by fasaxc** [dominikh/go-tools#79]
Running `staticcheck` on my codebase seem to use 2+GB of RAM, is that expected?  It's enough that my CI runs on SemaphoreCI are getting killed.

Are there any sub-linters I can disable to get it under control or any way I could have misconfigured it?

I'm running
```
git clone git@github.com:projectcalico/felix.git
cd felix
make vendor  # this runs glide install
staticchecks `glide nv`
```

I was originally running staticcheck via gometalinter but gometalinter runs many concurrent copies of staticcheck making the problem even worse.

**Comment by dominikh** [comment]
Yes, the memory usage is expected, and disabling checks won't help. The largest portion of memory is used by go/types and go/ast, as we need type information and the AST for all the code and all of its dependencies. go-tools itself also keeps some state around that is needed by all checks.

I have no idea what `glide nv` does. I will assume that it lists all of your packages, excluding vendored code? If your project is large and consists of many packages with somewhat disjoint sets of dependencies, you can run staticcheck on each package (or sets of packages) sequentially. This may reduce the memory usage, by trading increased CPU time for it.

`staticcheck database/sql` uses about 310 MB and `staticcheck std` uses about 2 GB. You can use that to judge the memory usage you can expect to see.

While I might reduce overall memory usage at some point, it will not be very significant. That is, after accounting for rounding errors, your 2 GB usage will still be roughly 2 GB.
