### ISSUE TITLE
Deprecated package not detected

### ISSUE THREAD

**Issue by flimzy** [dominikh/go-tools#798]
- The output of 'staticcheck -version'
I built staticcheck from master (SHA 925e3c1d1b)
```
staticcheck (no version)
```
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck (no version)

Compiled with Go version: go1.14.2
Main module:
        honnef.co/go/tools
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.2.0 (sum: h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=)
        golang.org/x/tools@v0.0.0-20200609164405-eb789aa7ce50 (sum: h1:59syOWj4+Fl+op4LL8fX1kO7HmbdEWfxlw4tcGvH+y0=)
        golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 (sum: h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=)
```
- The output of 'go version'

```
go version go1.14.2 linux/amd64
```

- The output of 'go env'
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonhall/.cache/go-build"
GOENV="/home/jonhall/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/lana,gitlab.lana.tech,gitlab.com/FlashbackSRS/priv"
GONOSUMDB="github.com/lana,gitlab.lana.tech,gitlab.com/FlashbackSRS/priv"
GOOS="linux"
GOPATH="/home/jonhall/go"
GOPRIVATE="github.com/lana,gitlab.lana.tech,gitlab.com/FlashbackSRS/priv"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jonhall/src/lana/mx-merino/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build148405989=/tmp/go-build -gno-record-gcc-switches"
```
- Exactly which command you ran
```
/home/jonhall/go/bin/staticcheck
```
- Output of the command and what's wrong with the output
```
asdf.go:11:31: tls.VersionSSL30 is deprecated: SSLv3 is cryptographically broken, and is no longer supported by this package. See golang.org/issue/32716.  (SA1019)

Run '/home/jonhall/go/bin/staticcheck -explain <check>' or visit https://staticcheck.io/docs/checks for documentation on checks.
```

The output correctly identifies that `ts.VersionSSL30` is deprecated, but fails to identify that the [`testy`](https://godoc.org/github.com/flimzy/testy) package (the entire package--not a specific symbol) is deprecated.

- Where we can read the code you're running staticcheck on
```
package main

import (
	"crypto/tls"
	"fmt"

	"github.com/flimzy/testy"
)

func main() {
	fmt.Println(testy.Environ(), tls.VersionSSL30)
}
```

Additional notes:

It's certainly possible that there's some subtlety about my `testy` package that I've missed, that is causing it not to be read properly or detected as deprecated, but I cannot find it. :confused:  And best I can tell, this [should be supported](https://github.com/dominikh/go-tools/issues/413) by staticcheck.

**Comment by dominikh** [comment]
I cannot reproduce the problem:

```
$ staticcheck .            
foo.go:7:2: package github.com/flimzy/testy is deprecated: This package is no longer maintained. Please use gitlab.com/flimzy/testy instead.  (SA1019)
foo.go:11:31: tls.VersionSSL30 is deprecated: SSLv3 is cryptographically broken, and is no longer supported by this package. See golang.org/issue/32716.  (SA1019)
```

I've tested with staticcheck's master as well as 2020.1.4, and I've tested with Go modules as well as GOPATH.

Are you sure you're testing with the correct version of `testy`, and not an older version that lacks the deprecation notice?

**Comment by flimzy** [comment]
> Are you sure you're testing with the correct version of `testy`, and not an older version that lacks the deprecation notice?

Thank you for the quick reply.

Indeed that does appear to be the problem. According to `go.mod` it was using "github.com/flimzy/testy v0.1.17-0.20190521133342-95b386c3ece6", which was one commit before the deprecation notice was added.

My apologies for the false alarm.
