### ISSUE TITLE
gosimple: suggest merging var and assign lines

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-tools#8]
```
var a int
a = 3
```

can be reduced to either

```
a := 3
```

or

```
var a int = 3
```

Depends on the context. The latter is sometimes needed, e.g. for interfaces. In any case, two lines are unnecessary verbosity.

**Comment by dominikh** [comment]
> In any case, two lines are unnecessary verbosity

That is actually not true unconditionally. There is one stylistic reason, and one requirement, that necessitate splitting it into two lines.

The stylistic reason is this:

```
var x []SomeType
x = append(x, m...)
```

which people can prefer over 

```
x := append(([]SomeType)(nil), m...)
```

The case that requires two lines is the one where the variable initialization depends on the variable. The most common case are recursive anonymous functions. Another, less common case, are `math/big`-like APIs. Taken from one of `math/big`'s tests:

```
var z nat
z = z.shl(test.in, test.shift)
```

**Comment by mvdan** [comment]
Good call - and thanks for implementing!
