### ISSUE TITLE
detect n-square and n-cube loops

### ISSUE THREAD

**Issue by siddharth178** [dominikh/go-tools#804]
Hello all,

This is more of a question than any idea or feature request. Recently I found couple of cases in codebase that I work on where a range loop calling another function was resulting in n*m kind of complexity. Both these functions were written by different developers and written at different times. So there was no easy way to detect this in code-review. Fortunately we are using this function on small size data, so it was not causing any "real" issues at the moment. But that triggered a thought in my head - how many such loops will be there in our code that could someday result in unexpected performance penalties.

* Is there a way to detect if code is getting into looping structures (direct or indirect way) thats resulting in n-square or n-cube complexity?
* Where can I find more information about this topic? Any existing tools do it for other languages? Any papers/documents?

Thanks,
Siddharth

**Comment by dominikh** [comment]
I'm sorry, but computing the big O complexity of algorithms isn't something I've investigated, so I can't point you towards any existing research. If I had to guess, I would assume that it boils down to detecting nested loops and inspecting the variables they loop over.
