### ISSUE TITLE
staticcheck: SA4006 false positive

### ISSUE THREAD

**Issue by bradfitz** [dominikh/go-tools#805]
https://github.com/tailscale/tailscale/commit/4aba86cc0338fff616432683139f3b8cc036da58 regrettably added a `//lint:ignore SA4006 staticcheck is wrong` line for package `tailscale.com/ipn/ipnserver`

```
staticcheck (devel, v0.0.1-2020.1.0.20200727014854-3b5b85696619)
```

I see other SA4006 bugs open here, but none seem like this case, so filing a new one.

Without the ignore directive, I get:

```
$ go run honnef.co/go/tools/cmd/staticcheck tailscale.com/ipn/ipnserver
ipn/ipnserver/server.go:191:4: this value of eng is never used (SA4006)
```

But that's not true. It's used down below at:

https://github.com/tailscale/tailscale/blob/4aba86cc0338fff616432683139f3b8cc036da58/ipn/ipnserver/server.go#L220
```go
     b, err := ipn.NewLocalBackend(logf, logid, store, eng)
```

**Comment by ainar-g** [comment]
<p>I may be misreading something (since it's 01:00 in Moscow), but that
<code>for</code> block is followed with a conditionless
<code>return</code> on line 207, so that value of <code>eng</code> is,
indeed, not used.</p>

**Comment by bradfitz** [comment]
Hah, whoops. This code could really use some tests 😭
