### ISSUE TITLE
unused: false positive involving unnamed struct types, named struct types and implicit conversions

### ISSUE THREAD

**Issue by kylrth** [dominikh/go-tools#810]
I discovered this while using the `unused` linter in `golangci-lint`. I hope I found the right place to report this issue. :crossed_fingers:

Here's some code that reproduces it:

```go
package unused_test

import "fmt"

type Thing struct {
	stuff int
	has   struct {
		a bool
		b bool
	}
}

func ExampleThing() {
	type temp struct {
		a bool
		b bool
	}

	stuff := map[string]Thing{
		"hello": {has: temp{true, false}},
	}

	fmt.Println(stuff["hello"].stuff, stuff["hello"].has)
	// Output: 0 {true false}
}
```

Running `./golangci-lint run unused_test.go` results in ``unused_test.go:14:7: type `temp` is unused (unused)``.

**Comment by dgryski** [comment]
Does this reproduce with the latest staticcheck?

**Comment by kylrth** [comment]
Yes, I get the following output with `staticcheck` build from master on this repo:
```
unused_test.go:14:7: type temp is unused (U1000)

Run './staticcheck -explain <check>' or visit https://staticcheck.io/docs/checks for documentation on checks.
```

**Comment by dominikh** [comment]
Simpler reproducer: 

```
package foo

type Thing struct {
	has struct {
		a bool
	}
}

func Fn() {
	type temp struct {
		a bool
	}

	x := Thing{
		has: temp{true},
	}
	_ = x
}
```

the issue seems to be caused by the implicit conversion to the unnamed struct type in `Thing`.

**Comment by qdm12** [comment]
I can confirm (found using `golangci-lint` `v1.44.2` built using Go 1.18):

```go
package main

import (
	"fmt"
)

type someStruct struct {
	parentField struct {
		n int
	}
}

type someStruct2 struct {
	n int
}

func main() {
	x := someStruct{
		parentField: someStruct2{n: 1},
	}
	fmt.Println(x)
}
```

Error: `type `someStruct2` is unused (unused)`
