### ISSUE TITLE
simple: flag type assertions into the same type

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#821]
<p>(Inspired&#xA0;by&#xA0;golang/go#41174.)</p> 

<p><code>simple</code>&#xA0;should flag type assertions
into&#xA0;the&#xA0;same type.&#x2003;The&#xA0;original issue is
about&#xA0;generated code, but&#xA0;I&#xA0;think I've seen such code
in&#xA0;the&#xA0;wild, something&#xA0;like:</p> 

<pre><code>// Used to be some other type.
var f io.ReadCloser = os.NewFile(0, "stdin")

// (Lots of code skipped.)

// Doesn't make sense any more.
var r io.ReadCloser = f.(io.ReadCloser)</code></pre>

<p>Same&#xA0;for&#xA0;type&#xA0;switches.</p>

**Comment by dominikh** [comment]
The weirdest find so far, from our old friends at Kubernetes:

```
func TestNewFakeManager(t *testing.T) {
	fm := NewFakeManager()

	if _, ok := fm.(Manager); !ok {
		t.Errorf("Result is not Manager type")

	}
}
```

I guess some people really don't trust the type system.

**Comment by ainar-g** [comment]
Maybe they're just the kind of developer who is very picky about those pesky _management types_.

Jokes aside, it may be a variation of interface satisfaction assertions from Dave Cheney's [_Go, Without Package Scoped Variables_] that, in a fashion similar to what I described in the OP, became useless over time.

[_Go, Without Package Scoped Variables_]: https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables

**Comment by dominikh** [comment]
Unfortunately, the existence of nil interface values mean that this isn't strictly a type-based analysis. Consider this:

```
package main

type SomeInterface interface {
	Foo()
}

func fn(x SomeInterface) {
	_ = x.(SomeInterface)
}

func main() {
	fn(nil)
}

/*
panic: interface conversion: interface is nil, not main.SomeInterface

goroutine 1 [running]:
main.fn(...)
	/home/dominikh/prj/src/sandbox/foo/foo.go:8
main.main()
	/home/dominikh/prj/src/sandbox/foo/foo.go:12 +0x35
exit status 2
*/
```

And in general, we don't know whether a variable contains a nil interface value or not. That's certainly true for all examples so far.

**Comment by dominikh** [comment]
I suppose we could suggest being more explicit, and using an actual nil comparison, instead of relying on the side-effect of the type assertion.
