### ISSUE TITLE
staticcheck: Add option for passing folders that should be avoided

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#822]
It would be great if you could pass a folder (or folders) where you don't want `staticcheck` to  check the .go files. Useful if you, for example, are vendoing a different go module outside of the normal vendor folder.

**Comment by Jacalz** [comment]
Might be related to #429

**Comment by ainar-g** [comment]
<p>That's&#xA0;a&#xA0;relatively simple <i>POSIX Shell</i>
script&#xA0;though:</p> 

```sh
$ go list ./... | grep -F -e example.com/bad/pkg -v | xargs staticcheck
```

**Comment by Jacalz** [comment]
Thanks @ainar-g. That is quite a good workaround until this is solved in a better way :)

**Comment by dominikh** [comment]
> until this is solved in a better way
There will likely not be a better way. Passing the packages you want checked on the command-line is exactly the way to solve this. If the `...` pattern matches too many packages, then you'll have to use something like Ainar's approach to filter that list. This is in line with tools like `go test`, where `go test ./...` will (probably?) also run more tests than you intended.

You could also place a `staticcheck.conf` at the top of your "vendor" directory that disables all checks (`checks = []`) – but you may have to delete nested staticcheck.conf files if your vendored dependencies have any, or they might re-enable checks.
