### ISSUE TITLE
stylecheck: find godoc headers that won't be rendered as such

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#826]
<p>Here&#xA0;<q>Exit&#xA0;Codes</q> won't be rendered as&#xA0;a&#xA0;header:</p> 

```go
// […]
//
// Exit Codes
//
//   0 = Success
//   1 = Failure
```

<p>Here&#xA0;it&#xA0;will:</p> 

```go
// […]
//
// Exit Codes
//
// Here are some exit codes for you:
//
//   0 = Success
//   1 = Failure
```

<p>This&#xA0;is&#xA0;because:</p>

<pre>$ go doc go/doc.ToHTML
package doc // import "go/doc"

func ToHTML(w io.Writer, text string, words map[string]string)
    […]

    Each span of unindented non-blank lines is converted into a single
    paragraph. There is one exception to the rule: a span that consists of a
    single line, <strong>is followed by another paragraph span</strong>, begins with a capital
    letter, and contains no punctuation other than parentheses and commas is
    formatted as a heading.

    […]</pre>

<p>Since&#xA0;a&#xA0;code block is not&#xA0;considered a&#xA0;paragraph span,
<q>Exit&#xA0;Codes</q> won't become a&#xA0;header.</p>

**Comment by dominikh** [comment]
The obvious question is: can we be sure that what looks almost like a header was meant to be a header, and isn't intentionally the way it is?

**Comment by ainar-g** [comment]
<p>I've been trying to&#xA0;analyse some code to&#xA0;find an&#xA0;exact set
of&#xA0;criteria, but&#xA0;it seems like&#xA0;that's rather
futile.&#x2003;I&#xA0;assumed that&#xA0;everyone precedes their code blocks
with&#xA0;a&#xA0;colon, but&#xA0;even in&#xA0;the&#xA0;standard library that's
not&#xA0;the&#xA0;case.&#x2003;I&#xA0;guess the&#xA0;issue can
be&#xA0;closed.</p>
