### ISSUE TITLE
simple: don't use double-negatives

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#830]
<p>The&#xA0;code:</p> 

```go
package main

func f() (ok bool) { return 1 == 2 }
func g() (ok bool) {
	if !f() {
		return false
	}

	return true
}

func main() {
	_ = g()
}
```

<p>The&#xA0;message:</p> 

<pre>$ staticcheck --checks=all ./tmp.go
tmp.go:5:2: should use 'return <strong>!(!f())</strong>' instead of 'if !f() { return false }; return true' (S1008)

Run 'staticcheck -explain &lt;check&gt;' or visit https://staticcheck.io/docs/checks for documentation on checks.</pre>

<p>A&#xA0;better&#xA0;message:</p> 

<pre>$ staticcheck --checks=all ./tmp.go
tmp.go:5:2: should use 'return <strong>f()</strong>' instead of 'if !f() { return false }; return true' (S1008)

Run 'staticcheck -explain &lt;check&gt;' or visit https://staticcheck.io/docs/checks for documentation on checks.</pre>

<details>
<summary>Formalities</summary>

<pre>$ go version
go version go1.15 linux/amd64
$ staticcheck --version
staticcheck (devel, v0.0.1-2020.1.0.20200914055839-8040d28b8db8) 
$ staticcheck --debug.version
staticcheck (devel, v0.0.1-2020.1.0.20200914055839-8040d28b8db8)

Compiled with Go version: go1.15
Main module:
	honnef.co/go/tools@v0.0.1-2020.1.0.20200914055839-8040d28b8db8 (sum: h1:05W+ragjlmgSs5FK4QfaOkYC9xe98kh5P7vlC4BPbVo=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.2.0 (sum: h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=)
	golang.org/x/tools@v0.0.0-20200609164405-eb789aa7ce50 (sum: h1:59syOWj4+Fl+op4LL8fX1kO7HmbdEWfxlw4tcGvH+y0=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)</pre>
</details>

**Comment by dominikh** [comment]
https://www.youtube.com/watch?v=63NCvjX7X8E

**Comment by ainar-g** [comment]
#897 seems to have fixed this for me.  Closing the issue?

**Comment by dominikh** [comment]
Thanks Ainar.
