### ISSUE TITLE
staticcheck: add option to turn off compiling

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#831]
For situations where there is no need to have staticcheck compile code because of it being handled by another step in testing or because of all dependencies not being installed, it would make sense to be able to turn off the compilation.

Right now it just takes unnecessary time of CI builds. I hid the messages of it not being able to compile by setting the debug flag to hide compilation issues, but it still tries to compile and the issues are numbered. So if we have three compile errors and ask staticcheck to hide compile errors, we still have 3 issues noted in the bottom, but no printed indication (obviously).

Thus, I propose to be able to turn off compilation when only code style checks are desired.

**Comment by dominikh** [comment]
Almost every check in Staticcheck needs type information, including many of the style checks. As such, we fundamentally can't "turn off compiling". If your code doesn't compile, then Staticcheck cannot check it.
