### ISSUE TITLE
anyone really was using 'keyify' ?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [dominikh/go-tools#834]
```
bash-4.4$ keyify src/shape/x.go:#8
can't find package containing /home/shane/tmp_test_dir/tmp_go_proj/shape/src/shape/x.go
bash-4.4$ 
```

or:
```
bash-4.4$ keyify abc/x.go:#59
can't find package containing /home/shane/tmp_test_dir/tmp_go_proj/shape/src/shape/abc/x.go
bash-4.4$ tree
.
├── abc
│   └── x.go
├── go.mod
└── main.go

1 directory, 3 files
bash-4.4$ 
```

```
bash-4.4$ keyify -version
keyify (devel, v0.0.1-2020.1.0.20200917201753-2b63335d5ff1)
bash-4.4$ 
```

**Comment by dominikh** [comment]
> anyone really was using 'keyify'

probably not many at this point.

As for your specific problem: keyify has never been updated to work with Go modules; it only works in GOPATH mode. It's unlikely that this will be fixed, either. At this point, the likely way forward is that keyify will be integrated with gopls at some point, and the standalone tool will go away.

**Comment by Shane-XB-Qian** [comment]
> it only works in GOPATH mode

i tried `export GOPATH=`pwd`"/..":$GOPATH`, looks not working still, i was using a wrong case.
but even it worked, looks it's not a convenience way ..

> keyify will be integrated with gopls at some point, and the standalone tool will go away.

better be, thanks your info and reply. looking forward this.
