### ISSUE TITLE
Chained appends

### ISSUE THREAD

**Issue by gwvandesteeg** [dominikh/go-tools#837]
```
$ go version
go version go1.13.5 linux/amd64
```

When creating a complex list using multiple append statements using generator functions we get a false positive.
```
cmd/server/metrics.go:38:26: SA4021: x = append(y) is equivalent to x = y (staticcheck)
```
```
var RequestSizeBuckets = append(append(append(append(
        prometheus.LinearBuckets(100, 100, 5),
        prometheus.LinearBuckets(1000, 1000, 5)...),
        prometheus.LinearBuckets(10000, 10000, 5)...),
        middleware.BodySizeBuckets...), // array of 1MB to 250MB
)
```

Chained appends like this cannot be reduced down to a single x = append(y)

**Comment by dominikh** [comment]
You have one too many `append` calls. Using placeholders, your code reads

```
RequestSizeBuckets = append(append(append(append(arg1, arg2...), arg3...), arg4...))
```

which, pulled apart, is identical to

```
ret1 = append(arg1, arg2...)
ret2 = append(ret1, arg3...)
ret3 = append(ret2, arg4...)
RequestSizeBuckets = append(ret3)
```

and `append(ret3)` doesn't do anything useful; it is the same as `ret3` itself.

**Comment by gwvandesteeg** [comment]
Wow, thanks, that fixed it.  Hah, that was a copy from 2 existing open source projects and passed through code review here...
