### ISSUE TITLE
false positive in SA1005

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#84]
The following code:

```go
func vmwareGetInfo(key string) string {
	cmd := exec.Command("/Library/Application Support/VMware Tools/vmware-tools-daemon",
		"--cmd",
		"info-get "+key)
```

triggers SA1005: 

```
cmd/buildlet/buildlet.go:1341:22: first argument to exec.Command looks like a shell command, but a program name or path are expected (SA1005)
```

However, it's a perfectly valid program, and "Application Support" is a system folder on Macs, so it's not clear how users should work around this.

**Comment by dominikh** [comment]
The current check flags any exec.Command where the first argument contains spaces and no backslash (to avoid false positives on Windows). I can't immediately think of a solid approach for OS X. Of course we can ignore exec.Command calls with >1 arguments, or those with spaces but no words that look like CLI flags. But all of these will still likely produce false positives.

We may have to turn off the check.

**Comment by kevinburke** [comment]
My other idea was to have some kind of whitelist but that's also
problematic because everyone will want exceptions.


--
Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by dominikh** [comment]
Let's ignore commands with forward slashes in them, too, and wait until someone else complains.

**Comment by kevinburke** [comment]
Thanks. Was just thinking, another possibility would be to do `strings.Split(cmd, " ")[0]` and then call LookPath on that. Which would get you e.g. `exec.Command("git pull origin master")`.

Of course the machine running the checks might not match the machine the binary eventually runs on.

**Comment by dominikh** [comment]
I was going to make the same suggestion, however I was intending for it to be a joke.
