### ISSUE TITLE
S1019 reported on make invocations with 2 arguments.

### ISSUE THREAD

**Issue by based64god** [dominikh/go-tools#857]
- The output of 'staticcheck -version'
`golangci-lint has version 1.31.0 built from 3d6d0e7 on 2020-09-07T15:14:41Z`
was where I'd originally found it.
The issue still appears in `staticcheck 2020.1.6`
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck 2020.1.6

Compiled with Go version: go1.14.6
Main module:
        honnef.co/go/tools@v0.0.1-2020.1.6 (sum: h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/tools@v0.0.0-20200410194907-79a7a3126eef (sum: h1:RHORRhs540cYZYrzgU2CPUyykkwZM78hGdzocOo9P8A=)
        golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 (sum: h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=)
```
- The output of 'go version'
`go version go1.15.3 darwin/amd64`
- The output of 'go env'
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/emmetthitz/Library/Caches/go-build"
GOENV="/Users/emmetthitz/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/emmetthitz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/emmetthitz/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/Cellar/go/1.15.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pr/ss2t5nlx6px8vy0qvtcrfkzc0000gn/T/go-build876300367=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
- Exactly which command you ran
`./staticcheck`
- Output of the command and what's wrong with the output
`main.go:8:37: should use make(map[string]string) instead (S1019)`
`make()` requires at least two arguments. applying the suggested fix prevents compilation
- Where we can read the code you're running staticcheck on
  (GitHub repo, link to playground, code embedded in the issue, ...)

https://play.golang.org/p/Lcpea9AVBtQ

super simple

**Comment by ainar-g** [comment]
https://play.golang.org/p/UPla_4Ogcl_F?

**Comment by based64god** [comment]
> https://play.golang.org/p/UPla_4Ogcl_F?

I feel like I must be going crazy. When I initially tried this, compilation failed due to `make()` requiring two args. For whatever reason, it works now. Thanks.

**Comment by dominikh** [comment]
> I feel like I must be going crazy. When I initially tried this, compilation failed due to make() requiring two args. For whatever reason, it works now. Thanks.

That is true for slices, but not maps.
