### ISSUE TITLE
stylecheck: ST1003 triggers on names with no letters

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#858]
<details>
<summary>Formalities</summary>

<pre>$ staticcheck --version</pre>
<pre>staticcheck (devel, v0.0.1-2020.1.0.20201012230725-8ea76608cc77)</pre>
<pre>$ staticcheck --debug.version</pre>
<pre>staticcheck (devel, v0.0.1-2020.1.0.20201012230725-8ea76608cc77)

Compiled with Go version: go1.15.2
Main module:
	honnef.co/go/tools@v0.0.1-2020.1.0.20201012230725-8ea76608cc77 (sum: h1:lt7RL2qsRUpEPBHt4uBk0+zL1rR4UP5UxuH6WUhKlts=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.2.0 (sum: h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=)
	golang.org/x/tools@v0.0.0-20200609164405-eb789aa7ce50 (sum: h1:59syOWj4+Fl+op4LL8fX1kO7HmbdEWfxlw4tcGvH+y0=)
	golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 (sum: h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=)</pre>
</details>

<p>Code:</p>

```go
package main

import (
	"fmt"
	"math/big"
)

func main() {
	var _2 = big.NewInt(2)
	var _1000 = big.NewInt(1000)

	fmt.Println(new(big.Int).Mul(_2, _1000))
}
```

<p>Results:</p>

<pre>tmp.go:10:6: should not use ALL_CAPS in Go names; use CamelCase instead (ST1003)</pre>

<p>I've&#xA0;been doing some mathy stuff with&#xA0;<code>math/big</code>
recently.&#x2003;I've been using this <code>_NNNN</code> naming convention
for&#xA0;some <q>constant</q> values, and <code>staticcheck</code> seems
to&#xA0;not&#xA0;like it one bit, heh.&#x2003;I&#xA0;agree that the&#xA0;naming
is… unorthodox, but&#xA0;still.&#x2003;There are actually some examples
of&#xA0;using such identifiers in&#xA0;Go packages,
like&#xA0;in&#xA0;<a href="https://github.com/golang/go/blob/b2a8317b31d652b3ee293a313269b8290bcdf96c/src/crypto/elliptic/p256_asm.go#L126"><code>crypto/elliptic/p256_asm.go</code></a>:

```go
var (
	_1      = table[4*0 : 4*1]
	_11     = table[4*1 : 4*2]
	_101    = table[4*2 : 4*3]
	_111    = table[4*3 : 4*4]
	_1111   = table[4*4 : 4*5]
	_10101  = table[4*5 : 4*6]
	_101111 = table[4*6 : 4*7]
	x       = table[4*7 : 4*8]
	t       = table[4*8 : 4*9]
)
```

<p>So&#xA0;I&#xA0;think that&#xA0;this <em>maybe</em> should be
allowed?&#x2003;Even&#xA0;if&#xA0;we decide against&#xA0;it, the&#xA0;error
message should at&#xA0;least be clearer.&#x2003;Otherwise, I&#xA0;think
that&#xA0;I&#xA0;can send a&#xA0;patch.</p>

**Comment by dominikh** [comment]
I don't intend to flag variable names for not containing any letters; we shouldn't flag this code.

> Otherwise, I think that I can send a patch

You can if you want to, but it won't get merged any faster than if I fix it myself. Your call.

**Comment by ainar-g** [comment]
<p>I&#xA0;would like to&#xA0;try and&#xA0;do it myself, if&#xA0;you don't
mind.&#x2003;I've been wanting to&#xA0;contribute some code
to&#xA0;<code>staticcheck</code> for&#xA0;a&#xA0;long time now,&#xA0;heh.</p>

**Comment by dominikh** [comment]
Feel free to :)
