### ISSUE TITLE
Detect returning nil after `err != nil` check

### ISSUE THREAD

**Issue by ilinum** [dominikh/go-tools#863]
I would like staticcheck to detect the following:
```go
func foo() error {
  ...
  err := bar()
  if err != nil {
    return nil // BUG! Most of the time it should be `return err`
  }
  ...
}
```

Sometimes, of course, you want to explicitly return an error there, so this check will have quite a few false positives.
Most of the time, however, it will detect bugs.

**Comment by ilinum** [comment]
I'd be happy to implement this but I would like to hear some input first with regards to whether or not this would cause too many false positives for the value that the check would provide.

**Comment by dominikh** [comment]
> so this check will have quite a few false positives

That, unfortunately, makes it ineligible for Staticcheck. We err on the side of false negatives, and checks are expected to have no false positives in the general case. As such, we can't just flag `if err != nil { return nil }`.

This might be better suited for https://github.com/go-critic/go-critic

**Comment by dgryski** [comment]
This pattern is very easy to match with ruleguard or semgrep.

**Comment by dominikh** [comment]
Reopening under the `aggressive` label, for a future set of checks specific to code review.

**Comment by dominikh** [comment]
Running this against `k8s.io/kubernetes/pkg/...` yields

- 6 false positives
- 2 instances I'm really not sure about
- 1 instance that is probably a true positive

Do people see this kind of bug during code review, and how often?

**Comment by dominikh** [comment]
> Does the check that you run include something like an exception for branches with comments?

That implementation did not. However, none of the results found in k8s had comments, either.

> I've definitely seen this kind of bug a couple of times in code reviews and at least a dozen of times in the code that I wrote but haven't committed yet.

Thanks.

**Comment by seiyab** [comment]
I've scanned some projects with my toy analyzer and found some real bugs.
- https://github.com/beego/beego/pull/5455
- https://github.com/cli/cli/issues/8026

And it also detects false positives.
- https://github.com/cli/cli/blob/c0658b7ab450dcc1b3fa70190f5744a1cad89da4/pkg/cmd/pr/shared/templates.go#L257-L259
- https://github.com/go-kratos/kratos/blob/311016862b20f14f9306f847b2d6bbb8c4f8b3c4/transport/http/server.go#L217-L221
