### ISSUE TITLE
Bazel / rules_go / nogo support

### ISSUE THREAD

**Issue by robfig** [dominikh/go-tools#865]
Wonderful project, thank you!

We use Bazel at work, and I was interested in applying some of the staticcheck checks using "nogo", which requires just a set of Analyzers. I think this shouldn't be too hard to support based on my cursory understanding of nogo and the staticcheck code, but before I DIY, I was curious if you were aware of any existing support? Thanks!

https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst

**Comment by dominikh** [comment]
I've never tried it, but in theory it should "just work", assuming `nogo` functions as a proper analysis runner. Looking at the readme, I can't tell if it expects each analysis to exist in a separate package. If it does, then that'll be problematic. Otherwise, if you can make nogo use the analyzers defined in the `staticcheck`, `simple` and `stylecheck` packages, then it should work.

**Comment by robfig** [comment]
Related: https://github.com/bazelbuild/bazel-gazelle/issues/578

**Comment by sluongng** [comment]
@dominikh just to clarify a bit on how `rules_go`'s `nogo` works:

It has a [template file](https://github.com/bazelbuild/rules_go/blob/master/go/tools/builders/generate_nogo_main.go#L33) that will be filled in by the data from nogo configuration and then get used by [nogo_main.go](https://github.com/bazelbuild/rules_go/blob/master/go/tools/builders/nogo_main.go)

So the easiest way for staticcheck to be used together with `nogo` is to provide a set of `analysis.Pass` like https://pkg.go.dev/golang.org/x/tools/go/analysis/passes@v0.0.0-20201110201400-7099162a900a that we can just add into the nogo config file.

I think currently staticcheck (or golangci-lint?) provides a slice of analysis.Analyzer directly? Which duplicate with how nogo template file functionality a bit.

**Comment by dominikh** [comment]
Staticcheck exposes maps of `analysis.Analyzer`, mapping from check name to `analysis.Analyzer`, see for example https://github.com/dominikh/go-tools/blob/a6ed285e57c7d3a0fb2922170942f39c5cd6eadb/staticcheck/analysis.go#L23. 

Judging by the template you've linked to, nogo expects a single analyzer, named `Analyzer`, per package? That won't work with Staticcheck, we have many analyzes in a single package.

**Comment by sluongng** [comment]
@dominikh is it possible for you to drive an upstream change into `rules_go` for this? I wonder if we can establish a common way to run, not only staticcheck with `nogo`, but also other Analyzers in `golangci-lint` as well.

**Comment by derekperkins** [comment]
Related conversation about integrating nogo and `golangci-lint` https://github.com/golangci/golangci-lint/issues/1473

**Comment by sluongng** [comment]
https://github.com/sluongng/staticcheck-codegen

If somebody is looking for a work around.

**Comment by sluongng** [comment]
FYI my approach in above repo☝️  works with some caveats that I noted in README.md

There is also a pending issue https://github.com/dominikh/go-tools/issues/1089 that is preventing me from upgrading staticcheck there to latest version. But right now it's working with version `2020.2.4` which is second to latest.

**Comment by dominikh** [comment]
I am going to close this issue. https://github.com/sluongng/nogo-analyzer seems to be doing the work necessary to use Staticcheck with rules_go.
