### ISSUE TITLE
staticcheck: consider automatically ignoring SA4xxx for generated code

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#87]
I just wanted to bring something up as I add an ignore. I get that staticcheck is for finding things that we expect to be bugs, but for generated code certain classes of checks, particularly the ones that detect dead/useless code, are more likely to be false positives. (Well, not really false positives, but "we know and we don't care".)

For example, I have to ignore some easyjson code that looks like this:

``` go
	for !in.IsDelim('}') {
		key := in.UnsafeString()   // <---- line 31
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}

```

```
xxx_easyjson.go:31:3: this value of key is never used (SA4006)
```

**Comment by bradleyfalzon** [comment]
This should already be excluding generated code using its own heuristics: https://github.com/dominikh/go-tools/blob/f637af825144df9db357bdbe921707f4a535f316/lint/lint.go#L415-L423 - I presume your code doesn't match this check?

I believe this does also match the spec at https://github.com/golang/go/issues/13560

/cc @shurcooL

**Comment by cespare** [comment]
My code does match that check -- I just changed easyjson to have the right header: https://github.com/mailru/easyjson/pull/115

I didn't realize that staticcheck is supposed to ignore generated code. I'll look into why it's not. (gosimple, which uses the same logic, does already ignore my easyjson code.)

**Comment by cespare** [comment]
Ah! It looks like staticcheck only ignores generated code for SA9003.

So I guess my proposal is to also ignore generated code for all of SA4xxx, or else SA4006 in particular.

**Comment by dominikh** [comment]
staticcheck is not supposed to ignore all generated code. We do ignore generated code in staticcheck on a per-check basis. Generated code can have bugs, too :)

I wouldn't be comfortable ignoring SA4006 in generated code, as it can catch buggy generators.

This isn't the first time someone had a "false positive" with that particular `switch` though, so I'll look into how difficult it'd be to filter that one in particular.

**Comment by cespare** [comment]
I'm using file ignores for this at this point and it seems okay to me.
