### ISSUE TITLE
SA5011 false positive after os.Exit on Go 1.16

### ISSUE THREAD

**Issue by kevinburkemeter** [dominikh/go-tools#872]
I'm running staticcheck at commit dc546986a51bad12b9de769571a7bc1b6b98da28 (the latest one) on a Mac. The following code errors.

```
	matches := radioRx.FindStringSubmatch(radio)
	if matches == nil {
		logger.Error(`invalid radio argument"`, "arg", radio)
		os.Exit(2)
	}
	radio = matches[2]
```

with this message:

```
$ make lint
envdir envs/localdev go vet ./...
time envdir envs/localdev /Users/kevin/bin/staticcheck ./...
src/cmd/meter-set-radio/main.go:135:10: possible nil pointer dereference (SA5011)
	src/cmd/meter-set-radio/main.go:131:5: this check suggests that the pointer can be nil

Run '/Users/kevin/bin/staticcheck -explain <check>' or visit https://staticcheck.io/docs/checks for documentation on checks.
Command exited with non-zero status 1
2.17user 1.07system 0:01.03elapsed 314%CPU (0avgtext+0avgdata 61588maxresident)k
0inputs+0outputs (10major+99968minor)pagefaults 0swaps
make: *** [Makefile:127: lint] Error 1
```

As far as I am aware it is impossible to continue program termination past a call to `os.Exit()`. 

This issue was previously reported in #611 (https://github.com/dominikh/go-tools/issues/611#issuecomment-544569774) but it either has popped up again after being fixed, or other parts of that issue were fixed but not this one.

**Comment by ainar-g** [comment]
<p>I&#xA0;can't reproduce that
with&#xA0;<a href="https://play.golang.org/p/M7fQ0jf1jr5">this code</a>,
and&#xA0;I'm also on&#xA0;that commit.&#x2003;Are you sure that&#xA0;that is
the&#xA0;code that triggers the&#xA0;error?</p>

**Comment by kevinburkemeter** [comment]
Change `[]int` to `[]string`

```main.go
package main

import (
	"log"
	"os"
)

func main() {
	m := f()
	if m == nil {
		log.Println("error")
		os.Exit(2)
	}

	mm := m[2]
	log.Println(mm)
}

func f() []string {
	return nil
}
```

**Comment by ainar-g** [comment]
<p>I've&#xA0;rechecked with <code>[]string</code>,
and&#xA0;<code>staticcheck</code> still doesn't complain.&#x2003;I&#xA0;thought,
that&#xA0;that may be a&#xA0;<i>macOS</i>-only issue, but&#xA0;my colleague
with&#xA0;a&#xA0;<i>macOS</i> machine checked as&#xA0;well, and&#xA0;he didn't
get any errors&#xA0;either.&#x2003;Very&#xA0;weird.</p>

**Comment by kevinburkemeter** [comment]
Oh... perhaps it's because I'm running Go `tip`?

```
$ go version
go version devel +979e137609 Mon Nov 9 15:46:56 2020 +0000 darwin/amd64
```

**Comment by kevinburkemeter** [comment]
I can't reproduce on go 1.15. So that must be it, something changed in the parser, or something.

**Comment by dominikh** [comment]
Can reproduce the problem, am working on a fix.
