### ISSUE TITLE
SA5011(go version is  13.1)_: Could not find nil pointer line  fmt.Println(emptyPoint.String())

### ISSUE THREAD

**Issue by liuss01** [dominikh/go-tools#878]
package main

import (
	"fmt"
	"reflect"
)

type Worker interface {
	String() string
}

type Person struct {
	Age  uint8
	Name string
	Sex  string
}

type Employee struct {
	Person
}

type Employer struct {
	Title string
	Person
}

func (p *Person) String() string {
	return fmt.Sprintf("Name: %s, Sex: %s, Age: %d", p.Name, p.Sex, p.Age)
}

func (er *Employer) String() string {
	return fmt.Sprintf("%s, Title: %s", er.Person.String(), er.Title)
}

func main() {
	test()
}

func test() {
	var (
		w          Worker
		emptyPoint *Employee
	)

	w = &Employer{
		Title: "Title",
		Person: Person{
			Name: "Tom",
			Age:  50,
			Sex:  "male",
		},
	}

	if IsNil(w) {
		fmt.Printf("interface w is nil")
		return
	}

	// **bad**
	e := w.(*Employee)
	fmt.Println(e.String())
	// ok
	if e, ok := w.(*Employee); ok {
		fmt.Printf("It's Employee, %s\n", e.String())
	} else if e, ok := w.(*Employer); ok {
		fmt.Printf("It's Employer, %s\n", e.String())
	}

	// **bad**
	fmt.Println(emptyPoint.String())
}

func IsNil(i interface{}) bool {
	vi := reflect.ValueOf(i)
	if vi.Kind() == reflect.Ptr {
		return vi.IsNil()
	}
	return false
}

**Comment by dominikh** [comment]
This is not something we aim to flag.
