### ISSUE TITLE
staticcheck panic

### ISSUE THREAD

**Issue by daixiang0** [dominikh/go-tools#882]
Output:
https://github.com/golangci/golangci-lint/issues/1537#issuecomment-739508618

Code:
https://github.com/daixiang0/kubeedge/tree/test-ci

**Comment by dominikh** [comment]
There is no `test-ci` branch in that repository, and I cannot reproduce the crash on the master branch.

**Comment by ldez** [comment]
I have a copy of the branch:

https://github.com/ldez/kubeedge/tree/test-ci

**Comment by dominikh** [comment]
Thanks @ldez, and thanks for the debugging work in https://github.com/golangci/golangci-lint/issues/1537
