### ISSUE TITLE
quickfix: suggest replacing conditionals with boolean initialisation

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#884]
<p>Code&#xA0;like&#xA0;this:</p>

<pre><code>myBool := false
if n != 0 {
&#x09;myBool = true
}</code></pre>

<p>Should&#xA0;be simplified to&#xA0;this:</p>

<pre><code>myBool := n != 0</code></pre>

<p>As&#xA0;of <code>v0.0.1-2020.1.0.20201208010337-0767310fbbbb</code> that
doesn't seem to be the&#xA0;case.</p>

https://play.golang.org/p/6J86IXDL8Gk

**Comment by dominikh** [comment]
I'll move this to a quickfix instead. Same old issue: consistency with surrounding code is better than simplicity.
