### ISSUE TITLE
simple: S1015 is questionable

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#89]
This code

``` go
func formatInt32(n int32) string { return strconv.FormatInt(int64(n), 10) }
```

gives

> should use strconv.Itoa instead of strconv.FormatInt (S1015)

Presumably gosimple thinks it should be written as

``` go
func formatInt32(n int32) string { return strconv.Itoa(int(n)) }
```

This doesn't seem like a significant simplification to me, and using Itoa has an extra function indirection.

I suggest that this check be restricted to the case that the input is already an int.

**Comment by shurcooL** [comment]
> I suggest that this check be restricted to the case that the input is already an int.

That sounds reasonable to me, and probably intended.

**Comment by dominikh** [comment]
Not a bug because we actually did intend to make this suggestion. I do, however, agree, that it's not much of a simplification and will change the check.

Even in the actually simpler case, the extra function call may be an issue, but hopefully mid-stack inlining in Go 1.9 will eliminate that cost.
