### ISSUE TITLE
simple or quickfix: simplify tagless switch statements

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#903]
```
switch {
case x == Value1 || x == Value2:
 ...
}
```

can be simplified to

```
switch x {
case Value1, Value2:
...
}
```

Related: #902

**Comment by dominikh** [comment]
I'm still undecided if this should go in `simple` or in `quickfix`. The usual deciding factor is this: is there a valid reason for using the current form, for example to stay consistent with surrounding code, or is the simplification always a net improvement?

**Comment by ainar-g** [comment]
The only half-decent reason I see to prefer the first form to the second one is when the developer “knows” that they will add more conditions later and that the new conditions will be more complex.

**Comment by josharian** [comment]
One reason to use the longhand form is if you know certain values occur much more frequently than others. In that case, you might want to control the order in which cases are evaluated. On the other hand, that’s dependent on the exact details of the compiler.
