### ISSUE TITLE
Is there a place for suggestions with high chance of false positives?

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#91]
[`strings.Compare`](https://godoc.org/strings#Compare) function is documented as:

> Compare returns an integer comparing two strings lexicographically. The result will be 0 if a==b, -1 if a < b, and +1 if a > b.
>
> Compare is included only for symmetry with package bytes. It is usually clearer and always faster to use the built-in string comparison operators ==, <, >, and so on.

So the absolute only reason the function exists in standard library is for allowing code symmetry.

In theory, the only reason that function would be used, instead of operators, is when the programmer consciously decides to prefer code symmetry over code simplicity/performance.

In practice, some programmers may not realize that their use of `strings.Compare` could be simplified and performance could be improved.

For the former, this report would be a false positive. For the latter, a helpful report.

Can we do anything about this? Is there a place this type of check could fit in, given its propensity for false positives (such that `gosimple` doesn't seem appropriate)?

**Comment by dominikh** [comment]
> Is there a place for suggestions with high chance of false positives?

The correct place for that would probably be your/your company's style guide. I don't see any tool we could fit this in.

**Comment by shurcooL** [comment]
> I don't see any [existing] tool we could fit this in.

I agree. Then the question is if it's worth making a new tool for just these checks. Probably not.

**Comment by dominikh** [comment]
Not for me, anyway. Luckily I don't hold a monopoly on linters ;)

**Comment by shurcooL** [comment]
Thanks for consideration!
