### ISSUE TITLE
Deprecated methods not outputed. 

### ISSUE THREAD

**Issue by skormos** [dominikh/go-tools#926]
Using the `// Deprecated: ` tag anywhere in a project doesn't seem to do anything. Goland signals the usage correctly, but within the same project, or across multiple projects, `staticcheck` itself seems to identify nothing. 

The [main function here](https://github.com/skormos/staticcheck-test-dependency/blob/main/cmd/main.go) calls a [publicly exported function](https://github.com/skormos/staticcheck-test-dependency/blob/main/pkg/utils/utils.go#L11) in the same project. Nothing is flagged in the output.

In separate projects, the same behavior happens. Check [this function](https://github.com/skormos/staticcheck-test/blob/main/internal/utils/utils.go#L5-L7) for a project using the other project as a dependency. 

I added a type switch around the underlying `ast.Node` type passed to the function for [CheckDeprecated](https://github.com/dominikh/go-tools/blob/3ce2d47909f4dde26ce09eabbbba06d21dea5282/staticcheck/lint.go#L3013) and the code can be found. I just don't understand why it's not reported to the linter.

I've tried every permutation of `staticcheck` with `-checks "all"` `-checks "SA1019"` with nothing. I've also tried every search term of `./...`,  `./path/to/file.go`, etc.

I've tried it in both the projects listed below. Something seems missing. 

- The output of 'staticcheck -version'
`staticcheck 2020.2.1 (v0.1.1)`
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
Compiled with Go version: go1.15.5
Main module:
	honnef.co/go/tools@v0.1.1 (sum: h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```

- The output of 'go version': `go version go1.15.5 darwin/amd64`. Also tried with `1.14` and same results.
- The output of 'go env':
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="<user director>/Library/Caches/go-build"
GOENV="<user directory>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="<path to>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="<path to>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="<path to project>/github.com/skormos/staticcheck-test-dependency/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3w/s1dtlnv10zj0dkznqd17vybh0000gn/T/go-build848498063=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
- Exactly which command you ran
`staticcheck ./...`, `staticcheck -checks "all" ./...`, `staticcheck -checks "SA1019" ./...` `staticcheck -checks "all" ./cmd/main.go`
- Output of the command and what's wrong with the output
   *No mention of any deprecated usage.*
- Where we can read the code you're running staticcheck on
  (GitHub repo, link to playground, code embedded in the issue, ...)
[Main Repo](https://github.com/skormos/staticcheck-test)
[Dependency Repo](https://github.com/skormos/staticcheck-test-dependency)

**Comment by ainar-g** [comment]
The `Deprecated:` comment should be at the beginning of a *paragraph*, by the way.

This is correct:

```go
// Foo is a foo.
//
// Deprecated: Use BetterFoo.
type Foo int
```

This isn't:

```go
// Foo is a foo.
// Deprecated: Use BetterFoo.
type Foo int
```

With that said, I can't seem to make it work either way in latest `staticcheck`, despite clearly remembering that that check used to work.  Perhaps a breakage upstream?

**Comment by skormos** [comment]
@ainar-g Thank you for the very quick reply. 

You are absolutely correct, and I somehow missed that [from the wiki](https://github.com/golang/go/wiki/Deprecated), despite ~reading~ skimming it several times.

Adding the new line before the `// Deprecated:` line worked for me. 
Before:
```
// SoSad is meant to be sad.
// Deprecated: Not sad anymore, use Awesome instead.
func SoSad(s string) string {
	return fmt.Sprintf("so sad your %s is not awesome", s)
}
```
After:
```
// SoSad is meant to be sad.
//
// Deprecated: Not sad anymore, use Awesome instead.
func SoSad(s string) string {
	return fmt.Sprintf("so sad your %s is not awesome", s)
}
```
Output from `staticcheck ./...` 

- for the dependency project: 
`cmd/main.go:11:14: utils.SoSad is deprecated: Not sad anymore, use Awesome instead.  (SA1019)` 

- for the main project calling the dependency: 
```
cmd/main.go:11:14: utils.SoSad is deprecated: Not sad anymore, use Awesome instead.  (SA1019)
internal/utils/utils.go:6:9: utils.SoSad is deprecated: Not sad anymore, use Awesome instead.  (SA1019)
```

I installed `staticcheck` using `go get honnef.co/go/tools/cmd/staticcheck`. I have not tried while wrapped up in `golangci-lint`, but it does seem to work now as advertised. 

Happy to close if you don't need any further information.

**Comment by ainar-g** [comment]
Apparently mine didn't work because I tried to use `// Deprecated:` in `package main`.

@dominikh, is excluding `package main` from SA1019 expected?

Also, perhaps a check against malformed deprecation notices should be added?

**Comment by dominikh** [comment]
@ainar-g You can freely use deprecated objects within the same package. Often, new API is implemented in terms of the deprecated API. We only flag the use across package boundaries.

> Also, perhaps a check against malformed deprecation notices should be added?

That seems like a game of whac-a-mole I'm not too interested in.

**Comment by ainar-g** [comment]
I'm asking about the malformed notice, because this is actually the *second* time I see this mistake, if not the third, so I can say that it's something that happens “often”.  But I guess I see your point too.

**Comment by dominikh** [comment]
I'm aware it happens, but I'm afraid this is one of the mistakes an actual human will have to catch in code review :P

Closing this issue, as everything seems to be working.

**Comment by spencer-kormos-gbf** [comment]
I've seen that level of style check for Linters in other languages, but I can see it as something not necessarily wanted. 

Personally, I would rather educate developers on the syntax, but that's just me. 

Either way, lesson learned, and thanks again!

**Comment by sourabh-upadhyay** [comment]
@ainar-g 

> The `Deprecated:` comment should be at the beginning of a _paragraph_, by the way.
> 
> This is correct:
> 
> ```go
> // Foo is a foo.
> //
> // Deprecated: Use BetterFoo.
> type Foo int
> ```
> 
> This isn't:
> 
> ```go
> // Foo is a foo.
> // Deprecated: Use BetterFoo.
> type Foo int
> ```
> 
> With that said, I can't seem to make it work either way in latest `staticcheck`, despite clearly remembering that that check used to work. Perhaps a breakage upstream?



> The `Deprecated:` comment should be at the beginning of a _paragraph_, by the way.
> 
> This is correct:
> 
> ```go
> // Foo is a foo.
> //
> // Deprecated: Use BetterFoo.
> type Foo int
> ```
> 
> This isn't:
> 
> ```go
> // Foo is a foo.
> // Deprecated: Use BetterFoo.
> type Foo int
> ```
> 
> With that said, I can't seem to make it work either way in latest `staticcheck`, despite clearly remembering that that check used to work. Perhaps a breakage upstream?

I have followed the same way to use deprecated in the struct. But it doesn't warn at all.
