### ISSUE TITLE
quickfix: suggest time.Time.Equal instead of ==

### ISSUE THREAD

**Issue by leventov** [dominikh/go-tools#932]
https://golang.org/pkg/time/#Time says:

> Note that the Go == operator compares not just the time instant but also the Location and the monotonic clock reading. Therefore, Time values should not be used as map or database keys without first guaranteeing that the identical Location has been set for all values, which can be achieved through use of the UTC or Local method, and that the monotonic clock reading has been stripped by setting t = t.Round(0). In general, prefer t.Equal(u) to t == u, since t.Equal uses the most accurate comparison available and correctly handles the case when only one of its arguments has a monotonic clock reading.

**Comment by dominikh** [comment]
As the quoted passage says, it _is_ possible to compare time.Time values directly and successfully, by stripping monotonic time and ensuring timezones are identical. I know of at least one major project that does this successfully. As such, we cannot categorically ban comparing time.Time values.

See #47 and #134 for prior discussions on this.

**Comment by dominikh** [comment]
For `==`, we can at least display a quickfix in editors that pushes users towards using Equal instead. There's not much we can do about maps, though.
