### ISSUE TITLE
unknown XML option "-" (SA5008)

### ISSUE THREAD

**Issue by cgiacomi** [dominikh/go-tools#934]
I have some code that is flagged by staticcheck, which I believe may not be correct.
Here is the information you requested.

- version: 
staticcheck 2020.2.1 (v0.1.1)

- debug version: 
Compiled with Go version: go1.15.6
Main module:
	honnef.co/go/tools@v0.1.1 (sum: h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c (sum: h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

- Go version:
go version go1.15.6 darwin/amd64

- command run:
staticcheck ./...

- output:
... unknown XML option "-" (SA5008)

I think this might be an error as the Go XML package [https://golang.org/pkg/encoding/xml/#Marshal](https://golang.org/pkg/encoding/xml/#Marshal) clearly states: "- a field with tag "-" is omitted" which seems indicate that "-" is a valid xml option.

The issue arises due to a struct that needs to be marshaled/unmarshaled to/from xml, and I need to omit a property completely, "-" is the correct way of doing this, as shown below:

```
type MyStruct struct {
        StatusText         string `xml:"statustext"`
	StatusNumber  string `xml:",-"` // property to omit
}
```

Thanks in advance for your time and help.

**Comment by dominikh** [comment]
`-` is a valid field name, not a valid option. You will find that your code isn't working as expected: https://play.golang.org/p/4-3VOFUbkiC

To omit a field, use `xml:"-"`.
