### ISSUE TITLE
How to handle the crypto/dsa deprecation

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#935]
Go 1.16 has deprecated crypto/dsa. Technically, viable alternatives exist since probably Go 1.0. If left to its defaults, [SA1019](https://staticcheck.io/docs/checks#SA1019) will flag all imports of crypto/dsa. I am not sure that is the right decision. The majority of people who still use DSA probably do so because of an external requirement, having to interface with other systems that still use DSA. As such, the deprecation warning would only act as unactionable noise and be ignored by users. I am inclined to not flag imports of crypto/dsa.

/cc @FiloSottile

**Comment by FiloSottile** [comment]
> The majority of people who still use DSA probably do so because of an external requirement

Do you have user reports about this? Most uses of the package I've seen were more of the "support all the algorithms" kind.

**Comment by dominikh** [comment]
> Do you have user reports about this?

None yet, and admittedly I guessed. Systems that require DSA do exist, and I couldn't believe that new code would willingly use it, given the choice.

**Comment by FiloSottile** [comment]
I would be curious to see if any show up.

I try to swing the deprecation hammer sparingly, because I know it will show up in users' faces, but crypto/dsa is meaningfully different from crypto/rsa in ways that might not be obvious to users. For example, I am working on moving math/big out of the security perimeter, but crypto/dsa will be left behind, and due to its parameters is way more susceptible to all kinds of attacks.

Even NIST, which is notoriously conservative, bans the use of DSA for signing, so I am not very convinced these intentional DSA deployments actually exist.

**Comment by dominikh** [comment]
In that case I shall do nothing for now and see if anyone actually complains about the warning.

Thank you, Filippo.

**Comment by FiloSottile** [comment]
Thank you! Feel free to cc me on any DSA (or crypto) related report.

**Comment by dominikh** [comment]
@FiloSottile In case you are interested, here are people running into the warning: https://github.com/zmap/zlint/pull/578

**Comment by christopher-henderson** [comment]
Howdy @dominikh and @FiloSottile . Coming over from the ZLint repo that got cross linked to this issue.

I would say that we are not a great example of a project that is particularly "dependent" upon this.

1. We have the [zcrypto](https://github.com/zmap/zcrypto/commit/efd761a7b7b07acefcd1430b9f6717512a7088c4) project which serves as a our own fork of various golang x509, pki, and crypto libraries specifically for shenanigans such as this (and we have already vendored `crypto/dsa` into the project).
2. We are a linter ourselves. Our usecase for importing `crypto/dsa` was to make sure that OTHER people weren't generating x509 certificates using `crypto/dsa`. In that regard, we quite agree that this package is deprecated. This is just an unfortunate/interesting interaction between our two projects.
