### ISSUE TITLE
Is this `unused` false positive?

### ISSUE THREAD

**Issue by hiromoon** [dominikh/go-tools#942]
Hi, I have a question.
Is this a false positive?

Static checker warns `unused` function.

```console
$ golangci-lint run
foo/example.go:15:16: func `(*Buzz).bar` is unused (unused)
func (b *Buzz) bar() {
```

This private function is  used through interface.

```golang
package main

import "./foo"

func main() {
	foo.Bar(&foo.Buzz{})
}
```
```golang
package foo

import "fmt"

type Foo interface {
	bar()
}

func Bar(f Foo) {
	f.bar()
}

type Buzz struct{}

func (b *Buzz) bar() {
	fmt.Println("foo bar buzz")
}
```

This problem happens with golangci-lint@v1.38.0, not with golangci-lint@v1.37.1.

**Comment by dominikh** [comment]
Can reproduce, looking into it.

**Comment by dominikh** [comment]
This should be fixed on master. I'd like to wait a day or two, to see if this change has caused any new bugs. If it hasn't, I'll make a new patch release.

**Comment by hiromoon** [comment]
I see! Thank you for quick response!
