### ISSUE TITLE
New check: converting a float variable into uint directly is needlessly platform-specific

### ISSUE THREAD

**Issue by leventov** [dominikh/go-tools#943]
```go
x := -1.0
y := uint32(x)
```

The behavior of this code is needlessly platform-specific (different on ARM and Mac). Because of https://golang.org/ref/spec#Conversions:

> In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

A possible fix is to add intermediate conversion into int:
```go
x := -1.0
y := uint32(int32(x))
```

**Comment by dominikh** [comment]
Merging into #101
