### ISSUE TITLE
staticcheck: flag when user uses math/rand as source of cryptographic random data

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-tools#95]
A frequent cryptographic error is to use a Reader from math/rand and use data from it as a random key. math/rand is a userspace RNG, and is not "random" enough for encryption purposes.

Some code:

b := make([]byte, 32)
math/rand.Read(b)
secretbox.Seal([]byte{}, .., .., b)

That's a security problem.

**Comment by dominikh** [comment]
While I am sympathetic to the idea, I don't see a clear way to implement it. Of course we can hard-code a number of well known crypto APIs, but that might create the illusion of safety.

**Comment by mvdan** [comment]
I'm going to play the devil's advocate - doesn't the false illusion of safety apply to other checks, like tail calls? It's still possible to get stack size limit exceeded panics even if `staticcheck` is happy, for example.

**Comment by shurcooL** [comment]
How can you tell whether math/rand is used a source of cryptographic random data or a source of non-cryptographic random data?

Does vet do anything about this?

**Comment by dominikh** [comment]
@mvdan The main difference between other checks and this one is user expectations. Other checks "just" find bugs. In the general case, if we fail to find a bug, that's unfortunate, but not tragic. If we claim to find security issues, but fail to do so, it might have more grave consequences. There is no *real* difference, but there may be different expectations

Tying into those expectations: most of our checks don't require a list of functions to check, or when they do, they're exclusively in the standard library. When we fail to find a bug, we can often improve our algorithms and that's it. For security checks like this one, however, users may rightly complain whenever we don't recognize some third party library, asking us to maintain an ever-growing list of 3rd party APIs and rules for them. This may not be a problem in the future, when we have support for external rule files, but we're not there yet.

For security issues, I would like to try a lot harder than the usual "any bug found is a net win".

**Comment by dominikh** [comment]
We really can't do this reliably.
