### ISSUE TITLE
cmd/staticcheck command line option -checks, unclear syntax

### ISSUE THREAD

**Issue by galileo-pkm** [dominikh/go-tools#951]
Documentation states:

> -checks | Allows overriding the list of checks to run.       Has the same syntax as the checks setting       in configuration files.

`staticcheck -checks ["-ST1005", "-SA1012"]`
returns:
`flag provided but not defined: -SA1012]`

Tried all other combinations I could think of, it eider fails with an error message or it apparently
disables all checks, for example:
`staticcheck -checks "["-ST1005", "-SA1012"]"`
returns 0 warnings. 
What is the proper syntax for this command line option.

**Comment by dominikh** [comment]
The correct invocation to mirror `checks = ["-ST1005", "-SA1012"]` would be `staticcheck -checks "-ST1005,-SA1012"`. But having a `checks` setting that only consists of exclusions isn't very useful, as it doesn't enable any checks. To run the default set of checks, minus some other checks, you would want `checks = ["inherit", "-ST1005", "-SA1012"]` and `staticcheck -checks "inherit,-ST1005,-SA1012"` respectively.

I'll try and make the documentation more clean.

**Comment by galileo-pkm** [comment]
Thank you.
