### ISSUE TITLE
false positive in SA5011

### ISSUE THREAD

**Issue by JAicewizard** [dominikh/go-tools#958]
<details>
  <summary>staticcheck -version</summary>

  `staticcheck 2020.2.3 (v0.1.3)`
</details>

<details>
  <summary>staticcheck -debug.version</summary>

```
staticcheck 2020.2.3 (v0.1.3)

Compiled with Go version: go1.16.2
Main module:
        honnef.co/go/tools@v0.1.3 (sum: h1:qTakTkI6ni6LFD5sBwwsdSO+AQqbSIxOauHTTQKZ/7o=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
        golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```
</details>

<details>
  <summary>go version</summary>

`go version go1.16.2 linux/amd64`
</details>

<details>
  <summary>go env</summary>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jaap/.cache/go-build"
GOENV="/home/jaap/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jaap/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jaap/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jaap/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build989216400=/tmp/go-build -gno-record-gcc-switches"
```
</details>

command being run: `staticcheck main.go` on code:

<details>
  <summary>code</summary>

  ```go
package main

import "fmt"

func main() {
	var didEscape *bool
	if didEscape == nil {
		panic("gfdkjn")
	}
	if didEscape != nil {
	}
	fmt.Printf("%v", *didEscape)
}
  ```
</details>

with output:

<details>
  <summary>output</summary>

  ```
main.go:10:2: empty branch (SA9003)
main.go:12:19: possible nil pointer dereference (SA5011)
        main.go:10:5: this check suggests that the pointer can be nil
  ```
</details>

This is solved by removing the code in between the nil check and the dereference

**Comment by dominikh** [comment]
I'm not sure I would consider this a false positive. The check on line 10 suggests that the pointer might be nil, which makes the unconditional dereference dangerous. Yes, strictly speaking it cannot be nil, due to the previous check and panic. But the solution is to remove the redundant nil check on line 10. Either the second check is pointless and should be removed, or it isn't pointless and signals that the pointer might still be nil for some reason.

**Comment by JAicewizard** [comment]
Removing that line indeed fixes the issue, and that check will always be false. I do not think that that check should influence how staticcheck thinks about the nil-ness of `didEscape`.

`or it isn't pointless and signals that the pointer might still be nil for some reason.` I am not sure how it could be nil, and even if it could be (via other go-routines possibly having a reference to this) I dont see how the check itself changes this.

**Comment by dominikh** [comment]
>  I do not think that that check should influence how staticcheck thinks about the nil-ness of didEscape

SA5011 is implemented precisely in terms of "does the pointer get checked against nil". Thus the check influences how the pointer gets treated. If there is a path through your function that both checks a pointer against nil, and dereferences it unconditionally, that path gets flagged. We do not try to deduce the impossibility of the check itself.

I really don't see the point in making SA5011 more complex when it is correctly pointing out an issue with your code: a pointless nil check. Remove the issue from the code, and the warning goes away. I consider that a true positive.

**Comment by JAicewizard** [comment]
Ok, I understand that it would make `SA5011` more complex, and if you would like to prevent that complexity then I can completely understand that. 
I still think its a false positive but theres no point in arguing about that. If you want to close this because you think its not a false positive, or you think that I should just fix the other checks first, thats fine. I will remove the branch, just not now.

**Comment by dominikh** [comment]
> If you want to close this because you think its not a false positive, or you think that I should just fix the other checks first, thats fine

I am going to close it as such, then.
