### ISSUE TITLE
staticcheck: flag bad runtime.GOOS checks in files with build constraints

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#964]
(I thought about posting this as a comment in #188, but decided that a simpler version can be implemented without the use of SAT.  Feel free to close as duplicate if you think otherwise.)

Consider the code:

```go
// +build linux

package main

import (
        "fmt"
        "runtime"
)

func main() {
        if runtime.GOOS == "windows" {
                fmt.Println("never printed")
        } else {
                fmt.Println("always printed")
        }
}
```

Since there is a Linux-only build constraint, `runtime.GOOS` cannot be `"windows"`.  Something more complex would probably actually need an SAT solver, but I think that a best-effort check could still be done for simple cases.

There is, of course, the case of `go run`, but as far as I know most `go run` scripts only use `+build ignore`, so I would assume that false positives there will be rare.

**Comment by dominikh** [comment]
>  Something more complex would probably actually need an SAT solver

Note that needing to SAT solve isn't really a problem for build tags. Usually there are so few terms that we can brute force the solution at little cost, which is what I'm doing as part of my work on #938.
