### ISSUE TITLE
toml is unmaintained

### ISSUE THREAD

**Issue by ChenhuaYang** [dominikh/go-tools#966]
See: https://github.com/BurntSushi/toml

toml is unmaintained, is it safe to use it？

**Comment by dominikh** [comment]
> Many folks are still using this package, and so long as you're happy, there's no pressing reason to switch to something else. 

We only use a small subset of TOML as is, and there are no known to me bugs in github.com/BurntSushi/toml that would affect this subset. We can migrate if we ever run into any issues.

**Comment by ChenhuaYang** [comment]
Thanks
