### ISSUE TITLE
SA9005: make error message clearer

### ISSUE THREAD

**Issue by kevinburkemeter** [dominikh/go-tools#969]
I'm using the latest version of staticcheck. I tried implementing a custom json marshaler: 

```go
type Term string
type Terms []Term

func (t Terms) MarshalJSON() ([]byte, error) {
	var s strings.Builder
	for i := range t {
		// don't need escaping because we know all of the constants
		s.WriteString(string(t[i]))
		if i < len(t)-1 {
			s.WriteByte(',')
		}
	}
	return json.Marshal(s)
}
```

When I run staticcheck on this, I get:

> struct doesn't have any exported fields, nor custom marshaling (SA9005)

on the json.Marshal line. My immediate thought was that staticcheck didn't like the custom marshaler I wrote or that it was somehow flagging a recursive loop or something. 

The actual error here - the one staticcheck is trying to flag - is that I should be calling `json.Marshal(s.String())` instead of `json.Marshal(s)`. 

I think the error message could be a little bit clearer to point people to the right issue... Maybe including the struct type would help? E.g.

> struct "strings.Builder" doesn't have any exported fields, nor custom marshaling (SA9005)

**Comment by dominikh** [comment]
SGTM
