### ISSUE TITLE
simple: fmt.Sprint(s) -> s when expression s has type string

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-tools#97]
I.e., a check that would've spotted the deleted code in https://github.com/google/go-github/pull/640/files.

`return fmt.Sprint(*l.Name)` could've been simplified to `return *l.Name` since `*l.Name` has type `string`.

**Comment by mvdan** [comment]
Potentially related to https://github.com/dominikh/go-tools/issues/66.

**Comment by shurcooL** [comment]
Definitely related. In https://github.com/dominikh/go-tools/issues/66#issuecomment-287566345, I said:

> Is there anything that catches `fmt.Sprint(s)` where `s` type is `string`?

To which @dominikh replied:

> @shurcooL I'll add it to the existing Sprint tests…

And commit b4570a299bb83075a8918f8dfe2b07788ea77720 said "Fixes #66", but I don't see any mention of `fmt.Sprint` in it.

**Comment by shurcooL** [comment]
Should this issue include `fmt.Sprintf(s) -> s` too, which was a subset of #100?

**Comment by dominikh** [comment]
fmt.Sprintf with a dynamic argument is a potential bug and caught by staticcheck. We don't really care about fmt.Sprintf with a string literal because I doubt anybody does that, and because it's not worth the extra work of parsing the format string.
