### ISSUE TITLE
website: update install instructions

### ISSUE THREAD

**Issue by 89z** [dominikh/go-tools#970]
From here [1]:

> If you use Go modules, you can simply run `go get honnef.co/go/tools/cmd/staticcheck`

No, this is not right, as it will modify `go.mod`. Correct command would be [2]:

~~~
go install honnef.co/go/tools/cmd/staticcheck@latest
~~~

continuing, you see this:

~~~
cd $GOPATH/src/honnef.co/go/tools/cmd/staticcheck
git checkout 2020.2.3
go get
go install
~~~

This is also not correct, as its no longer recommended for users to interact directly with `GOPATH` this way. User would just clone to local directory, like this:

~~~
git clone git://github.com/dominikh/go-tools
cd go-tools/cmd/staticcheck
go install
~~~

Please update this, as I have seen people using these instruction, then get confused when `go.mod` is changed.

1. https://staticcheck.io/docs
2. https://stackoverflow.com/a/65734439

**Comment by 89z** [comment]
https://github.com/walles/moar/pull/48

**Comment by dominikh** [comment]
Updating the install instructions is an ongoing process. The difficulty lies in catering to a wide audience that uses different versions of Go. If I'm not remembering incorrectly, your suggested `go install ...` command only works with the latest version of Go, not the previous version. We aim to support the last two versions of Go.

Similarly, GOPATH has been deprecated, but there are still plenty of people using it.

I do plan on making the recommended, most up to date way of installing Staticcheck more prominent.
