### ISSUE TITLE
`lint:ignore` doesn't work on ST1000

### ISSUE THREAD

**Issue by ditek** [dominikh/go-tools#974]
Setup info:

```sh
$ staticcheck -version
staticcheck 2020.2.3 (v0.1.3)

$ staticcheck -debug.version
staticcheck 2020.2.3 (v0.1.3)

Compiled with Go version: go1.16.3
Main module:
        honnef.co/go/tools@v0.1.3 (sum: h1:qTakTkI6ni6LFD5sBwwsdSO+AQqbSIxOauHTTQKZ/7o=)
Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
        golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

$ go version
go version go1.16.3 darwin/amd64

$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOENV="/Users/me/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/me/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/git/myproject/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r5/kps5ymgs7p192jr6mdxn_zr80000gn/T/go-build4195105037=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

I have an auto-generated mock package using mockery (https://github.com/vektra/mockery) and I want to ignore the package doc error for it. I tried using `lint:ignore` and I get this when running `staticcheck`:

```sh
$ staticcheck ./...
ncp/mocks/SerialPort.go:1:1: package comment should be of the form "Package mocks ..." (ST1000)
ncp/mocks/SerialPort.go:2:1: this linter directive didn't match anything; should it be removed? (staticcheck)
```

I tried placing it right on top of the declaration and even removed the auto-generated comment with no success:

```go
// Code generated by mockery v2.1.0. DO NOT EDIT.
//lint:ignore ST1000 auto-generated
package mocks

/* This also produces the same error */

//lint:ignore ST1000 auto-generated
package mocks
```

**Comment by dominikh** [comment]
The "code generated by" comment should not be attached to the `package` statement. You want this:

```
// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks
```

in which case Staticcheck will not complain, which removes the need for `//lint:ignore`.

**Comment by ditek** [comment]
Actually, that's how it was in the first place and Staticcheck complained. That's why I started looking into the ignore statement.
In this case staticcheck prints this:

```
ncp/mocks/SerialPort.go:3:1: at least one file in a package should have a package comment (ST1000)
```

**Comment by dominikh** [comment]
Note also that ST1000 isn't enabled by default. If it's not a check that you agree with, it would be easiest to just not enable it. Or if it's a check that you want to enable generally but doesn't apply to a specific package, disable it for just that package, with a `staticcheck.conf` file that disables the check:

```
checks = ["inherit", "-ST1000"]
```

If you'd prefer to use an ignore directive, then you will have to use [`lint:file-ignore`](https://staticcheck.io/docs/#file-based-linter-directives) instead of `lint:ignore`. Attaching a `lint:ignore` directive directly to the `package` clause would not work well, as it would show up in documentation. A file-wide ignore can stand on its own. So something like 

```
// Code generated by mockery v2.1.0. DO NOT EDIT.

//lint:file-ignore ST1000 We don't need useful documentation

package mocks
```

Personally, however, I would recommend using the `staticcheck.conf` approach instead, as it doesn't require modifying the output of `mockery`.

**Comment by ditek** [comment]
Thanks for the advice. If it's the expected behaviour, then I'll close this issue.
For the record, I haven't enabled any checks other than the default ones. This (and others) started showing up after updating Staticcheck to 2020.2.3.

**Comment by dominikh** [comment]
@ditek can you point me to the project in which you're running into this? I cannot reproduce the problem with a default config, and ST1000 is not enabled automatically in 2020.2.3 for me.

If you can't, what's the result of `find -name staticcheck.conf` at the top level of the project, and what are the contents of the configuration files, if any?

**Comment by ditek** [comment]
There is one config file that I added:

```sh
$ find staticcheck.conf   
staticcheck.conf
```

I use it to disable some checks. Here is its contents:

```json
checks = ["all", "-U1000", "-ST1012"]
```

**Comment by dominikh** [comment]
That enables _all_ checks, including all optional ones, and then disables U1000 and ST1012. So that's why ST1000 has been enabled for you. 

If you want to use the default set of checks, and then disable some of those, use `checks = ["inherit", '-U1000", "-ST1012"]` instead.

**Comment by ditek** [comment]
Oh, I feel dumb now 😅. Thanks, I'll change it.
