### ISSUE TITLE
false positive for U1000 when variable is used only in a test and on a different platform

### ISSUE THREAD

**Issue by josharian** [dominikh/go-tools#983]
> - The output of 'staticcheck -version'

staticcheck built at master May 3, 2021 (23b1890beaa2a99237b6b24a40e58a58bbb40af1)

> - The output of 'staticcheck -debug.version' (it is fine if this command fails)

```
staticcheck (no version)

Compiled with Go version: go1.16.3
Main module:
	honnef.co/go/tools
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```

> - The output of 'go version'

```
go version go1.16.3 darwin/arm64
```

> - The output of 'go env'

On request.

> - Exactly which command you ran
> - Output of the command and what's wrong with the output

```
$ GOOS=darwin GOARCH=arm64 staticcheck .
x.go:3:5: var v is unused (U1000)
```

(Env vars for explicitness; it's my local platform.)

The var v is in fact used in a test on darwin/arm64, even though it doesn't have any visible effect. (In the real code that I'm working with, it would be quite disruptive to reorganize the test code into platform-specific tests.)

> - Where we can read the code you're running staticcheck on

```
-- go.mod --
module scbug

go 1.16
-- x.go --
package p

var v int
-- x_darwin.go --
package p

func f() {}
-- x_linux.go --
package p

func f() {
	println(v)
}
-- x_test.go --
package p

import "testing"

func TestV(t *testing.T) {
	v = 5
	f()
}
```

(Generated by https://github.com/josharian/txtarfs/tree/main/cmd/txtar.)

**Comment by ainar-g** [comment]
Dup of #938?

**Comment by josharian** [comment]
Perhaps, although #938 doesn't list U1000. Perhaps it should?
